4972 ids rating wc - Still pending chance to be ready - DRAFT
infor-design/enterprise-wc pull request #102
Opened 2021-04-27 15:17 UTC by danielortiz1982

**Explain the details for making this change. What existing problem does the pull request solve?**

**Related github/jira issue (required)**:

**Steps necessary to review your pull request (required)**:

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [ ] A note to the change log.

2021-04-27 19:20 UTC, tmcconechy commented
Before we review can you
- update the PR template (make sure to include what isnt done yet and anything you need us to help look at)
- can also start by fixing the checks...

BTW converted to WIP

2021-04-28 15:39 UTC, tmcconechy requested changes
Note some of these comments may reply to the other PR

1. dont include an empty example.js ...
2. on the example page it looks like its readonly but i can still hover it and get a hover state and it looks like its clickable
3. complete types see example https://github.com/infor-design/enterprise-wc/blob/main/src/ids-hyperlink/ids-hyperlink.d.ts
4. new since you started this but please add themes as well see https://github.com/infor-design/enterprise-wc/tree/main/src/ids-base#ids-theme-mixin for notes
5. use the template and getters / setters more for consistency... 
6. can you use "value/stars" and update?
7. do we need a clickable example? i.e. in the PR try to add the examples and not make the reviewer add code to see its working, that should be in the examples already (or tests)

2021-04-28 15:39 UTC, tmcconechy commented on app/ids-rating/example.html
> +        <ids-text><h2>Ratings</h2></ids-text>
```suggestion
        <ids-text><h2>Ratings</h2></ids-text>
```

This should be ` <ids-text font-size="12" type="h1">Alerts</ids-text>` as the label/heading isnt styled right like other examples

2021-04-28 15:39 UTC, tmcconechy commented on src/ids-rating/README.MD
> +# ids rating wc
Example for when you do this https://github.com/infor-design/enterprise-wc/blob/main/src/ids-hyperlink/README.MD

Also some snippets from the old site
```
Displays a scale of selectable values in ascending order. A user can select exactly one value at a time. Best for showing a user's current selection relative to the lower and upper limits of a scale.
```

and https://design.infor.com/product/components/rating

2021-04-28 15:39 UTC, tmcconechy commented on src/ids-rating/ids-rating.js
> +
```suggestion
```

Extra space?

2021-04-28 15:39 UTC, tmcconechy commented on src/ids-rating/ids-rating.js
> +    ratingsConfig = {
For consistency we have been using `this.state.blah` so instead of config use this.state

2021-04-28 15:39 UTC, tmcconechy commented on src/ids-rating/ids-rating.js
> +    connectedCallback() {
All methods should have jsdoc and be either private or public. See examples .. (some might not have done that for this method but its a general rule)

2021-04-28 15:39 UTC, tmcconechy commented on src/ids-rating/ids-rating.js
> +      console.log(this.ratingsConfig)
Some lint errors to fix

2021-04-28 15:39 UTC, tmcconechy commented on src/ids-rating/ids-rating.js
> +        'value',
Please use props - see https://github.com/infor-design/enterprise-wc/blob/main/src/ids-alert/ids-alert.js#L41 for an example

2021-04-28 15:39 UTC, tmcconechy commented on src/ids-rating/ids-rating.js
> +    set value(v) {
Please correct jsdoc and maybe use same names as others for consistency https://github.com/infor-design/enterprise-wc/blob/main/src/ids-input/ids-input.js#L569

2021-04-28 15:39 UTC, tmcconechy commented on src/ids-rating/ids-rating.js
> +      if(v) {
For these props add the case where the attribute is empty and it clears it see https://github.com/infor-design/enterprise-wc/blob/main/src/ids-hyperlink/ids-hyperlink.js#L77

2021-04-28 15:39 UTC, tmcconechy commented on src/ids-rating/ids-rating.js
> +      return this.getAttribute('stars')
```suggestion
      return this.getAttribute('stars') || 5;
```

For the defaults you did above you can just do this....

2021-04-28 15:39 UTC, tmcconechy commented on src/ids-rating/ids-rating.js
> +    buildRatingStar(element, index) {
For these build** methods i think its simpler if you just put it in the template string instead of creating objects here.. That would remove maybe need for 2/3 methods... Many are like that https://github.com/infor-design/enterprise-wc/blob/main/src/ids-textarea/ids-textarea.js#L144

We dont usually use createElement just put all the logic in the template function

2021-04-28 15:39 UTC, tmcconechy commented on src/ids-rating/ids-rating.js
> +    ratingBuilder(el, stars) {
Are all these methods needed? they seem to not follow the patterns. I think that the template () comment might clean it up

2021-04-28 15:39 UTC, tmcconechy commented on src/ids-rating/ids-rating.js
> +    udpateValue() {
Spelled wrong but maybe i tihnk for all these updates we do it view the setter...

2021-04-28 15:39 UTC, tmcconechy commented on src/ids-rating/ids-rating.scss
> +  color: orange;
This isnt a valid color.. Please use the mixins...

2021-04-28 15:39 UTC, tmcconechy commented on test/ids-rating/ids-rating-func-test.js
> +        elem.template();
Do we need to call template here? Also i've changed these to use elem.shadowDOM.innerHTML as of now you can see the snap shot is empty. its more interesting to use the innerHTML of the shadow DOM

2021-04-29 11:58 UTC, danielortiz1982 commented on src/ids-rating/ids-rating.js
> +    ratingBuilder(el, stars) {
Hi Tim,
Can you please point me to a re-render example. I put this into it's own fn to create stars based on the stars attribute value being passed in. Thnx!

2021-04-29 11:59 UTC, danielortiz1982 commented on src/ids-rating/ids-rating.js
> +    udpateValue() {
Thanks! Didn't catch this.

2021-04-29 12:05 UTC, danielortiz1982 commented on src/ids-rating/ids-rating.js
> +      return this.getAttribute('stars')
Thanks, I will keep this in mind as I work through it. I was trying to write some defensive logic in case the attribute was not added to the wc. The setter and getter do not fire when the attribute is not present. That was my thinking behind it.

2021-04-29 13:29 UTC, tmcconechy commented on src/ids-rating/ids-rating.js
> +    ratingBuilder(el, stars) {
There is one example in list view https://github.com/infor-design/enterprise-wc/blob/main/src/ids-list-view/ids-list-view.js#L97-L102 you can make a method like that...

I also am considering a quick PR with a rerender in the pass that just reapplies the template. Would that be usable?

Also think you could fix this by just replacing the star count directly in the setter code.

2021-04-29 13:31 UTC, danielortiz1982 commented on src/ids-rating/ids-rating.js
> +    ratingBuilder(el, stars) {
Thanks! Will do, I will try this out.

2021-05-04 13:50 UTC, tmcconechy commented
Closing this as agreed until its ready. Comments will still be here for reference

2021-05-04 13:50 UTC, closed without merging