1013 - IdsCheckbox fix Safari issues
infor-design/enterprise-wc pull request #1030
Opened 2022-12-05 11:18 UTC by andriivarhanov

**Explain the details for making this change. What existing problem does the pull request solve?**
This PR fixes `validate` and `dirty-tracker` for `ids-checkbox` in Safari browser by adding getters for `input` and `labelEl` properties. Also fixes `hitbox` setting for `ids-checkbox` in Safari by adding connectedCallback to hitbox mixin.

**Related github/jira issue (required)**:
Closes #1013

**Steps necessary to review your pull request (required)**:
- pull and build
- go to http://localhost:4300/ids-checkbox/example.html in Safari browser
- see Dirty tracking example works
- see Required example works
- see hitbox examples work

**Included in this Pull Request**:
~- [ ] An e2e or functional test for the bug or feature.~
- [x] A note to the change log.

2022-12-05 14:33 UTC, EdwardCoyle requested changes
Hey @andriivarhanov, this is working in Safari but I think the logic is backward on the dirty tracking:  When toggling the checkbox on, it doesn't become "dirty", but the dirty tracker does show up when turning the checkbox off.  Oddly enough, it only appears to be that way in Safari (In Chrome, it seems to work fine):

| Safari | Chrome |
| -- | -- |
| ![Screen Shot 2022-12-05 at 9 29 46 AM](https://user-images.githubusercontent.com/3249601/205662688-f11b9e45-5773-403d-865a-c4fecfe54ef5.png) | ![Screen Shot 2022-12-05 at 9 29 57 AM](https://user-images.githubusercontent.com/3249601/205662741-7d889d78-4f5b-45b1-8785-4881a229de23.png) |

2022-12-07 18:02 UTC, andriivarhanov commented
@EdwardCoyle thanks for catching it, should be fixed in the last commit

2022-12-08 14:21 UTC, tmcconechy approved these changes

2022-12-09 19:32 UTC, EdwardCoyle approved these changes

2022-12-09 19:33 UTC, merged