992 - Add support for save user settings to data grid
infor-design/enterprise-wc pull request #1033
Opened 2022-12-06 17:01 UTC by deep7102

**Explain the details for making this change. What existing problem does the pull request solve?**
Added support for save user settings to data grid

**Related github/jira issue (required)**:
Closes #992

**Steps necessary to review your pull request (required)**:
Pull this branch and build/run the demo app
http://localhost:4300/ids-data-grid/save-settings.html
- Change any setting to be different then origin (reorder columns, go to next page etc...)
- After change it should be saved the current settings to local storage
- Refresh or close/open the page-size
- Data grid should restore as previously saved settings

http://localhost:4300/ids-data-grid/save-settings-manual.html
- Change any setting to be different then origin (reorder columns, go to next page etc...)
- After change it should be saved the current settings to local storage
- Refresh or close/open the page, and then click on Restore settings button
- Data grid should restore as previously saved settings

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2022-12-07 13:26 UTC, EdwardCoyle requested changes
@deep7102 This looks good, but I noticed on http://localhost:4300/ids-data-grid/save-settings-manual.html when you refresh the page, the settings don't seem to persist.  On the other page, everything works as expected

2022-12-07 16:02 UTC, EdwardCoyle submitted a review, later dismissed
I misunderstood the test steps on the second one.  All looks good here 👍

2022-12-07 16:33 UTC, tmcconechy requested changes
Looks great just wondering about

a. if the settings should drop the (s) for correct grammer
b. some minor grammar corrections

I like that this is a mixin.

2022-12-07 16:33 UTC, tmcconechy commented on src/components/ids-data-grid/demos/save-settings-manual.html
> +        <ids-text>4. Data grid should restore as previously saved settings</ids-text>
```suggestion
        <ids-text>4. Data grid should restore what was previously modified in saved settings</ids-text>
```

2022-12-07 16:33 UTC, tmcconechy commented on src/components/ids-data-grid/demos/save-settings.html
> +        <ids-text>4. Data grid should restore as previously saved settings</ids-text>
```suggestion
        <ids-text>4. Data grid should restore the previously saved settings</ids-text>
```

2022-12-09 18:36 UTC, deep7102 commented
@tmcconechy updated now, to use as single functions.

2022-12-09 18:37 UTC, deep7102 commented on src/components/ids-data-grid/README.md
> +- `savesActivePage` {boolean} Sets to saves active page to local storage.
updated now

2022-12-09 18:38 UTC, deep7102 commented on src/components/ids-data-grid/ids-data-grid.ts
> +      attributes.UNIQUE_ID,
its just uniqueId can be use also for something else if we need

2022-12-09 19:32 UTC, tmcconechy approved these changes

2022-12-12 21:37 UTC, EdwardCoyle approved these changes

2022-12-14 13:40 UTC, merged