648 - Add support for save user settings to data grid
infor-design/enterprise-wc pull request #1056
Opened 2022-12-19 20:33 UTC by deep7102

**Explain the details for making this change. What existing problem does the pull request solve?**
Added support for empty message to data grid

**Related github/jira issue (required)**:
Closes #648 

**Steps necessary to review your pull request (required)**:
Pull this branch and build/run the demo app
- http://localhost:4300/ids-data-grid/empty-message.html
- http://localhost:4300/ids-data-grid/empty-message-custom-thru-slot.html
- http://localhost:4300/ids-data-grid/empty-message-custom-thru-settings.html
- Data grid should display empty message
- Edit demo (.ts page) find `showEmptyData` change value to `false` and save
- See browser now, empty message should disappear

http://localhost:4300/ids-data-grid/filter.html
- Filter with something to make no result
- Empty message Data should display
- Remove filter empty message should disappear

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2022-12-20 16:18 UTC, andriivarhanov approved these changes
looks good

2022-12-20 20:04 UTC, tmcconechy requested changes
Looks good. But a couple things..


1) The icon and text isnt center vertically (also test if the height is bigger if it remains centered)
2) Can you only use the icons with -new in them for these examples? we want to promote those... i.e. `empty-no-data-new` not `empty-no-data`

2022-12-21 18:11 UTC, deep7102 commented
@tmcconechy updated now, new icon and center vertically.

2022-12-21 18:50 UTC, tmcconechy approved these changes

2022-12-22 08:13 UTC, andriivarhanov approved these changes

2022-12-22 16:38 UTC, merged