1045 - IdsDataGrid dropdown editor (M3)
infor-design/enterprise-wc pull request #1087
Opened 2023-01-05 15:57 UTC by jdilag90

**Explain the details for making this change. What existing problem does the pull request solve?**
Added grid support for dropdown editor. This PR only partially addresses the #1045 ticket, specifically (M3) 

NOTE: Dropdown editors near the bottom of grid will look cut off. Might be addressed [here](https://github.com/infor-design/enterprise-wc/issues/1065) or in another future ticket

**Related github/jira issue (required)**:
Partially Closes #1045 

**Steps necessary to review your pull request (required)**:
1. Checkout branch, `npm install`, `npm run start`
2. Go to http://localhost:4300/ids-data-grid/editable.html
3. Test Currency Column dropdown editor 
4. Test in different themes, languages

**Validation/Dirty**
- Change any currency cell value, dirty indicator should show when edit is finished
- Change any currency cell value to the empty value, it should show an error when edit is finished

**Keyboard**
- [Enter] Activate editing
- [ArrowDown] Opens Dropdown
- [ArrowDown/ArrowUp] Navigates Dropdown list
- [Enter] Selects value and starts editing the same cell in next row
- [Shift + Enter] Selects value and starts editing the same cell in previous row
- [Esc] Cancels editing
- [Tab] Finish editing and start editing the next cell
- [Shift + Tab] Finish editing and start editing the previous cell

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2023-01-05 18:55 UTC, tmcconechy requested changes
Looks overall awesome.. 👍🏻 Just a few things to improve

- when hovering the dropdown cell directly with the mouse the icon should show
- when keyboarding into the cell the dropdown arrow can also show see https://main-enterprise.demo.design.infor.com/components/datagrid/example-editable.html
- clicking the cell with the mouse should open it immediately (one click) see https://main-enterprise.demo.design.infor.com/components/datagrid/example-editable.html
- i noticed if you blank the cell you get the required message, but if you open it again and select a blank value again it doesnt show it anymore
- in xs, sm, md the dropdown arrow is a little far from the right (looks the same as normal in all themes)
![Screenshot 2023-01-05 at 1 53 11 PM](https://user-images.githubusercontent.com/814283/210858421-334e6f13-2cb5-4d1b-9723-75db9834e3b9.png)
- in dark mode the hover state looks like its from light mode (should be like https://main-enterprise.demo.design.infor.com/components/dropdown/example-index.html?theme=new&mode=dark&colors=0066D4 (but maybe one shade darker) seems like a dropdown issue but we could just correct it
![Screenshot 2023-01-05 at 1 48 33 PM](https://user-images.githubusercontent.com/814283/210858720-6b9cefa6-96a7-4e9f-bff4-65284ca65936.png)

All other tests pass. Looks really nice

2023-01-05 18:55 UTC, tmcconechy commented on src/components/ids-data-grid/README.md
> +`editorSettings.options` Data set used for dropdown editor's list box options.
```suggestion
`editorSettings.options` Dataset used for dropdown editor's list box options.
```

2023-01-06 20:20 UTC, tmcconechy approved these changes

2023-01-09 15:54 UTC, deep7102 approved these changes

2023-01-09 16:43 UTC, merged