1063 - IdsTimePicker: Add standalone picker component
infor-design/enterprise-wc pull request #1104
Opened 2023-01-19 17:25 UTC by EdwardCoyle

**Explain the details for making this change. What existing problem does the pull request solve?**
This PR follows up the work on #958 and separates the IdsTimePicker into its own component.  This is required for fixing containment issues in IdsDataGrid for #1064.

**Related github/jira issue (required)**:
Closes #1063 

**Steps necessary to review your pull request (required)**:
- Pull/Build/Run
- Open http://localhost:4300/ids-time-picker/example.html - compare all examples to https://main.wc.design.infor.com/ids-time-picker/example.html (behavior should be the same)
- Open http://localhost:4300/ids-time-picker/picker-only.html.  Check that the Popups' configs reflect what the labels say they should

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2023-01-20 15:16 UTC, tmcconechy requested changes
Looks really great! But see a couple of issues and a nit-pick during testing worth checking...

- in the code i see a new embeddable.html example but its not in the index / mentioned so just checking
- on the example http://localhost:4300/ids-time-picker/example.html can we make the first one a "Normal" example. We only show the "autoselect" and "autoupdate" examples but those really arent the defaults

Bug 1
- on http://localhost:4300/ids-time-picker/example.html click the trigger on "autoselect"
- press set time then press the trigger again (doesnt open)

Bug 2
- on http://localhost:4300/ids-time-picker/example.html click the trigger on "autoselect"
- while the popup is open try and click out to close -> think it should cancel and close on click out like the autoupdate one

Bug 3
- on http://localhost:4300/ids-time-picker/picker-only.html
- alter nate between clicking triggers on the 3 pickers i.e.
- click the trigger on the first picker then click out
- click the trigger on the last picker then click out
- click the trigger on the first picker then click out
- see how it animates from the "old location"
- not seeing an animation on http://localhost:4300/ids-time-picker/example.html -> ok with fixing the animation or eliminating it either way

2023-01-24 13:58 UTC, EdwardCoyle commented
@tmcconechy Thanks for this, all should be fixed now

2023-01-24 14:01 UTC, andriivarhanov reviewed
looks really good, some minor notes:
- “Set Time” button has gray background in contrast mode and feels like the text should be bolder in the button
![Pasted Graphic](https://user-images.githubusercontent.com/5204821/214312426-c856a968-da6d-494c-91e5-eb873b0902cc.png)
- `timeselected` event fires a couple of time on single time change in embeddable example http://localhost:4300/ids-time-picker/embeddable.html
![Pasted Graphic 1](https://user-images.githubusercontent.com/5204821/214312738-95b1d035-6068-45a2-8d8c-7bb4a92d8680.png)
- there is [open.html](http://localhost:4300/ids-time-picker/open.html) example where popup should be visible initially, not sure when it stopped working, but if we are going to make screenshots from the component without the popup we might need to remove open.html example and switch to main example

2023-01-26 14:56 UTC, tmcconechy approved these changes

2023-01-30 15:53 UTC, tmcconechy approved these changes

2023-01-30 16:53 UTC, andriivarhanov approved these changes

2023-01-30 17:38 UTC, merged