1065 - Separate IdsDropdown's Popup into its own component / integrate with IdsDataGridFilters
infor-design/enterprise-wc pull request #1133
Opened 2023-02-14 20:17 UTC by EdwardCoyle

**Explain the details for making this change. What existing problem does the pull request solve?**
This PR makes some changes to IdsDropdown to allow it to break out of IdsDataGrid's overflow containment while being used as a filter:
- Separates the IdsDropdown's popup into its own new component, IdsDropdownList.  This new component is the new home to IdsListBox/IdsListBoxOptions
- Reconnected IdsDropdownList into IdsDropdown and restored its previous behavior
- Provided examples/docs of how to use IdsDropdownList separately
- Integrated IdsDropdownList's usage into IdsDataGridFilters wherever dropdown is used.

**Related github/jira issue (required)**:
Closes #1065

**Steps necessary to review your pull request (required)**:

_Test dropdown integration:_
- open http://localhost:4300/ids-data-grid/filter-trigger-fields.html
- Use the columns that filter with Dropdowns.  Test that filtering works as expected
- Use the "Price" columns and filter on `13.99` (one option present in the grid).  Try opening the dropdown columns -- the dropdowns should not be cut off by Datagrid containment.

_Test separate list example:_
- open http://localhost:4300/ids-dropdown/separate-list.html
- use the Dropdown/DropdownList and make sure they behave like the others

_Smoke test previous behavior:_ check all these and make sure they work as expected:
- http://localhost:4300/ids-dropdown/example.html
- http://localhost:4300/ids-dropdown/sizes.html
- http://localhost:4300/ids-dropdown/typeahead.html
- http://localhost:4300/ids-dropdown/sandbox.html
- http://localhost:4300/ids-multiselect/example.html

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2023-02-22 18:46 UTC, andriivarhanov reviewed
looks good, here is a few issues I've found:
- popup's position when it's at the top or when validation error is triggered 
![image](https://user-images.githubusercontent.com/5204821/220728048-44b7a6ab-3b7e-4ef5-acd3-300314b0c714.png)
- there is something with click outside to close the popup, on the page http://localhost:4300/ids-dropdown/example.html click on the `Dropdown with Allow Blank` example and click on the `Dropdown Using Ajax`, the previous one didn't close
![image](https://user-images.githubusercontent.com/5204821/220721937-ccd50a97-dc71-4f6c-956b-2c9fbc5a965c.png)
- it looks like the popup should be 1px closer to the field
![image](https://user-images.githubusercontent.com/5204821/220722369-cd4628af-8791-4623-b279-936bce5f53c3.png)
- http://localhost:4300/ids-dropdown/typeahead.html `Dropdown typeahead with blank option` doesn't have blank option
- when you open typeahead dropdown input's text should be selected
- typeahead's suggestions can't be selected
- http://localhost:4300/ids-multiselect/clearable.html 
  - not all items are loaded in the popup
  - can’t select the items
  - when it’s focused you can’t unfocus it by clicking on another element on the page 
- http://localhost:4300/ids-multiselect/groups.html group label being focused when selecting an item

sorry it's not much detailed feedback, I can clarify on some items, let me know

2023-02-22 19:14 UTC, tmcconechy commented on .stylelintrc.json
> +    "string-quotes": "single"
Did this get re-added unintentionaly? This is the one i think got removed because its deprecated i spoke about.

2023-02-22 19:20 UTC, tmcconechy requested changes
i see a couple of issues now

1. on http://localhost:4300/ids-dropdown/example.html - move the mouse slowly down the right side away from the component as you pass the tooltip one the tooltip will show and never hide
2. click on one near the bottom and it will open upward. And its not connecting with the field
<img width="375" alt="image" src="https://user-images.githubusercontent.com/814283/220735897-192983dc-8daf-4b50-8c7e-9a0e32ec053b.png">
3. more noticible on http://localhost:4300/ids-dropdown/sizes.html the popup is a bit lower than it used to be
<img width="342" alt="image" src="https://user-images.githubusercontent.com/814283/220736080-7c380594-8056-47da-b889-d7c4b2543b03.png">
vs
<img width="370" alt="image" src="https://user-images.githubusercontent.com/814283/220736159-b23d5916-670d-47ce-a143-45d965c347aa.png">

see: https://main.wc.design.infor.com/ids-dropdown/sizes.html

2023-02-24 16:42 UTC, EdwardCoyle commented on .stylelintrc.json
> +    "string-quotes": "single"
I added this before you mentioned the change in the call -- without it the build had been failing on all SCSS files.  I'll rebase again and see if it helps without it

2023-02-24 16:47 UTC, tmcconechy commented on .stylelintrc.json
> +    "string-quotes": "single"
Ok i thought it was one that caused the deprecation warnings when you run `npm run lint` so maybe just confirm that.... That was the only reason i removed it

2023-03-01 15:04 UTC, tmcconechy approved these changes

2023-03-01 15:11 UTC, tmcconechy submitted a review, later dismissed

2023-03-01 15:37 UTC, andriivarhanov reviewed
still seeing some issues:
- there is something with click outside to close the popup, on the page http://localhost:4300/ids-dropdown/example.html click on the Dropdown with Allow Blank example and click on the Dropdown Using Ajax, the previous one didn't close
- when you open typeahead - dropdown input's text should be selected
- typeahead's/dropdown's list items can't be selected with keyboard
- http://localhost:4300/ids-multiselect/clearable.html `Clearable Dropdown (max choices 3)` example
  - not all items are loaded in the popup
  - can’t select an item except for the first one
  - when it’s focused you can’t unfocus it by clicking on another element on the page

2023-03-06 13:58 UTC, andriivarhanov approved these changes

2023-03-06 14:11 UTC, tmcconechy approved these changes

2023-03-06 14:11 UTC, merged