1102 idsdatagrid no longer emits scroll event add scroll to bottom and append
infor-design/enterprise-wc pull request #1145
Opened 2023-02-22 14:51 UTC by clayinfor

**Explain the details for making this change. What existing problem does the pull request solve?**

Add events for `virtualscroll-top` and `virtualscroll-bottom`.

**Related github/jira issue (required)**:

Closes #1102 

**Steps necessary to review your pull request (required)**:

1. Run tests to ensure they all pass: `npx jest -- data-grid-func-test`
2. Check out branch, and do: `npm --components=data-grid run start`
3. @see http://localhost:4300/ids-data-grid/virtual-scroll-infinite-scroll.html

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2023-02-22 20:13 UTC, tmcconechy requested changes
Only a few things

1) does the new event virtualScrollTop work in both virtualscroll mode and or not? If not i think it should work on either setting and just act as a scroll event that tells you details on how far. So should be renamed scrollend or scrollstart or just scroll something without the name "virtual" as part of the setting. This is why i suggested on the issue to just fire the normal scroll event on the component so it looks standard then pass the ratio in the event details but willing to wiggle on that. Just think virtual isnt right.
2) For the example to match what m3 is doing can you make the number of records initially a lot lower (at least you so you dont need to scroll a long time down to test). They use 33 rows each time but thats based on what fits in a page. So might need to adjust this (maybe 100 or whatever works visually)
3) Would like another api name than `moreData` when setting but not sure what? Any other name ideas cc @EdwardCoyle ?
4) As i scroll down and append more data it doesn't seem to keep the scroll position and re-set it. the old example could do this on https://main-enterprise.demo.design.infor.com/components/listview/example-footer-navigation.html (middle example). Basic Idea was: save scrollTop then add rows then reset scrollTop 
 
I think this also solves https://github.com/infor-design/enterprise-wc/issues/1074

Lemme know if you need to discuss and im in any way unclear

2023-02-24 15:27 UTC, tmcconechy approved these changes
Very Nice. Thanks @clayinfor

2023-02-24 17:01 UTC, deep7102 submitted a review, later dismissed
Looks good 🍌 

on demo examples looks it loading same data again and again
```
return data.slice(0, 33);
return data.slice(0, 100);
```

2023-02-24 17:31 UTC, tmcconechy commented
Thats true @deep7102 might want to make it "count up" / loop...

2023-02-24 18:08 UTC, clayinfor commented
Good call @deep7102 . I've updated the demos @tmcconechy so that it doesn't look like it's repeating same items.

2023-02-24 18:34 UTC, tmcconechy submitted a review, later dismissed

2023-02-25 02:34 UTC, deep7102 approved these changes

2023-02-27 21:21 UTC, EdwardCoyle reviewed
@clayinfor This looks really great!  I'm just following up on this one item below, but otherwise ready to approve

2023-02-27 21:21 UTC, EdwardCoyle commented on src/components/ids-data-grid/ids-data-grid.ts
> +  moreData(value: Array<Record<string, any>>) {
Per @tmcconechy's comment, I'd say maybe this should be `addData` or `insertMoreData`, or just some indication of the action of "adding additional data" and not replacing it.  `moreData` doesn't bother me personally but could be confusing.

2023-02-28 15:30 UTC, tmcconechy approved these changes

2023-02-28 15:51 UTC, EdwardCoyle approved these changes

2023-02-28 15:53 UTC, merged