763 - Add support for search with list view
infor-design/enterprise-wc pull request #1187
Opened 2023-03-15 19:21 UTC by deep7102

**Explain the details for making this change. What existing problem does the pull request solve?**
Added support for search to filter list

- Added support for search with list view
- Added example page to show the different types of text styles
- More tests and coverage
- Update docs and other cleanup

**Related github/jira issue (required)**:
Closes #763

**Steps necessary to review your pull request (required)**:
Pull this branch and build/run the demo app
Navigate to below urls to filter the search:
- http://localhost:4300/ids-list-view/search.html
- http://localhost:4300/ids-list-view/search-thru-slot.html
- http://localhost:4300/ids-list-view/search-custom-filter.html
- http://localhost:4300/ids-list-view/search-thru-id.html
- Test the search it should filter results

Example to show the different types of text styles:
http://localhost:4300/ids-list-view/text-headings.html

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2023-03-16 13:17 UTC, andriivarhanov reviewed
search functionality looks good, the only thing I've noticed is some comments are `undefined`, we might need to add some check there to show empty string instead of undefined
![image](https://user-images.githubusercontent.com/5204821/225627940-2314bbdf-0c38-4d19-a8d5-868cded11586.png)

2023-03-16 13:57 UTC, deep7102 commented
@andriivarhanov 
Updated now, to not show comments data field as undefined

2023-03-16 14:54 UTC, tmcconechy requested changes
@deep7102 one issue i noticed is

http://localhost:4300/ids-list-view/search.html
- tab in and type DI
- tab 2 times to get to the list
- hit down arrow -> does not move -> maybe the keyboard code needs updating to skip hidden items?

Otherwise looks great to me

2023-03-20 09:36 UTC, andriivarhanov approved these changes

2023-03-20 15:00 UTC, merged