1205 - IdsPopupMenu:  Enable scrolling in fixed-sized `max-height` menus
infor-design/enterprise-wc pull request #1212
Opened 2023-03-30 19:54 UTC by EdwardCoyle

**Explain the details for making this change. What existing problem does the pull request solve?**
This PR allows IdsPopupMenu configured with a `max-height` property to scroll its content.  This scrolling behavior also accounts for submenu position, placing opened submenus adjacent to their parent menu items as expected.

Additionally, a change in the IdsToolbarMoreActions component structure was needed to account for the menu changes.  Now, IdsToolbarMoreActions allows users to slot IdsPopupMenu and IdsMenuButton elements as children (not just IdsMenuGroup elements).  A codepath for "migration" from the old slotting method has been added, and tests and documentation have been updated to reflect this change.

**Related github/jira issue (required)**:
Closes #1205

**Steps necessary to review your pull request (required)**:
Pull/build/run, then try these test steps:

_Test scrollable menus:_
- Open http://localhost:4300/ids-popup-menu/scrolling.html
- Right click to activate a scrolling IdsPopupMenu
- Scroll down and activate submenu items.  The menu should appear adjacent to its parent menu item
- Also try this on IdsDataGridCells: http://localhost:4300/ids-data-grid/contextmenu-thru-data.html

_Test non-scrollable menus:_
Open and test the context menus and/or menu buttons in these examples.  When testing IdsPopupMenu components, and make sure their submenus open accurately:
- http://localhost:4300/ids-popup-menu/example.html
- http://localhost:4300/ids-popup-menu/selected-state.html
- http://localhost:4300/ids-popup-menu/data-driven.html
- http://localhost:4300/ids-menu-button/example.html

_Test IdsToolbarMoreActions:_
- Open http://localhost:4300/ids-toolbar/example.html
- Use the "..." button and activate its submenus.  Submenus should open in the correct place
- Shrink the browser viewport to push the "Menu" button into toolbar overflow.  Use the "..." and activate the "Menu" item's submenu, and its child submenus.  All elements should display within the viewport.

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2023-03-31 14:53 UTC, tmcconechy reviewed
Looks pretty good. Not sure i want to request changes as its a bit of an edge case but at this height the top and bottom are cut off.

![Screenshot 2023-03-31 at 10 49 59 AM](https://user-images.githubusercontent.com/814283/229154930-518f0d3a-4e14-42a2-836c-8528d355799b.png)
![Screenshot 2023-03-31 at 10 51 01 AM](https://user-images.githubusercontent.com/814283/229154932-c66d3125-7914-42ef-afc0-63fde5788dd8.png)

Also i see in the percy that the layout is off on one example now. Worth checking. I made a comment there.

2023-04-04 16:02 UTC, EdwardCoyle commented
@tmcconechy I reworked this a bit to support an automatic change to the "fixed height" mode if the viewport/container is too small -- should work better.  You can see it when resizing the browser on http://localhost:4300/ids-popup-menu/selected-state.html:

[Untitled_ Apr 4 2023 11_59 AM.webm](https://user-images.githubusercontent.com/3249601/229850462-8e640052-fb14-4ce8-acaf-f3fd4e93b1bb.webm)

2023-04-05 17:16 UTC, tmcconechy approved these changes
Looks good to me, but did rerun the tests as i saw an issue (Axe) now

2023-04-07 15:53 UTC, andriivarhanov submitted a review, later dismissed

2023-04-07 16:03 UTC, tmcconechy requested changes
@EdwardCoyle i do see two things that i noticed from the images.

1. Something effected masthead
http://localhost:4300/ids-masthead/example.html  -> resize to mobile -> compare with https://main.wc.design.infor.com/ids-masthead/example.html

2. this image looks strange 
![image](https://user-images.githubusercontent.com/814283/230640090-c1c5d856-4d82-4414-b98b-b81c48da42c3.png)
 but i dont see it on the page

3. also noticed on http://localhost:4300/ids-popup-menu/example.html when i right click the first time it works but if i right click in another place it doesnt close and reopen in that other place (good punt to later if you want)

2023-04-07 16:05 UTC, tmcconechy commented on src/components/ids-dropdown/ids-dropdown.ts
> -      'aria-description': this.localeAPI?.translate('PressDown'),
FYI this did work. But it may be flagged by Axe but they plan on fixing that as its newer https://github.com/dequelabs/axe-core/issues/3121 so i did it this way.

2023-04-07 16:13 UTC, EdwardCoyle commented on src/components/ids-dropdown/ids-dropdown.ts
> -      'aria-description': this.localeAPI?.translate('PressDown'),
Should I just ignore that rule in the meantime?

2023-04-07 16:14 UTC, tmcconechy commented on src/components/ids-dropdown/ids-dropdown.ts
> -      'aria-description': this.localeAPI?.translate('PressDown'),
Yeah i figure leave it and ignore the Axe warning. As when i last tested it with the screen reader it sounded good to me.
This could be ok. But i did not test with screen reader.

2023-04-07 18:43 UTC, EdwardCoyle commented
@tmcconechy I'll punt item 3 to another issue but I think I've addressed the other points

2023-04-10 13:44 UTC, tmcconechy approved these changes

2023-04-10 14:03 UTC, andriivarhanov submitted a review, later dismissed

2023-04-11 15:14 UTC, merged