1179 - Add fixes for closing menu and cleanup
infor-design/enterprise-wc pull request #1252
Opened 2023-04-25 15:10 UTC by tmcconechy

**Explain the details for making this change. What existing problem does the pull request solve?**

Takes the code in side-by-side that was implemented to hide menus when a menu in the older framework is opened/closes and implements it in the component as a more permanent solution.

Uses mutation observer and setting classes. Also found a mutation observer that may not be cleaned up and fixed it and some JSDoc warnings.

Note: Includes https://github.com/infor-design/enterprise-wc/pull/1251 as it caused testing issues otherwise.

**Related github/jira issue (required)**:
Fixes #1179 

**Steps necessary to review your pull request (required)**:
- go to http://localhost:4300/ids-popup-menu/side-by-side.html
- right click between each component (old and new) and alternate seeing that one closes the other and vise versa

**Included in this Pull Request**:
- [x] A note to the change log.

2023-04-25 15:32 UTC, andriivarhanov submitted a review, later dismissed
looks good

2023-04-25 17:08 UTC, andriivarhanov commented
@tmcconechy it looks like initial fix for the context menu doesn't work for some other menus (tests are failing for that reason), I've made another change adding hide only for context menu https://github.com/infor-design/enterprise-wc/pull/1251/files , tests should pass now

2023-04-25 18:33 UTC, andriivarhanov approved these changes

2023-04-26 12:26 UTC, andriivarhanov approved these changes

2023-04-26 16:56 UTC, EdwardCoyle requested changes
If we add detection directly into the Popup Menu I think we might need a safer approach.  Please see below

2023-04-26 16:56 UTC, EdwardCoyle commented on src/components/ids-popup-menu/ids-popup-menu.ts
> +    this.#mo = new MutationObserver((mutations) => {
We might not want to rebuild this on every 'show' event.  These fire often, so I'd say try and set this up once in `connectedCallback`.  The above code for closing the menus can run on each `show`

2023-04-26 16:56 UTC, EdwardCoyle commented on src/components/ids-popup-menu/ids-popup-menu.ts
> +    openMenuElem?.classList.remove('is-open');
I think it's better to fire the [popupmenu's `close()` API](https://github.com/infor-design/enterprise/blob/main/src/components/popupmenu/popupmenu.js#L2384-L2390):
```suggestion
    openMenuElem?.data('popupmenu')?.close(true, true);
```

I think this is necessary because there are events bound during `open()/close()`, among other component interactions that wouldn't be accounted for simply by using the class to hide.

2023-05-01 14:20 UTC, tmcconechy commented on src/components/ids-popup-menu/ids-popup-menu.ts
> +    openMenuElem?.classList.remove('is-open');
@EdwardCoyle while this would be better it would require using the jQuery API and introduce a dependency. Since this is about cancelling it only I think it would be fine so i did it this way.

2023-05-01 14:21 UTC, tmcconechy commented on src/components/ids-popup-menu/ids-popup-menu.ts
> +    this.#mo = new MutationObserver((mutations) => {
What if we do it only if elements are found in the page on the show? Think that would fly? I was thinking that maybe we dont add it unless we need it sort of thing.

2023-05-02 15:08 UTC, EdwardCoyle approved these changes

2023-05-02 15:41 UTC, deep7102 approved these changes
LGTM 🍌

2023-05-02 17:07 UTC, merged