904 - Fix to remove hash links for navigation with scroll view
infor-design/enterprise-wc pull request #1264
Opened 2023-05-01 17:40 UTC by deep7102

**Explain the details for making this change. What existing problem does the pull request solve?**
Fixed to remove hash links for navigation with scroll view
- Changed the logic to move the slides
- Add api methods (play, stop, toggle, first, last, previous, next, slideTo)
- Add events (some veto able)
- Add tests/covrage

**Related github/jira issue (required)**:
Closes #904

**Steps necessary to review your pull request (required)**:
Pull this branch and build/run the demo app
- Navigate to:
- http://localhost:4300/ids-scroll-view/example.html
- http://localhost:4300/ids-scroll-view/sandbox.html
- See url when move slides, does not use hash links
- See the api calls should work
- Should work fine with other platforms(angular etc..)

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2023-05-01 21:07 UTC, jdilag90 commented on src/components/ids-scroll-view/ids-scroll-view.ts
> +    };
Can we use a setTimeout to handle delay instead of a raf? If you insert a `console.log` inside `repeatOften()` you can see the function gets run ~1k times on a 60hz display.

2023-05-01 21:11 UTC, jdilag90 commented on src/components/ids-scroll-view/ids-scroll-view.ts
> +    };
Everything else looks good, one other thing. `currentSlideNumber()` sometimes returns a decimal since `scrollLeft` is used in the calculation

2023-05-02 11:38 UTC, deep7102 commented on src/components/ids-scroll-view/ids-scroll-view.ts
> +    };
Thanks! @jdilag90 
 - Updated now, `currentSlideNumber()` to be return whole number or undefined
 - About handle delay I had in mind RAF is more better in all cases epically in performance, I had read few articles in past like as: https://css-tricks.com/using-requestanimationframe/#aa-why-better or https://www.paulirish.com/2011/requestanimationframe-for-smart-animating. But after your comment I think about it more... and bit confuse now, because you have point too. It run with every frame also RAF come with some good stuff which `setTimeout()` or `setInterval()` not supported (like stops automatically when inactive, more battery-friendly etc.)
 - I can take some help here please guide, should we keep as RAF? or I can replace with `setInterval()`, because both ceases have some give or take.

2023-05-02 13:23 UTC, tmcconechy commented on src/components/ids-scroll-view/ids-scroll-view.ts
> +    };
Can we avoid both a Raf and setTimeout? Thats ideal. So far we avoided setTimeout entirely and it would be the very first one.

2023-05-02 14:35 UTC, deep7102 commented on src/components/ids-scroll-view/ids-scroll-view.ts
> +    };
@tmcconechy @jdilag90 
Updated now, please review

2023-05-02 15:01 UTC, tmcconechy requested changes
@deep7102 i think the `loop` setting was not fully removed in all places

Also in terms of functionality i see one thing
1. http://localhost:4300/ids-scroll-view/example.html
2. swipe left and it updates the pager
3. but keep swiping to the end one and the pager is not updated... ui swipe so last one is in view.

2023-05-02 15:24 UTC, deep7102 commented on src/components/ids-scroll-view/README.md
> +- `loop` {boolean} sets the loop, true will loop back after next/previous reached to end
- When swipe the pager is updating soon it stops swiping, otherwise it flickering because too many call to set selected state. It move depends on how much force was applied while swipe. 
- `loop` setting we need it use with next/previous so if it set to true it can keep going around

2023-05-02 15:25 UTC, deep7102 commented on src/components/ids-scroll-view/demos/example.html
> -          <img class="camera-2" slot="scroll-view-item" alt="Slide 3, Sony Camera, Back Display"/>
Nothing wrong, looks like was just typo in alt text it should be 2nd slide so it updated

2023-05-02 15:27 UTC, deep7102 commented on src/components/ids-scroll-view/ids-scroll-view.ts
> +  get loop(): boolean {
No need to remove this setting

2023-05-02 15:36 UTC, jdilag90 commented on src/components/ids-scroll-view/README.md
> +- `loop` {boolean} sets the loop, true will loop back after next/previous reached to end
I think what Tim means is that the pager loses sync with the active slide. If you swipe left to the last camera image, the last circle in `ids-scroll-view-controls` isn't shown as selected

2023-05-02 15:55 UTC, tmcconechy approved these changes
Not seeing it now tho. @jdilag90 did you see it. Looked ok on device simulator but not with magic mouse. But will approve since i cant see it anymore

2023-05-02 16:04 UTC, jdilag90 approved these changes

2023-05-02 17:06 UTC, merged