1228 - Fix column click callback trigger with data grid
infor-design/enterprise-wc pull request #1288
Opened 2023-05-17 19:40 UTC by deep7102

**Explain the details for making this change. What existing problem does the pull request solve?**
Fixed pressing enter on a column header filter input field was executing the `column's click` callback for hyperlinks.

**Related github/jira issue (required)**:
Closes #1228

**Steps necessary to review your pull request (required)**:
Pull this branch and build/run the demo app
- Navigate to: http://localhost:4300/ids-data-grid/columns-click-callback.html
- Add some text on the first column header filter
- Press `Enter` key
- Column's click callback should not executed
- Press `Enter` key in first column's cell (any row)
- Should trigger column's click callback
- See console and should popup toast message

**Included in this Pull Request**:
- [x] A note to the change log.

2023-05-19 20:45 UTC, tmcconechy requested changes
As discussed:

- would rather not have to change the listeners to keyboard events
- as we will need it to support keyboard on the header row later

Also https://github.com/infor-design/enterprise-wc/issues/1228 needs fixing.

Lets look for a simpler fix next week on this specific issue.

2023-05-22 16:38 UTC, deep7102 commented
Thanks! @tmcconechy, updated now as simple fix.

2023-05-22 16:49 UTC, tmcconechy approved these changes

2023-05-24 13:56 UTC, EdwardCoyle approved these changes

2023-05-24 15:21 UTC, merged