4458 - Add field, trackdirty, validation and update input, labels
infor-design/enterprise-wc pull request #13
Opened 2020-10-15 19:15 UTC by deep7102

**Explain the details for making this change. What existing problem does the pull request solve?**
Added some basic components and mixin as below
- ids-field: wrapper for form fields
- ids-validation-message: wrapper to for validation messages
- ids-trackdirty-mixin: to keep track user changes
- ids-validation-mixin: to check/set validation on form fields
- ids-icon: added new size `15`, use for validation message

Update some feature as:
ids-input: add attributes state, validation and dispatch basic events
ids-label: add attributes state, audible, required

**Related github/jira issue (required)**:
Fixes infor-design/enterprise-ng#4458

**Steps necessary to review your pull request (required)**:
- Pull this branch and build/run the demo app
- Navigate to: http://localhost:4300
- See the styles for validation message (icons, color and audible text for each type)
- Test ids-fields as
   - First Name (required and trackdirty)
   - Last Name (trackdirty only)
   - Email (required, email and no trackdirty)
- Test enable/disable/readonly 

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [ ] A note to the change log.

2020-10-16 18:56 UTC, tmcconechy commented on src/ids-base/ids-trackdirty-mixin.js
> +  useTrackdirty: false,
Whats the idea around this? i dont follow

2020-10-16 19:02 UTC, tmcconechy requested changes
Just a few comments but looks good

- [ ] Some errors in the console on http://localhost:4300/ids-field
- [ ] The labels arent working (cant click them to focus the field). I tried adding a for and id and this didnt work. So what im thinking we try is add the label in with input. The means that we cant use the ids-label component in it. It would be like this in the template. Lets see if this works.

```
<label for="x">
</input id="x">
```
- [ ] Can we add more complete input styles from current uplift?
- [ ] Maybe ids-dirty-tracker sounds better than trackdirty
- [ ] Eventually tests and docs and a typings file(s)

2020-10-16 19:02 UTC, tmcconechy commented on src/ids-input/ids-input.js
> +  set fieldState(val) {
What is field-state for? It seems a bit generic sounding i dont follow it.

2020-10-16 19:02 UTC, tmcconechy commented on src/ids-label/ids-label.js
> +  set fieldState(val) {
Again im not sure about fieldState - maybe we need to be more specific with a name?

2020-10-16 19:02 UTC, tmcconechy commented on src/ids-label/ids-label.scss
> +  &.audible {
I think Ed has this on His PR as well but i like having it in ids-label. Css @EdwardCoyle

2020-10-19 13:45 UTC, deep7102 commented on src/ids-base/ids-trackdirty-mixin.js
> +  useTrackdirty: false,
- I was doing something else, and this logic left in there. You right we do not need this anymore because now doing different way, so going to remove `useTrackdirty`

2020-10-19 13:49 UTC, deep7102 commented
> Just a few comments but looks good
> 
>     * [1]  Some errors in the console on http://localhost:4300/ids-field
> 
>     * [2]  The labels arent working (cant click them to focus the field). I tried adding a for and id and this didnt work. So what im thinking we try is add the label in with input. The means that we cant use the ids-label component in it. It would be like this in the template. Lets see if this works.
> 
> 
> ```
> <label for="x">
> </input id="x">
> ```
> 
>     * [3]  Can we add more complete input styles from current uplift?
> 
>     * [4]  Maybe ids-dirty-tracker sounds better than trackdirty
> 
>     * [5]  Eventually tests and docs and a typings file(s)

1) will check for errors: http://localhost:4300/ids-field
2) yes, same way I thought we need both input + label under one shadow root. I was thinking `ids-input` to extend the `ids-label` this way we do not have to manage different set of styles/features as `ids-label` having we should do this for all low level elements which go with `label + element` like textarea, checkbox, radio etc.

3) yes, will check for input styles from current uplift
4) yes, I do like `ids-dirty-tracker` better than `trackdirty`
5) yes, was thinking to do after all final then write tests and docs about

2020-10-19 13:50 UTC, deep7102 commented on src/ids-icon/ids-icon.js
> +  15: 15
- sure, will try both `small and medium` sizes. I was trying to match with EP styles

2020-10-19 13:51 UTC, deep7102 commented on src/ids-input/ids-input.js
> +  set fieldState(val) {
- `field-state` to keep track for `enabled/disabled/readonly`. Put this on `ids-filed`, because `ids-filed ` is main root level for input and see that as main input component which should hold more info about like dirty-tracker, error-msg or what type of input inside etc. Please let me know if you have other name for this property was can update

2020-10-19 13:52 UTC, deep7102 commented on src/ids-label/ids-label.js
> +  set fieldState(val) {
Please let me know if you have other name for this property was can update

2020-10-19 14:05 UTC, tmcconechy commented on src/ids-icon/ids-icon.js
> +  15: 15
Yeah please do - we want to remove this inconsistency in sizes.

2020-10-19 14:06 UTC, tmcconechy commented on src/ids-input/ids-input.js
> +  set fieldState(val) {
Does it work to just only use enabled/disabled/readonly each on their own?

2020-10-19 14:08 UTC, tmcconechy commented
For the label problem. Try adding the label in with ids-input for now and get it working. I think i can see maybe that we dont need ids-field then. As all elements like ids-input , ids-checkbox ect will all container their own label.

Then add a label attribute on the ids-input and then the label is in the template? Think that could work.

2020-10-19 14:10 UTC, EdwardCoyle commented on src/ids-label/ids-label.scss
> +  &.audible {
The use case on mine is similar, but it's specifically on "audible" spans inside of buttons.  Makes sense to have it in both.  Is there a way we could share it -- does it belong in the base styles?

2020-10-19 14:22 UTC, tmcconechy commented on src/ids-label/ids-label.scss
> +  &.audible {
What i was thinking maybe is 
- if labels are in the form element components we dont need to support labels in ids-label
- rename ids-label to ids-text
- add an audible property to it
- use it in both places as ids-text to make the audible spans.

2020-11-03 21:28 UTC, closed without merging

2020-11-03 21:33 UTC, deep7102 commented
Close this, so can use other PR https://github.com/infor-design/enterprise-wc/pull/16