1244 - Add support for uppercase, disabled rows, collapse/expand all and redrawn event with data grid
infor-design/enterprise-wc pull request #1312
Opened 2023-06-01 19:18 UTC by deep7102

**Explain the details for making this change. What existing problem does the pull request solve?**
Added support with data grid as:
 - Text uppercase (cells, editors and filters)
 - Disabled rows
 - A icon`(+)` in column header to collapse/expand all rows for expandable or tree rows
 - Api methods `collapseAll()`, `expandAll()` for expandable or tree rows
 - Event that omits after redraw
 - Tests/coverage/docs and cleanup

**Related github/jira issue (required)**:
Closes #1244

**Steps necessary to review your pull request (required)**:
Pull this branch and build/run the demo app
http://localhost:4300/ids-data-grid/uppercase.html
- Add some text on the first column header filter
- See columns `Product Name`, `Activity` `Action` text should be uppercase
- Use editor/filter inputs should also text be uppercase

http://localhost:4300/ids-data-grid/disabled-rows.html
- See rows (2,3,4,5) should be disabled
- Cells not be editable/clickable and all rows grayed out to look disabled

http://localhost:4300/ids-data-grid/tree-grid-expand-collapse.html
- See 2nd column header `Name`, should have `(+)`icon
- Click on this (+) icon to collapse/expand all rows
- Top button use api methods to collapse/expand all rows
- FYI: here in this example page the api method calls and `(+)` icon in header are not in sync, for example after page load/refresh very first thing if clicked top button `Collapse All` then click in header `(+)` icon. It will not expand all rows. Need to click two times in order to expand all rows

http://localhost:4300/ids-data-grid/after-redraw.html
- Open developer tools
- Page load/refresh
- See logs in console should fired event `redrawn`

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2023-06-02 15:53 UTC, tmcconechy requested changes
Looks really good but a few comments:

- see inline comments regarding docs
- for after-redraw can we call it afterrendered (example and setting name)
- i think for http://localhost:4300/ids-data-grid/tree-grid-expand-collapse.html when you click it it should at least toggle (when you click it toggles from open to closed) it doesnt have to match every row for mixed case but when you click it i think just toggle the state

2023-06-02 15:53 UTC, tmcconechy commented on src/components/ids-data-grid/README.md
> +|`uppercase` | {boolean} | Allows you to set the text as uppercase.
I think this should go in column settings section not grid settings section

2023-06-02 15:53 UTC, tmcconechy commented on src/components/ids-data-grid/README.md
> +- `redrawn` Fires after redraw the data grid.
Can we call this `afterrendered` as i think that matches other components better

2023-06-02 15:53 UTC, tmcconechy commented on src/components/ids-data-grid/README.md
>  - `exoprtToExcel(format: 'csv' | 'xlsx', filename: string, keepGridFormatting: boolean)` Export datagrid datasource to an excel file. This keeps grid formatting by default.
```suggestion
- `exportToExcel(format: 'csv' | 'xlsx', filename: string, keepGridFormatting: boolean)` Export datagrid datasource to an excel file. This keeps grid formatting by default.
```

2023-06-02 18:31 UTC, deep7102 commented on src/components/ids-data-grid/README.md
> +- `redrawn` Fires after redraw the data grid.
Updated now, event name to `afterrendered`

2023-06-02 18:32 UTC, deep7102 commented on src/components/ids-data-grid/README.md
> +|`uppercase` | {boolean} | Allows you to set the text as uppercase.
Updated now, to move to column section

2023-06-02 18:32 UTC, deep7102 commented
@tmcconechy
Updated now, all the points you saw.

2023-06-05 14:51 UTC, tmcconechy approved these changes

2023-06-06 15:12 UTC, clayinfor approved these changes
Looks very good 👍

2023-06-06 15:15 UTC, merged