1284 - Datagrid tree not selecting or collapsing all children
infor-design/enterprise-wc pull request #1350
Opened 2023-06-26 15:36 UTC by clayinfor

**Explain the details for making this change. What existing problem does the pull request solve?**

Collapsing children on datagrid tree-view - all the children should be collapsed
Selecting parent checkbox - all the children should have the checkbox ticked
Deselecting parent checkbox - all children should have the checkbox tick removed

**Related github/jira issue (required)**:

Closes #1284 

**Steps necessary to review your pull request (required)**:

1. Check out branch and run: `nvm use && npm run start`
2. Open http://localhost:4300/ids-data-grid/tree-grid.html
3. Verify you're able to collapse all parents and children on tree grid using plus/minus sign
4. Verify you're able to select all parents and children on tree grid using checkboxes
5. Run tests to ensure they all pass: `npx jest -- data-grid-func-test`
6. Run `npm run publish:link`
7. Switch to `enterprise-wc-examples/angular-ids-wc`
8. Copy zip file from #1284 to `src/app/components/ids-data-grid/demos/`
9. Add `tree` route for `TreeComponent` here: `src/app/components/ids-data-grid/ids-data-grid-routing.module.ts`
10. Add `TreeComponent` here: src/app/components/ids-data-grid/ids-data-grid.module.ts
11. Run `rm -fr ./.angular/cache`
12. Run `npm run build`
13. Run `npm run start`
14. Verify you're able to collapse all parents and children on tree grid using plus/minus sign
15. Verify you're able to select all parents and children on tree grid using checkboxes

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2023-06-27 14:16 UTC, tmcconechy requested changes
@clayinfor everything looks good regarding expanding and collapsing but i see a related issue

1. on http://localhost:4300/ids-data-grid/tree-grid.html
2. collapse all parents (Building 4 and Building 5) so they are all collapsed
3. sort on the name column
4. notice after rerender/sort the children are reopened. (should be a rowExpanded) on the data it reads in the formatter. So should respect sorting.

2023-06-29 21:31 UTC, clayinfor commented
> @clayinfor everything looks good regarding expanding and collapsing but i see a related issue
> 
> 1. on http://localhost:4300/ids-data-grid/tree-grid.html
> 2. collapse all parents (Building 4 and Building 5) so they are all collapsed
> 3. sort on the name column
> 4. notice after rerender/sort the children are reopened. (should be a rowExpanded) on the data it reads in the formatter. So should respect sorting.

hey @tmcconechy , the sort issue you mentioned here is now fixed

2023-06-30 16:36 UTC, tmcconechy submitted a review, later dismissed
Looks good. Thanks @clayinfor just tried to update the PR to retrigger percy. Lets see if that helps

2023-07-06 16:57 UTC, EdwardCoyle approved these changes

2023-07-07 14:29 UTC, merged