1042 - update ids-list-view-item (added ids-list-view-item child component)
infor-design/enterprise-wc pull request #1377
Opened 2023-07-11 11:40 UTC by clayinfor

**Explain the details for making this change. What existing problem does the pull request solve?**

This PR adds support for `ids-list-view-item` child component to IdsListView.

```html
<ids-list-view selectable="multiple" sortable>
  <ids-list-view-item>
    <ids-text font-size="16" type="h2">First Column</ids-text>
    <ids-text font-size="12" type="span">ID: 1</ids-text>
    <ids-text font-size="12" type="span">Comments: One</ids-text>
  </ids-list-view-item>
  <ids-list-view-item active>
    <ids-text font-size="16" type="h2">Second Column</ids-text>
    <ids-text font-size="12" type="span">ID: 2</ids-text>
    <ids-text font-size="12" type="span">Comments: Two</ids-text>
  </ids-list-view-item>
  <ids-list-view-item disabled>
    <ids-text font-size="16" type="h2">Third Column</ids-text>
    <ids-text font-size="12" type="span">ID: 3</ids-text>
    <ids-text font-size="12" type="span">Comments: Three</ids-text>
  </ids-list-view-item>
</ids-list-view>
```

**Related github/jira issue (required)**:

Closes #1042 

**Steps necessary to review your pull request (required)**:

1. Check out branch and run: `nvm use && npm run start`
2. Open http://localhost:4300/ids-list-view/list-view-items.html
4. Open http://localhost:4300/ids-list-view/list-view-items-selectable-mixed.html
5. Open http://localhost:4300/ids-list-view/list-view-items-selectable-multiple.html
6. Open http://localhost:4300/ids-list-view/list-view-items-sortable.html
7. Run tests to ensure they all pass: `npx jest -- list-view-func-test`

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2023-07-12 14:10 UTC, tmcconechy requested changes
Everything looks good but a few trivial doc/ suggestions inline.

Also on some of the examples im wondering about a few things

1) on http://localhost:4300/ids-list-view/list-view-items.html i see two selected but i cant seem to change selection. Maybe just remove selection from the example page since its on another page?
2) similarly on http://localhost:4300/ids-list-view/list-view-items-selectable-mixed.html i cant seem to "activate" the rows (change by clicking)
3) http://localhost:4300/ids-list-view/list-view-items-selectable-multiple.html also a problem changing selection
4) on http://localhost:4300/ids-list-view/list-view-items-search.html a) the search doesnt seem to work and b) it would look better if it was 100% width

Otherwise really nice work here.

2023-07-12 14:10 UTC, tmcconechy commented on doc/CHANGELOG.md
> +- `[ListView]` Added support for `ids-list-view-item` child component. ([#1042](https://github.com/infor-design/enterprise-wc/issues/1042))
Alpha. Order please

2023-07-12 14:10 UTC, tmcconechy commented on src/components/ids-list-view/ids-list-view-item.ts
> + * IDS List View Component
```suggestion
 * IDS List View Item Component
```

2023-07-12 14:10 UTC, tmcconechy commented on src/components/ids-list-view/ids-list-view-item.ts
> +  set disabled(value: boolean) {
Can we add JS Doc for all these setters?

2023-07-12 19:33 UTC, tmcconechy commented on doc/CHANGELOG.md
> +- `[ListView]` Added support for `ids-list-view-item` child component. ([#1042](https://github.com/infor-design/enterprise-wc/issues/1042))
Can you add this in new section `### 1.0.0-beta.14 Fixes` now (depending if that section is there yet if you merge main)

2023-07-17 13:35 UTC, EdwardCoyle commented
Overall everything looks great with this.  However, I'm seeing something when the main example page loads -- seems like one in every five-or-so refreshes causes the List View to populate with no actual contents, and more rows.  Most of the time, the correct behavior occurs.  I managed to catch it a couple times in the video below:

[Untitled_ Jul 17 2023 9_31 AM.webm](https://github.com/infor-design/enterprise-wc/assets/3249601/4700f8e7-046a-4a9f-b4ad-8c5fa40f0ed8)

2023-07-18 19:39 UTC, tmcconechy commented
@clayinfor put WIP on as i keep checking this but appears incomplete from some comments. Just remove the tag when your done 👍🏻

2023-07-24 15:28 UTC, clayinfor commented
Hey @tmcconechy , I removed the WIP label from this as it's good to go... I was actually working on an almost total refactor but I'm running out of time in the sprint... so I will have to circle back to it later.  

The issue @EdwardCoyle pointed out seems to happen for me in incognito mode and I think it has something to do with the JSON file not being asynchronously loaded sometimes. Will have to look into that later as well.

2023-07-24 15:44 UTC, clayinfor commented
hey @tmcconechy , I'm thinking we merge this one, and then I'll circle back to the other PR to get that merged later.

2023-07-24 16:59 UTC, tmcconechy commented
@clayinfor i still see all of these issues:

1. on http://localhost:4300/ids-list-view/list-view-items.html i see two selected but i cant seem to change selection. Maybe just remove selection from the example page since its on another page?
2. similarly on http://localhost:4300/ids-list-view/list-view-items-selectable-mixed.html i cant seem to "activate" the rows (change by clicking)
3. http://localhost:4300/ids-list-view/list-view-items-selectable-multiple.html also a problem changing selection
4. on http://localhost:4300/ids-list-view/list-view-items-search.html a) the search doesnt seem to work and b) it would look better if it was 100% width

So basically search and selection dont work anymore.

2023-07-25 14:40 UTC, merged