1339 - IdsTabs alabaster cleanup
infor-design/enterprise-wc pull request #1389
Opened 2023-07-18 14:35 UTC by jdilag90

**Explain the details for making this change. What existing problem does the pull request solve?**
Adds alabaster changes to tab variants
Here's the [figma](https://www.figma.com/file/gRpli2TgQ3scLE6GF4e2Hz/Alabaster-Clean-up?type=design&node-id=127-38900&mode=design&t=dpqYzczH4cRrCmdA-0)

**Related github/jira issue (required)**:
Fixes #1339 

**Steps necessary to review your pull request (required)**:
1. Checkout branch, `npm install`, `npm run start`
2. Go to each http://localhost:4300/ids-tabs examples
3. Test tab styles, by clicking, hovering, keyboard navigating/Tabbing
4. Test each page in light, dark, contrast mode

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2023-07-19 16:20 UTC, tmcconechy requested changes
Just a few things but overall looks excellent.

http://localhost:4300/ids-tabs/app-example.html
- for disabled color a) keep the background color the same as normal tabs b) make the text slate 50 (was decided in QA on other issue)
- resize the page so the more button shows, then click + or reload and see the tabs change height
- hover state on the X should a) go up in icon color one shade b) have 8px border-radius c) should use  background-color: rgba(0,0,0,.1) instead of azure
<img width="63" alt="Screenshot 2023-07-19 at 12 05 01 PM" src="https://github.com/infor-design/enterprise-wc/assets/814283/66e60dd5-1d3b-4c7d-81d3-3f1d04d51bc7">
- text should go to ellipsis when cut 
<img width="140" alt="Screenshot 2023-07-19 at 12 05 46 PM" src="https://github.com/infor-design/enterprise-wc/assets/814283/1b7b6017-fdcf-4c50-a094-2b5ce031591c">
- can all the module tabs get X? i think thats a setting right?

http://localhost:4300/ids-tabs/counts.html
- also the x should just change the icon glow, should a) go up in icon color one shade b) have 8px border-radius c) should use  background-color: rgba(0,0,0,.1) instead of azure

http://localhost:4300/ids-tabs/dismissible.html
- same with hover glow

http://localhost:4300/ids-tabs/header-tabs.html
- can you check the height it looks combined a lot more https://main-enterprise.demo.design.infor.com/components/tabs-header/example-index.html?colors=ffffff

http://localhost:4300/ids-tabs/vertical.html
- think it needs a max width and then text ellipsis (arbitrary max for now maybe 250) - can see this if you make the text very large (can maybe use ` <ids-text overflow="ellipsis" tooltip="true">`

Did you check through all these a bit?

https://www.figma.com/file/gRpli2TgQ3scLE6GF4e2Hz/Alabaster-Clean-up?type=design&node-id=137-31812&mode=design&t=sdx2fkFQhryVNv52-0 

https://www.figma.com/file/gRpli2TgQ3scLE6GF4e2Hz/Alabaster-Clean-up?type=design&node-id=527-33769&mode=design&t=yBF5DWr1k7WBWJo3-0

https://www.figma.com/file/gRpli2TgQ3scLE6GF4e2Hz/Alabaster-Clean-up?type=design&node-id=478-32401&mode=design&t=XGH0gcwpDJhJ1Gjv-0

A bit hard to follow bit maybe worth a second look

2023-07-21 20:19 UTC, tmcconechy commented
Same here with the change log in beta.14 please @jdilag90

2023-07-24 14:34 UTC, tmcconechy submitted a review, later dismissed

2023-07-24 15:00 UTC, EdwardCoyle submitted a review, later dismissed

2023-07-24 15:04 UTC, merged