Added window-size breakpoints for grid flow.
infor-design/enterprise-wc pull request #1406
Opened 2023-07-27 17:32 UTC by yousef-elkaisi

**Explain the details for making this change. What existing problem does the pull request solve?**
Allows us to adjust the flow attribute on an ids-layout-grid depending on the screen size.

**Related github/jira issue (required)**:
[Issues: 1405](https://github.com/infor-design/enterprise-wc/issues/1405)
**Steps necessary to review your pull request (required)**:
Included an example-flow.html file to view the different flows and test the responsiveness when changing the screen size.

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [ ] A note to the change log.

2023-07-27 17:59 UTC, jmacaluso711 requested changes
@yousef-elkaisi Looks good! Just 1 minor change in the example. Can you update the titles to be consistent with the other examples?

You can use the following as a template:

```
  <ids-layout-grid
        auto-fit="true"
        padding="md"
      >
        <ids-layout-grid-cell>
          <ids-text font-size="12" type="h1">8 Flow Row</ids-text>
        </ids-layout-grid-cell>
  </ids-layout-grid>

  ...  

```

2023-07-27 18:06 UTC, tmcconechy commented on doc/CHANGELOG.md
> +- `[LayoutGrid]` Added breakpoint sizes for the flow attribute in the grid-layout. ([#1405](https://github.com/infor-design/enterprise-wc/issues/1405))
Also minor thing but can you put this in alphabetical order within this section?

2023-07-28 13:33 UTC, tmcconechy approved these changes

2023-07-31 14:29 UTC, tmcconechy approved these changes

2023-08-01 14:13 UTC, merged