1311 - datagrid-header tooltip-callback fix
infor-design/enterprise-wc pull request #1418
Opened 2023-08-03 14:28 UTC by clayinfor

**Explain the details for making this change. What existing problem does the pull request solve?**

Closes #1311 

**Related github/jira issue (required)**:

**Steps necessary to review your pull request (required)**:

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2023-08-03 15:52 UTC, tmcconechy requested changes
@clayinfor can you add another check as i described. Where it only "always" shows the tooltip if the tooltip is set as an option to provide a custom tooltip?

Logic should be..
- if a custom tooltip is shown, always show it regardless if cut off or not
- if no custom tooltip is added, it only shows the title text if cut off.

Issue:
http://localhost:4300/ids-data-grid/example.html
- hovering every column now shows the tooltip which is redundent
- should only show on the ones with ...

Can maybe just check if the option is set/true/false

2023-08-03 19:20 UTC, clayinfor commented
hey @tmcconechy , I've updated PR in line with your suggestion above.

2023-08-04 14:31 UTC, tmcconechy approved these changes
Looks great now. Thanks @clayinfor

2023-08-04 15:26 UTC, jdilag90 submitted a review, later dismissed

2023-08-04 16:03 UTC, merged