Chore: Bump 'ids-identity' package to latest (4.14.11)
infor-design/enterprise-wc pull request #1444
Opened 2023-08-21 15:45 UTC by EdwardCoyle

**Explain the details for making this change. What existing problem does the pull request solve?**
This PR just bumps the current version of the design system assets used in the Web Components.  I noticed some colors were off and traced it to this package being on an older version.

**Related github/jira issue (required)**:
Fixes #1427 

**Steps necessary to review your pull request (required)**:
- Pull/build/run
- Open the demoapp and smoke test (color differences I noticed were on some datagrid filters on http://localhost:4300/ids-data-grid/filter-custom.html)

2023-08-21 15:46 UTC, tmcconechy submitted a review, later dismissed

2023-08-22 13:17 UTC, jdilag90 approved these changes

2023-08-22 18:21 UTC, tmcconechy requested changes
Something is definitely wrong with this package as the fills are hardcoded

![Screenshot 2023-08-22 at 2 19 13 PM](https://github.com/infor-design/enterprise-wc/assets/814283/f996c4d5-4ec9-4ec1-a709-3de67082b62f)

Will discuss with @corpulent it happens in Enterprise too

![Screenshot 2023-08-22 at 2 21 17 PM](https://github.com/infor-design/enterprise-wc/assets/814283/d82aa1f9-dddb-459b-abc6-f7a679d8ea2b)

2023-08-23 14:18 UTC, tmcconechy commented
Closing this for now until icons are fixed

2023-08-23 14:18 UTC, closed without merging