1429 - IdsPopupMenu rtl support
infor-design/enterprise-wc pull request #1448
Opened 2023-08-29 16:55 UTC by jdilag90

**Explain the details for making this change. What existing problem does the pull request solve?**
Added support for rtl in our context menu popups

**Related github/jira issue (required)**:
Fixes #1429 

**Steps necessary to review your pull request (required)**:
1. Go to http://localhost:4300/ids-data-grid/contextmenu.html
2. And go to http://localhost:4300/ids-popup-menu/example.html
3. Change to an RTL lang, test that the submenu popup opens on the left side
4. Check that keyboard navigation opens submenu with `ArrowLeft`, and closes submenu with `ArrowRight`

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2023-08-31 15:50 UTC, tmcconechy requested changes
Looks good. And this is a nit pick but the arrows do not seem 100% mirrored. It looks like that are too far to the right they appear centered in the field but look just a pixel or two off comparing

<img width="699" alt="Screenshot 2023-08-31 at 11 50 04 AM" src="https://github.com/infor-design/enterprise-wc/assets/814283/773d5f21-4d68-4995-8858-01444b1d05e7">

2023-09-05 13:57 UTC, clayinfor submitted a review, later dismissed

2023-09-05 17:16 UTC, tmcconechy submitted a review, later dismissed
Fixed the RTL issue for you. Just a unneeded rule since we can use margin-inline to place

2023-09-05 18:54 UTC, EdwardCoyle submitted a review, later dismissed

2023-09-06 17:38 UTC, merged