1298 - Use Date/Time Picker Popups in IdsDataGridCell
infor-design/enterprise-wc pull request #1463
Opened 2023-09-08 18:18 UTC by EdwardCoyle

**Explain the details for making this change. What existing problem does the pull request solve?**
This PR replaces the usage of IdsDatePicker/IdsTimePicker directly in grid cells, in favor of the same solution used in the filter row inputs -- IdsDatePickerPopup and IdsTimePickerPopup attached to trigger fields, controlled by their respective grid cell editors.  This fixes a problem where the popups were previously unable to escape the stacking context enforced by the data grid's shadow root container.

**Related github/jira issue (required)**:
Fixes #1298

**Steps necessary to review your pull request (required)**:
- Pull/build/run
- Open http://localhost:4300/ids-data-grid/editable.html
- Use the "Pub. Date" and "Pub. Time" columns to set the value of the cells
- Open the popups attached to these cells.  The popups should be able to escape the boundaries of the data grid.

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2023-09-11 16:02 UTC, jdilag90 commented
LGTM, ready to approve just some tests need adjusting

2023-09-11 18:23 UTC, tmcconechy requested changes
@EdwardCoyle this introduced two things compared to https://main.wc.design.infor.com/ids-data-grid/editable.html

**1. Looses focus**
- click on the trigger icon in the cell
- select a value
- notice the cell is no longer focused after selection

**2. It doesnt work if you enter the cell first**

- click on cell (not on the trigger icon) so it goes into the cell first
- try and click the trigger icon and notice the popup doesnt open.

(Only works if you click the icon on the cell)

2023-09-12 14:44 UTC, tmcconechy commented
@EdwardCoyle i reran the tests to confirm but looks like something coming up there.

2023-09-14 20:51 UTC, jdilag90 approved these changes

2023-09-15 16:00 UTC, tmcconechy approved these changes

2023-09-15 16:00 UTC, merged