1481 Fix IdsDataGridCell's checkbox formatter alignment
infor-design/enterprise-wc pull request #1537
Opened 2023-10-10 18:04 UTC by EdwardCoyle

**Explain the details for making this change. What existing problem does the pull request solve?**
This PR implements propagation of the `align` property of IdsGridColumnOptions into the checkbox formatter, allowing it to set alignment of the checkbox within the column.

**Related github/jira issue (required)**:
Closes #1481

**Steps necessary to review your pull request (required)**:
- Pull/build/run
- Open http://localhost:4300/ids-data-grid/columns-checkbox-alignment.html
- See that checkbox alignment should match the column header
- Try row heights and make sure the checkbox padding matches the "ID" column's text

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2023-10-11 15:28 UTC, tmcconechy requested changes
This looks great @EdwardCoyle but i see in the percy images it messed up some of the header checkboxes from being centered.

See: https://percy.io/00aaa841/enterprise-wc/builds/30574915/changed/1689443610?browser=chrome&browser_ids=48&subcategories=approved&viewLayout=overlay&viewMode=new&width=1280&widths=375%2C1280

Or http://localhost:4300/ids-data-grid/ids-data-grid-tree-grid.html
Expect checkbox to stay centered on header checkbox column.

2023-10-11 17:44 UTC, EdwardCoyle commented
@tmcconechy good catch, I changed the scoping of the alignment rules to only affect the cells, considering the "selection" checkboxes should always be centered.

For testing this I tried these samples and it seems to have fixed the issue:
- http://localhost:4300/ids-data-grid/list-style.html
- http://localhost:4300/ids-data-grid/tree-grid-custom-css.html
- http://localhost:4300/ids-data-grid/tree-grid.html

2023-10-11 18:11 UTC, clayinfor approved these changes

2023-10-12 17:45 UTC, tmcconechy approved these changes

2023-10-12 17:45 UTC, merged