1664 - IdsDataGrid empty message height
infor-design/enterprise-wc pull request #1665
Opened 2023-11-29 16:09 UTC by jdilag90

**Explain the details for making this change. What existing problem does the pull request solve?**
Fixes an issue where the datagrid container loses its original inline style height when empty message mode is enabled.
https://github.com/infor-design/enterprise-wc/blob/349398009a9e081244c44d3c82044ad13442cb52/src/components/ids-data-grid/ids-data-grid-empty-message.ts#L115
I moved the line above to css where `height: unset !important` is only applied when ids-data-grid `.has-empty-message`.
The inline height applied by `auto-fit` should remain intact

**Related github/jira issue (required)**:
Closes #1664 

**Steps necessary to review your pull request (required)**:
1. Checkout branch
2. Go to http://localhost:4300/ids-data-grid/virtual-scroll.html
3. Run `const copy = $('ids-data-grid').data;` to create data copy
4. Run `$('ids-data-grid').data = [];` to make datagrid empty
5. Run `$('ids-data-grid').data = copy;` to re populate datagrid
6. Check that datagrid virtual-scroll still works ok
7. Also test on http://localhost:4300/ids-data-grid/example.html, to check non-virtual scroll examples

**Included in this Pull Request**:
- [ ] A test for the bug or feature.
- [x] A note to the change log.

2023-11-29 20:05 UTC, EdwardCoyle approved these changes
This looks great, thanks @jdilag90!  For sake of being thorough, I checked these as well -- all seems good:

- http://localhost:4300/ids-data-grid/empty-message.html
- http://localhost:4300/ids-data-grid/empty-message-custom-thru-slot.html
- http://localhost:4300/ids-data-grid/empty-message-custom-thru-settings.html

2023-12-04 17:51 UTC, tmcconechy requested changes
I think might be a bit more here.

1. when i run step `$('ids-data-grid').data = [];` first changes the size of the grid, this is probably an issue with the `auto-fit` setting, but as you change back and forth from the copy and [] you see it change
2. the empty message doesnt seem centered in auto-fit. Even on http://localhost:4300/ids-data-grid/empty-message.html it looks a little high up.

Can we take a look?

2023-12-11 16:49 UTC, EdwardCoyle approved these changes
@jdilag90 looks good to me

2023-12-11 19:56 UTC, tmcconechy approved these changes

2023-12-11 19:56 UTC, merged