1588 - datagrid fix for left/right arrow-keys to work inside editable-cell
infor-design/enterprise-wc pull request #1783
Opened 2024-01-19 17:47 UTC by clayinfor

**Explain the details for making this change. What existing problem does the pull request solve?**

**Related github/jira issue (required)**:

Closes #1588 

**Steps necessary to review your pull request (required)**:

**Included in this Pull Request**:
- [ ] Some documentation for the feature.
- [ ] A test for the bug or feature.
- [ ] A note to the change log.

2024-01-19 19:59 UTC, tmcconechy requested changes
@clayinfor looks good but there is two keyboard "behaviors" that have become now problematic but some of it will change here https://github.com/infor-design/enterprise-wc/issues/1682

We wanted to copy how that works. But the two things we should maybe look at now are

1. click in # cell, then arrow right to the editable cell. Start to type "a" for example and as you type it wil auto enter editable mode. But the value will change wrong 101 -> becomes 1101. I think instead it should select all text and type over it (so 101 becomes 1)
2. The tab is not working. Focus the first editable cell now tab and it should go to the next editable field. This works on https://main.wc.design.infor.com/ids-data-grid/editable-inline.html but poorly

Also tabing doesnt work on http://localhost:4300/ids-data-grid/editable.html (compared to https://main.wc.design.infor.com/ids-data-grid/editable.html)

With those i think we will be in a good place with this

2024-01-22 18:18 UTC, clayinfor commented
hey @tmcconechy , I updated the PR to get it closer to what you suggested in #1682 ... there's still some room for improvement, but I figure whoever gets that ticket can take it across the finish line =)

2024-01-23 19:34 UTC, tmcconechy approved these changes

2024-01-23 19:34 UTC, tmcconechy approved these changes

2024-01-29 18:04 UTC, tmcconechy approved these changes

2024-01-30 17:56 UTC, tmcconechy approved these changes

2024-01-31 19:59 UTC, jdilag90 approved these changes

2024-01-31 20:24 UTC, merged