4972 ids rating wc - WIP 🚧
infor-design/enterprise-wc pull request #190
Opened 2021-05-19 12:44 UTC by danielortiz1982

**Explain the details for making this change. What existing problem does the pull request solve?**

**Related github/jira issue (required)**:

**Steps necessary to review your pull request (required)**:

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [ ] A note to the change log.

2021-05-19 19:50 UTC, tmcconechy commented
@danielortiz1982 - just remove the WIP and add a PR description (see some others for reference) at that point I / we will review the PR

2021-05-20 14:20 UTC, tmcconechy requested changes
See small comments this is looking very good now....but needs some final touch ups

1. Remove draft status?
1. Edit the PR and fill in the template 
1. Either fix the coverage or add /* istanbul ignore next */ to the sections that dropped the coverage if you cant figure it out?
1. add the e2e and percy tests like the others (should take only a few moments)

2021-05-20 14:20 UTC, tmcconechy commented on src/ids-rating/README.MD
> +## States
I dont think we need to include these static images as they will be out of date. So i would suggest removing the variants section and just mention the "decimals" version in the states or show a code example for it in the above section.

2021-05-20 14:20 UTC, tmcconechy commented on src/ids-rating/README.MD
> +## Designs
Can remove this section its already out of date

2021-05-20 14:20 UTC, tmcconechy commented on src/ids-rating/TODO.MD
> +- [] Stars attribute render stars on setter and getter
Can we merge the CHECKLIST.md with the TODO.md into one (just TODO.md) as they seem redundant.

2021-05-20 14:20 UTC, tmcconechy commented on src/ids-rating/ids-rating.js
> +// @ts-ignore
I think all ts-ignores can now safely be removed

2021-05-20 14:20 UTC, tmcconechy commented on src/ids-rating/ids-rating.js
> +      return [...props.MODE, props.VERSION, props.VALUE, 'stars', props.READONLY, props.CLICKABLE, props.COMPACT, props.SIZE];
Minor but i started to alphabetize these

2021-05-20 14:20 UTC, tmcconechy commented on src/ids-rating/ids-rating.js
> +     * @returns {Array<string>} this component's observable properties
Try and add brief comment to all methods

2021-05-20 14:20 UTC, tmcconechy commented on src/ids-rating/ids-rating.scss
> +#rating {
Is it going to be a problem that the ID is hard coded? I think i would make it class="rating" instead in the template

2021-05-21 16:34 UTC, tmcconechy approved these changes

2021-05-24 14:05 UTC, EdwardCoyle approved these changes
Looks great, well done!

2021-05-24 14:06 UTC, tmcconechy commented
Great! Will merge so i can fix my other PR with these changes

2021-05-24 14:07 UTC, merged