139 ids button accessibility options
infor-design/enterprise-wc pull request #196
Opened 2021-05-25 15:35 UTC by rob2d

**Explain the details for making this change. What existing problem does the pull request solve?**

This branch is mainly to add accessibility options so that both Axe tests and Vox tool works properly with WC for some compound components (in this case for the IdsSpinbox). 

(1) Because of some quirks in the shadowDOM, tabIndex has to persist for -1 to the WC as well for disabling things.
(2) There was also some inconsistency with disabled not applying to the button when toggling enabled => disabled that (discovered during dev on the spinbox component for #139).

**Related github/jira issue (required)**:

Supports #139 but does not have a direct ticket on JIRA.

**Steps necessary to review your pull request (required)**:

- pull this branch (`139-ids-button-accessibility-options`)
- do a quick sanity check that buttons do not behave abnormally/regressively with tabbing on test page.
- see that tests pass on PR

**Included in this Pull Request**:
- [X] An e2e or functional test for the bug or feature.
- [ ] A note to the change log.

2021-05-25 17:48 UTC, tmcconechy approved these changes

2021-05-25 19:31 UTC, tmcconechy requested changes
Lets remove the role, lets just test it works on your end

2021-05-25 19:31 UTC, tmcconechy commented on src/ids-button/ids-button.js
> +    if (!this.hasAttribute('role')) {
Suggest removing this entirely it works in Axe without it. So no role for now. This causes an issue in chrome vox where it doesnt read "button" but this works in voice over and other screen readers so this will probably get fixed at some point

```
  if (!this.hasAttribute('role')) {
    this.setAttribute('role', 'button');
   }
```

2021-05-27 14:21 UTC, tmcconechy approved these changes

2021-05-27 16:34 UTC, deep7102 submitted a review, later dismissed

2021-05-27 16:44 UTC, EdwardCoyle requested changes
@rob2d just a minor thing regarding the attribute changes here, but other than that this should be OK

2021-05-27 16:44 UTC, EdwardCoyle commented on src/ids-button/ids-button.js
> -    this.shouldUpdate = true;
This line is still needed if future updates to properties are to occur (a check for `shouldUpdate` wraps the property updates in this component).  Maybe move this to L297?

2021-05-27 16:44 UTC, EdwardCoyle commented on src/ids-button/ids-button.js
>      this.shouldUpdate = true;
This one can go as well

2021-05-28 20:10 UTC, rob2d commented
@EdwardCoyle adjustments made to a reasonable extent here -- besides that there's no noticeable performance/functional issues that I observed and don't have workarounds for WC framework causing the setter issues. If you would like to spend time to address this I am perfectly ok with it but it isn't something I can be working on further this sprint and was a blocker for #139 that was a little out of scope here.

2021-06-01 13:04 UTC, tmcconechy reviewed
Looks good to me if @EdwardCoyle is happy with it now

2021-06-01 13:32 UTC, EdwardCoyle commented
@rob2d Looks good to me now - just removed that one extraneous change to the `shouldUpdate` flag 👍

2021-06-01 13:32 UTC, EdwardCoyle approved these changes

2021-06-01 13:33 UTC, tmcconechy approved these changes

2021-06-01 13:33 UTC, merged

2021-06-01 15:21 UTC, rob2d commented
cool thanks @EdwardCoyle