1847 - IdsModal components test conversion
infor-design/enterprise-wc pull request #1995
Opened 2024-03-04 22:40 UTC by jdilag90

**Explain the details for making this change. What existing problem does the pull request solve?**
Converted tests for IdsModal, IdsActionPanel, IdsAbout, IdsErrorPage

**Related github/jira issue (required)**:
Closes #1847 

**Steps necessary to review your pull request (required)**:
1. Checkout branch
2. Run tests
3. Check if coverage improved

**Included in this Pull Request**:
- [ ] Some documentation for the feature.
- [x] A test for the bug or feature.
- [x] A note to the change log.

2024-03-05 14:54 UTC, tmcconechy requested changes
@jdilag90 everything looks good except i noticed in percy it looks like the modal lost the seperator above the buttons. Can you check?


https://percy.io/00aaa841/enterprise-wc/builds/32978290/changed/1808890796?browser=chrome&browser_ids=56&subcategories=unreviewed%2Cchanges_requested&viewLayout=overlay&viewMode=new&width=1280&widths=375%2C1280

2024-03-05 15:13 UTC, jdilag90 commented
@tmcconechy I fixed the missing separator. Good catch, thanks!

2024-03-05 15:41 UTC, tmcconechy approved these changes

2024-03-06 16:05 UTC, clayinfor approved these changes

2024-03-06 21:02 UTC, merged