1928 - Convert data labels and checkbox group to Playwright
infor-design/enterprise-wc pull request #2009
Opened 2024-03-07 11:16 UTC by n-ace-ancog

**Explain the details for making this change. What existing problem does the pull request solve?**
Conversion of `ids-data-labels` and `ids-checkbox-group` test scripts to Playwright

**Related github/jira issue (required)**:
Closes #1928 
Closes #1921 

**Steps necessary to review your pull request (required)**:
Pull this branch, build, and run the app
Run the test suite
Check the code conversion
New converted tests should pass

**Included in this Pull Request**:
- [ ] Some documentation for the feature.
- [x] A test for the bug or feature.
- [ ] A note to the change log.

2024-03-07 15:35 UTC, tmcconechy commented on tests-to-convert/ids-checkbox-group/ids-checkbox-group-func-test.ts
> -
@n-ace-ancog please delete the whole file as all tests look converted (and the folder if its empty after of no more tests)

2024-03-07 15:37 UTC, tmcconechy commented on tests/ids-checkbox-group/ids-checkbox-group.spec.ts
> +      const changeLabel: string = 'Label Test';
Just a tip on this line and the one above. you dont always have to declare it, as it figures it out automatically and will give you a lint warning if it cant and it needs declaration (its self declaring)

2024-03-07 15:37 UTC, tmcconechy commented on tests/ids-checkbox-group/ids-checkbox-group.spec.ts
> +    test('can get checkboxes', async ({ page }) => {
Maybe better test name? I guess this is checking they render?

2024-03-07 15:59 UTC, n-ace-ancog commented on tests/ids-checkbox-group/ids-checkbox-group.spec.ts
> +    test('can get checkboxes', async ({ page }) => {
It's returning all the checkboxes context under the group. From what I understand, it doesn't render the checkboxes to the page. 

![image](https://github.com/infor-design/enterprise-wc/assets/156752175/9de8315a-2711-40ac-bd58-26ba9c5a264e)

2024-03-07 17:27 UTC, tmcconechy reviewed
@n-ace-ancog some more suggestions:

2024-03-08 01:48 UTC, n-ace-ancog commented on tests/ids-checkbox-group/ids-checkbox-group.spec.ts
> +    test.skip('can select checkboxes', async ({ page }) => {
For this test case, I'm trying to make a coverage for the `value` property of the `ids-checkbox-group` component. 
![image](https://github.com/infor-design/enterprise-wc/assets/156752175/b18dfec0-6f2e-42fb-a383-48faa6b9c3cc)

Set `value` updates the values of all child `ids-checkboxes` from the `ids-checkbox-group` depending on the input. This  was tagged as not covered due to the `test.skip` during this run
![image](https://github.com/infor-design/enterprise-wc/assets/156752175/48af64cd-927b-4585-b749-bad886db428e)

Seems like there is an issue setting the `value` to `true` via `ids-checkbox-group` component as it only changes it aesthetically and the value beneath still equates to `false`.
![Animation](https://github.com/infor-design/enterprise-wc/assets/156752175/0df4828b-6fbe-419a-bc4f-edf5895e7a61)

Is this a bug? Maybe for now, I can suppress the validation after setting it to true so that we can cover the code.

2024-03-08 02:00 UTC, n-ace-ancog commented on tests/ids-checkbox-group/ids-checkbox-group.spec.ts
> +    test.skip('can get selected checkboxes', async ({ page }) => {
I'm trying to cover the `checkboxesSelected` property here. It returns all the `ids-checkbox` checked under the `ids-checkbox-group`, then comparing its `length` to what Playwright's `locator('ids-checkbox input[checked]')` can return.
![image](https://github.com/infor-design/enterprise-wc/assets/156752175/d5d1708f-f988-4a4e-b9be-9bb04bd21f33)

**Coverage**
![image](https://github.com/infor-design/enterprise-wc/assets/156752175/73628a60-fdec-4a00-8ffb-8bd09de0e571)

I used `test.skip` since I think this is an issue as its still returning non-checked `ids-checkbox`
![Animation](https://github.com/infor-design/enterprise-wc/assets/156752175/89f82166-4225-462e-a153-1fc8692b642f)

2024-03-08 02:05 UTC, n-ace-ancog commented on tests/ids-checkbox-group/ids-checkbox-group.spec.ts
> +    test('can get checkboxes', async ({ page }) => {
I can rename it to can **get checkboxes under the group**. In the test case, I'm just counting it to validate if it returns the same amount of checkboxes as what Playwright's `idsCheckBoxGroup.locator('ids-checkbox')` returns.

2024-03-08 02:18 UTC, n-ace-ancog commented on tests/ids-checkbox-group/ids-checkbox-group.spec.ts
> +      const idsCheckBoxGroup: Locator = page.locator('ids-checkbox-group').first();
Should we do `await` even on non-Promise functions? 
From, what I understand adding `await` on non-Promise adds more time in the execution rather than it resolving immediately and can also leads to scenarios where the sequence of execution may vary.

https://stackoverflow.com/questions/55262996/does-awaiting-a-non-promise-have-any-detectable-effect

2024-03-08 17:05 UTC, tmcconechy commented on tests/ids-checkbox-group/ids-checkbox-group.spec.ts
> +    test('can get checkboxes', async ({ page }) => {
Sure. Not trying to get too crazy with what we call it. Just thought in that case it wasnt quite clear to me.

2024-03-08 17:06 UTC, tmcconechy commented on tests/ids-checkbox-group/ids-checkbox-group.spec.ts
> +      const idsCheckBoxGroup: Locator = page.locator('ids-checkbox-group').first();
Only on the ones that wait. But thats both the `locator` and `evaluate`. Some simple statements like a variable check we dont need.

I might add a css rule to help with this 👍🏻

2024-03-08 17:09 UTC, tmcconechy commented on tests/ids-checkbox-group/ids-checkbox-group.spec.ts
> +    test.skip('can get selected checkboxes', async ({ page }) => {
@n-ace-ancog did you try my tests suggestions. I dont think you need to skip it its correct. Its just that the attribute can be either:

```
checked
(nothing)
checked="true"
checked="false"
```

Are all valid just need to take that into account

2024-03-08 17:10 UTC, tmcconechy commented on tests/ids-checkbox-group/ids-checkbox-group.spec.ts
> +    test.skip('can select checkboxes', async ({ page }) => {
yes the values in the console look like a bug. can you raise that?

2024-03-08 17:11 UTC, tmcconechy requested changes
@n-ace-ancog the only thing left here then is I think we do need an `await` on every page.locator command.

Its showing it here https://playwright.dev/docs/api/class-locator  i think it is one that waits and every other test does this. It could be flaky otherwise.

I will implement a css rule for this.

2024-03-11 03:22 UTC, n-ace-ancog commented on tests/ids-checkbox-group/ids-checkbox-group.spec.ts
> +    test.skip('can select checkboxes', async ({ page }) => {
Opened #2020 for this issue.

2024-03-11 15:04 UTC, tmcconechy approved these changes

2024-03-12 15:01 UTC, clayinfor approved these changes

2024-03-12 15:05 UTC, merged