1861 -  ids-multiselect change event not firing in Angular
infor-design/enterprise-wc pull request #2037
Opened 2024-03-13 11:03 UTC by clayinfor

**Explain the details for making this change. What existing problem does the pull request solve?**

Fixes a few bugs in `IdsMultiselect` that needed be addressed.

**Related github/jira issue (required)**:

Closes #1861 

**Steps necessary to review your pull request (required)**:

1. Go to  http://localhost:4300/ids-multiselect/example.html
2. Try to set the value in the console `$('ids-multiselect').value = ['ca'] `
3.  Open the list and see the checkboxes are not updated
4. `npm run build:dist` and copy to https://github.com/infor-design/enterprise-wc-examples
5. In http://localhost:4200/ids-forms/example  try to edit the multiselect and note that it does not omit an onChange event for some reason (dropdown does)
6. In http://localhost:4200/ids-reactive-forms/example try to press the button to update values or change the multiselect and then console log. Check the values for it in both the formControl and values section, and note its not update
7. Once fixed make the test `test.skip('should fire a change event'` unskipped and work

**Included in this Pull Request**:
- [ ] Some documentation for the feature.
- [ ] A test for the bug or feature.
- [x] A note to the change log.

2024-03-13 15:42 UTC, tmcconechy requested changes
The only issue i see is that the change event fires 3 times. When i run the command.

2024-04-24 15:14 UTC, tmcconechy commented
@clayinfor just a bump on this one... can we complete soon?

2024-05-01 13:59 UTC, clayinfor commented
hey @tmcconechy , this should be good to go

2024-05-01 14:17 UTC, tmcconechy approved these changes

2024-05-06 13:59 UTC, merged