5032 add ids breadcrumb
infor-design/enterprise-wc pull request #208
Opened 2021-06-01 17:09 UTC by chrisakinrinade

**Explain the details for making this change. What existing problem does the pull request solve?**
Adding IdsBreadcrumb component to the web component repo. It uses IdsHyperlinks as inner components.

**Related github/jira issue (required)**:
Addresses #137 

**Steps necessary to review your pull request (required)**:
Pull this branch, build, and run the app
Go to http://localhost:4300/ids-breadcrumb
Check the code implementations and functional tests.

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2021-06-02 15:39 UTC, tmcconechy requested changes
Looking good ! A few small edits and a couple things to improve it

1. Its missing focus states -> try tabbing into the bread crumb -> you might just need href="#" in the markup
2. Along those lines trying http://localhost:4300/ids-breadcrumb/add-remove and i see a mix of links with underline or not? Is that related to the href? And maybe remove the large example
3. http://localhost:4300/ids-breadcrumb/standalone-css doesnt seem to look the same for some reason?

2021-06-02 15:39 UTC, tmcconechy commented on app/ids-breadcrumb/add-remove.html
> +  <ids-text font-size="12" type="h1">BREADCRUMBS</ids-text>
```suggestion
  <ids-text font-size="12" type="h1">Add/Remove Breadcrumbs</ids-text>
```

2021-06-02 15:39 UTC, tmcconechy commented on app/ids-breadcrumb/add-remove.html
> +  <ids-button type="primary">Add Link</ids-button>
```suggestion
  <ids-button type="secondary">Add Link</ids-button>
```

2021-06-02 15:39 UTC, tmcconechy commented on src/ids-breadcrumb/README.md
> +/*
Dont think these comments are needed?

2021-06-02 15:39 UTC, tmcconechy commented on src/ids-breadcrumb/ids-breadcrumb.d.ts
> +export default class IdsBreadcrumb extends HTMLElement {
Can you add all the types for settings? At least mode and theme i think if no other settings?

2021-06-02 15:39 UTC, tmcconechy commented on src/ids-breadcrumb/ids-breadcrumb.js
> + * @type {IdsBreadcrumb}
```suggestion
 *  IDS Breadcrumb Component
 * @type {IdsBreadcrumb}
```

2021-06-02 15:39 UTC, tmcconechy commented on src/ids-breadcrumb/ids-breadcrumb.js
> +   * @param {Element} breadcrumb The HTML element with which to add
```suggestion
   * @param {Element} breadcrumb The HTML element with which to add
   * @private
```

And could make it #push (private class)

2021-06-02 15:39 UTC, tmcconechy commented on src/ids-breadcrumb/ids-breadcrumb.js
> +  pop() {
also private?

2021-06-03 17:32 UTC, chrisakinrinade commented
> Looking good ! A few small edits and a couple things to improve it
> 
> 1. Its missing focus states -> try tabbing into the bread crumb -> you might just need href="#" in the markup
> 2. Along those lines trying http://localhost:4300/ids-breadcrumb/add-remove and i see a mix of links with underline or not? Is that related to the href? And maybe remove the large example
> 3. http://localhost:4300/ids-breadcrumb/standalone-css doesnt seem to look the same for some reason?
> 4. And maybe comment out the coverage issue

@tmcconechy 
1. Should crumbs without hrefs be focusable?
2. The underline is an issue w/ the hyperlink -- the css for it just hasn't been done yet. Do you think that should be fixed with this ticket? And np, I'll get rid of the large example.
3. The sizing was done w/ js. I'll see if there's a workaround I can do about that.

2021-06-03 17:59 UTC, tmcconechy commented
1. I think it would be ok if they are not focusable if no href (as its just static text) but the color should look the same as before
2. If its easy? As it looks strange if they are mixed but if its only when adding/removing or its complicated then we can leave it for now
3. 👍🏻

2021-06-04 15:57 UTC, chrisakinrinade commented on src/ids-breadcrumb/ids-breadcrumb.js
> +   * @param {Element} breadcrumb The HTML element with which to add
Actually I intended push and pop to be public. That's how people would interface with the breadcrumbs.

2021-06-08 14:35 UTC, tmcconechy submitted a review, later dismissed

2021-06-09 14:30 UTC, deep7102 reviewed
Looks good, few things see
http://localhost:4300/ids-breadcrumb
1) hover styles (is should as 4.x)
2) is last one `Current Item` should be hyperlink or just text?

http://localhost:4300/ids-breadcrumb/standalone-css
1) Disabled (keyboard has focus state)

2021-06-09 15:08 UTC, tmcconechy commented
@deep7102 I fixed those points just now. But note that the style in the old system is incorrect on hover as it changes blue color. So i left that off it just shows the underline.

2021-06-09 15:13 UTC, deep7102 approved these changes
🍌 Looks good, Thanks!

2021-06-10 14:02 UTC, merged