1881 - ids-module-nav icons missing in angular
infor-design/enterprise-wc pull request #2123
Opened 2024-03-26 15:51 UTC by clayinfor

**Explain the details for making this change. What existing problem does the pull request solve?**

IdsModuleNav icons were not properly rending in Angular examples

**Related github/jira issue (required)**:

Closes #1881 

**Steps necessary to review your pull request (required)**:

1. Check out this branch and run: `nvm use && npm install && npm run start`
2. Ensure no regressions here: http://localhost:4300/ids-module-nav/sandbox.html
3. In another terminal window, and run `npm run publish:link`
4. Then check out https://github.com/infor-design/enterprise-wc-examples
5. Then run: `npm install && npm link ids-enterprise-wc`
6. Then run: `rm -fr .angular/cache && npm run build && npm run start`
7. Then confirm all icons display properly here: http://localhost:4200/ids-module-nav/sandbox

**Included in this Pull Request**:
- [ ] Some documentation for the feature.
- [ ] A test for the bug or feature.
- [x] A note to the change log.

2024-03-26 16:05 UTC, clayinfor commented
## Fixed:
<img width="1728" alt="Screenshot 2024-03-26 at 12 04 15 PM" src="https://github.com/infor-design/enterprise-wc/assets/93789065/a0896d6f-e882-4356-95dc-2dcb08f85ca7">

2024-03-26 17:42 UTC, tmcconechy requested changes
@clayinfor looks good but can you just move to the new beta.23 change log section i added (pull main)

2024-03-28 20:15 UTC, tmcconechy approved these changes

2024-04-01 14:00 UTC, tmcconechy approved these changes

2024-04-01 14:00 UTC, merged