1976 - Convert Swipe action to Playwright
infor-design/enterprise-wc pull request #2172
Opened 2024-04-04 16:54 UTC by n-ace-ancog

**Explain the details for making this change. What existing problem does the pull request solve?**
Converts swipe action tests to Playwright.

**Related github/jira issue (required)**:
Closes #1976 

**Steps necessary to review your pull request (required)**:
Pull this branch, build, and run the app
Run the test suite
Check the code conversion
New converted tests should pass

**Included in this Pull Request**:
- [ ] Some documentation for the feature.
- [x] A test for the bug or feature.
- [x] A note to the change log.

2024-04-04 17:50 UTC, tmcconechy commented on tests/ids-swipe-action/ids-swipe-action.spec.ts
> +        await page.waitForTimeout(500);
Please dont use `waitForTimeout` as it just slows down the test suite and can cause flakyness. Instead waitFor something specific like:

a) a locator https://playwright.dev/docs/api/class-locator#locator-wait-for
b) or an element state https://playwright.dev/docs/api/class-elementhandle#element-handle-wait-for-element-state
c) or use an await for the previous thing to finish ect

2024-04-04 17:50 UTC, tmcconechy requested changes
Something is failing but requesting changes as trying not to introduce waitForTimeout as its an anit-pattern

2024-04-05 11:59 UTC, n-ace-ancog commented on tests/ids-swipe-action/ids-swipe-action.spec.ts
> +        await page.waitForTimeout(500);
I've removed the `waitForTimeout` and instead replaced it with a `waitForButton` function that retries until the `element.container!.scrollLeft` value reached a "ideal" value.

2024-04-05 12:02 UTC, tmcconechy approved these changes

2024-04-05 16:38 UTC, ericangeles approved these changes

2024-04-05 17:41 UTC, merged