4629 - Add ids checkbox and more
infor-design/enterprise-wc pull request #22
Opened 2020-12-02 23:40 UTC by deep7102

**Explain the details for making this change. What existing problem does the pull request solve?**
- ids-checkbox: add checkbox component
- ids-hide-focus-mixin: handle focus/click events
- ids-dirty-tracker-mixin: add support for checkbox
- ids-validation-mixin: add support to handle multi events and support for checkbox
- ids-input: Remove attribute `name/fieldName` was in conflict
- Added docs and tests
- Added standalone css example

**Related github/jira issue (required)**:
Fixes infor-design/enterprise#4629

**Steps necessary to review your pull request (required)**:
- Pull this branch and build/run the demo app
- Navigate to:
- http://localhost:4300
- http://localhost:4300/ids-checkbox
- http://localhost:4300/ids-checkbox/standalone-css.html
- See checkbox uplift styles
- See checked, unchecked, disabled checkbox
- See checkbox colors
- Test dirty tracker
- See required label with red `*` star and no-indicator without red `*` star
- Test validation for required (must be checked to pass validation)
- Test to set/remove indeterminate state (click on checkbox will change state to checked/unchecked)

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.

2020-12-04 14:45 UTC, tmcconechy requested changes
Looking really good 🍌 Just a few suggestions inline and as well:

- can you check the branch coverage its only 93.1% for checkbox i think that can be fixed. (and any others you want).
- for standalone really just need the first standard parts - but since you did it dont have to take it out
- in terms of styling the only thing i see is a bit too much margin between the checkboxes . Should be 16px now but its closer to 20
- e2e tests?

Also assume the radios and switch will follow? Then maybe dont close the issue on the pr.

2020-12-08 18:08 UTC, deep7102 commented on app/ids-checkbox/example.html
> +    <ids-checkbox label="Option 1 I am long" display-inline="true"></ids-checkbox>
Update now as horizontal

2020-12-08 18:09 UTC, deep7102 commented on src/ids-base/ids-colorpalette-variables.scss
> +$color-names: ruby01 ruby02 ruby03 ruby04 ruby05 ruby06 ruby07 ruby08 ruby09 ruby10
Updated now, use as css variables

2020-12-08 18:09 UTC, deep7102 commented on src/ids-checkbox/README.md
> +The IDS Checkbox component is a simple wrapper around a standard HTMLInputElement that is styled with Infor branding, and contains some additional API that makes it easy to set checkbox, label, and f
updated now

2020-12-08 18:10 UTC, deep7102 commented on src/ids-checkbox/README.md
> +
updated now

2020-12-08 18:11 UTC, deep7102 commented
Hi @tmcconechy updated now, the points you found above.

2020-12-08 19:09 UTC, tmcconechy approved these changes

2020-12-08 20:49 UTC, EdwardCoyle approved these changes

2020-12-08 21:08 UTC, merged