1968 - Convert ids-scrollview test to playwright
infor-design/enterprise-wc pull request #2217
Opened 2024-04-12 14:25 UTC by jbrcna

**Explain the details for making this change. What existing problem does the pull request solve?**

**Related github/jira issue (required)**:

closes https://github.com/infor-design/enterprise-wc/issues/1968

**Steps necessary to review your pull request (required)**:

Pull this branch, build, and run the app
Run the test suite
Check the code conversion
New converted tests should pass

**Included in this Pull Request**:
- [ ] Some documentation for the feature.
- [x] A test for the bug or feature.
- [x] A note to the change log.

2024-04-12 14:51 UTC, tmcconechy requested changes
@jbrcna 

1. looks like some lint issues (check test output)
2. never use waitForTimeout, instead use a different waitFor like https://pptr.dev/api/puppeteer.page.waitforselector or waitForFunction

https://github.com/infor-design/enterprise-wc/pull/2217/files#diff-39829b67dd5973b5d1ace28507432931d30f24e98ee02ebd93b42927d6626145R202

3. Delete old tests that were converted

2024-04-12 14:51 UTC, tmcconechy commented on tests/ids-scroll-view/ids-scroll-view.spec.ts
> +    test.describe('e2e tests', () => {
```suggestion
    test.describe('functionality tests', () => {
```

2024-04-15 14:59 UTC, tmcconechy reviewed
Looks good. I merged main to see if it fixes the failing tests tho

2024-04-15 16:13 UTC, andrivarhanov approved these changes

2024-04-15 16:33 UTC, merged