1806 - ids-toolbar misposition in header overflow menu
infor-design/enterprise-wc pull request #2276
Opened 2024-05-01 11:12 UTC by clayinfor

**Explain the details for making this change. What existing problem does the pull request solve?**

Fix so that menus and submenu popup positions are correct when using `IdsToolbar` inside `IdsAppMenu` (and `IdsHeader`)

**Related github/jira issue (required)**:

Closes #1806 

**Steps necessary to review your pull request (required)**:

1. Check out this branch and run: `nvm use && npm install && npm run start`
2. Then go to: http://localhost:4300/ids-toolbar/in-header.html
3. Click the hamburger button on the left of the toolbar title. This should open up the application side-panel menu.
4. Click on the more-actions button (the 3 dots) on the right side of the toolbar.
5. The popup menu should appear properly positioned, and a horizontal scrollbar should not appear.
6. Hover over the "More Options" submenu in the more actions menu, and ensure the submenu appears.

**Included in this Pull Request**:
- [ ] Some documentation for the feature.
- [ ] A test for the bug or feature.
- [x] A note to the change log.

2024-05-01 14:29 UTC, tmcconechy reviewed
@clayinfor the one issue i see is that its loosing the highlight.

<img width="527" alt="Screenshot 2024-05-01 at 10 24 37 AM" src="https://github.com/infor-design/enterprise-wc/assets/814283/88538910-6b3d-47d5-b585-6925bd73e0d2">

The highlight used to stay on the both menu items similar to this:

<img width="501" alt="Screenshot 2024-05-01 at 10 24 21 AM" src="https://github.com/infor-design/enterprise-wc/assets/814283/66e33fae-c9ca-4d62-b8c3-ad5485572e68">

2024-05-02 16:31 UTC, tmcconechy requested changes
Marking as request changes for the above

2024-05-20 14:52 UTC, tmcconechy commented on src/components/ids-popup/ids-popup.ts
> +      if (navigator.userAgent.indexOf('Firefox') === -1) {
Does this cause a warning? May also want to sync main here as this PR is now pretty old

2024-05-23 14:27 UTC, tmcconechy commented
@clayinfor any updates on this one? Been sitting a long time

2024-06-03 12:57 UTC, tmcconechy commented
@clayinfor any updates on this one? Been sitting a long time. Shouldnt need too much to finish it?

2024-06-14 15:11 UTC, clayinfor commented
hey @tmcconechy, let's merge this, and create a new task to address the remaining issues.

2024-06-14 15:52 UTC, tmcconechy commented
@clayinfor ok great. Can you make the issue as im not sure i know whats left?

2024-06-14 16:36 UTC, clayinfor commented
Ok @tmcconechy , I used John's comment to create an issue [here](https://github.com/infor-design/enterprise-wc/issues/2464).

2024-06-17 13:34 UTC, merged