131 ids colorpicker wc
infor-design/enterprise-wc pull request #228
Opened 2021-06-28 16:11 UTC by danielortiz1982

**Explain the details for making this change. What existing problem does the pull request solve?**

**Related github/jira issue (required)**:

**Steps necessary to review your pull request (required)**:

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [ ] A note to the change log.

2021-06-30 16:39 UTC, EdwardCoyle reviewed
Looks really nice so far!  Functionality and style are both there.  I think it just needs a few things (will approve after these are done):

- [ ] Need to add JSDoc comments for everything that's missing
- [ ] Fix lints

Thinking about what comes next, these two things I'd like to maybe discuss for future PRs (will approve without these):

- [ ] (Possibly a phase 2) There are use cases for Colorpicker where we want users to be forced to pick an available swatch (as opposed to choosing any random color from the native picker).  If we are going to allow access via the native picker, we may also want to have a boolean setting so it can be enabled/disabled independently of the rest of the component.  I added this in a suggestion to the TODO list below
- [ ] (Possibly for phase 2) We might want to figure out how to abstract out the structure of linking an IdsPopup to an IdsTriggerButton/Field, and returning a value from the IdsPopup's contents.  The same structure here in the Colorpicker will also apply to Time/Datepicker (and potentially others), and it would be nice if all of these pickers operated in the same predictable manner.

2021-06-30 16:39 UTC, EdwardCoyle commented on src/ids-color-picker/TODO.md
> +- [ ] Click out close (popup issue)
```suggestion
- [ ] Click out close (popup issue -- will be fixed in #225)
```

2021-06-30 16:39 UTC, EdwardCoyle commented on src/ids-color-picker/TODO.md
> +- [ ] Fix arrow position
- [ ] Enable/Disable standard HTML colorpicker with boolean attribute
- [ ] Standardize/Abstract out Popup/Picker/"return value" interface (to be used in this and other pickers)

2021-06-30 17:38 UTC, danielortiz1982 commented on src/ids-color-picker/TODO.md
> +- [ ] Click out close (popup issue)
Thanks for your feedback @EdwardCoyle. @tmcconechy has a similar idea. I will see what type effort is needed to achieve this for a round 2 PR.

2021-06-30 19:37 UTC, tmcconechy reviewed
in addition to Ed's comments if you just fix coverage (or skip) on https://coveralls.io/builds/41013226/source?filename=src%2Fids-color-picker%2Fids-color-picker.js#L63

should be good enough for now for phase 1

2021-07-01 17:34 UTC, deep7102 requested changes
Hi @danielortiz1982 this looks good found some points as:
- Addition to @EdwardCoyle and @tmcconechy comments
- Some text hard coded in component, should give setting/slots to user change those text strings (saw in template())
- Styles not match with 4.x (popup container) - swatch/hover/spacing etc [see example here](https://main-enterprise.demo.design.infor.com/components/colorpicker/example-index.html)
- Did not see the tooltip
- Why container need hard coded width/height (saw 360px/250px in css)
- Markup should be simpler, default color list should load from our theme palette
- `<ids-color-picker label="Default Colors"></ids-color-picker>`
- Custom color list can pass separately as json style dataset (can set dynamically or through a DataSource)
- `[{ label: 'Slate', number: '08', value: '383838', border: 'dark', arrowClass: 'dark' }]`
- Check mark color should change based on swatch background (check mark color can get from colorlist -arrowClass)
- Should be able to show `color-name` azure06 or `color-hax` #ffffff [see example here](https://main-enterprise.demo.design.infor.com/components/colorpicker/example-custom-labels.html)
- Did not see other examples are we going to add them later or in this phase (validation, readonly) [see example here](https://main-enterprise.demo.design.infor.com/components/colorpicker/test-states.html)

2021-07-01 19:27 UTC, tmcconechy reviewed
Actually too more things that are probably important.

1) Can you test themes (or did you) might need some styles here
2) Can you add a test that the change event fires when you change it? It might because thats in input already but thats rather important. Shoud be a test there.

Also still failing on builds/coverage so just add a skip

2021-07-08 15:25 UTC, tmcconechy commented
I added some more TODO's based on the comments. I guess im ok with approving this for now but we will need to circle back as there are a lot of important TODO's

2021-07-08 15:25 UTC, tmcconechy approved these changes

2021-07-08 15:26 UTC, danielortiz1982 commented
> I added some more TODO's based on the comments. I guess im ok with approving this for now but we will need to circle back as there are a lot of important TODO's

Thanks Tim.

2021-07-08 15:51 UTC, EdwardCoyle approved these changes
I'm approving as well, acknowledging we still have quite a bit to finish here

2021-07-08 16:16 UTC, deep7102 approved these changes
I'm approving too, hope will get thru most important TODO's next circle

2021-07-08 16:22 UTC, merged