1983 - Convert ids-toast test to playwright
infor-design/enterprise-wc pull request #2287
Opened 2024-05-03 12:03 UTC by jbrcna

**Explain the details for making this change. What existing problem does the pull request solve?**

**Related github/jira issue (required)**:

**Steps necessary to review your pull request (required)**:

Run the test suite
Check the code conversion
New converted tests should pass

**Included in this Pull Request**:
- [ ] Some documentation for the feature.
- [ ] A test for the bug or feature.
- [ ] A note to the change log.

**Note:**
Test with TODO comments have errors.

2024-05-03 14:28 UTC, tmcconechy commented
@jbrcna this looks good overall but

a) seems like some lint errors. The page object is not used
b) similar to above instead of `await toast.evaluate` i think we should use `await page.evaluate` like other tests
c) 3 is failing for me

```
  3 failed
    [chromium] › ids-toast/ids-toast.spec.ts:390:9 › IdsToast tests › functionality tests › can  restore saved position 
    [chromium] › ids-toast/ids-toast.spec.ts:417:9 › IdsToast tests › functionality tests › can  reset saved position 
    [chromium] › ids-toast/ids-toast.spec.ts:446:9 › IdsToast tests › functionality tests › can  clear saved position
```

2024-05-06 17:29 UTC, n-ace-ancog commented on tests/ids-toast/ids-toast.spec.ts
> +    await button.click();
The `button.click()` in `beforeEach` here requires the rest of the test cases inside the `test.describe` to follow a specific action even when not needed. Either isolate the button clicking on each individual test case using `await page.locator('#btn-toast-demo').click()` or group them better.

2024-05-06 17:35 UTC, tmcconechy commented on tests/ids-toast/ids-toast.spec.ts
> +    await button.click();
Yes i agree @n-ace-ancog i always use `await page.locator(` only in the individual test. good call

2024-05-09 08:55 UTC, n-ace-ancog commented on tests/ids-toast/ids-toast.spec.ts
> +    test('can  check if can save position to local storage', async ({ page }) => {
You can use the code below for this test case which check the local storage of the browser. Reference it as well on other test case that includes validating local storage. I've added some comments for explanation and considered that clicking the button to trigger the toast is isolated within the test case. Take note of `await page.waitForFunction(() => window.localStorage.length > 0);` as this is important in retrieving and waiting for the local storage to be filled before validating further.

```ts
test('can check if can save position to local storage', async ({ page }) => {
  // get information from local storage
  const localStorage = async () => {
    const store = await page.evaluate(() => window.localStorage);
    return store;
  };
  const prefix = 'ids-toast-container';
  const suffix = 'usersettings-position';
  const uniqueId = 'some-uniqueid';
  const transform = 'translate(100px, 250px)';

  // check if local storage is empty
  expect(await localStorage()).toEqual({});
  // button is declared and located on the immediate test.describe
  await button.click();
  await toast.evaluate((element: IdsToast, opt) => {
    element.uniqueId = opt.uniqueId;
    element.savePosition = true;
    element.draggable = true;
    element.toastContainer()!.style.transform = opt.transform;
  }, { uniqueId, transform });
  // wait for the toast to be attached in DOM - very important!!
  await toast.waitFor({ state: 'attached' });
  // wait for the localStorage to have an item - very important!!
  await page.waitForFunction(() => window.localStorage.length > 0);
  // validation if information is saved in local storage
  const storage = await localStorage();
  expect(storage.hasOwnProperty(`${prefix}-${uniqueId}-${suffix}`)).toBeTruthy();
  expect(storage[`${prefix}-${uniqueId}-${suffix}`]).toEqual(transform);
});
```

2024-05-13 03:44 UTC, jbrcna commented
I wasn't sure what to do with the 3 failing tests. it's about local storage. tried to fix it bot to no avail. I'm stuck. need help.

2024-05-13 13:15 UTC, jbrcna commented on tests/ids-toast/ids-toast.spec.ts
> +    test('can  check if can save position to local storage', async ({ page }) => {
it says TypeError: localStorage.setItem is not a function

this also received false. 
`expect(storage.hasOwnProperty(${prefix}-${uniqueId}-${suffix})).`
and undefined
`expect(storage[${prefix}-${uniqueId}-${suffix}]).toEqual(transform);`

2024-05-13 13:20 UTC, tmcconechy commented on tests/ids-toast/ids-toast.spec.ts
> +    test('can  check if can save position to local storage', async ({ page }) => {
@jbrcna maybe the problem is you can only use localStorage in a `await page.evaluate(() => {});`

2024-05-14 02:16 UTC, n-ace-ancog requested changes

2024-05-14 02:16 UTC, n-ace-ancog commented on tests/ids-toast/ids-toast.spec.ts
> +    test('can  set toast to progress bar', async () => {
Remove the extra space between **can** and **set** in the test title. Check the rest of the test titles.

2024-05-14 02:16 UTC, n-ace-ancog commented on tests/ids-toast/ids-toast.spec.ts
> +      await toast.evaluate((element: IdsToast, opt) => {
There's a lint error in the `opt` variable. Just explicitly state it as any like `opt:any`.

2024-05-14 02:16 UTC, n-ace-ancog commented on tests/ids-toast/ids-toast.spec.ts
> +    // test('can  check if can save position to local storage', async ({ page }) => {
If not needed, you can remove this block of code that is commented out.

2024-05-14 02:16 UTC, n-ace-ancog commented on tests/ids-toast/ids-toast.spec.ts
> +      await localStorage.setItem(id(uniqueId), transform);
The issue here is you wanted to use the [localStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) from the window api, but instead refers to the `localStorage` function declared at the top of the test case, hence the error. As what @tmcconechy, mentioned on the previous review - you can only use the [localStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) inside a `page/locator.evaluate` method to `setItem`.

You can use the code below for the restoring of saved position.

```typescript
test('can restore saved position', async ({ page }) => {
  const prefix = 'ids-toast-container';
  const suffix = 'usersettings-position';
  const uniqueId = 'some-uniqueid';
  const key = `${prefix}-${uniqueId}-${suffix}`;
  const transform = 'translate(-596px, 232px)';
  await page.evaluate((storage) => { window.localStorage.setItem(storage.key, storage.transform); }, { key, transform });
  // wait for the localStorage to have an item - very important!!
  await page.waitForFunction(() => window.localStorage.length > 0);
  await page.evaluate((uId) => {
    const elem = document.createElement('ids-toast')! as IdsToast;
    elem.setAttribute('id', 'toasty-example');
    elem.uniqueId = uId;
    elem.savePosition = true;
    elem.draggable = true;
    document.querySelector('ids-container')!.appendChild(elem);
    elem.show({
      title: 'Test',
      message: 'Some test text'
    });
  }, uniqueId);
  const theToast = await page.locator('#toasty-example');
  await theToast.waitFor({ state: 'attached' });
  await expect(theToast).toBeAttached();
  await expect(await theToast.locator('ids-draggable')).toHaveAttribute('style', `transform: ${transform};`);
});
```

2024-05-14 14:11 UTC, jbrcna commented on tests/ids-toast/ids-toast.spec.ts
> +    test('can  check if can save position to local storage', async ({ page }) => {
I was able to use it w/o page.evaluate (as Storage)
<img width="673" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/5b004bf0-484c-4ebc-8016-e14d30fb9429">

2024-05-14 14:13 UTC, tmcconechy commented
ok @jbrcna just skip the local storage tests for now.

2024-05-15 11:10 UTC, n-ace-ancog commented on tests/ids-toast/ids-toast.spec.ts
> +      while (await toastmsg.count() > 0) { return; }
Either replace this with `expect(toastmsg).not.toBeAttached()` or `await page.waitForFunction(() => !document.querySelector('ids-toast-message'));`. Both waits for the element to be removed with built in timeouts.

2024-05-15 11:39 UTC, ericangeles commented on tests/ids-toast/ids-toast.spec.ts
> +      while (await toastmsg.count() > 0) { return; }
waitForFunction would be ideal, since it returns a promise of jshandle (an in-page JS object). Good idea, @n-ace-ancog.

2024-05-15 12:12 UTC, n-ace-ancog commented on tests/ids-toast/ids-toast.spec.ts
> +    test('can  check if can save position to local storage', async ({ page }) => {
@jbrcna if you were able to use localStorage outside of `page.evaluate` then you are using it with the context of Playwright instead of the browser/page in test. `page.evaluate` lets you run javascript code in the browser itself. I assume, based from your screenshot, the validation passes as its checking for `null` - which will always be `null` since it was not setup in the first place and ran on Playwright's context while `el.clearPosition()` ran on the browser's context.

![image](https://github.com/infor-design/enterprise-wc/assets/156752175/6008977d-44b2-4b34-9299-0e492ed1e917)
Reference: https://playwright.dev/docs/evaluating#introduction

2024-05-16 03:16 UTC, jbrcna commented on tests/ids-toast/ids-toast.spec.ts
> +      while (await toastmsg.count() > 0) { return; }
thanks for suggesting @n-ace-ancog . I've tried using that but gives me error.
expect(toastmsg).not.toBeAttached()
<img width="384" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/29f037eb-e45c-4a52-9480-63a500b4b2e4">
await page.waitForFunction(() => !document.querySelector('ids-toast-message'));
<img width="514" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/40e228b7-ea13-4da1-8a35-3ce92b483ae4">

2024-05-16 08:26 UTC, jbrcna commented
Thank you for the code change @n-ace-ancog 👍

2024-05-16 13:06 UTC, n-ace-ancog approved these changes

2024-05-16 13:44 UTC, tmcconechy approved these changes

2024-05-16 17:33 UTC, merged