134 ids header wc
infor-design/enterprise-wc pull request #236
Opened 2021-07-01 19:55 UTC by danielortiz1982

**Explain the details for making this change. What existing problem does the pull request solve?**

**Related github/jira issue (required)**:

**Steps necessary to review your pull request (required)**:

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [ ] A note to the change log.

2021-07-02 13:45 UTC, tmcconechy commented
@danielortiz1982 do you need me figure out something here for you to complete this if so please explain whactu need?

2021-07-21 16:32 UTC, EdwardCoyle reviewed
@danielortiz1982 just some minor things with docs and a question about the Input field sample:

2021-07-21 16:32 UTC, EdwardCoyle commented on app/ids-header/header-breadcrumb.html
> +{{> ../layouts/footer.html }}
```suggestion
{{> ../layouts/footer.html }}

```

2021-07-21 16:32 UTC, EdwardCoyle commented on app/ids-header/header-eyebrow.html
> +{{> ../layouts/footer.html }}
```suggestion
{{> ../layouts/footer.html }}

```

2021-07-21 16:32 UTC, EdwardCoyle commented on src/ids-header/README.md
> +
```suggestion
Header components can contain other navigation components, such as [IdsBreadcrumb](../ids-breadcrumb/README.md) and `[IdsToolbar](../ids-toolbar/README.md):

```html
<ids-header>
  <ids-toolbar id="my-toolbar">
    <ids-toolbar-section type="title">
      <ids-text font-size="20">My Header</ids-text>
      <ids-text font-size="14">With some extra information below</ids-text>
    </ids-toolbar-section>
    <ids-toolbar-section type="buttonset" align="end">
      <ids-button id="button-1" role="button">
        <span slot="text">Text</span>
      </ids-button>
      <ids-button id="button-2">
        <span slot="text" class="audible">Settings</span>
        <ids-icon slot="icon" icon="settings"></ids-icon>
      </ids-button>
    </ids-toolbar-section>
  </ids-toolbar>
</ids-header>
```

```

2021-07-21 16:32 UTC, EdwardCoyle commented on app/ids-header/header-search-field.html
> +<ids-header class="ids-header-example" color="#EB9728">
@tmcconechy what do you think about taking this example out for now?  The Search Field isn't complete yet and I'm not sure we should demo the standalone input field here.  If we keep the sample, @danielortiz1982 probably need to at least change the color to azure here (don't want to demo personalization without the system just yet)

2021-07-21 16:53 UTC, tmcconechy requested changes
A couple of small things but overall pretty good 👍🏻 . But one more style thing i'd like to add is the size is significantly taller than the old version for example https://main-enterprise.demo.design.infor.com/components/header/example-searchfield-expanded.html

I think maybe you just need to remove `<ids-text font-size="12" type="h1">Ids Header</ids-text>` from the examples.

Add TODOs for known outstanding issues

2021-07-21 16:53 UTC, tmcconechy commented on src/ids-header/ids-header.js
> +import '../ids-input/ids-input';
```suggestion
import IdsInput from '../ids-input/ids-input';
```

Same for all these imports... But sort of wondering if we want to require all these. @EdwardCoyle ?

2021-07-21 16:53 UTC, tmcconechy commented on src/ids-header/ids-header.js
> + * IDS Rating Component
```suggestion
 * IDS BreadCrumb Component
```

2021-07-21 16:53 UTC, tmcconechy commented on src/ids-header/ids-header.js
> +    this.color = this.color;
I'd like to investigate why this is needed. What exactly goes wrong if we remove?

2021-07-21 16:53 UTC, tmcconechy commented on src/ids-header/ids-header.js
> +    return [attributes.MODE, attributes.VERSION, attributes.COLOR];
```suggestion
    return [attributes.COLOR, attributes.MODE, attributes.VERSION];
```

2021-07-21 16:53 UTC, tmcconechy commented on src/ids-header/ids-header.js
> +    return [attributes.MODE, attributes.VERSION, attributes.COLOR];
We have been keeping this in order

2021-07-21 16:53 UTC, tmcconechy commented on src/ids-header/ids-header.js
> +   * Create the template for the rating contents
```suggestion
   * Create the template for the breadcrumb contents
```

2021-07-21 16:53 UTC, tmcconechy commented on src/ids-header/ids-header.js
> +    return this.getAttribute('color') || '#0072ed';
Is the default set with css? If so maybe you dont need this.color = this.color since you dont need it to initially fire if seet with css.

2021-07-21 16:53 UTC, tmcconechy commented on app/ids-header/header-breadcrumb.html
> +    <ids-text font-size="12" type="h1">Header Breadcrumb</ids-text>
For this example can we show it with the larger text similar to https://main-enterprise.demo.design.infor.com/components/header/example-breadcrumbs.html

2021-07-21 16:53 UTC, tmcconechy commented on app/ids-header/header-search-field.html
> +<ids-header class="ids-header-example" color="#EB9728">
Sure we can take it out but just add a TODO.md and add - add searchfield example and - add color/personalization example

2021-07-21 16:53 UTC, tmcconechy commented on app/ids-header/header-breadcrumb.html
> +{{> ../layouts/head-no-padding.html }}
For all of these examples can you rename for consistency. For Example:

header-breadrumb - breadcrumb
header-eyebrow - eyebrow

2021-07-21 17:08 UTC, EdwardCoyle commented on src/ids-header/ids-header.js
> +    return this.getAttribute('color') || '#0072ed';
There is no default CSS for the header background at the moment.  @danielortiz1982 and I had discussed adding a CSS rule for each mode/version with just a background and text color.

2021-07-23 14:42 UTC, tmcconechy commented on app/ids-header/index.scss
> +body {
The only problem with this is it will end up in the prod builds. Is this needed with the container?

2021-07-23 19:25 UTC, EdwardCoyle approved these changes
@tmcconechy I'm OK merging this and continuing on the font color problems as part of #254

2021-07-23 19:45 UTC, tmcconechy commented
ok i pushed my fixes as well to remove the reset i added a reset setting that sets the margin to 0 on the body

2021-07-23 19:45 UTC, tmcconechy approved these changes

2021-07-23 19:46 UTC, merged