201 ids loading indicator
infor-design/enterprise-wc pull request #237
Opened 2021-07-02 20:13 UTC by rob2d

**Explain the details for making this change. What existing problem does the pull request solve?**

This PR adds the `ids-loading-indicator` design changes on the WC side.

**Related github/jira issue (required)**:

Partially Addresses #201
There's also a redesign portion for existing `enterprise` repo so it doesn't close out the issue.

**Steps necessary to review your pull request (required)**:

- after pulling the branch, visit `http://localhost:4300` or `http://localhost:4300/ids-loading-indicator`
- make sure all tests pass and that the functionality is satisfactory

**Included in this Pull Request**:
- [X] An e2e or functional test for the bug or feature.
- [X] A note to the change log.

2021-07-06 20:20 UTC, EdwardCoyle approved these changes
Looks really good!

2021-07-06 20:20 UTC, EdwardCoyle commented on test/ids-loading-indicator/ids-loading-indicator-func-test.js
> +  const createElemViaTemplate = async (innerHTML) => {
@tmcconechy (maybe for a future PR) This seems like something we should do in any tests where we insert markup instead of using `new`... This should probably end up being moved to a helper function at some point.

2021-07-08 16:11 UTC, deep7102 approved these changes
🍌 This is nice addition, Thanks! @rob2d

2021-07-08 19:56 UTC, tmcconechy requested changes
The only thing i'm wondering about in the example is why the 5 right most ones aren't doing anything?

https://drive.google.com/file/d/1Ju5_bOIEqtDXPUUjQisWQEye2utqaxal/view

Can we make those start up too? Everything else looks wonderful. 

Do we need any TODO's for things like attaching it to other components?
I'd also like to see an example with it at the very top of the page, in a card and in a datagrid for that.

2021-07-09 14:51 UTC, rob2d commented
@tmcconechy the ones on the right are determinate e.g. just representing a loader with specific percentage complete, so in a real app they would be moving... I couldn't tell from the figma spec since they don't animate but I wasn't aware of any functionality on it. 

Would it help to add some buttons to change the % for each of these? 

For the top of the page I didn't see we had a central index so I wasn't sure on adding lots of example pages since people wouldn't find it but I can add one.

2021-07-09 14:56 UTC, tmcconechy commented
yeah maybe a button that loops through and runs them all? and i guess skip the card/datagrid/page examples for now but we probably want them eventually.

2021-07-09 19:36 UTC, rob2d commented
@tmcconechy added some spinboxes to the examples. 

Needed to add a `label-hidden` attribute to `ids-spinbox`, just because things looked super off-balance with it in this scenario even though it seemed like an idiomatic way to adjust them (until we have full sliders).

![image](https://user-images.githubusercontent.com/1799905/125127785-0e6dec80-e0cb-11eb-83c4-9109041be61b.png)

2021-07-12 14:05 UTC, tmcconechy commented
@rob2d I just checked with design and the fact that the labels(35% / 72% ) are graphite 03 is a mistake. I noticed this since they are hard to see.

This was made before we got rid of graphite as a general rule. So can you make these Slate 60 instead? (the default text color)

2021-07-12 16:15 UTC, rob2d commented
@tmcconechy thanks for the catch, adjusted the palette.

2021-07-14 14:29 UTC, tmcconechy commented
This issue was previously approved so merging

2021-07-14 14:29 UTC, merged