242 ids container padding
infor-design/enterprise-wc pull request #248
Opened 2021-07-09 18:19 UTC by danielortiz1982

**Explain the details for making this change. What existing problem does the pull request solve?**

**Related github/jira issue (required)**:

**Steps necessary to review your pull request (required)**:

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [ ] A note to the change log.

2021-07-09 18:26 UTC, tmcconechy reviewed
Some thoughts... Looks correct tho

2021-07-09 18:26 UTC, tmcconechy commented on src/ids-container/ids-container.js
> +    this.padding = this.padding;
Why do we need to do this again? Didnt have to for scrollable option

2021-07-09 18:26 UTC, tmcconechy commented on src/ids-container/README.MD
> +<ids-container scrollable="true" padding="8px">
```suggestion
<ids-container scrollable="true" padding="8">
```

this is up for discussion but wondering if we should just assume always pixels? but maybe we might want other options?

2021-07-09 18:26 UTC, tmcconechy commented on src/ids-container/ids-container.js
> +    this.container.style.padding = value;
I the case of zero could just not set the inline style. (its one less hit on the DOM)

2021-07-09 18:35 UTC, danielortiz1982 commented on src/ids-container/README.MD
> +<ids-container scrollable="true" padding="8px">
I tried both and landed with a string as a value. Let's have a side chat about that. I would to show you my findings on it.

2021-07-09 18:36 UTC, danielortiz1982 commented on src/ids-container/ids-container.js
> +    this.container.style.padding = value;
Let me see how I can make that happen, I think it's being set by the setter.

2021-07-09 18:40 UTC, danielortiz1982 commented on src/ids-container/ids-container.js
> +    this.padding = this.padding;
Not sure where the issue lies, but the setter and getter do not work as expected until  you do this.

2021-07-09 18:48 UTC, tmcconechy commented on src/ids-container/README.MD
> +<ids-container scrollable="true" padding="8px">
Sure lets chat i just to clarify mean the "px" part...Unless we might need `em` `rem` ect

2021-07-12 14:17 UTC, tmcconechy commented
@danielortiz1982 is this ready? If so please add PR information for starts and take it out of draft?

2021-07-13 14:34 UTC, tmcconechy commented on src/ids-container/README.MD
> +- `Padding` {number} Sets the padding in px around the Ids Container.
```suggestion
- `padding` {number} Sets the padding in px around the Ids Container.
```

2021-07-13 14:40 UTC, tmcconechy requested changes
This isn't quite right. I think we need the width to be

1) width: calc(100% - padding)
2) Also you are no longer negating the browser 8px margin so we need to keep that part as well.

So i think it needs

a) the margins back
b) set the width to calc(100% - 8px + padding)
c) also the same with the height

Also if padding is zero (default) i dont think we should need to set anything

2021-07-13 15:31 UTC, tmcconechy commented
@danielortiz1982 ok will take i look i might have gotten the logic im saying wrong

2021-07-13 15:56 UTC, tmcconechy commented
@danielortiz1982 added the margin and defaults back. I think this way the percy tests should be the same as before and we have the reset and width set

2021-07-13 20:34 UTC, tmcconechy approved these changes
Made necessary changes.

2021-07-15 16:16 UTC, merged