2327 - ids-alert alignment within ids-text
infor-design/enterprise-wc pull request #2500
Opened 2024-06-26 21:16 UTC by clayinfor

**Explain the details for making this change. What existing problem does the pull request solve?**

Properly vertically-align `ids-alert` text when placed inside `ids-text`.

**Related github/jira issue (required)**:

Closes #2327 

**Steps necessary to review your pull request (required)**:

1. Check out this branch and run: `nvm use && npm i && npm run start`
2. Go to: http://localhost:4300/ids-alert/example.html
3. Ensure the alerts with the "Sample text" are correctly vertically aligned.

**Included in this Pull Request**:
- [ ] Some documentation for the feature.
- [ ] A test for the bug or feature.
- [x] A note to the change log.

2024-06-27 17:29 UTC, tmcconechy requested changes
@clayinfor 

a) can you add `margin-inline-end: 6px;` (or 4 i cant decide) so there is a little space
b) is there anything we can do about this overflow state? (something QA might flag) maybe we only need to show one here in the example for the text to fix?

<img width="334" alt="Screenshot 2024-06-27 at 1 29 00 PM" src="https://github.com/infor-design/enterprise-wc/assets/814283/54360f3c-5b44-4884-9ee7-cba28a75d0c6">

2024-07-01 08:15 UTC, glenlieorillo approved these changes
![image](https://github.com/infor-design/enterprise-wc/assets/102151352/235d72d1-e0ac-490d-bc24-b075c5954aa4)


https://github.com/infor-design/enterprise-wc/assets/102151352/6d31ba7b-06cf-4b39-b2ee-ef5d6095dc38


![image](https://github.com/infor-design/enterprise-wc/assets/102151352/01905419-e916-4072-a9b0-dcdc5a42af7e)

2024-07-01 12:19 UTC, jbrcna reviewed
this is working as expected.
<img width="612" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/0a168ddf-9189-49e0-9d21-b357c5fd3b33">

<img width="514" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/cf661a44-9464-4643-9ae4-4854f91f36b4">

However, in safari the icon alignment is a little different. wasn't sure if this is an issue
**Safari**
<img width="529" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/533ae6a1-99bb-4d43-97ca-04da80a429a6">

**Firefox**
<img width="585" alt="image" src="https://github.com/infor-design/enterprise-wc/assets/56722184/cc704af7-b775-4c28-a2ca-ee26111ae60f">

2024-07-01 13:44 UTC, tmcconechy approved these changes

2024-07-01 13:44 UTC, merged