2449 - ids-data-grid added keyword search
infor-design/enterprise-wc pull request #2528
Opened 2024-07-05 17:54 UTC by clayinfor

**Explain the details for making this change. What existing problem does the pull request solve?**

Added search feature to datagrid via `searchable` and `search-term-min-size` attributes.

**Related github/jira issue (required)**:

Closes #2449 

**Steps necessary to review your pull request (required)**:

1. Check out this branch and run: `nvm use && npm i && npm run start`
2. Go to: http://localhost:4300/ids-data-grid/searchable.html
3. Ensure that you can use the search-bar to filter the datagrid and that pagination, etc works.

**Included in this Pull Request**:
- [ ] Some documentation for the feature.
- [ ] A test for the bug or feature.
- [x] A note to the change log.

2024-07-05 19:59 UTC, jdilag90 submitted a review, later dismissed
Nice!, looks good to me

2024-07-08 14:53 UTC, tmcconechy requested changes
@clayinfor this looks good but two suggestions

1) Can we just have one toolbar (so put the search field on the same toolbar as above)
2) Does the search action omit an event? We recently added this and i think we should omit the same event and add to the docs https://github.com/infor-design/enterprise-ng/pull/1742

2024-07-12 06:22 UTC, jbrcna submitted a review, later dismissed
nice work! 
![Large GIF (1704x678)](https://github.com/user-attachments/assets/9197e1bf-7d26-4ab4-a2f9-676d7209116a)

2024-07-12 14:10 UTC, tmcconechy commented
@clayinfor did you check out my suggestions? Should be quick i hope then we can merge.

2024-07-19 20:14 UTC, tmcconechy commented
@clayinfor  also can you sync main and put this in a new 1.4.0 change log so it will reflect in the right version? Thanks

2024-07-22 16:38 UTC, clayinfor commented on doc/CHANGELOG.md
> +- `[Datagrid]` Fixed problem with `searchable` datagrid where eraser button was not persisting on search-filtered rows. ([#2449](https://github.com/infor-design/enterprise-wc/issues/2449))
hey @tmcconechy , this problem with the Eraser button we'll want to put in a new ticket please, because it was already buggy before (see [here](https://main.wc.design.infor.com/ids-data-grid/pagination-client-side.html)), and it's taking me more much time to debug.

2024-07-22 16:48 UTC, tmcconechy commented on doc/CHANGELOG.md
> +- `[Datagrid]` Fixed problem with `searchable` datagrid where eraser button was not persisting on search-filtered rows. ([#2449](https://github.com/infor-design/enterprise-wc/issues/2449))
Ok thats fine. Just make a new issue with the steps for later and let QA know on the issue. @clayinfor

2024-07-22 18:06 UTC, clayinfor commented on doc/CHANGELOG.md
> +- `[Datagrid]` Fixed problem with `searchable` datagrid where eraser button was not persisting on search-filtered rows. ([#2449](https://github.com/infor-design/enterprise-wc/issues/2449))
New issue created here: https://github.com/infor-design/enterprise-wc/issues/2615

2024-07-23 01:13 UTC, glenlieorillo approved these changes
https://github.com/user-attachments/assets/a6d8dc65-fdd7-4155-af67-f06990e492e2

2024-07-23 03:03 UTC, jbrcna approved these changes
<img width="1266" alt="image" src="https://github.com/user-attachments/assets/68e2bb59-0fe6-4bc7-a1a5-78d1b6a78bce">

2024-07-23 14:38 UTC, tmcconechy approved these changes

2024-07-23 14:38 UTC, merged