2472 - ids-data-grid virtual scroll performance
infor-design/enterprise-wc pull request #2575
Opened 2024-07-10 21:28 UTC by clayinfor

**Explain the details for making this change. What existing problem does the pull request solve?**

Fix virtual-scroll performance on datagrid.

**Related github/jira issue (required)**:

Closes #2472 

**Steps necessary to review your pull request (required)**:

1. Check out this branch and run: `nvm use && npm i && npm run start`
2. Go to: http://localhost:4300/ids-data-grid/virtual-scroll-programmatic.html
3. Click the button "Grid init & load the data"
4. Scroll all the way to the bottom of the grid, and scroll all the way to the right.
5. Ensure the datagrid loads quickly and doesn't show the white-screen too much.
6. Click the "Hide/Show first column" and ensure the datagrid doesn't show the white-screen.
7. Compare to stackblitz: https://stackblitz.com/edit/ids-enterprise-wc-120-scqypu?file=index.html

**Included in this Pull Request**:
- [ ] Some documentation for the feature.
- [ ] A test for the bug or feature.
- [x] A note to the change log.

2024-07-12 18:23 UTC, tmcconechy submitted a review, later dismissed
This is looking pretty good. I still think the scrolling is a bit clunky and wonder if it can be improved further?

Also when i click "hide/show" first column it looks wierd / something strange is happing it looks like the column that is readonly is replaced with the adjustcent column. Could be an issue

2024-07-13 07:08 UTC, clayinfor commented
thanks for your feedback @tmcconechy , I've added `display:none` to columns with `columns-offscreen-right`attribute, and this prevents browser repaint which helps a lot

2024-07-15 10:14 UTC, n-ace-ancog commented
Clicking the select all doesn't update the checkboxes shown in the page. Scrolling down and up corrects this.

https://github.com/user-attachments/assets/148367dc-255b-45e4-93bd-8efe1483b276

2024-07-15 13:42 UTC, clayinfor commented on src/components/ids-data-grid/ids-data-grid-cell.ts
> +    if (this.innerHTML !== template) {
see if we could use some sort of diffing algo to do this comparison (sort of like how ReactJS virtual DOM works)

2024-07-15 14:04 UTC, clayinfor commented on src/components/ids-data-grid/ids-data-grid.ts
> +  readonly TOO_MANY_COLUMNS = 30; // 30 is arbitrary number that we can recondsider
We added this number of 30 so that horizontal virtual scrolling optimizations are ignored on datagrids with less columns, but we can consider tweaking it, turning it off, or converting it into a configurable attribute that end-users can control.

2024-07-15 14:32 UTC, jdilag90 commented
Nice, virtual scroll feels smoother on all the virtual scroll examples so far

However, still seeing issue with the tree grid expanded/collapsed states
1). Go to http://localhost:4300/ids-data-grid/tree-grid-virtual-scroll.html
2). Scroll to the bottom and collapse some rows
3). Scroll up to the top
4). Scroll back down to the bottom
5). Notice the collapse/expanded icons are incorrect
6). Might have to try a few times to trigger it

https://github.com/user-attachments/assets/967093af-faa3-4efb-b15b-706f1ceb7d8d

2024-07-17 04:17 UTC, jbrcna requested changes
![Large GIF (1710x830)](https://github.com/user-attachments/assets/d34be66c-8bec-4533-ab11-74d1c65c19c9)

2024-07-17 10:27 UTC, glenlieorillo requested changes
I still see too much white screen on my end.

https://github.com/user-attachments/assets/a8f66739-481c-4eda-b60f-cbf3952489f7

2024-07-19 20:14 UTC, tmcconechy commented
@clayinfor  also can you sync main and put this in a new 1.4.0 change log so it will reflect in the right version? Thanks

2024-08-13 15:41 UTC, tmcconechy commented
@clayinfor any updated to complete this?

2024-09-09 16:16 UTC, tmcconechy commented
@jdilag90 Trying to get this going again. Do you still see the issues with the tree?

2024-09-11 10:26 UTC, clayinfor commented on src/components/ids-data-grid/ids-data-grid-row.ts
> +      [...cells].forEach((cell) => cell?.renderCell?.());
Only problem with doing this is `IdsDataGridRow.cellsHTML()` sets some important attributes and cssParts that are missed by calling `IdsDataGridCell.renderCell()`... so we must ensure that `renderCell()` doesn't miss any of these.

2024-09-12 06:24 UTC, jbrcna approved these changes
![Large GIF (1084x654)](https://github.com/user-attachments/assets/0225900f-a8b4-41b2-b23d-71682d69655f)

2024-09-12 17:34 UTC, tmcconechy commented
1. https://github.com/infor-design/enterprise-wc/pull/2622/files#diff-b36602c50a71b802ead0a99f28f4026557a47fe4e35f01496aab87a8da42ec4dR431
 
But later its gone? Something with the row caching?
2.  The other thing which may be related is it seems to not be rendering the right data in the columns...
 
Before: https://main.wc.design.infor.com/ids-data-grid/columns-fixed.html
After: http://localhost:4300/ids-data-grid/columns-fixed.html 

3. Tests....

Will close this for now. So we can redo this PR once these are resolved

2024-09-12 17:34 UTC, closed without merging

2024-09-17 05:50 UTC, clayinfor commented on src/components/ids-data-grid/ids-data-grid-row.ts
> +      [...cells].forEach((cell) => cell?.renderCell?.());
`IdsDataGridRow.cellsHTML()` is concerned with classes and attributes on the "outerHTML" (i.e. `<ids-data-grid-cell />`) and `IdsDataGridCell.renderCell()` is concerned with the "innerHTML" (i.e. the contents inside the cell tag), so I think we're good here...