2248 - IdsDropdown fix size setting for angular
infor-design/enterprise-wc pull request #2580
Opened 2024-07-11 17:23 UTC by jdilag90

**Explain the details for making this change. What existing problem does the pull request solve?**
Fixed dropdown size setting for angular templating.
DropdownList needed to be configured on `slotchange` for dynamic content projection

**Related github/jira issue (required)**:
Closes #2248 

**Steps necessary to review your pull request (required)**:
1. Checkout branch
2. Go to http://localhost:4300/ids-dropdown/sizes.html
3. Check that size `full` and `large` still work

**Test in angular**
1. `npm link` this branch's build to the angular wc examples repo
2. Run angular example project
3. Go to http://localhost:4200/ids-dropdown/sizes
4. Check that dropdown size are correct
5. Go to http://localhost:4200/ids-multiselect/example
6. Run both `$('#multiselect-2').size = 'full';` `$('#multiselect-2').size = 'lg';` in console
7. Check that the multiselect dropdown are properly sized

**Included in this Pull Request**:
- [ ] Some documentation for the feature.
- [ ] A test for the bug or feature.
- [x] A note to the change log.

2024-07-11 19:21 UTC, tmcconechy approved these changes

2024-07-12 10:07 UTC, n-ace-ancog requested changes
In http://localhost:4200/ids-dropdown/sizes, when a dropdown is resized to `full` then resized again to `sm`, pop up opens even when clicking outside of the dropdown.

**Steps to reproduce**
1. Enter `$('ids-dropdown:nth-child(6)').size = 'full'`
2. Enter `$('ids-dropdown:nth-child(6)').size = 'sm'`
3. Click outside the resized dropdown

https://github.com/user-attachments/assets/d6db3339-3ebf-4261-acf0-73a86d48f59a

2024-07-12 13:27 UTC, jdilag90 commented
@n-ace-ancog fixed `full` size toggling and its open trigger zones

2024-07-12 18:34 UTC, tmcconechy approved these changes

2024-07-15 05:18 UTC, jbrcna approved these changes
![Large GIF (1698x678)](https://github.com/user-attachments/assets/ebd0a0eb-33fb-428d-90eb-f6a992e3852f)
<img width="1319" alt="image" src="https://github.com/user-attachments/assets/d1e82f6f-04ac-4c28-988b-49bc7c786aaf">

2024-07-15 09:44 UTC, n-ace-ancog approved these changes
Now working on my end.

https://github.com/user-attachments/assets/f792f0cb-338c-4bb6-bac3-41272acd48e5

I just noticed this very intermittent behavior when switching languages. A dropdown may or may not work after doing so. Its hard to replicate, but seems like it has something to do with switching languages. The issue came at the end of the video below.

https://github.com/user-attachments/assets/e0286a5b-c356-4dae-8cdb-70f9f4763ff7

2024-07-15 13:10 UTC, jdilag90 commented
@n-ace-ancog can you please make an ticket for that last video?

2024-07-19 18:15 UTC, merged