229 - Implement IdsNotificationBanner
infor-design/enterprise-wc pull request #262
Opened 2021-07-19 20:19 UTC by jmacaluso711

**Explain the details for making this change. What existing problem does the pull request solve?**
Adds the Ids Notification Banner web component

**Related github/jira issue (required)**:
closes #229 

**Steps necessary to review your pull request (required)**:
- pull this branch, then go to http://localhost:4300/ids-notification-banner and http://localhost:4300/ids-notification-banner/dynamic
- Make sure functionality it accounted for and all tests pass.

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2021-07-20 15:15 UTC, tmcconechy requested changes
Looks great. Just some minor things.

1) you can use https://github.com/infor-design/enterprise-wc/pull/236/files#diff-d5229cb85a06ecb886c23fa73563d14bc82822c8d7e541f2ca443268099de90bR15 when its merged so its flush with the sides
2) the X looks a lot bigger then https://main-enterprise.demo.design.infor.com/components/notification/example-index.html maybe you can use the smaller size icon so its closer. Also is the text a different color

2021-07-20 15:15 UTC, tmcconechy commented on src/ids-notification-banner/ids-notification-banner.js
> + * @part container - the notification banner element
These are the things to add to the TODO (themable parts) in the readme fyi. https://github.com/infor-design/enterprise-wc/blob/main/src/ids-tag/README.MD#themeable-parts

2021-07-20 15:15 UTC, tmcconechy commented on src/ids-notification-banner/ids-notification-banner.js
> +  attributeChangedCallback(name, oldValue, newValue) {
Do we need this? IdsElement should handle this logic as far as i can tell by reading?

2021-07-20 15:15 UTC, tmcconechy commented on src/ids-notification-banner/ids-notification-banner.js
> +      attributes.TYPE,
Nit: but can keep this alphabetized

2021-07-20 17:51 UTC, jmacaluso711 commented on src/ids-notification-banner/ids-notification-banner.js
> +  attributeChangedCallback(name, oldValue, newValue) {
👍  Not needed, removing

2021-07-20 17:51 UTC, jmacaluso711 commented on src/ids-notification-banner/ids-notification-banner.js
> + * @part container - the notification banner element
👍

2021-07-20 17:51 UTC, jmacaluso711 commented on src/ids-notification-banner/ids-notification-banner.js
> +      attributes.TYPE,
👍

2021-07-21 14:33 UTC, tmcconechy commented on src/ids-notification-banner/TODO.MD
> +- [] `bgColor` Allows you to further style the background
Sorry what i meant was this can go in the todo section of the README.md https://github.com/infor-design/enterprise-wc/pull/262/files?file-filters%5B%5D=.MD&file-filters%5B%5D=.html&file-filters%5B%5D=.js&file-filters%5B%5D=.md&file-filters%5B%5D=.snap&file-filters%5B%5D=.ts#diff-7410e66193a0896842afe5ceedecd4938866ba1ff3b649b2cab249390b4861c6R78

Other than that looks good

2021-07-21 15:28 UTC, jmacaluso711 commented on src/ids-notification-banner/TODO.MD
> +- [] `bgColor` Allows you to further style the background
👍

2021-07-21 16:37 UTC, tmcconechy approved these changes

2021-07-21 17:04 UTC, EdwardCoyle commented on src/ids-notification-banner/ids-notification-banner.js
> +  add(notification) {
Would be nice if we could generalize this pattern in a mixin and provide object-based batch settings for any component -- I've run into a few spots where this could be useful (maybe for phase 2)

2021-07-22 13:18 UTC, merged