2583 - IdsSplitter fix scrollbar in splitter pane
infor-design/enterprise-wc pull request #2659
Opened 2024-07-30 17:55 UTC by jdilag90

**Explain the details for making this change. What existing problem does the pull request solve?**
Amends issue #2583 to readd the scrollbar

**Related github/jira issue (required)**:
Closes #2583 

**Steps necessary to review your pull request (required)**:
1. Checkout branch
2. Go to http://localhost:4300/ids-splitter/expand-collapse.html
3. Expand tree component nodes to create an overflow inside left splitter pane
4. Check that a scrollbar appears and looks correct
5. Resize viewport and check that scrollbar for listview component in right pane is correct

**Included in this Pull Request**:
- [x] A note to the change log.

2024-07-30 18:44 UTC, tmcconechy approved these changes

2024-07-31 06:29 UTC, jbrcna approved these changes
<img width="610" alt="image" src="https://github.com/user-attachments/assets/05c253a3-ca37-46cf-9015-3d926316f9d3">

2024-07-31 10:03 UTC, n-ace-ancog requested changes
Clicking the menu button a couple of times hides some elements.

https://github.com/user-attachments/assets/fe90cffd-d30c-4a41-ad00-4fa72866206f

2024-07-31 12:31 UTC, pwpatton commented
> Clicking the menu button a couple of times hides some elements.

I believe this one is already reported here: https://github.com/infor-design/enterprise-wc/issues/2588

2024-07-31 12:35 UTC, tmcconechy commented
Yes @n-ace-ancog we have some additional splitter issues related to restoring size. Will do those next sprint.

2024-07-31 12:53 UTC, pwpatton commented
We seem to have lost the styled scrollbars. This is happening on windows.

![image](https://github.com/user-attachments/assets/1f47dbeb-ecc6-4c72-9ac9-7bc27e342633)

In 1.2 they were styled

![image](https://github.com/user-attachments/assets/309b9439-e5e6-4838-97be-158caaa00520)

2024-07-31 13:00 UTC, tmcconechy commented
yeah we arent doing the styled scoll bars anymore as of now... We could tho? But i think its a seperate discussion. I still think its a bad idea but may be needed in a mixed context @pwpatton so out of scope lets make a new issue for discussing this.

2024-07-31 13:45 UTC, n-ace-ancog approved these changes
Thanks @tmcconechy. Looks good to me.

2024-07-31 18:17 UTC, merged