247 - fix the padding for ids-toggle-button w/ text + icon
infor-design/enterprise-wc pull request #266
Opened 2021-07-20 18:56 UTC by vivz753

**Explain the details for making this change. What existing problem does the pull request solve?**

- The padding was being overrided by old `_reset.scss`, so the css for .ids-toggle-button just needed an `!important` to override it (only an issue when old components + new components are being used together in the same page)
- I also added in a fix for when the icon is aligned to the right (there was no padding btw the text and icon in that order)

**Related github/jira issue (required)**:

- Closes #247 

**Steps necessary to review your pull request (required)**:

- `npm run start:watch` 
- http://localhost:4300/ids-toggle-button/side-by-side
- http://localhost:4300/ids-toggle-button
- http://localhost:4300/ids-toggle-button/icon-align-right
- Ensure that the padding is consistent btw the icon and text for all the examples above

After changes:
icon-align-right
<img width="195" alt="Screen Shot 2021-07-20 at 11 53 21 AM" src="https://user-images.githubusercontent.com/22609861/126379861-cb0ce2b6-7977-4b1e-9d7b-fc4e3bc10ba5.png">
side-by-side
<img width="265" alt="Screen Shot 2021-07-20 at 11 53 28 AM" src="https://user-images.githubusercontent.com/22609861/126379862-f8c3dd0d-717e-4826-96eb-70fc35d21008.png">

Before changes:
icon-align-right
<img width="185" alt="Screen Shot 2021-07-20 at 11 55 14 AM" src="https://user-images.githubusercontent.com/22609861/126379864-3498e830-06ea-48af-8641-276d04926768.png">
side-by-side
<img width="234" alt="Screen Shot 2021-07-20 at 11 55 20 AM" src="https://user-images.githubusercontent.com/22609861/126379865-66916e30-b17b-4fc0-be30-eecaf22c42dc.png">

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [ ] A note to the change log.

2021-07-21 00:43 UTC, vivz753 commented
Note to self: this messes up the padding btw text and icons for `ids-button` (for some reason now the padding is non-existent for those, even though the padding shows up for `ids-toggle-button` now; must be in the `ids-button.scss` file since it lumps both `ids-button` and `ids-toggle-button` classes together)

2021-07-21 14:40 UTC, tmcconechy requested changes
I think this change caused a couple visual regressions see https://percy.io/00aaa841/enterprise-wc/builds/11637268/changed/654742439?browser=chrome&browser_ids=16&subcategories=unreviewed%2Cchanges_requested&viewLayout=side-by-side&viewMode=new&width=1280&widths=375%2C1280

The checkbox one im not sure about but on http://localhost:4300/ids-button the left side icon is not inverse

![Screen Shot 2021-07-21 at 10 38 18 AM](https://user-images.githubusercontent.com/814283/126507404-c6312799-fd15-472b-b5b8-990ee028a427.png)

Maybe padding on both left and right?

Related http://localhost:4300/ids-expandable-area the button on the bottom never look right and seems ok with both left and right padding?

2021-07-21 15:53 UTC, vivz753 commented
I've fixed the issue w putting back the padding for the `ids-button` 
<img width="141" alt="Screen Shot 2021-07-21 at 8 53 22 AM" src="https://user-images.githubusercontent.com/22609861/126519956-43afaadc-043f-41bc-8d01-5db2fa1ea58e.png">


Regarding http://localhost:4300/ids-expandable-area, the button has padding 4px from the left of the <span> text, looks fine to me 

<img width="117" alt="Screen Shot 2021-07-21 at 8 51 29 AM" src="https://user-images.githubusercontent.com/22609861/126519794-b38b14c8-6e71-48c0-aa92-aefc2cf67872.png">

2021-07-22 14:06 UTC, tmcconechy approved these changes

2021-07-23 14:15 UTC, EdwardCoyle approved these changes

2021-07-23 14:39 UTC, merged