4631 - Check the way typings implement
infor-design/enterprise-wc pull request #27
Opened 2020-12-28 20:10 UTC by ericangeles

**Explain the details for making this change. What existing problem does the pull request solve?**

I see no problem the way we create our ts files (typing definitions) in web components. So this PR will just contain a tsconfig.json that will (an optional way) check and act just a linter for the ts files.

Below are the information that we can use for linting/plugin on TypeScript for the different editors

**VSCode**
TypeScript Compiler
https://code.visualstudio.com/docs/languages/typescript
Eslint
https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint

**Atom**
TypeScript Compiler
https://atom.io/packages/atom-typescript
Eslint
https://atom.io/packages/linter-eslint

**Sublime**
TypeScript Compiler
https://packagecontrol.io/packages/TypeScript
Eslint
https://packagecontrol.io/packages/ESLint

**Related github/jira issue (required)**:

Partial fix https://github.com/infor-design/enterprise/issues/4631
Related fix https://github.com/infor-design/enterprise-wc-examples/pull/4

**Steps necessary to review your pull request (required)**:
- Pull this branch
- Run `npm start`
- To test the tsconfig, try to edit any ts files. (Make errors)
- In the command line run `npm run lint:types`
- If the ts files you change has error, it should prompt the errors

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [ ] A note to the change log.

2020-12-28 21:03 UTC, tmcconechy commented on package.json
> +    "typescript": "~3.9.7",
Latest version is 4.1.3 https://www.npmjs.com/package/typescript i think we should start with that.

Also tslint is deprecated https://www.npmjs.com/package/tslint so think it would be better if we can find a way to run the lint task with eslint? https://codeburst.io/from-eslint-to-tslint-and-back-again-bf259c2e7437
i think we will need a seperate command for that and possibly a seperate eslint config?

I have some newer eslint versions in my coming PR but that shouldnt matter too much

Can you try that out?

2020-12-29 15:43 UTC, tmcconechy requested changes
Lets use eslint to lint TS files as tslint is deprecated

2021-01-04 04:12 UTC, ericangeles commented
@tmcconechy I just changed the parser to `@typescript-parser`. For some reason, babel-eslint doesn't work correctly without any config. 

I've got the same issue on this link
https://github.com/typescript-eslint/typescript-eslint/issues/962

2021-01-04 14:56 UTC, tmcconechy reviewed
OK, I think maybe because of the errors added with combining configs we can try what this project does.

https://github.com/elix/elix/blob/master/package.json#L13
https://github.com/elix/elix/blob/master/package.json#L54

So just a type check and add a main ts file that imports them all. Also i think that the BIG PR i just did will affect this. So once thats merged i'll take a deeper look here.

2021-01-05 14:38 UTC, tmcconechy commented
@ericangeles i've worked through this. And will close this and do a new PR with what i've added. I went the type checking route as it uncovered a few things that will help. So no need to continue on this PR for now ...  new PR to follow

2021-01-05 14:38 UTC, closed without merging