#1957 - Ids multiselect  conversion
infor-design/enterprise-wc pull request #2736
Opened 2024-08-19 11:43 UTC by jbrcna

**Explain the details for making this change. What existing problem does the pull request solve?**

**Related github/jira issue (required)**:

closes #1957 

**Steps necessary to review your pull request (required)**:

Run the test suite
Check the code conversion
New converted tests should pass

**Included in this Pull Request**:
- [ ] Some documentation for the feature.
- [ ] A test for the bug or feature.
- [ ] A note to the change log.

2024-08-19 13:06 UTC, ericangeles commented on tests/ids-multiselect/ids-multiselect.spec.ts
> +    test('supports async beforeShow', async ({ page }) => {
You can avoid using `evaluate` repeatedly by combining actions when possible.

2024-08-19 13:07 UTC, ericangeles requested changes
Looks good, but please fix the lint issue (unused `page` parameter).

2024-08-19 13:42 UTC, jbrcna commented on tests/ids-multiselect/ids-multiselect.spec.ts
> +    test('supports async beforeShow', async ({ page }) => {
What exactly do you mean by this?
should it look like this?
```
await multiselectElem.evaluate((elem: IdsMultiselect) => {
await elem.open();
elem.popup!.visible
another action;
just another action;
}
```

2024-08-19 14:47 UTC, ericangeles commented on tests/ids-multiselect/ids-multiselect.spec.ts
> +    test('supports async beforeShow', async ({ page }) => {
This is more of a preference. What I would do is,

```js
test('supports async beforeShow', async ({ page }) => {
  // Ensure the initial state is correct
  const initialOptionsCount = await page.locator('ids-list-box-option').count();
  expect(initialOptionsCount).toEqual(34);

  // Set up the async beforeShow function
  await multiselectElem.evaluate((elem: IdsMultiselect, state: any) => {
    elem.beforeShow = async () => {
      return new Promise((resolve) => setTimeout(() => resolve(state), 1));
    };
  }, states);

  // Open the multiselect element
  await multiselectElem.evaluate(async (elem: IdsMultiselect) => {
    await elem.open();
  });

  // Verify the updated state
  const updatedOptionsCount = await page.locator('ids-list-box-option').count();
  expect(updatedOptionsCount).toEqual(86);
});
```

As you can see, I consolidated the `evaluate` calls. Setting up `beforeShow` and opening the element are done separately to reduce the number of evaluate calls.

Also, I used `count` to simplified the process of checking the number of elements instead of getting all and measuring by length.

2024-08-22 16:03 UTC, tmcconechy submitted a review, later dismissed

2024-08-22 18:46 UTC, andrivarhanov approved these changes

2024-08-27 03:43 UTC, n-ace-ancog submitted a review, later dismissed

2024-08-28 06:19 UTC, ericangeles commented
@tmcconechy, looks like there's something wrong with the visual test

https://percy.io/00aaa841/enterprise-wc/builds/36076652/changed/1972895232?browser=chrome&browser_ids=59&group_snapshots_by=similar_diff&subcategories=unreviewed%2Cchanges_requested&utm_source=github_status_public&viewLayout=side-by-side&viewMode=new&width=1280&widths=375%2C1280

2024-08-28 12:46 UTC, tmcconechy commented
@ericangeles some weird stuff going on there. I am looking at it and I have a support ticket with Percy

2024-08-28 15:40 UTC, merged