268 - add completion chart web component
infor-design/enterprise-wc pull request #284
Opened 2021-07-30 23:07 UTC by vivz753

**Explain the details for making this change. What existing problem does the pull request solve?**

Added Progress Chart component, test cases, documentation

**Related github/jira issue (required)**:

- Closes #268 

**Steps necessary to review your pull request (required)**:

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [ ] A note to the change log.

2021-08-02 15:08 UTC, EdwardCoyle requested changes
@vivz753 This is looking really nice!  I found a few issues with the API surrounding setting labels, which are detailed below.  I also added a few docs/checklist suggestions.  Also had one question about the render lifecycle overall.  I'd be ready to approve after you review these 👍

2021-08-02 15:08 UTC, EdwardCoyle commented on src/ids-progress-chart/ids-progress-chart.js
> +  set label(value) {
The getter for this seems to be working, but this doesn't seem to actually update the label when changed (attribute works though).

2021-08-02 15:08 UTC, EdwardCoyle commented on src/ids-progress-chart/ids-progress-chart.js
> +    this.setAttribute(attributes.LABEL_PROGRESS, value || '');
This one isn't updating the label either

2021-08-02 15:08 UTC, EdwardCoyle commented on src/ids-progress-chart/ids-progress-chart.js
> +    this.setAttribute(attributes.LABEL_TOTAL, value || '');
This one also isn't updating its label

2021-08-02 15:08 UTC, EdwardCoyle commented on test/ids-progress-chart/ids-progress-chart-func-test.js
> +    expect(chart.progressLabel).toBe('50 meters');
Probably also want to check the value that gets applied to the shadow DOM labels in each of these label tests.

2021-08-02 15:08 UTC, EdwardCoyle commented on doc/CHECKLIST.md
> + - [ ] Completion Chart (ids-progress-chart)
```suggestion
 - [x] Completion Chart (ids-progress-chart)
```

2021-08-03 14:51 UTC, tmcconechy requested changes
Few small things.. In addition regarding the functionality on http://localhost:4300/ids-progress-chart/

- not seeing the icon example
- not seeing the right side label examples?
- not seeing the "13h" example

2021-08-03 14:51 UTC, tmcconechy commented on app/ids-progress-chart/example.html
> +  <ids-text font-size="12" type="h1">README.md Examples</ids-text>
Lets put these on a separate page or not include? (just to keep it clean and simple)

2021-08-03 14:51 UTC, tmcconechy commented on src/ids-base/ids-attributes.js
>    LABEL_REQUIRED: 'label-required',
This section looks out of alphabetic order (some from before)

2021-08-03 14:51 UTC, tmcconechy commented on src/ids-progress-chart/ids-progress-chart.d.ts
> +  progress: string;
Add comments for these as well?

2021-08-03 14:51 UTC, tmcconechy commented on src/ids-progress-chart/ids-progress-chart.js
> +      attributes.PROGRESS,
Pls keep these in alphabetic order.

2021-08-03 14:51 UTC, tmcconechy commented on src/ids-progress-chart/ids-progress-chart.js
> +  updateColor() {
Add comment? And if private can use #updateColor https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields

2021-08-03 14:51 UTC, tmcconechy commented on src/ids-progress-chart/ids-progress-chart.js
> +  updateLabel(labelType) {
Same for all these methods.. If private use private class features and a comment with @private
If public just a comment but i think these are private as you would set these with the setter.

2021-08-03 16:22 UTC, deep7102 commented
Looks Nice! great work, just few things see as addition of Ed and Tim.
- empty attributes can be removed from markup, The empty state can be handled in shadow dom `label-total="" total=""`
- is `alert` should have `warning` and `alert-yellow` should have `caution` color
- saw error in console, on loading the example page: http://localhost:4300/ids-progress-chart/

<img width="893" alt="image" src="https://user-images.githubusercontent.com/38439203/128049474-9f42dd55-ed57-4afb-9233-6ef62f700aa1.png">

2021-08-03 23:55 UTC, vivz753 commented on app/ids-progress-chart/example.html
> +  <ids-text font-size="12" type="h1">README.md Examples</ids-text>
Done

2021-08-04 00:10 UTC, vivz753 commented on test/ids-progress-chart/ids-progress-chart-func-test.js
> +    expect(chart.progressLabel).toBe('50 meters');
Done

2021-08-04 00:11 UTC, vivz753 commented
> Few small things.. In addition regarding the functionality on http://localhost:4300/ids-progress-chart/
> 
> * not seeing the icon example
> * not seeing the right side label examples?
> * not seeing the "13h" example

Try now?

2021-08-04 13:24 UTC, tmcconechy reviewed
Looks good on my comments - added a few more comments. In addition need a test that covers the new line https://coveralls.io/builds/41883116/source?filename=src%2Fids-progress-chart%2Fids-progress-chart.js#L139

2021-08-04 13:24 UTC, tmcconechy commented on app/ids-progress-chart/index.yaml
> + category: Data Visualization
```suggestion
 category: Charts and Visualizations
```

2021-08-04 13:24 UTC, tmcconechy commented on test/ids-progress-chart/ids-progress-chart-e2e-test.js
> +    // await expect(page).toPassAxeTests();
Instead of commenting it out  you can do this and disable the contrast check. Since it is the design its valid to disable for now

```
await expect(page).toPassAxeTests({ disabledRules: ['color-contrast'] });
```

2021-08-04 13:51 UTC, deep7102 commented
@vivz753 
Great, all the points I had working now and no error anymore -thanks

2021-08-04 15:42 UTC, vivz753 commented on test/ids-progress-chart/ids-progress-chart-e2e-test.js
> +    // await expect(page).toPassAxeTests();
Thanks, done!

2021-08-04 18:41 UTC, jmacaluso711 commented on src/ids-progress-chart/ids-progress-chart.js
> +        <ids-text class="label-main">${this.label ? this.label : ''}</ids-text>
Small thing.. Probably better to wrap the component in the ternary that way it doesn't render if the label is left empty for some reason:

`${this.label ? : <ids-text class="label-main">${this.label}</ids-text> : ''}`

2021-08-04 18:41 UTC, jmacaluso711 commented on src/ids-progress-chart/ids-progress-chart.js
> +        <ids-text class="label-progress">${this.progressLabel ? this.progressLabel : ''} </ids-text>
Same here

2021-08-04 18:41 UTC, jmacaluso711 commented on src/ids-progress-chart/ids-progress-chart.js
> +          <ids-text class="label-total">${this.totalLabel ? this.totalLabel : '' }</ids-text>
and here

2021-08-04 19:00 UTC, tmcconechy commented
One more thing the Yaml is not auto importing now so have to add an entry

here
https://github.com/infor-design/enterprise-wc/blob/main/app/example.js#L30
and here
https://github.com/infor-design/enterprise-wc/blob/main/app/example.js#L98

2021-08-04 19:19 UTC, vivz753 commented
It doesn't look good with the normal size icon @tmcconechy 

Here is a screenshot with `size="normal"` / `size="medium"`
![Screen Shot 2021-08-04 at 12 18 18 PM](https://user-images.githubusercontent.com/22609861/128241706-eb505a54-dc8f-411d-8ae2-f6570a89a9e7.png)

`ids-icon` offers small (10px) medium (18px) or large (24px)

The original example has it in 14px

2021-08-05 14:11 UTC, tmcconechy commented
Thinking that we could add the 14px icon to ids-icon.js the problem is that what would we call it ? small-medium?

2021-08-05 14:21 UTC, EdwardCoyle commented
@tmcconechy I'm in need of an "extra-large" size for icons, so maybe makes sense to punt new icon sizes to another issue.  I'm not sure we should do the "small-medium" thing as that got really confusing in 4.x.  I think what's there now is fine until we re-work our sizes.  @vivz753 I'm ready to approve once the coverage is up.

2021-08-05 14:23 UTC, tmcconechy commented
yeah agree we wanted to do away with it ok lets stick to that. we can add an xl later if needed. this looks good to me too other than the coverage so will also approve when thats up/ignored

2021-08-05 23:03 UTC, vivz753 commented
Tests are now at 100% coverage! 

Now, what's the process for getting new snapshots in Percy approved?

Anyone know why would this error dialog be affected?

<img width="1424" alt="Screen Shot 2021-08-05 at 4 01 32 PM" src="https://user-images.githubusercontent.com/22609861/128432148-b048aee8-d4d0-4c15-b577-2723ee431c16.png">

2021-08-06 13:26 UTC, tmcconechy commented
@vivz753 for percy you can self approve them but since your newer might not know every detail so me and ed can look. regarding the message one there is a known issue here https://github.com/infor-design/enterprise-wc/issues/295 we will fix it later so i approved this for now

Great Job on your first one 🥇

2021-08-06 13:26 UTC, tmcconechy approved these changes

2021-08-06 14:05 UTC, deep7102 approved these changes
Looks good 🍌

2021-08-06 16:19 UTC, EdwardCoyle approved these changes
Really nice @vivz753!

2021-08-06 18:34 UTC, merged