276 add summary form
infor-design/enterprise-wc pull request #300
Opened 2021-08-06 21:02 UTC by vivz753

**Explain the details for making this change. What existing problem does the pull request solve?**

- Adds the Summary Form Web Component 
- Based on 4.x Summary Fields here https://main-enterprise.demo.design.infor.com/components/form/example-forms.html

**Related github/jira issue (required)**:

- Closes #276 

**Steps necessary to review your pull request (required)**:

- npm run start:watch
- http://localhost:4300/ids-summary-form

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [ ] A note to the change log.

<img width="393" alt="Screen Shot 2021-08-06 at 2 01 58 PM" src="https://user-images.githubusercontent.com/22609861/128570706-3e30f0bf-64d6-4a6e-ac08-36b7bf5d1de7.png">

2021-08-06 21:04 UTC, vivz753 commented on src/ids-summary-form/ids-summary-form.js
> +        <ids-text class="data" font-weight="${this.fontWeight ?? 'bold'}">${this.data ?? ''}</ids-text>
Null coalescing operator calls the get() one less than doing `this.label ? this.label : ''`

Read more here: https://medium.com/quick-programming/3-javascript-features-you-might-not-know-de8ef797b6e4

2021-08-06 21:27 UTC, vivz753 commented
I don't think I have the ability to approve Percy tests, which I'm assuming is done with the green thumb icon in the top right (it's disabled for me)

<img width="1677" alt="Screen Shot 2021-08-06 at 2 26 54 PM" src="https://user-images.githubusercontent.com/22609861/128572790-aae4ab7c-a7ef-4e36-8213-4b884dab95a7.png">

2021-08-06 21:46 UTC, vivz753 commented on app/ids-progress-chart/example.html
> +      <ids-icon slot="icon" icon="error" size="medium"></ids-icon>
Forgot to change this in the example for `ids-progress-chart` PR @tmcconechy

2021-08-06 21:46 UTC, vivz753 commented on src/ids-mixins/README.md
> +6. Add the color changes for each theme scss file. For example:
@EdwardCoyle noticed this when we were discussing the color variant, please confirm

2021-08-09 13:46 UTC, tmcconechy requested changes
Looks really good just a few small things

2021-08-09 13:46 UTC, tmcconechy commented on app/ids-summary-form/example.html
> +  <ids-summary-form label="Synopsis of Game of Thrones pilot episode" data="
Might be a little much text going on for the example. While an interesting plot i think some of the topics could be a little sensitive to some sensitive people. We generally stick to something like "office ipsum" or "corporate ipsum" and sometimes "hipster ipsum".

So maybe use one of these and make it a bit shorter just enough to show the line wraps

2021-08-09 13:46 UTC, tmcconechy commented on src/ids-mixins/README.md
> +6. Add the color changes for each theme scss file. For example:
If that works because of the spaces thats good? but normally you can do this:

1. item one
1. item two

It has an advantage in that you dont need to renumber them all if you add one

2021-08-09 13:46 UTC, tmcconechy commented on src/ids-progress-chart/ids-progress-chart.js
> -        <ids-text class="label-progress">${this.progressLabel ? this.progressLabel : ''}</ids-text>
Just to make sure these changes on ids-progress-chart are intentional?

2021-08-09 13:46 UTC, tmcconechy commented on src/ids-summary-form/ids-summary-form.js
> +  IdsThemeMixin
Is theme mixin actually doing anything? or is it just getting the properties (i think ids-text handles the colors fo this so it might not be needed)

2021-08-09 17:01 UTC, vivz753 commented on src/ids-progress-chart/ids-progress-chart.js
> -        <ids-text class="label-progress">${this.progressLabel ? this.progressLabel : ''}</ids-text>
Yeah this is just to replace the ternary with null coalescing operator

2021-08-09 17:04 UTC, vivz753 commented on src/ids-mixins/README.md
> +6. Add the color changes for each theme scss file. For example:
Ohh, I see. I didn't know that! In that case I'll just leave it

2021-08-09 17:13 UTC, vivz753 commented on src/ids-summary-form/ids-summary-form.js
> +  IdsThemeMixin
Did you mean to say IdsEventsMixin? Because I'm not using any events... However, if I remove IdsThemeMixin, the component does not render at all

2021-08-09 17:15 UTC, tmcconechy commented on src/ids-summary-form/ids-summary-form.js
> +  IdsThemeMixin
No i did mean it might not need IdsThemeMixin as the ids-text elements do the themes right. What does it do when you remove? (Can ping me and chat)

But your right i assume IdsEventsMixin isnt needed either since there are no events here. I missed that, good catch

2021-08-09 17:18 UTC, vivz753 commented on app/ids-summary-form/example.html
> +  <ids-summary-form label="Synopsis of Game of Thrones pilot episode" data="
Oops, sorry! I didn't even read the second half of it. Changed.

2021-08-09 18:14 UTC, tmcconechy commented
Two more issues i found during testing

1) i dont think we need the "not bold" setting. I dont think this is something that will be used and its maybe confusing to have the option
2) i made a mistake on the original ticket this component is call SummaryField not SummaryForm

2021-08-10 14:02 UTC, tmcconechy reviewed
Looks fantastic. Only one more thing. I think the bottom section where we have a non bold text is a bit confusing we dont really need that case. So i would just cut the example off here:

Removing the bottom bit with random data and the non bold text

![Screen Shot 2021-08-10 at 10 02 20 AM](https://user-images.githubusercontent.com/814283/128880910-d606d833-f1d9-482a-a2d1-eb7cd39b74a6.png)

2021-08-10 17:17 UTC, vivz753 commented
There is no SummaryField optioin in `doc/CHECKLIST.md`, should I add it there?

2021-08-10 17:19 UTC, tmcconechy commented on app/ids-summary-field/example.html
> +  <ids-summary-field label="This is some random label" data="
```suggestion
  <ids-summary-field label="Comments" data="
```

2021-08-10 17:19 UTC, tmcconechy reviewed
Sure 👍🏻 and maybe lets label this one better 👍🏻

2021-08-11 13:48 UTC, tmcconechy submitted a review, later dismissed

2021-08-17 13:13 UTC, tmcconechy approved these changes

2021-08-17 13:21 UTC, jmacaluso711 approved these changes
Looks good 👍

2021-08-17 13:26 UTC, merged