4630 - Expandable area/Accordion
infor-design/enterprise-wc pull request #31
Opened 2021-01-06 16:48 UTC by jmacaluso711

**Explain the details for making this change. What existing problem does the pull request solve?**
Adding the Expandable Area and Accordion components. 

**Related github/jira issue (required)**:
Closes infor-design/enterprise#4630

**Steps necessary to review your pull request (required)**:
Pull and run branch and check that the components function as expected. Check focus states, mouse and keyboard events.

- http://localhost:4300/ids-accordion
- http://localhost:4300/ids-expandable-area

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [] A note to the change log.

2021-01-07 14:51 UTC, tmcconechy requested changes
Looks really great. Some small tweaks in the comments. In addition visually a couple issues.

1. http://localhost:4300/ids-expandable-area
- you could add a hyperlink component too with the correct styles?
- is the bottom divider right?

2. http://localhost:4300/ids-accordion
- the focus state is using the browser one not the same as before

2021-01-07 14:51 UTC, tmcconechy commented on app/index.js
> +import IdsAccordion from '../src/ids-accordion/ids-accordion';
Im just wondering if maybe we include IdsAccordion only and that in turn included the header and panel?

2021-01-07 14:51 UTC, tmcconechy commented on src/ids-accordion/ids-accordion-header.d.ts
> +export class IdsAccordionPanel extends HTMLElement {
Maybe just need an ids-accordion.d.ts that includes all the parts

2021-01-07 14:51 UTC, tmcconechy commented on src/ids-accordion/ids-accordion-header.js
> +@mixin(IdsEventsMixin)
I think these mixins arent used

2021-01-07 14:51 UTC, tmcconechy commented on src/ids-accordion/ids-accordion-panel.js
> +@mixin(IdsEventsMixin)
Same here

2021-01-07 14:51 UTC, tmcconechy commented on src/ids-accordion/ids-accordion-panel.js
> +  setTitles() {
Comments? Private?

2021-01-07 14:51 UTC, tmcconechy commented on src/ids-accordion/ids-accordion-panel.js
> +  /* istanbul ignore next */
Is this intentionally ignored? i'd think if you added a test that changes the expanded property in the DOM this would run.

2021-01-07 14:51 UTC, tmcconechy commented on src/ids-accordion/ids-accordion-panel.js
> +   * @private
Which of the expand/collapse ones should be the public API?

2021-01-07 14:51 UTC, tmcconechy commented on src/ids-accordion/ids-accordion.js
> +@mixin(IdsEventsMixin)
Same here?

2021-01-07 14:51 UTC, tmcconechy commented on src/ids-accordion/ids-accordion.js
> +  constructor() {
Is this needed?

2021-01-07 14:51 UTC, tmcconechy commented on test/ids-accordion/ids-accordion-e2e-test.js
> +    await percySnapshot(page, 'ids-expandable-area');
Should this be ids-accordion?

2021-01-11 22:24 UTC, jmacaluso711 commented
@tmcconechy Fixed the above issues and added keyboard support. `ArrowUp`, ArrowDown`, and `Space` should all be functioning.

2021-01-13 15:10 UTC, tmcconechy reviewed
Looks good - just a few small comments also need to correct the type checks https://github.com/infor-design/enterprise-wc/pull/31/checks?check_run_id=1695795366#step:7:47 that i had added recently. Ping me if any questions on that

2021-01-13 15:10 UTC, tmcconechy commented on app/ids-accordion/index.js
> +import IdsAccordionHeader from '../../src/ids-accordion/ids-accordion-header';
I think based on the other change you can remove the imports if they are in IdsAccordion now

2021-01-13 15:10 UTC, tmcconechy commented on src/ids-accordion/README.md
> +## Use Cases
Can we add more, just thinking we should fill in what we can on the docs and spend a bit of time so its not forgotten later? What i've been doing is  take some content from:

https://design.infor.com/product/components/accordion-menu
https://design.infor.com/code/ids-enterprise/latest/accordion

2021-01-13 15:10 UTC, tmcconechy commented on src/ids-expandable-area/README.md
> +The IDS Expandable Area component is a UI pattern that is comprised of a title, content and a toggle button or link for expanding and collapsing.
Same here - maybe just a bit more filled in

2021-01-13 15:10 UTC, tmcconechy commented on src/ids-expandable-area/ids-expandable-area.js
> +@mixin(IdsExampleMixin)
Can remove ExampleMixin and IdsEventsMixin here as IdsEventsMixin is newed up and example is just an example

2021-01-19 20:26 UTC, tmcconechy approved these changes

2021-01-21 16:55 UTC, deep7102 approved these changes
Looks good! 🍌

2021-01-21 17:39 UTC, merged