279 - tabs header variant, content/context, attribute provider iteration
infor-design/enterprise-wc pull request #319
Opened 2021-08-30 20:48 UTC by rob2d

**Explain the details for making this change. What existing problem does the pull request solve?**

(1) iteration on `ids-tabs`:
- adds `ids-tabs-context` & `ids-tabs-content` components:
`ids-tabs-context` passes `active` flag to the `ids-tabs-content` that has a matching `value` attribute in it's DOM.
- examples: add tab content, standalone CSS and some things missing on first go around.
- change `ids-tabs`/`ids-tab` to use callbacks so it would be easier to refactor later.
- added `color-variant="alternate"` for header tabs. When ids-tabs gets placed in a header this would be set automatically (but is overridable).

(2) iterate on `ids-attribute-provider-mixin`: 
  - added an optional `valueTransformer` param to set `ids-tab-content.active` based on values when updated.
  - passes `depth` option (changed to BFS vs DFS to do that)
  - iterated on the interface to just accept object entries so it's easier for mapping up from children on changes (iterative/WIP).
  - accepts`attributeProviderDefs` as an argument, since will need to create lookup maps that are shared between classes once it allows for two-way binding with child => parent (related to above).
(3) some small adjustments on `expectEnumAttributeBehavior` util since some coverage wasn't being reached.

⚠️ Ready for review on the component changes but need to add some notes on documentation so marked WIP ⚠️
 
**Related github/jira issue (required)**:

Closes #279 

**Steps necessary to review your pull request (required)**:

- pull branch and reset dev server
- visit: 
  - http://localhost:4300/ids-tabs 
  - http://localhost:4300/ids-tabs/header-tabs.html
  - http://localhost:4300/ids-tabs/standalone-css.html
- make sure functionality is alright there (standalone is just a skeleton)

**Included in this Pull Request**:
- [X] An e2e or functional test for the bug or feature.
- [ ] A note to the change log.

2021-08-31 08:59 UTC, danielortiz1982 commented on demos/ids-tabs/standalone-css.js
> +      t.addEventListener('click', () => { this.selectedIndex = i; });
This looks good, however I would recommend a small change to check for a click target and apply one event handled for just the ids-tab-container you want to work with. That will avoid creating a fn for DOM elements that are not currently being clicked on. Since this is the standalone js I think it's fine.

2021-08-31 09:00 UTC, danielortiz1982 commented on demos/ids-tabs/standalone-css.js
> +window.addEventListener('load', () => {
Same comment as above.

2021-08-31 09:10 UTC, danielortiz1982 commented on src/components/ids-tabs/ids-tabs.js
> +    this.onEvent('tabselect', this, (e) => /* istanbul ignore next */ {
Looks good, however... Same comment as above, add this to it's own #handleEvents fn.

2021-08-31 09:15 UTC, danielortiz1982 commented on src/components/ids-tabs/ids-tabs.js
> +    /* istanbul ignore next */
This seems like a good solution, I was wondering can this be done in a setter/getter instead???

2021-08-31 09:23 UTC, danielortiz1982 commented on src/components/ids-tabs/ids-tabs.js
>        this.offEvent(`click.${tabValue}`);
I am not 100% sure what this is doing, however if your working with an event I think you can do this with targets and reduce the amount of iterations being done. Again, I am not sure what your goal is here so it's just a recommendation.

2021-08-31 09:31 UTC, danielortiz1982 commented on src/mixins/ids-attribute-provider-mixin/ids-attribute-provider-mixin.js
> +      for (const element of domNodes) {
I am still a little unclear what this is doing, however I think three nested for loops is a bit excessive. Maybe we can fine a time to talk this solution over a little more.

2021-08-31 14:59 UTC, rob2d commented on src/components/ids-tabs/ids-tabs.js
> +    /* istanbul ignore next */
The mutation observer observes "childList" which looks for mutation in the DOM -- basically if a user changes the structure of the IdsTabs which they can do through appendChild/innerHTML/etc. That can't be reproduced with a getter/setter

2021-08-31 15:00 UTC, tmcconechy requested changes
A few minor doc suggestions and nits. 

- The only bigger one is the mixin readme got some extra stuff back in it
- Also for placeholder text we decided to use https://hipsum.co/ so it just placeholder and nothing to read. For the tabs could we use `type="p"` so there is more padding ect. See https://github.com/infor-design/enterprise/issues/5325 (we might want to update ids-text to show proper p type padding and line height)

In terms of functionality i see a couple things:
- click on the theme switcher then tab into the tabs on http://localhost:4300/ids-tabs/header-tabs.html its not showing the focus on the selected tabs
- use arrow left and hit space -> should select the tab but only enter is working see https://main-enterprise.demo.design.infor.com/components/tabs-header/example-index.html

2021-08-31 15:00 UTC, tmcconechy commented on demos/ids-summary-field/demo.scss
> +.tab-container {
This do anything?

2021-08-31 15:00 UTC, tmcconechy commented on demos/ids-tabs/index.yaml
> +    description: Tabs within header and content in body updating.
```suggestion
    description: Header Tabs and content in body updating.
```

Just thinking should refer to it as header tabs as thats whats known

2021-08-31 15:00 UTC, tmcconechy commented on src/components/ids-tabs/README.md
> +Using a tab context auto-updates the active `ids-tab-content`.
```suggestion
Using a tab context to show the active tab content in `ids-tab-content`.
```

More clear?

2021-08-31 15:00 UTC, tmcconechy commented on src/components/ids-tabs/README.md
> +Ids Header
Should we document the header tabs as well as the "updating content"?

2021-08-31 15:00 UTC, tmcconechy commented on src/components/ids-tabs/ids-tab-content.js
> +  set active(value) {
Some comment on this one?

2021-08-31 15:00 UTC, tmcconechy commented on src/components/ids-tabs/ids-tab.js
> +export default class IdsTab extends mix(IdsElement).with(IdsEventsMixin) {
Is  this right? Maybe should keep it at the bottom like every other component?

2021-08-31 15:00 UTC, tmcconechy commented on src/components/ids-tabs/ids-tabs-context.js
> + * IDS TabsContext Component
```suggestion
 * IDS Tabs Context Component
```

2021-08-31 15:00 UTC, tmcconechy commented on src/components/ids-tabs/ids-tabs-context.js
> + * @part container - the container of all tabs
Dont think this is being used?

2021-08-31 15:00 UTC, tmcconechy commented on src/ids-mixins/README.md
> +## Ids Keyboard Mixin
Something wrong with the merge here because now each mixin has its own README.md in the folder. 

This root readme should just be about "what are mixins"

2021-08-31 15:01 UTC, rob2d commented on src/components/ids-tabs/ids-tabs.js
>        this.offEvent(`click.${tabValue}`);
ln 314:   // clear tab values tracked

2021-08-31 15:06 UTC, rob2d commented on src/components/ids-tabs/ids-tabs.js
>        this.offEvent(`click.${tabValue}`);
So when the component mounts/unmounts, the listeners are tracked (comment is above the line where you commented). The tab events are namespaced with their value e.g. `click.value-a`. 

They need to be unsubscribed when the tabs change e.g. user edits innerHTML or appends a new tab, or the tab values change. 

Otherwise there will be memory leaks. It doesn't have to do with when the events themselves are called;  only happens on initial bind e.g. if child list is changed or component is re-rendered/connected.

2021-08-31 15:14 UTC, rob2d commented on src/components/ids-tabs/ids-tabs-context.js
> +    this.onEvent('tabselect', this, (e) => {
So on the context this is purposefully a really simple component (just there to provide values); there is no other place these are binded on the context, and offEvent cleans itself. So seems adding a method there is a little overkill since it only happens once on lifecycle and events are auto-unbinded.

There's another issue which is the naming convention `this.#handleEvents` has some issues (e.g. it gives the connotation the event handler is handling the event on the component, but actually it's binding events). That's sort of an unrelated issue but the convention is a little confusing since "event handler" interfaces give the impression that calling them is having them handled", while with that we're kinda saying "handle" the event... but its pretty ambiguous e.g. if the event is handled its firing.

2021-08-31 15:17 UTC, tmcconechy commented on src/components/ids-tabs/ids-tabs-context.js
> +    this.onEvent('tabselect', this, (e) => {
Depends how you look at it. It is binding the events but then it adds a handler for it too. So basically both half make sense. We just always used handleXXX

2021-08-31 15:18 UTC, rob2d commented on demos/ids-tabs/standalone-css.js
> +      t.addEventListener('click', () => { this.selectedIndex = i; });
Since we're binding the index, it was done that way to just grab the index that was iterated on during the click. Otherwise need to use O(N) to scan vs simple setter on-click. 

(if it was not a specific circumstance though it would be a good idea 👍)

2021-08-31 15:20 UTC, rob2d commented on src/mixins/ids-attribute-provider-mixin/ids-attribute-provider-mixin.js
> +      for (const element of domNodes) {
80/20 rule. This is just walking the DOM to find children elements; the result is the work saved on components that use it.

2021-08-31 15:28 UTC, rob2d commented on src/components/ids-tabs/ids-tab.js
> +export default class IdsTab extends mix(IdsElement).with(IdsEventsMixin) {
It's valid syntax and seemed a little more compact, but I'll change it to match the other components also.

2021-08-31 15:29 UTC, tmcconechy commented on src/components/ids-tabs/ids-tab.js
> +export default class IdsTab extends mix(IdsElement).with(IdsEventsMixin) {
Yeah keep it the same as much as possible for example as i was looking for it at the bottom when doing other things as i recall. This would trip me up.

2021-08-31 15:34 UTC, rob2d commented on src/components/ids-tabs/README.md
> +Ids Header
yeah this one was just WIP but I got a little sidetracked troubleshooting an uncaught bug on a setter in the button yesterday. Am just going to sort the minor things and then try to add a clear example before removing the WIP label here thanks

2021-08-31 15:42 UTC, rob2d commented on demos/ids-summary-field/demo.scss
> +.tab-container {
good catch this was outdated after some changes, thanks.

2021-08-31 17:40 UTC, rob2d commented on src/components/ids-tabs/ids-tabs-context.js
> +    this.onEvent('tabselect', this, (e) => {
I understand the different perspective, I was more saying it in the context of programming terminology on the web and maybe even resources in libraries we use. Some use cases of `handle` elsewhere, which make this a bit fuzzy:

- in React and several other libs `handle` is used for the action the method is taking on a callback.
- in NodeJS' `EventEmitter` (which is kind of the core to most the stuff going on in Node since it's event based), they use `handle` everywhere to describe when a callback is executed (vs binded)
![image](https://user-images.githubusercontent.com/1799905/131537797-c0f6bc36-69cb-43b0-b140-4ac35d39801a.png)
- on sites like W3 schools or MDN they use the verb "handle" to mean a callback that is being executed by a pub/sub
![image](https://user-images.githubusercontent.com/1799905/131538071-c6abbd12-4620-4c62-817d-51d9a2c16c7f.png)

There is actually even a `handleEvent` method in native JS objects here too -- this gets fired when any event is called, vs to add the event: can see an example here: https://dev.to/rikschennink/the-fantastically-magical-handleevent-function-1bp4

The term "event handler" also means the method itself just to clarify, as in the method itself that is "handle-event"ing is a "handler", not the over all component. Just as a reference: it's not something I'm inventing here, its just sort of the term for this:
https://en.wikipedia.org/wiki/Event_(computing)#Event_handler

I am ok with if we want to keep doing what we're doing at this point (though I don't think this sub needs a specific method specifically), but I guess just an fyi that it can create some fuzzy thinking to use the same word to mean different things with events in overall ecosystem of JS.

2021-08-31 17:42 UTC, tmcconechy commented on src/components/ids-tabs/ids-tabs-context.js
> +    this.onEvent('tabselect', this, (e) => {
I dont mind a different name. But for consistency in finding the event handler code i think its good to have it in specific component method. So if your just avoiding doing that because you dont like `handle` lets use something else.

2021-08-31 18:08 UTC, tmcconechy commented on src/mixins/ids-attribute-provider-mixin/ids-attribute-provider-mixin.js
> + * @property {Array} cliffTags tags where we know we won't find our
stopAtTag? or some other name?

2021-08-31 18:08 UTC, tmcconechy commented on src/mixins/ids-attribute-provider-mixin/ids-attribute-provider-mixin.js
> + * @property {Function} valueXformer transforms the value assigned
valueTransform

2021-09-01 15:23 UTC, rob2d commented on src/mixins/ids-attribute-provider-mixin/ids-attribute-provider-mixin.js
> + * @property {Array} cliffTags tags where we know we won't find our
@tmcconechy would `sentinelTags` make sense? (just from perspective of it terminating the search at those points e.g. https://en.wikipedia.org/wiki/Sentinel_value /  https://en.wikipedia.org/wiki/Sentinel_node)

2021-09-01 15:30 UTC, tmcconechy commented on src/mixins/ids-attribute-provider-mixin/ids-attribute-provider-mixin.js
> + * @property {Array} cliffTags tags where we know we won't find our
Maybe something less "fancy". I've never heard of that? Like `exitTags`,  `breakTags`( like break in a loop) or `tripTags` (sentinel value also referred to as a flag value, trip value, rogue value, signal value, or dummy data) ?

2021-09-01 15:42 UTC, deep7102 commented on src/mixins/ids-attribute-provider-mixin/ids-attribute-provider-mixin.js
> + * @property {Array} cliffTags tags where we know we won't find our
`excludeTags`, `ignoreTags`

2021-09-01 18:59 UTC, tmcconechy commented on src/mixins/ids-attribute-provider-mixin/ids-attribute-provider-mixin.js
> + * @property {Array} cliffTags tags where we know we won't find our
I like `exitTags` better.

OK, Maybe i heard of it way back or something and the concept did resonate when i read the link so i learned a new word again. But the main reason for suggesting something simpler is i think it's more likely people (developers/users) will be able to tell with the setting does being something they don't have to google to understand.

I'm only commenting on Apis and things when the names aren't as clear when there are other options or seem confusing or difficult to follow. If we get locked in to some named API that causes confusing it's hard to change it. I know this is internal but that's my general thought pattern when these come up.

2021-09-01 20:41 UTC, rob2d commented on src/mixins/ids-attribute-provider-mixin/ids-attribute-provider-mixin.js
> + * @property {Array} cliffTags tags where we know we won't find our
@tmcconechy thanks on the explanation/reasoning for that. Will do.

2021-09-03 13:22 UTC, tmcconechy commented
@rob2d to clarify is this ready to review again (still see WIP tag?)

2021-09-07 13:42 UTC, tmcconechy commented
@rob2d ready to approve when the checks pass :)

2021-09-08 13:21 UTC, tmcconechy approved these changes

2021-09-12 17:44 UTC, deep7102 approved these changes

2021-09-13 13:42 UTC, merged