304 - Ids Slider add component
infor-design/enterprise-wc pull request #326
Opened 2021-09-03 00:55 UTC by vivz753

**Explain the details for making this change. What existing problem does the pull request solve?**

**Related github/jira issue (required)**:

- Closes #304 

**Steps necessary to review your pull request (required)**:

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [ ] A note to the change log.

2021-09-03 13:43 UTC, tmcconechy reviewed
@vivz753 the PR with the new lint rules is in so you can merge it on. Did a surface pass on this as well see comments.

1. Check inline comments
2. On the example im only seeing the vertical slider. Do you have examples for the others to add?
3. When clicking the slider I see a blue area which wasnt in the design (but i dont hate it)
<img width="107" alt="Screen Shot 2021-09-03 at 9 42 25 AM" src="https://user-images.githubusercontent.com/814283/132015008-1c20a6cd-6edd-4eb3-9ec1-231f8e403829.png">
4. When i tab into it and use up/down arrow the keys appear to be reversed (up is down/ down is up)

2021-09-03 13:43 UTC, tmcconechy commented on src/components/ids-slider/README.md
> +- Minimum: The smallest value possible, on one end of the slider
```suggestion
- **Minimum**: The smallest value possible, on one end of the slider
```

For all these please bold like the other examples

2021-09-03 13:43 UTC, tmcconechy commented on src/components/ids-slider/README.md
> +## Settings (Non-attributes)
Whats the different with attributes and none attributes ?

2021-09-03 13:43 UTC, tmcconechy commented on src/components/ids-slider/README.md
> +this.labels = ['very bad, poor, average, good, excellent']; // where 'this' is the ids-slider
So there is no way to set the label in the DOM? Or is that just for the step ones because its an object/array

2021-09-03 13:43 UTC, tmcconechy commented on src/components/ids-slider/README.md
> +Holds the value(s) between a minimum and maximum, which can be controlled by the thumb(s) along the track of the slider. There is a single slider (1 thumb), double slider (2 thumbs), and a step slide
```suggestion
Displays a range of selectable values(s) between a minimum and maximum, which can be controlled by the thumb(s) along the track of the slider. There is a single slider (1 thumb), double slider (2 thumbs), and a step slider (1 thumb and x amount of ticks). They can also be converted from horizontal (default) to vertical orientation. The value(s) can be modified by either clicking the area around the track, by dragging the thumb back and forth, or by focusing and pressing the arrow keys.  A user can select a single value or range of values. 
```

2021-09-03 13:43 UTC, tmcconechy commented on src/components/ids-slider/README.md
> +- Control an input with limited options through clicking/dragging/keyboard interaction
```suggestion
- Control an input with limited options through clicking/dragging/keyboard interaction.
- . Best for showing a user’s current selection relative to the lower and upper limits of a scale.
```

2021-09-03 13:43 UTC, tmcconechy commented on src/components/ids-slider/ids-slider.d.ts
> +  /** Sets the color theme of the chart */
```suggestion
  /** Sets the color of the slider bar */
```

2021-09-03 13:43 UTC, tmcconechy commented on src/components/ids-slider/ids-slider.js
> +  slider;
These are all fine. But what i have been doing is not declaring them and just doing this to declare them. Not sure if this is better but a minor point to consider.

```
this.slider = this.container.querySelector('.slider');
```

2021-09-03 13:43 UTC, tmcconechy commented on src/components/ids-slider/ids-slider.js
> +  get isRtl() {
```suggestion
  get isRTL() {
```

2021-09-03 13:43 UTC, tmcconechy commented on src/components/ids-slider/ids-slider.js
> +      this.isRtl = isRtl;
Maybe make it all RTL like the locale api. Is there any need to have this.isRTL when there is this.locale.isRTL?

2021-09-03 13:43 UTC, tmcconechy commented on src/components/ids-slider/ids-slider.js
> +    this.#addKeyboardEvents();
```suggestion
    this.#addKeyboarListeners();
```

Did this on the other PR... for a name

2021-09-03 13:43 UTC, tmcconechy commented on src/components/ids-slider/ids-slider.js
> +    // console.log('this.trackArea.clientHeight: ' + this.trackArea.clientHeight) // 24
Remove these comments?

2021-09-03 16:22 UTC, vivz753 commented on src/components/ids-slider/README.md
> +## Settings (Non-attributes)
this if for this.labels

it's technically not an attribute because we don't want arrays being passed through HTML as strings... so they would have to set it using javascript, hence "non-attribute"

2021-09-03 16:23 UTC, vivz753 commented on src/components/ids-slider/README.md
> +this.labels = ['very bad, poor, average, good, excellent']; // where 'this' is the ids-slider
Yeah this is for the step slider... currently the default labels are the min and max value

2021-09-03 16:23 UTC, tmcconechy commented on src/components/ids-slider/README.md
> +## Settings (Non-attributes)
ok thats what i guessed. Thanks

2021-09-03 16:24 UTC, vivz753 commented on src/components/ids-slider/ids-slider.js
> +  slider;
That's what I was doing initially, but Robert suggested initializing them in the class just for better readability to know what variables can be used

2021-09-03 16:25 UTC, vivz753 commented on src/components/ids-slider/ids-slider.js
> +    this.#addKeyboardEvents();
I'll commit it on my end since it's not spelled correctly here

2021-09-03 16:27 UTC, tmcconechy commented on src/components/ids-slider/ids-slider.js
> +  slider;
ok i guess not a bad idea but then they maybe should have comments.

2021-09-03 16:27 UTC, vivz753 commented on src/components/ids-slider/ids-slider.js
> +    // console.log('this.trackArea.clientHeight: ' + this.trackArea.clientHeight) // 24
> @vivz753 the PR with the new lint rules is in so you can merge it on. Did a surface pass on this as well see comments.
> 
> 1. Check inline comments
> 2. On the example im only seeing the vertical slider. Do you have examples for the others to add?
> 3. When clicking the slider I see a blue area which wasnt in the design (but i dont hate it)
> 
> <img alt="Screen Shot 2021-09-03 at 9 42 25 AM" width="107" src="https://user-images.githubusercontent.com/814283/132015008-1c20a6cd-6edd-4eb3-9ec1-231f8e403829.png">
> 
> 4. When i tab into it and use up/down arrow the keys appear to be reversed (up is down/ down is up)

1. What do you mean check inline comments? 
2. Updating the examples with the other sliders now
3. The blue area hover was just to help me develop, I can remove it
4. The reason why up/down is like that is because I have plans to reverse the min/max to be bottom/top (right now it's min/max top/bottom)

2021-09-03 16:30 UTC, tmcconechy commented on src/components/ids-slider/ids-slider.js
> +    // console.log('this.trackArea.clientHeight: ' + this.trackArea.clientHeight) // 24
1. I mean look at the comments i put on the code inline (you did)
2. cool
3. sure or can make it a setting
4. ok cool as long as its the right way in the end... (up goes up and down goes down / left decreased / right increases)

2021-09-03 16:32 UTC, vivz753 commented on src/components/ids-slider/ids-slider.js
> +      this.isRtl = isRtl;
I've changed `isRtl` to `isRTL` ... I suppose I could technically perform all the updates in the event listener for language change, but it's nice to keep it encapsulated and refer to isRTL in my own class.. I'm not exactly sure what you mean, but I'm open to suggestions if you can provide examples

2021-09-03 16:33 UTC, vivz753 commented on src/components/ids-slider/ids-slider.js
> +    this.#addKeyboardEvents();
Should this be `attachKeyboardListeners()` instead of `add`?

2021-09-03 16:36 UTC, vivz753 commented on src/components/ids-slider/README.md
> +- Minimum: The smallest value possible, on one end of the slider
Done

2021-09-03 16:37 UTC, vivz753 commented on src/components/ids-slider/README.md
> +- Control an input with limited options through clicking/dragging/keyboard interaction
Done

2021-09-03 16:37 UTC, vivz753 commented on src/components/ids-slider/ids-slider.js
> +  get isRtl() {
Done

2021-09-03 16:42 UTC, tmcconechy commented on src/components/ids-slider/ids-slider.js
> +    this.#addKeyboardEvents();
Yes my bad as per https://github.com/infor-design/enterprise-wc/pull/321#issue-723790999 

attachEventHandlers and attachKeyboardListeners

2021-09-03 16:44 UTC, tmcconechy commented on src/components/ids-slider/ids-slider.js
> +      this.isRtl = isRtl;
I mean if you need to check for isRTL anywhere in the code you could use 

```
if (this.locale.isRTL())
```

So `this.isRTL` may be redundant?

2021-09-03 22:02 UTC, vivz753 commented on src/components/ids-slider/ids-slider.js
> +    // console.log('this.trackArea.clientHeight: ' + this.trackArea.clientHeight) // 24
Finished making changes, pretty much all ready to go--it took a bit longer than expected bc I discovered some bugs where calculating the x/y screwed up when scrolling away from the initial window position.

2021-09-03 22:12 UTC, vivz753 commented on src/components/ids-slider/ids-slider.js
> +      this.isRtl = isRtl;
I have events that I need to trigger when RTL gets changed so in my set isRTL() I recalculate the boundaries of the component, update the position of thumbs and progress bar.. I think it's simpler for me to keep that encapsulated there... 

I think I can get rid of the `await this.setLanguage(e.detail.language.name)` though

2021-09-03 22:22 UTC, vivz753 commented on demos/ids-slider/example.js
> +  document.querySelector('.survey').labels = ['very bad', 'poor', 'average', 'good', 'excellent'];
I need help getting this to work.. this file isn't linking up to my `example.html` for some reason

How does this example.js file link to the html in the other component demos? @tmcconechy

2021-09-07 13:47 UTC, tmcconechy commented on src/components/ids-slider/ids-slider.js
> +      this.isRtl = isRtl;
That implementation is part of the local mixin. Once its mixed on you get the locale functions.
You don't have to pass the language in. If you don't it will take the correct language.

2021-09-07 13:50 UTC, tmcconechy commented on demos/ids-slider/example.js
> +  document.querySelector('.survey').labels = ['very bad', 'poor', 'average', 'good', 'excellent'];
@vivz753 I think the example.js is linked. Its firing...for me. Maybe restart the demo app?

```
document.addEventListener('DOMContentLoaded', () => {
  alert('DOMContentLoaded');
  document.querySelector('.survey').labels = ['very bad', 'poor', 'average', 'good', 'excellent'];
});
alert('in the js');
```

2021-09-07 13:52 UTC, tmcconechy commented
@vivz753 a couple more things since now i see the examples more

1. If i do left and right arrow on the horizontal splitters it scrolls the whole page
2. the numbers on step slider doesn't quite line up
3. should also be able to click the numbers like https://main-enterprise.demo.design.infor.com/components/slider/example-index.html
4. should make the "pointer" cursor show on the bar/ticks and slider

That being said I am impressed with the work on this PR.

2021-09-07 14:20 UTC, EdwardCoyle reviewed
@vivz753 This looks great!  Willing to approve after addressing Tim's comments, along with this:

- On the 4.x Range (double) Slider, the tooltip is only supposed to appear on the "active" thumb.  I don't really dislike seeing both values when manipulating the slider, but wondering if we should either put it behind a setting or limit the tooltip to just the "active" thumb for the sake of matching the current functionality.

2021-09-07 14:20 UTC, EdwardCoyle commented on demos/ids-slider/example.js
> +  document.querySelector('.survey').labels = ['very bad', 'poor', 'average', 'good', 'excellent'];
@vivz753 I was able to set a breakpoint on this line and see it trigger.  Could just need to restart 👍

2021-09-07 14:34 UTC, jmacaluso711 requested changes
@vivz753 I left a few minor comments related to your .scss file. Also looks like there are a few js lint errors you need to address. A bunch are related to ternary and line length, but there are some that are unrelated, like spacing issues.

2021-09-07 14:34 UTC, jmacaluso711 commented on src/components/ids-slider/ids-slider.scss
> +      background-color: #0072ED;
Should probably use our token here `--ids-color-palette-azure-90`

2021-09-07 14:34 UTC, jmacaluso711 commented on src/components/ids-slider/ids-slider.scss
> +      background-color: #004A99;
Same as above as well as on lines 205 and 209

2021-09-07 14:34 UTC, jmacaluso711 commented on src/components/ids-slider/ids-slider.scss
> +
One general comment for this file: Nested styles should have 1 line space above and 1 below (if not the last declaration in the block). Not sure why the linter didn't catch it. For example lines 9-10

2021-09-07 17:03 UTC, vivz753 commented
> @vivz753 a couple more things since now i see the examples more
> 
>     1. If i do left and right arrow on the horizontal splitters it scrolls the whole page
> 
>     2. the numbers on step slider doesn't quite line up
> 
>     3. should also be able to click the numbers like https://main-enterprise.demo.design.infor.com/components/slider/example-index.html
> 
>     4. should make the "pointer" cursor show on the bar/ticks and slider
> 
> 
> That being said I am impressed with the work on this PR.

Thank you for the compliment!!

1. added e.preventDefault() to stop scrolling when pressing arrow keys
2. added justify-content:center to center labels for non-RTL and RTL
3. added functionality to click labels to update value
4. added cursor pointer css on track area and labels

2021-09-07 17:06 UTC, vivz753 commented on src/components/ids-slider/ids-slider.scss
> +      background-color: #0072ED;
this is actually `--ids-color-palette-asure-60` and `--ids-color-brand-primary-base`

going with the `ids-color-brand-primary-base`

2021-09-07 17:09 UTC, vivz753 commented on src/components/ids-slider/ids-slider.scss
> +      background-color: #004A99;
Done

2021-09-07 17:09 UTC, vivz753 commented on demos/ids-slider/example.js
> +  document.querySelector('.survey').labels = ['very bad', 'poor', 'average', 'good', 'excellent'];
Thanks, that worked

2021-09-07 18:47 UTC, vivz753 commented
> @vivz753 This looks great! Willing to approve after addressing Tim's comments, along with this:
> 
>     * On the 4.x Range (double) Slider, the tooltip is only supposed to appear on the "active" thumb.  I don't really dislike seeing both values when manipulating the slider, but wondering if we should either put it behind a setting or limit the tooltip to just the "active" thumb for the sake of matching the current functionality.

Yeah I noticed that but still intentionally added the visibility for both. It made more sense imo to show both--why should a user have to constantly click back and forth just to see/check both values? That's 2 actions and then them having to remember the previous value to make sure they entered precisely the correct numbers. Doesn't seem like a good design to me... but I acknowledge that may have been on purpose for whatever reason.

Thank you for reviewing @EdwardCoyle

2021-09-08 13:25 UTC, tmcconechy commented on demos/ids-slider/example.html
> +    <ids-text font-size="12" type="h1">Double Slider: </ids-text>
I think we should call "double" "range" so lets refer to the two handle slider as a range slider as before https://main-enterprise.demo.design.infor.com/components/slider/example-range.html

2021-09-08 13:26 UTC, tmcconechy commented on src/components/ids-slider/TODO.md
> +  - [-] bugs
It might make sense too just have the points that are left open so there isnt so much in here as a TODO thats already done

2021-09-08 13:27 UTC, tmcconechy commented on src/components/ids-slider/ids-slider.scss
> +      bottom: -6px; // horizontal
Maybe all these //horiz comments can be formed into more complete comments

2021-09-08 13:34 UTC, tmcconechy commented on src/components/ids-slider/ids-slider.js
> +    this.setAttribute(attributes.COLOR, value);
I noticed this means you can pass in "green" but we want to stick to (or at last support our color pallete variables) i tihnk do the color setter like ids-text https://github.com/infor-design/enterprise-wc/blob/main/src/components/ids-text/ids-text.js#L216-L234

Then update the example to `ruby-60` `emerald-60` ect

2021-09-09 13:53 UTC, tmcconechy approved these changes

2021-09-14 16:17 UTC, deep7102 approved these changes
Looks very nice, Thanks! @vivz753

2021-09-14 16:41 UTC, merged