4727 - Add Ids Alert wc
infor-design/enterprise-wc pull request #37
Opened 2021-01-28 13:03 UTC by ericangeles

**Explain the details for making this change. What existing problem does the pull request solve?**

Implements IDS Alert for the web components. The Ids Alert component acts a wrapper that can be use for different alert messages. It has 3 properties that can be use, `type`, `icon` and `size`.

**Related github/jira issue (required)**:

Closes https://github.com/infor-design/enterprise/issues/4727

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4300/ids-alert
- Check the codes and review the codes

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [ ] A note to the change log.

2021-01-28 14:31 UTC, tmcconechy requested changes
Try to use <ids-icon instead> so we dont need to the big import twice. Also try and do 100% coverage when done with that change.

Otherwise looks good 👍🏻 

Thanks

2021-01-28 14:31 UTC, tmcconechy commented on src/ids-alert/ids-alert.d.ts
> +  type: 'error' | 'warning' | 'success' | 'info';
I think there is a few more types?

2021-01-28 14:31 UTC, tmcconechy commented on app/ids-alert/example.html
> +    <ids-alert type="alert" icon="alert" size="normal"></ids-alert>
Im thinking we dont need both a type and an icon. So maybe just type.

2021-01-28 14:31 UTC, tmcconechy commented on src/ids-alert/ids-alert.js
> +import pathData from 'ids-identity/dist/theme-uplift/icons/standard/path-data.json';
This file is very big so i think what we should do is just use the <ids-icon> instead of this. So try not to import this and use <ids-icon> in the template.

2021-01-28 14:31 UTC, tmcconechy commented on src/ids-alert/ids-alert.js
> +    return `<svg xmlns="http://www.w3.org/2000/svg" stroke="currentColor"
This is redundant as mentioned. I think we should use <ids-icon> in here directly instead of duplicating its code.
If any problem setting the alert color we can make a color setting on the ids-icon (if not already there)?

This should reduce code

2021-01-28 17:42 UTC, tmcconechy commented on app/ids-alert/example.html
> +    <ids-alert type="success-solid"></ids-alert>
Rethinking this setting name... If it is one to one with the icons in <ids-icon> maybe we should call the setting `icon` so its consistent

2021-01-29 16:41 UTC, tmcconechy commented
@ericangeles 

1. dont worry about the lcov error its fixed on the other PR
2. but the only thing left is please try and make the coverage 100%

```
_ids-alert | 80 | 50 | 83.33 | 80 |  
-- | -- | -- | -- | -- | --
_ ids-alert.js | 80 | 50 | 83.33 | 80 | 54-57
```

By adding more tests see coverage/index.html for details

2021-01-29 19:27 UTC, tmcconechy commented on src/ids-icon/ids-icon.scss
> +@import '../ids-alert/ids-alert.scss';
I think this isnt needed and perhaps whats causing the UI changes here https://percy.io/00aaa841/enterprise-wc/builds/8609550/changed/489246062?browser=chrome&browser_ids=9&subcategories=unreviewed%2Cchanges_requested&viewLayout=overlay&viewMode=new&width=1280&widths=375%2C1280

2021-01-29 19:28 UTC, tmcconechy commented on src/ids-alert/ids-alert.scss
> +svg {
```suggestion
svg {
```

Probably better to do this on a class you add like ids-alert?

2021-01-29 19:38 UTC, ericangeles commented on src/ids-alert/ids-alert.scss
> +svg {
For some reason, it doesn't change the stylings unless I import it in the `ids-icon.scss`.

2021-01-29 20:01 UTC, tmcconechy commented on src/ids-alert/ids-alert.scss
> +svg {
I can have a look maybe. what are you trying to change with it?

2021-01-29 20:13 UTC, ericangeles commented on src/ids-alert/ids-alert.scss
> +svg {
@tmcconechy sure, you can take a look.

2021-02-01 12:51 UTC, ericangeles commented on src/ids-alert/ids-alert.scss
> +svg {
@tmcconechy i think i found the solution for this. Will push some updates later.

2021-02-01 14:03 UTC, tmcconechy commented on src/ids-alert/ids-alert.scss
> +  @include mr-20();
```suggestion
  @include mr-8();
```

Would less padding work ok? Because 1. We want to work in 4s now (2, 4, 8, 16) and i think 20 seems like a lot and is something we would probably have to negate somehow when using the alerts later.

2021-02-01 14:04 UTC, tmcconechy submitted a review, later dismissed
Looks good - just thinking maybe reduce the internal margins? I assume thats just to seperate them in the example?

Ideally it doesnt have any margin/padding at all in it and thats done outside?

2021-02-01 14:05 UTC, ericangeles commented
> Looks good - just thinking maybe reduce the internal margins? I assume thats just to seperate them in the example?
> 
> Ideally it doesnt have any margin/padding at all in it and thats done outside?

Sure, Tim. Give me a sec.

2021-02-01 14:07 UTC, tmcconechy commented
Maybe it would work if you use the way the icon page is built with the layout grid doing the separation instead of the internal margin?

2021-02-01 14:44 UTC, tmcconechy approved these changes

2021-02-01 15:24 UTC, EdwardCoyle approved these changes

2021-02-01 15:25 UTC, merged