296 ids icon size type updates
infor-design/enterprise-wc pull request #424
Opened 2021-11-12 15:51 UTC by Jah25

**Explain the details for making this change. What existing problem does the pull request solve?**

added new sizing options for ids-icon including custom height, width and viewbox options. Additionally includes support for empty-message icons in ids-icon

**Related github/jira issue (required)**:

closes [#296](https://github.com/infor-design/enterprise-wc/issues/296)

**Steps necessary to review your pull request (required)**:

-run the application locally
- navigate to http://localhost:4300/ids-icon/
- new icons should be visible at the bottom of the example page in larger size
- all tests should pass

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2021-11-12 16:24 UTC, Jah25 commented
missed an update to the typescript file, updating shortly

2021-11-15 15:19 UTC, tmcconechy commented
@Jah25 looks like the percy tests uncovered a couple of things. Most notable is the changed logo size on ids-about.
Can you take a look at those and see what you think?

Also if not up to date with main i would merge it on as seeing the splitter changes and doing that might fix those.

2021-11-15 18:02 UTC, vivz753 commented on src/components/ids-icon/README.md
> +Icons come in 6 ssizes depending where it is used.
```suggestion
Icons come in 6 sizes depending where it is used.
```

2021-11-15 18:03 UTC, vivz753 commented on src/components/ids-icon/README.md
> +<ids-icon icon="notes" size="xlarge"></ids-icon>
```suggestion
<ids-icon icon="notes" size="3xl"></ids-icon>
<ids-icon icon="notes" size="xl"></ids-icon>
```

Consider using shorter names

2021-11-15 18:05 UTC, vivz753 commented on src/components/ids-icon/README.md
> +<ids-icon icon="notes" size="xlarge"></ids-icon>
```suggestion
<ids-icon icon="notes" size="3xl"></ids-icon>
<ids-icon icon="notes" size="xl"></ids-icon>
```
Consider using shorter names

2021-11-15 18:06 UTC, vivz753 commented on src/components/ids-icon/README.md
> +The most common implimentation of custom sizing is for empty-message icons, which are available through ids-icon
```suggestion
The most common implementation of custom sizing is for empty-message icons, which are available through ids-icon
```

2021-11-15 18:07 UTC, vivz753 commented on src/components/ids-icon/ids-icon.d.ts
> +   size: 'normal' | 'small' | 'medium' | 'large' | 'xlarge' | 'largex3';
Change the size names here if you do decide to go with the shorter names

2021-11-15 18:08 UTC, vivz753 commented on src/core/ids-attributes.js
> +  CUSTOM_WIDTH: 'custom-width',
Was there a reason to use these over the existing `HEIGHT` `WIDTH`, and just add a `VIEWBOX` to ids-attributes.js?

2021-11-15 18:12 UTC, vivz753 submitted a review, later dismissed

2021-11-15 18:21 UTC, Jah25 commented on src/core/ids-attributes.js
> +  CUSTOM_WIDTH: 'custom-width',
mostly for specificity, since these are overrides for the existing sizing behavior but if you think it makes sense to use the existing names I'm not married to the custom name.

2021-11-15 18:56 UTC, tmcconechy commented on src/core/ids-attributes.js
> +  CUSTOM_WIDTH: 'custom-width',
I think i agree with @vivz753 maybe we just use height, viewbox, width instead of adding the word custom. Just because it works like regular css/properties ect?

2021-11-15 19:33 UTC, Jah25 commented on src/core/ids-attributes.js
> +  CUSTOM_WIDTH: 'custom-width',
no problem, I'll make sure it gets updated.

2021-11-16 14:09 UTC, tmcconechy commented on src/components/ids-icon/ids-icon.js
>    xl: 34,
yeah either that or just `xxl/xxxl` is maybe more consistent with the others

2021-11-16 18:51 UTC, Jah25 commented on src/components/ids-icon/ids-icon.js
>    xl: 34,
3xl wound up being an issue because it caused testing errors. I could update it to something like `x3l` or go with the `xxxl`

2021-11-16 19:05 UTC, tmcconechy commented on src/components/ids-icon/ids-icon.js
>    xl: 34,
As discussed might as well use`xxl` (since we dont have a double xxl anyways)

2021-11-16 23:21 UTC, vivz753 commented on src/components/ids-icon/README.md
> +- Custom-Width
Did you mean to remove the word Custom here as well?

2021-11-16 23:22 UTC, vivz753 approved these changes
Everything looks good to me.

2021-11-17 14:26 UTC, tmcconechy requested changes
I think we just need to change xl3 to xxl

2021-11-17 15:03 UTC, Jah25 commented on src/components/ids-icon/README.md
> +- Custom-Width
yup, missed it in the purge

2021-11-18 14:38 UTC, tmcconechy approved these changes

2021-11-18 18:10 UTC, tmcconechy submitted a review, later dismissed

2021-11-19 10:27 UTC, andriivarhanov commented on src/components/ids-icon/ids-icon.js
> +    } else if (this.icon === 'logo' || this.icon === 'logo-trademark') {
I think we can remove this condition since it was added as a temporary fix and now icon has `viewport` setting. Once removed `viewbox="0 0 35 34"` should be added to icon="logo" and icon="logo-trademark"

2021-11-29 17:29 UTC, tmcconechy commented
Minor linting issue https://github.com/infor-design/enterprise-wc/runs/4356677383?check_suite_focus=true#step:8:9

2021-11-29 17:30 UTC, tmcconechy approved these changes

2021-11-29 17:31 UTC, andriivarhanov submitted a review, later dismissed

2021-11-29 18:18 UTC, Jah25 commented on src/components/ids-icon/ids-icon.js
> +    } else if (this.icon === 'logo' || this.icon === 'logo-trademark') {
checked in that change

2021-11-29 18:28 UTC, Jah25 commented
> Minor linting issue https://github.com/infor-design/enterprise-wc/runs/4356677383?check_suite_focus=true#step:8:9

just cleaned it up weirdly it wasn't detecting it in my local.

2021-11-29 19:36 UTC, tmcconechy commented
ok cool @Jah25 maybe try 
```
rm -rf node_modules
npm i
```

As some rules had been updated somewhat recently (for next time)

2021-11-29 20:06 UTC, tmcconechy submitted a review, later dismissed

2021-11-29 20:13 UTC, vivz753 commented on src/components/ids-icon/ids-icon.js
> +      width = this.getAttribute(attributes.WIDTH);
Why not just use `this.height` and `this.width`? The getters do the same exact thing

2021-11-29 20:14 UTC, vivz753 commented on src/components/ids-icon/ids-icon.js
> +    }
Can return these as default values in the getters for height/width too, to minimize code in template()

2021-11-29 20:16 UTC, vivz753 approved these changes

2021-11-30 15:08 UTC, tmcconechy commented
@Jah25 just two more comments from @vivz753 to address/discuss

2021-12-01 16:05 UTC, tmcconechy approved these changes

2021-12-01 16:39 UTC, andriivarhanov approved these changes

2021-12-01 17:45 UTC, merged