384 label attr issue
infor-design/enterprise-wc pull request #431
Opened 2021-11-18 02:44 UTC by jeffwa428

**Explain the details for making this change. What existing problem does the pull request solve?**

- Removed `.color-input-value-no-label` class in order to get rid of padding when there is no label.
- Added LABEL_AUDIBLE option to ids-checkbox
- Added new section for ids-checkbox with no label
- Updated `.audible` for `label-checkbox`

**Related github/jira issue (required)**:

Closes https://github.com/infor-design/enterprise-wc/issues/384

**Steps necessary to review your pull request (required)**:

- Go to demos/ids-color-picker/example.html and remove label attributes
- Go to http://localhost:4300/ids-color-picker and check if color picker ui should be displayed correctly without label

- Go to demos/ids-checkbox/example.html and add `label-audible` attribute with `true/false`
- Go to http://localhost:4300/ids-checkbox and check if checkbox should be displayed correctly without label

2021-11-18 14:46 UTC, tmcconechy requested changes
This is a great first PR! The only problem i see is pretty small.

![Screen Shot 2021-11-18 at 9 44 05 AM](https://user-images.githubusercontent.com/814283/142437430-60b43f6e-0c5e-44eb-986d-d2a05873a5d0.png)

When no label it seems like the padding below the field is less than when there is one with a field. We should try and make that equal?

2021-11-18 15:58 UTC, tmcconechy approved these changes

2021-11-18 18:01 UTC, tmcconechy commented
@jeffwa428 looks like a few tests to fix https://github.com/infor-design/enterprise-wc/runs/4253677698?check_suite_focus=true#step:9:246

`npx jest -- checkbox`

2021-11-19 14:26 UTC, andriivarhanov reviewed
looks good, couple of things:
- please add label audible to the readme with short description on what it does
- add label audible to typescript file `ids-checkbox.d.ts`
- add some e2e or func tests for label audible attribute and property

2021-11-19 14:26 UTC, andriivarhanov commented on src/components/ids-checkbox/ids-checkbox.js
> +
please add `set` for `labelAudible` property

2021-11-19 14:53 UTC, tmcconechy requested changes
Requesting changes. See @andriivarhanov comments please
Also please try to fix the tests https://github.com/infor-design/enterprise-wc/runs/4256625935?check_suite_focus=true#step:9:243 and check the coverage.

2021-11-24 14:49 UTC, EdwardCoyle commented
@jeffwa428 This looks really nice now!  I just approved the percy tests as everything seems to be in order.  Could you address the outstanding comment(s?) from @andriivarhanov?  Then we can merge this 👍

2021-11-24 19:09 UTC, jeffwa428 commented
Okay, I almost finished that. I will push new update soon.

2021-11-29 15:25 UTC, jeffwa428 commented
@tmcconechy , @andriivarhanov @EdwardCoyle 
I have made changes requested and pushed. Kindly check it and let me know if there is any issue.

2021-11-29 15:37 UTC, andriivarhanov commented on src/components/ids-checkbox/ids-checkbox.js
> +    if (value === 'true' || value === true) {
please use `IdsStringUtils.stringToBool` util here

2021-11-29 15:51 UTC, andriivarhanov approved these changes

2021-11-29 17:46 UTC, tmcconechy approved these changes

2021-11-29 19:37 UTC, merged