151 - Added IdsTimePicker component
infor-design/enterprise-wc pull request #432
Opened 2021-11-18 14:31 UTC by clayinfor

**Explain the details for making this change. What existing problem does the pull request solve?**

Adds the IdsTimePicker web component: `<ids-time-picker></ids-time-picker>`

**Related github/jira issue (required)**:

@see https://github.com/infor-design/enterprise-wc/issues/151

**Steps necessary to review your pull request (required)**:

1. Checkout this branch: `151-time-picker-component`
2. Run: `nvm use`
3. Run: `npx yarn install`
4. Run: `npx yarn test time-picker-func`
4. Run: `npx yarn start:watch`
5. Go to and test: `http://localhost:4300/ids-time-picker/`

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [ ] A note to the change log.

2021-11-18 15:05 UTC, tmcconechy requested changes
This looks overall really excellent just a couple things im thinking about ....

1. On the dialog the space between the fields looks uneven and there is a bigger gap on the right side. 
![Screen Shot 2021-11-18 at 9 49 53 AM](https://user-images.githubusercontent.com/814283/142440186-daac71aa-44d0-405b-abdb-03aa8a68db25.png)

Should look more like this https://main-enterprise.demo.design.infor.com/components/timepicker/example-index.html

2. Is the keyboard behavior in scope for this issue? As if i try down arrow to open it doesnt focus the dialog and i cant use the keyboard to select. Can also try keyboard to see the behavior on https://main-enterprise.demo.design.infor.com/components/timepicker/example-index.html

3. For organization could we take the `locale` and `language` off so we can set it on the ids-container and see that it updates the format by default? I.E. should take the current locale by default in addition to "hard coding" one but i cant seem to test that on the examples. Could show them all using the set locale and one with a hard coded locale (with a label).

The test failure may be temporary. i synced with main as well with the button so we will see if that fixes anything....

2021-11-18 15:29 UTC, tmcconechy reviewed
I was also wondering about the `timepicker` vs `time-picker` but i can see there is a `color-picker` so thats a good call.

2021-11-19 15:01 UTC, tmcconechy commented
Checked through again and see its not all done but I found one more when at a smaller breakpoint the dropdowns would look nicer centered:

![Screen Shot 2021-11-19 at 10 00 42 AM](https://user-images.githubusercontent.com/814283/142643958-e86c331c-0895-4324-887e-3099b3211422.png)

2021-11-20 00:29 UTC, vivz753 commented on src/components/ids-time-picker/ids-time-picker.js
> +  }
Nice and clean. I like it. Didn't even need to use the stringToBool()

2021-11-20 00:32 UTC, vivz753 commented on src/components/ids-time-picker/ids-time-picker.js
> +    const disabled = value ?? (value !== 'false' && value !== false);
Could probably use the stringToBool() function here, if I'm reading your logic correctly.. You're just checking for the presence of the attribute, and returning true so long as it's not `'false'` or `false`, correct?

2021-11-20 00:36 UTC, vivz753 commented on src/components/ids-time-picker/ids-time-picker.js
> +    this.setAttribute(attributes.DISABLED, disabled);
Do values have to be casted to strings before setting the attributes? 

Nvm, they don't have to be, [source](https://developer.mozilla.org/en-US/docs/Web/API/Element/setAttribute#example)
```
value
A DOMString containing the value to assign to the attribute. Any non-string value specified is converted automatically into a string.
```

I ask this because I've seen `value.toString()` passed in for setAttribute in some components

2021-11-20 00:44 UTC, vivz753 commented on src/components/ids-time-picker/ids-time-picker.js
> +    const disabled = value ?? (value !== 'false' && value !== false);
This probably wouldn't ever happen.. but if `undefined` is passed to this function, it would return `true`

2021-11-20 00:47 UTC, vivz753 commented on src/components/ids-time-picker/ids-time-picker.js
> +    const readonly = value ?? (value !== 'false' && value !== false);
Same for here. You sure you don't want to use the `stringToBool`? Maybe the function name should be changed to `castToBool` instead, since it technically checks bool types too. Then it wouldn't be misleading to use here

2021-11-20 00:53 UTC, vivz753 commented on src/components/ids-trigger-field/ids-trigger-field.js
> +          ${attrs.disabled}
Nice refactoring

2021-11-20 00:55 UTC, vivz753 commented on src/components/ids-trigger-field/ids-trigger-field.js
> +    this.setAttribute(attributes.TABBABLE, !!value);
Not a fan of the stringToBool()? 

There's an issue here, though
`this.tabbable = 'false'` would set the attribute to `true`

2021-11-22 21:35 UTC, jmacaluso711 commented on src/components/ids-time-picker/ids-time-picker.js
> +  get hasSeconds() { return this.format.toLowerCase().includes('ss'); }
Do we need jsdocs comments for these getters/setters?

2021-11-23 18:48 UTC, clayinfor commented on src/components/ids-time-picker/ids-time-picker.js
> +    this.elements = {
Adding `this.elements` was helpful because it provided a single-point of reference for adding mouse and keyboard event handlers, and for working with these elements in testing.  It also allowed me to target and affect elements within other components, such as the label inside of the `IdsTriggerField` component.  

Also bagging them within `this.elements`, instead of having a getter for each one reduced class-method pollution.

The only catch is, I needed to call `super()` to get `IdsElement` to render `template()` before `querySelector()` would actually return any of the elements.  One work around to this would be to `this.elements` without the `connectedCallback()` method, but, in opinion, the `constructor()` is the most-appropriate place to have this kind of class-variable defining/initialization.

2021-11-23 18:49 UTC, clayinfor commented on src/components/ids-time-picker/ids-time-picker.d.ts
> +  format?: string | 'hh:mm:ss a';
Here, I'm making the attribute's default-value ('hh:mm:ss a') explicit.

2021-11-23 18:55 UTC, clayinfor commented on src/components/ids-time-picker/ids-time-picker.js
> +  }
Overriding `getAttributes()` here gives this element a chance to dictate how it behaves rather than being dictated to from the top-down via inherited-behavior…

As Vivian mentioned, this could be a good place to centralize doing things with `stringToBool()` and other helper/utility functions.  I also considered overriding `setAttributes()`, and removing attributes such as `disabled` whenever it was set to false, but Daniel’s comment about Angular made me rethink this approach.

2021-11-23 18:59 UTC, clayinfor commented on src/components/ids-time-picker/ids-time-picker.js
> +    const hours = this.dropdown({ id: 'hours', label: 'Hours', options: options.hours });
This is where I started to use to [tagged-functions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#tagged_templates), but I decided to revert to a regular function, because I couldn't help but feel I was trying to shoehorn tagged functions into this code as pattern.  The main take away I wanted from tagged-functions was to have my IDE/code-editor help me to parse the HTML, but I wasn't getting that with the taggd-functions approach, so I used a regular, which was still helpful in building the final string template-literal for dropdowns.

2021-11-23 19:10 UTC, clayinfor commented on src/components/ids-trigger-field/ids-trigger-field.js
> +    const attrs = {
This pattern could make it easier to add attributes to template literals. 

The class attribute could be handled as follows:
```javascript
const classes = [ attrs.disabled, attrs.readonly, attrs.required ].join('');
```

```javascript
const template = `<article class="${classes}">Article text</article>`;
```

2021-11-23 19:58 UTC, clayinfor commented on src/components/ids-time-picker/ids-time-picker.scss
> +  @include ml-16();
replace this with `margin-inline-start` attribute

2021-11-23 19:58 UTC, clayinfor commented on src/components/ids-time-picker/ids-time-picker.scss
> +      content: ':';
for localization, we will need to have this in the template (i.e. `<span>:</span>`

2021-11-24 15:40 UTC, EdwardCoyle commented on src/components/ids-time-picker/ids-time-picker.js
> +    this.elements = {
I like this for when there are many references to internal elements.  In a lot of places, we use readonly getters for these references, which changes the behavior a bit (on-demand reference as opposed to one that's cached).  This can be good if the ref isn't needed often, but if it is used often, maybe better to do it this way.

It's also true that when you have many of those readonly getters, readability decreases quite a bit.  If we agreed to standardize against a single object ref for storing those, I wouldn't be opposed.

2021-11-24 15:48 UTC, EdwardCoyle commented on src/components/ids-time-picker/ids-time-picker.js
> +  }
I like the idea of setting up attributes to automatically respond to their assigned types so we can avoid that bulky type checking everywhere.  Per our discussion on the call yesterday, I think we should consider targeting these more appropriately somehow (for example, not every attribute in this component is a boolean attribute, like 'label', 'placeholder', or 'value', and should respond to `'false'` in this manner).  Other than that, this looks good to me 👍

2021-11-24 15:50 UTC, EdwardCoyle commented on src/components/ids-time-picker/ids-time-picker.js
> +    const hours = this.dropdown({ id: 'hours', label: 'Hours', options: options.hours });
I ran into a similar problem in the Toolbar component recently, where it made more sense to just offload to another method that returns a string.  Template literals are fine where appropriate but I don't think it's a problem to use regular methods.

My only comment might be to consider if the `.dropdown` method can be made private

2021-11-24 15:55 UTC, EdwardCoyle commented on src/components/ids-trigger-field/ids-trigger-field.js
> +    const attrs = {
If dealing strictly with classes, this could definitely help.  Since `disabled` and `readonly` have to be handled by attributes here, I think this works well 👍

2021-11-24 16:10 UTC, EdwardCoyle commented on src/components/ids-time-picker/ids-time-picker.scss
> +  @include ml-16();
I raised infor-design/design-system#478 for eventually getting these in Tailwind-style mixin format

2021-11-24 17:48 UTC, EdwardCoyle requested changes
@clayinfor This is looking good so far! I appreciate you looking into some of our current patterns and trying to improve our approaches 👍 

I responded to some of your initial comments above, and also added a few new ones below.   Some we probably want to address now but one or two could be pushed to a Phase 2 issue.

Also before we accept this PR, we'll need to merge/rebase against `main` FYI.

2021-11-24 17:48 UTC, EdwardCoyle commented on src/components/ids-trigger-field/ids-trigger-field.js
> +    this.onEvent('click.label', this.elements.label, () => {
I'm wondering if this is necessary?  I can see it's focusing the IdsInput's label, but the IdsInput already handles that behavior as seen on http://localhost:4300/ids-input

2021-11-24 17:48 UTC, EdwardCoyle commented on src/components/ids-time-picker/ids-time-picker.js
> +  TWELVE: range(1, 12),
Is there a way we can generate these ranges using the `Date` object or some other API, so we don't have to assume manually?  I'm guessing you have to generate here because of the step feature.

Also worth noting that these will also be dependent on our Locale system at some point.  If the range can be driven by the format, we could potentially pull this information from the "culture" files that define each Locale's date format, day periods, whether to use 12 vs 24 hours, etc.  For example, [this info lives here for `en-US` locale](https://github.com/infor-design/enterprise-wc/blob/main/src/components/ids-locale/cultures/es-US.js#L42-L45).

I'd be OK with punting on this for now but we should raise another issue if we do, maybe for a Phase 2

2021-11-24 17:48 UTC, EdwardCoyle commented on src/components/ids-time-picker/ids-time-picker.js
> +  get is24Hours() { return this.format.includes('HH') || !this.hasPeriod; }
I think in the 4.x components, some of these getters for detection of specific parts of the date format were public out of necessity (before we could hide them via `#privateMethods()`), but I'm not sure that's necessary for the Web Component.

2021-11-24 17:48 UTC, EdwardCoyle commented on src/components/ids-time-picker/ids-time-picker.js
> +      this.onEvent('change', dropdowns.hours, (e) => { this.setTimeOnField({ hours: e.detail.value }); });
For the sake of limiting the amount of event listeners tied to each element, would it be possible to have only one here that delegates down to all Dropdowns in the picker, and handles each accordingly?

For context, we've become aware recently that we're generating a huge amount of event listeners at the individual component level, and we are actively seeking out ways of cutting down the sheer number of them.

2021-11-24 17:48 UTC, EdwardCoyle commented on src/components/ids-time-picker/ids-time-picker.js
> +    this.onEvent('mouseup', setTimeButton, () => {
Same deal with events here - maybe just have one `mouseup` handler and track which element is being dealt with via `e.target`

2021-11-24 17:50 UTC, EdwardCoyle commented on src/components/ids-time-picker/ids-time-picker.js
> +  get is24Hours() { return this.format.includes('HH') || !this.hasPeriod; }
Also as far as detecting the number of hours goes, you probably could get away with only detecting a single `H` or `h`.  Eventually we need to support leading zeroes in the time part output, which is signified by `HH` or `hh` respectively.

2021-11-24 17:53 UTC, EdwardCoyle commented on src/components/ids-time-picker/ids-time-picker.d.ts
> +  format?: string | 'hh:mm:ss a';
Having defaults is fine but keep in mind the default configuration for IDS Timepickers doesn't contain seconds (looks like `h:mm a`)

2021-11-30 12:42 UTC, andriivarhanov commented on src/components/ids-time-picker/ids-time-picker.js
> +  get value() { return this.getAttribute('value') || ''; }
please use `attributes.VALUE` here

2021-11-30 12:42 UTC, andriivarhanov commented on src/components/ids-time-picker/ids-time-picker.js
> +  set autoupdate(value) { this.setAttribute(attributes.AUTOUPDATE, !!value); }
`autoupdate` can't be set/unset dynamically, `document.querySelector('ids-time-picker').autoupdate = false` - same behavior

2021-11-30 12:42 UTC, andriivarhanov commented on src/components/ids-time-picker/ids-time-picker.js
> +  set autoselect(value) { this.setAttribute(attributes.AUTOSELECT, !!value); }
`autoselect` can't be set/unset dynamically, `document.querySelector('ids-time-picker').autoselect = false` - same behavior

2021-12-01 17:45 UTC, vivz753 commented on src/components/ids-time-picker/README.MD
> +- `isOpen` {boolean} Is the timepicker's popup open?
```suggestion
- `isOpen` {boolean} Is the timepicker's popup open?

```

2021-12-01 17:59 UTC, vivz753 commented on src/components/ids-time-picker/ids-time-picker.js
> +    this.elements = {
I did a similar thing in `ids-slider` where I querySelected a bunch of elements and saved them into local variables, but I did it in connectedCallback() because some of my elements are conditionally rendered depending on certain attributes. Am wondering if there is any difference in performance when doing it in constructor() vs doing it in connectedCallback() 🤔 Technically connectedCallback() will get called every time and element is added to the DOM, so in my case it would make sense to have it there, since some elements are conditionally rendered depending on what type of slider it is (double slider needs two buttons, single slider needs one button)

2021-12-07 14:49 UTC, tmcconechy commented
@clayinfor any progress on resolving the remaining things on this one? Thank You

2021-12-10 16:00 UTC, clayinfor commented on src/components/ids-time-picker/ids-time-picker.js
> +            <ids-text audible="true">Timepicker trigger</ids-text>
Thanks for the tip!  I attempted to do this, but got a lot of errors thrown and a broken page. See screenshot:
![image](https://user-images.githubusercontent.com/93789065/145603554-f60285d9-2e36-4566-bc19-b93fac7a8e07.png)

2021-12-10 17:06 UTC, clayinfor commented on src/components/ids-time-picker/ids-time-picker.js
> +    this.elements = {
I've decided to move this.elements out of the constructor and into a getter for the sake of making it `readonly`... the component would break if someone changed it's structure.

2021-12-10 17:33 UTC, clayinfor commented on src/components/ids-time-picker/ids-time-picker.js
> +    const hours = this.dropdown({ id: 'hours', label: 'Hours', options: options.hours });
Thanks for the tip!  When I try to make `this.dropdowns()` private `this.#dropdowns()`, I get the following error:
![image](https://user-images.githubusercontent.com/93789065/145616861-18549812-24dd-4d3d-bcfb-2d916d845cda.png)

2021-12-12 19:24 UTC, clayinfor commented on src/components/ids-time-picker/ids-time-picker.js
> +  TWELVE: range(1, 12),
Added to the timepicker's TODO.md file.

2021-12-12 19:31 UTC, clayinfor commented on src/components/ids-time-picker/ids-time-picker.js
> +  get is24Hours() { return this.format.includes('HH') || !this.hasPeriod; }
I attempted to make these private (i.e `this.is24Hours` into `this#is24Hours()`), but got the following error:
![image](https://user-images.githubusercontent.com/93789065/145726701-e97cd134-f54a-488c-89d3-5bef96019cc8.png)

2021-12-12 19:31 UTC, clayinfor commented on src/components/ids-time-picker/ids-time-picker.js
> +  get is24Hours() { return this.format.includes('HH') || !this.hasPeriod; }
Added to the timepicker's TODO.md file.

2021-12-12 19:31 UTC, clayinfor commented on src/components/ids-time-picker/ids-time-picker.js
> +            <ids-text audible="true">Timepicker trigger</ids-text>
Added to the timepicker's TODO.md file.

2021-12-12 19:33 UTC, clayinfor commented on src/components/ids-time-picker/ids-time-picker.js
> +    const hours = this.dropdown({ id: 'hours', label: 'Hours', options: options.hours });
Added to the timepicker's TODO.md file.

2021-12-12 21:35 UTC, clayinfor commented on src/components/ids-time-picker/ids-time-picker.js
> +            <ids-text audible="true">Timepicker trigger</ids-text>
Never mind, I think those errors were being thrown by Chrome's ScreenReader plugin which I was using to test this.

2021-12-13 00:01 UTC, clayinfor commented on src/components/ids-time-picker/ids-time-picker.d.ts
> +  format?: string | 'hh:mm:ss a';
Couldn't get `this.locale.calendar().timeFormat` to return a value for me, so I've tabled and added this suggestion to the TODO.md file.
![image](https://user-images.githubusercontent.com/93789065/145735009-9288b9f8-32ec-41f5-a48e-339fe334b88f.png)

2021-12-14 13:31 UTC, andriivarhanov commented on src/components/ids-time-picker/ids-time-picker.js
> +            <ids-text audible="true">Timepicker trigger</ids-text>
@clayinfor thanks, it's there, but it doesn't translate for some reason 
![image](https://user-images.githubusercontent.com/5204821/146007613-1821229a-00d2-47a4-8b23-68218dca1325.png)

2021-12-14 13:37 UTC, andriivarhanov commented on src/components/ids-time-picker/ids-time-picker.js
> +  get value() { return this.getAttribute('value') || ''; }
@clayinfor could you please use `attributes.VALUE` in value setter as well

2021-12-14 14:24 UTC, clayinfor commented on src/components/ids-time-picker/ids-time-picker.js
> +            <ids-text audible="true">Timepicker trigger</ids-text>
hey @andriivarhanov , I actually saw that, but thought that's the way the output was supposed to be.  I also had issues using `this.locale.calendar()` as a default for the `get format()` that @tmcconechy suggested.  Now I'm starting to wonder if I may be using the `IdsLocaleMixin` incorrectly.

2021-12-14 15:47 UTC, tmcconechy requested changes
Im not sure about the trigger field changes. What was necessary there. I can see it broke two things.

1. is badly broken http://localhost:4300/ids-dropdown compare too https://main.wc.design.infor.com/ids-dropdown/ (i live site of whats on main)
2. tests point to some errors https://github.com/infor-design/enterprise-wc/runs/4521487299?check_suite_focus=true#step:9:3481
3. the size of the dropdown broke
![Screen Shot 2021-12-14 at 10 45 34 AM](https://user-images.githubusercontent.com/814283/146031198-a4775521-ac90-4e82-9e40-0034db573415.png)

2021-12-14 15:47 UTC, tmcconechy commented on src/components/ids-layout-grid/ids-layout-grid.scss
> +  --grid-min-col-width: 50px;
his could also be the reason http://localhost:4300/ids-dropdown broke? any reason for this? cc @jmacaluso711

2021-12-14 15:47 UTC, tmcconechy commented on src/components/ids-time-picker/TODO.md
> +- [ ] Update README.md
Are all these still valid? At least README.md seems updated

2021-12-14 15:47 UTC, tmcconechy commented on src/components/ids-time-picker/ids-time-picker.d.ts
> +  ['minute-interval']?: number;
Shouldnt this be `minuteInternal`?

2021-12-14 15:47 UTC, tmcconechy commented on src/components/ids-time-picker/ids-time-picker.d.ts
> +  setTimeOnField(timeunits: {
Would it be cleaner to use a `value` setting that did this?

2021-12-14 15:47 UTC, tmcconechy commented on src/components/ids-trigger-field/ids-trigger-field.d.ts
> +  readonly elements: {
Would anyone need this using the component?

2021-12-14 16:18 UTC, clayinfor commented on src/components/ids-trigger-field/ids-trigger-field.d.ts
> +  readonly elements: {
good question... probably not... I'll take it out.

2021-12-14 17:43 UTC, clayinfor commented on src/components/ids-time-picker/TODO.md
> +- [ ] Update README.md
I removed this Update README line from TODO.md

2021-12-14 17:49 UTC, clayinfor commented on src/components/ids-time-picker/ids-time-picker.d.ts
> +  setTimeOnField(timeunits: {
`value` is already used to set the input-field's value.

2021-12-14 21:14 UTC, jmacaluso711 commented on src/components/ids-trigger-field/ids-trigger-field.scss
> +  @include inline-flex();
@tmcconechy @clayinfor Looks like this is causing the layout issue in the dropdown. I think it can be reverted back to flex without breaking the time-picker

2021-12-15 12:42 UTC, clayinfor commented on src/components/ids-trigger-field/ids-trigger-field.scss
> +  @include inline-flex();
yup that fixed it, thanks @jmacaluso711 !

2021-12-15 12:44 UTC, clayinfor commented on src/components/ids-time-picker/ids-time-picker.js
> +    this.onEvent('mouseup', setTimeButton, () => {
hey @EdwardCoyle , I was able to group the dropdown event handlers, but I left these `mouseup` events alone because the trigger button has an icon in the middle of it that interferes with it's event bubbling and causes inconsistent `mouseup` targeting behavior.

2021-12-15 14:18 UTC, tmcconechy commented on src/components/ids-time-picker/ids-time-picker.d.ts
> +  format?: string | 'hh:mm:ss a';
Thanks - i'll follow up on this on after merging my locale changes

2021-12-15 14:50 UTC, andriivarhanov commented on src/components/ids-time-picker/ids-time-picker.js
> +            <ids-text audible="true">Timepicker trigger</ids-text>
@clayinfor  yeah, you are right, it may be something with `IdsLocaleMixin`. To see a correct behaviour of translations and `this.locale.calendar()` just remove `language="pt"` from the example
![demosids-time-pickerexample html](https://user-images.githubusercontent.com/5204821/146208182-a18a4e39-2f7c-4887-b2b9-4c350bdd5a2e.png)

including @tmcconechy in the conversation since he is working on locale changes now

2021-12-15 15:01 UTC, andriivarhanov commented on src/components/ids-time-picker/ids-time-picker.d.ts
> +  format?: string | 'hh:mm:ss a';
@clayinfor it looks like you need include `languagechange` `localechange` events and get timeformat once calendar is loaded. Example of the events is here
https://github.com/infor-design/enterprise-wc/blob/main/src/components/ids-icon/ids-icon.js#L76-L94

2021-12-16 16:08 UTC, jmacaluso711 submitted a review, later dismissed

2021-12-16 16:08 UTC, jmacaluso711 commented on src/components/ids-time-picker/ids-time-picker.scss
> +  #dropdowns {
nit pick here: but we might want to stay away from using IDs for styling? Otherwise this looks great to me

2021-12-16 16:36 UTC, tmcconechy commented on src/components/ids-time-picker/ids-time-picker.d.ts
> +  setTimeOnField(timeunits: {
Can you explain the difference im not sure i understand then what setTimeOnField vs value does?

2021-12-16 16:36 UTC, tmcconechy commented
@clayinfor still some test failures on trigger fields here. Not sure 100% whats going on with that but didnt spend much time on it. The rest looks good though. And one question i added.

2021-12-16 16:41 UTC, clayinfor commented on src/components/ids-time-picker/ids-time-picker.d.ts
> +  setTimeOnField(timeunits: {
Sure, @tmcconechy :  `this.value` will set the input-field directly... whereas `this.setTimeOnField()` will calculate what the input-field's value should be by using the current values in the dropdown-selections.  

I actually had a different name for `this.setTimeOnField()` (something like `this.updateTimestring()`, but saw that's the name the legacy-component used, so I stuck with that convention.

2021-12-16 16:45 UTC, clayinfor commented on src/components/ids-time-picker/ids-time-picker.d.ts
> +  setTimeOnField(timeunits: {
To elaborate, if someone did `this.value = "Hello World"`, the input-field would display `Hello World`... `this.setTimeOnField()` would calculate and set the input-field's value back to what it should correctly be based on current dropdown-selections.  So `this.value` is just standard input-field behavior that gives users a way to override the input-field value.

2021-12-16 16:52 UTC, tmcconechy commented on src/components/ids-time-picker/ids-time-picker.d.ts
> +  setTimeOnField(timeunits: {
ok I see. On the old version we were a bit limited in that we couldnt override the value setting as we didnt have a custom component. So not attached to it.

One similar change was on the dropdown i decided to make value() actually lookup the dropdown value and set it https://github.com/infor-design/enterprise-wc/blob/main/src/components/ids-dropdown/ids-dropdown.js#L183 so its somewhat similar...

What if you used value here but in the setter but allow it two ways..

```
comp.value = time: {hours: 10, minutes: 20: seconds: 30: period: 'AM}
// or
comp.value = '10:10:20 AM';
```

i.e if the value is an object with `time` convert it and set it and if its just a string set that direct in?

2021-12-16 16:55 UTC, clayinfor commented on src/components/ids-time-picker/ids-time-picker.d.ts
> +  setTimeOnField(timeunits: {
Ok, that looks good 🤓   What should I then do with `this.setTimeOnField()`?

2021-12-16 16:56 UTC, tmcconechy commented on src/components/ids-time-picker/ids-time-picker.d.ts
> +  setTimeOnField(timeunits: {
get rid of it in favor of passing the time info in to the value setter... It can go away in that case, right? 👍🏻

2021-12-16 16:57 UTC, clayinfor commented on src/components/ids-time-picker/ids-time-picker.d.ts
> +  setTimeOnField(timeunits: {
Right, ok cool 👍

2021-12-21 17:27 UTC, tmcconechy approved these changes

2021-12-21 22:14 UTC, tmcconechy requested changes
there is a couple things on the percy tests that caught
- disabled color on trigger disabled label
- dropdown bottom padding
- something on search?

2021-12-22 10:53 UTC, clayinfor commented on src/components/ids-trigger-field/ids-trigger-field.js
> +    this.onEvent('click.label', this.elements.label, () => {
I tried removing this block of code, but the input doesn't autofocus once the label is clicked... so this block of code appears to be necessary.

2021-12-22 13:08 UTC, clayinfor commented
> there is a couple things on the percy tests that caught
> 
> * disabled color on trigger disabled label
> * dropdown bottom padding
> * something on search?

Thanks @tmcconechy! I was able to fix these... the remaining percy test-fails just require an approval/thumbs-up.

2021-12-22 14:17 UTC, tmcconechy approved these changes

2021-12-27 17:13 UTC, deep7102 approved these changes
Looks good 🍌 
Thanks! @clayinfor

2021-12-27 18:55 UTC, merged