438 - Implement theme on notification banner
infor-design/enterprise-wc pull request #440
Opened 2021-11-23 18:32 UTC by jeffwa428

**Explain the details for making this change. What existing problem does the pull request solve?**

Implemented theme on notification banner

**Related github/jira issue (required)**:

Closes https://github.com/infor-design/enterprise-wc/issues/438

**Steps necessary to review your pull request (required)**:

Steps to reproduce the behavior:

- Go to http://localhost:4300/ids-notification-banner
- Click on '....'
- Select the 6 mode/themes
- Colors should match https://main-enterprise.demo.design.infor.com/components/notification/example-index.html in the old versions

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [ ] A note to the change log.

2021-11-24 18:17 UTC, EdwardCoyle submitted a review, later dismissed

2021-11-25 10:18 UTC, andriivarhanov reviewed
looks good, one minor thing, a bit of cleanup

2021-11-25 10:18 UTC, andriivarhanov commented on src/components/ids-notification-banner/ids-notification-banner.js
> -      this.container.style.backgroundColor = bgColor;
I think we can remove `color` in `TYPES` object here https://github.com/infor-design/enterprise-wc/blob/2fba8067cbe50693bd0cd02b28a394660d92bc93/src/components/ids-notification-banner/ids-notification-banner.js#L24 since it's not used anymore

2021-11-29 18:00 UTC, tmcconechy commented on src/components/ids-notification-banner/ids-notification-banner.js
> -      this.container.style.backgroundColor = bgColor;
I think we might use this someplace at some point so might be ok to leave it. Seems like a common property name?

2021-11-29 18:02 UTC, tmcconechy requested changes
Im not seeing the Theme: New -> Mode: High Contrast being changed vs
https://main-enterprise.demo.design.infor.com/components/notification/example-index.html?theme=new&mode=contrast&colors=003876 (text is darker ect)

Can ignore the "Classic" for now as that may be removed https://github.com/infor-design/enterprise-wc/issues/395

2021-12-01 17:28 UTC, vivz753 commented on src/components/ids-notification-banner/ids-notification-banner.scss
> +
I think the better way to organize the hierarchy would be to use the light/contrast/dark as the outer selector first, then the type of banner.

```css
.ids-notification-banner {
 &[mode='light'], &[mode='contrast'] {
    &[type='success'], &[type='alert'], &[type='info'], &[type='error'] {
      ids-text::part(text) {
        color: var(--ids-color-palette-slate-90);
      }
      ids-hyperlink::part(link) {
        color: var(--ids-color-palette-slate-90);
      }
    }
  }
}
```

2021-12-01 17:30 UTC, vivz753 commented on src/components/ids-notification-banner/ids-notification-banner.scss
> +
```suggestion
.ids-notification-banner[mode='dark'] {
  &[type='success'], &[type='alert'], &[type='info'], &[type='error'] {
    ids-text::part(text) {
      color: var(--ids-color-palette-slate-10);
    }

    ids-hyperlink::part(link) {
      color: var(--ids-color-palette-slate-10);
    }
}

```

2021-12-01 17:34 UTC, vivz753 commented on src/components/ids-notification-banner/ids-notification-banner.scss
> +
But according to Tim's comment regarding the text color for the contrast/light theme the text colors differ slightly

#3e3e42 for high contrast
#47474c for light

So you would end up separating the light and contrast selectors anyway

2021-12-01 19:24 UTC, jeffwa428 commented on src/components/ids-notification-banner/ids-notification-banner.scss
> +
@vivz753  Thanks for your recommendation. I think it would be better for the code organization.

2021-12-02 13:42 UTC, tmcconechy requested changes
@jeffwa428 Im still not seeing changes on contrast theme? Could be my mistake?
Also one thing i noticed is the X button is very small. Compared to the previous version. Can you check if it has some styling thats making it not the same as a normal button?

2021-12-02 13:45 UTC, jeffwa428 commented
@tmcconechy For the contrast, I have changed color text, and updated style for the link. I will check the X button.

2021-12-02 13:58 UTC, tmcconechy commented
Ok also check the colors on the error/info icon ect? If thats easy to change. if not its probably ok like this.

2021-12-03 14:52 UTC, tmcconechy approved these changes

2021-12-06 18:27 UTC, deep7102 approved these changes
🍌

2021-12-07 14:51 UTC, merged