437 - Hide button in swipe action card on load
infor-design/enterprise-wc pull request #441
Opened 2021-11-23 18:37 UTC by jeffwa428

**Explain the details for making this change. What existing problem does the pull request solve?**

Fix issue of showing swipe button on initial load

**Related github/jira issue (required)**:

Closes https://github.com/infor-design/enterprise-wc/issues/437

**Steps necessary to review your pull request (required)**:

Steps to reproduce the behavior:

- Go to http://localhost:4300/ids-swipe-action
- You should not see swipe button in first card whenever you reload the page

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [ ] A note to the change log.

2021-11-24 18:32 UTC, EdwardCoyle approved these changes
This definitely fixes the state problem (no more swipe action on the right), but I wonder if we could improve this further by not animating the swipe state at all?  Currently when the page loads, the left swipe action is animating out.

2021-11-24 18:32 UTC, EdwardCoyle commented on src/components/ids-swipe-action/ids-swipe-action.js
> +      setTimeout(() => {
We're trying to standardize these in favor of `requestAnimationFrame()`:

```suggestion
      requestAnimationFrame(() => {
```

2021-11-24 18:34 UTC, EdwardCoyle requested changes
Sorry meant to request changes before

2021-11-24 18:59 UTC, jeffwa428 commented
> Sorry meant to request changes before

Okay, I will make this change.

2021-12-01 16:08 UTC, jeffwa428 commented on src/components/ids-swipe-action/ids-swipe-action.js
> +      setTimeout(() => {
@EdwardCoyle 
I tried with requestAnimationFrame but it was same. What can I do for now?

2021-12-01 17:54 UTC, tmcconechy commented on src/components/ids-swipe-action/ids-swipe-action.js
> +      setTimeout(() => {
It seems to work with it for me? The only thing i see is sometimes i get an extra line on the border:

![Screen Shot 2021-12-01 at 12 54 08 PM](https://user-images.githubusercontent.com/814283/144287521-de0ecff4-1a34-4085-9d7a-7721cb56277b.png)

2021-12-01 18:04 UTC, jeffwa428 commented on src/components/ids-swipe-action/ids-swipe-action.js
> +      setTimeout(() => {
You don't see any swipe left animation on page load?

2021-12-01 18:10 UTC, tmcconechy commented on src/components/ids-swipe-action/ids-swipe-action.js
> +      setTimeout(() => {
I see it move across the page (which isnt ideal) but i see the same thing with setTimeout or requestAnimationFrame

2021-12-01 18:17 UTC, jeffwa428 commented on src/components/ids-swipe-action/ids-swipe-action.js
> +      setTimeout(() => {
Yes, it's same. The purpose was to remove that animation on the page load.

2021-12-02 13:46 UTC, tmcconechy commented
@jeffwa428 I still see it animating when the page loads? Wonder if there is a way to prevent that? I think worth exploring
Also still seeing the border on the left of 1px. Maybe that part can be fixed by:

```
.ids-swipe-container {
  ...
   // remove this margin-left: -1;
}
```

2021-12-03 14:53 UTC, tmcconechy requested changes
1. See if we can hide the animation initially (somehow)
2. Fix the double border
3. Eds suggestion of requestAnimationFrame

2021-12-07 15:05 UTC, tmcconechy approved these changes
@jeffwa428 i fixed this up the "border" issue. turns out it was missing the card import so it looks different now. I still see the animation but i guess there is no great way to fix that so approving for now

2021-12-09 19:52 UTC, tmcconechy commented on src/components/ids-swipe-action/ids-swipe-action.js
> +        setTimeout(() => {
The functionality is working well. But can we use the renderLoop pattern:

https://github.com/infor-design/enterprise-wc/blob/main/src/components/ids-toast/ids-toast-message.js#L131-L150


Is one example see also http://localhost:4300/ids-render-loop

2021-12-10 15:33 UTC, tmcconechy submitted a review, later dismissed

2021-12-10 18:24 UTC, tmcconechy approved these changes

2021-12-13 14:58 UTC, tmcconechy submitted a review, later dismissed

2021-12-15 22:09 UTC, EdwardCoyle reviewed
One minor nitpick/improvement and we can call this one good. Also, not marking "request changes" since I'll be out for a few days.

2021-12-15 22:09 UTC, EdwardCoyle commented on src/components/ids-swipe-action/ids-swipe-action.js
> +      const timeout = renderLoop.register(new IdsRenderLoopItem({
The use of the Renderloop can be good for the callback below this one, since it needs staggering by 200ms.  For the ones that should kick off during the next paint cycle, Renderloop usage is overkill.  This can be replaced with a call to `requestAnimationFrame` and save some cycles:

```suggestion
      requestAnimationFrame(() => {
        this.container.scrollLeft = 85;
      });
```

2021-12-16 15:19 UTC, tmcconechy approved these changes

2021-12-16 16:18 UTC, merged