Refactor templates
infor-design/enterprise-wc pull request #446
Opened 2021-12-02 03:08 UTC by vivz753

**Explain the details for making this change. What existing problem does the pull request solve?**

**- Refactoring templates on ids-data-grid for better readability**

**Related github/jira issue (required)**:

**Steps necessary to review your pull request (required)**:

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [ ] A note to the change log.

2021-12-02 13:55 UTC, tmcconechy requested changes
Looks good. Just a few small things.

1) Two parts as noted in the inline comment (lets leave part="body")
2) Can you update ids-datagrid.d.ts as well with the new row heights
3) Can you update demos/ids-lookup/example.js with the row height change?

I was also wondering why percy changed the visual image as it seems like it should be the same? Any thoughts?

2021-12-02 13:55 UTC, tmcconechy commented on src/components/ids-data-grid/ids-data-grid.js
> +          <div class="ids-data-grid-body" part="style-wrapper" part="body" role="rowgroup"></div>
Two parts here? Does that work or a mistake? Prefer part="body" for the external API

2021-12-02 18:49 UTC, vivz753 commented on src/components/ids-data-grid/ids-data-grid.js
> +          <div class="ids-data-grid-body" part="style-wrapper" part="body" role="rowgroup"></div>
Removed the part="style-wrapper"

2021-12-02 18:50 UTC, vivz753 commented
Completed all 4 items listed above. Also changed rowHeight and row-height accordingly in a few other examples. Don't know why the styles changed in that previous iteration, but it should be gone now... waiting for test to finish.

2021-12-02 19:30 UTC, tmcconechy submitted a review, later dismissed

2021-12-03 13:27 UTC, andriivarhanov reviewed
looks good, just one minor thing

2021-12-03 13:27 UTC, andriivarhanov commented on src/components/ids-data-grid/README.md
> +- `rowHeight` {string|number} Sets the height of each row
please remove `number` here and add 'xs' | 'sm' | 'md' | 'lg' options

2021-12-03 17:14 UTC, vivz753 commented on src/components/ids-data-grid/README.md
> +- `rowHeight` {string|number} Sets the height of each row
Done, thanks

2021-12-03 17:39 UTC, andriivarhanov approved these changes

2021-12-03 17:41 UTC, tmcconechy approved these changes

2021-12-03 17:42 UTC, merged