443 - Set validate attribute dynamically
infor-design/enterprise-wc pull request #448
Opened 2021-12-03 14:41 UTC by jeffwa428

**Explain the details for making this change. What existing problem does the pull request solve?**

Make it enable to set `validate` property dynamically.

**Related github/jira issue (required)**:

Closes https://github.com/infor-design/enterprise-wc/issues/443

**Steps necessary to review your pull request (required)**:

- Go to http://localhost:4300/ids-input
- Type in the console to toggle validation
```
document.querySelector('ids-lookup').validate = 'required'
'required'
document.querySelector('ids-lookup').validate = ''
```
Then `validate` attribute should be working correctly.

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [ ] A note to the change log.

2021-12-03 15:05 UTC, tmcconechy requested changes
Looks good @jeffwa428 nice fix. The only thing i would like to suggest is can you make a test for this in input and trigger field? I think this case should have a unit test

2021-12-03 15:07 UTC, jeffwa428 commented
Okay, no problem. I will implement test.

2021-12-06 16:06 UTC, tmcconechy commented on test/ids-lookup/ids-lookup-func-test.js
> +  it('adding validation dynamically', async () => {
```suggestion
  it('supports changing validation dynamically', async () => {
```

2021-12-06 16:06 UTC, tmcconechy approved these changes

2021-12-06 16:57 UTC, andriivarhanov approved these changes

2021-12-06 18:38 UTC, deep7102 approved these changes
🍌

2021-12-06 23:53 UTC, vivz753 approved these changes

2021-12-07 14:50 UTC, merged