369 - Ids Treemap Component
infor-design/enterprise-wc pull request #449
Opened 2021-12-03 21:09 UTC by jmacaluso711

**Explain the details for making this change. What existing problem does the pull request solve?**
This PR adds the Treemap data viz component

**Related github/jira issue (required)**:
closes #369 

**Steps necessary to review your pull request (required)**:
- pull and run branch
- go to http://localhost:4300/ids-treemap
- Make sure the treemap renders properly
- Resize the browser and make sure the treemap reflows properly
- Check tests func/e2e test coverage is sufficient

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2021-12-06 16:11 UTC, tmcconechy commented on src/components/ids-treemap/ids-treemap.d.ts
> +  result?: object | [{ value: 1 }, { value: 2 }];
Should we call this `data` like some of the other components? I think `result` seems a bit confusing to me? Its the data you feed in right?

2021-12-06 16:11 UTC, tmcconechy requested changes
Looks great! Just wondering about one setting name `result` other than that looks good

2021-12-06 18:04 UTC, andriivarhanov reviewed
Looks good, some review notes to discuss:
- please add dark / contrast mode
- please check the component in Checklist.md
- please add standalone (if needed, I'm not sure)
- some methods are marked as `@private` in comment but are not private. `#` is missing
- title can't be changed dynamically
- I think `width` `height` could be component's attributes

2021-12-06 20:01 UTC, jmacaluso711 commented on src/components/ids-treemap/ids-treemap.d.ts
> +  result?: object | [{ value: 1 }, { value: 2 }];
Yeah I was on the fence about that.. will change to `data`

2021-12-07 18:39 UTC, vivz753 commented on src/components/ids-treemap/ids-treemap.js
> +        <div class="treemap-title">${this.templateTitle()}</div>
```suggestion
        <div class="treemap-title">
          ${this.templateTitle()}
        </div>
```

2021-12-07 18:44 UTC, vivz753 commented on src/components/ids-treemap/ids-treemap.js
> +        ${this.title !== null ? this.title : 'Add Treemap Title'}
```suggestion
       ${typeof this.title === 'string' ? this.title : 'Add TreemapTitle'}
```

2021-12-07 18:45 UTC, vivz753 commented on src/components/ids-treemap/ids-treemap.js
> +        ${this.title !== null ? this.title : 'Add Treemap Title'}
Edge case where if someone did
```
this.title = undefined
this.title = NaN
this.title = {}
this.title = []
```
it would break the code

2021-12-07 18:47 UTC, vivz753 commented on src/components/ids-treemap/ids-treemap.js
> +   * @returns {Array} round value array
Might be good to add a comment mentioning the preservation of 2 decimals

2021-12-07 18:53 UTC, vivz753 commented on src/components/ids-treemap/ids-treemap.js
> +    if (!height || typeof height !== 'number' || height < 0) {
```suggestion
    if (typeof height !== 'number' || height <= 0) {
```

A bit more concise but essentially the same thing

2021-12-07 18:58 UTC, vivz753 commented on src/components/ids-treemap/ids-treemap.js
> +    if (!data || !Array.isArray(data) || data.length === 0 || !data.every((dataPoint) => Object.prototype.hasOwnProperty.call(dataPoint, 'value') && typeof dataPoint.value === 'number' && dataPoint.v
What exactly does this do?

What I got from it was 
- it checks if data is an array
- checks to make sure data length > 0
- checks that each item in data has a key named `value`
- each key is a number > 0

2021-12-07 19:03 UTC, vivz753 commented on src/components/ids-treemap/ids-treemap.js
> +    if (!data || !Array.isArray(data) || data.length === 0 || !data.every((dataPoint) => Object.prototype.hasOwnProperty.call(dataPoint, 'value') && typeof dataPoint.value === 'number' && dataPoint.v
```suggestion
    if (!Array.isArray(data) || data.length === 0 || !data.every((dataPoint) => Object.prototype.hasOwnProperty.call(dataPoint, 'value') && typeof dataPoint.value === 'number' && dataPoint.value >= 0)) {
```

If so, can get rid of redundant statements

2021-12-07 19:15 UTC, vivz753 submitted a review, later dismissed

2021-12-07 20:07 UTC, jmacaluso711 commented on src/components/ids-treemap/ids-treemap.js
> +    window.addEventListener('resize', () => {
Going to convert this to the ResizeObeserver

2021-12-09 19:53 UTC, tmcconechy approved these changes

2021-12-10 09:08 UTC, andriivarhanov approved these changes

2021-12-10 15:33 UTC, merged