379 ids process indicator responsive
infor-design/enterprise-wc pull request #450
Opened 2021-12-06 21:29 UTC by vivz753

**Explain the details for making this change. What existing problem does the pull request solve?**

- Refactored ids-process-indicator for more modular hierarchy for CSS classes and HTML elements
- Add responsive styling (when xs, hide the details and labels, and only display the active label)

**Related github/jira issue (required)**:

- Closes #379 

**Steps necessary to review your pull request (required)**:

- http://localhost:4300/ids-process-indicator
- Adjust the width of the window size to see responsive styling

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [ ] A note to the change log.

2021-12-06 21:29 UTC, vivz753 commented on src/components/ids-process-indicator/ids-process-indicator.js
> -    this.#calculateProgressLine();
No longer needed, as progress lines are now handled individually by each process-step

2021-12-07 15:15 UTC, tmcconechy requested changes
Looks good 👍🏻 

1. Maybe consider making that div a slot or component as mentioned
2. Can we make it break a breakpoint step earlier as when you get close to the breakpoint the alignment is a little off

![Screen Shot 2021-12-07 at 10 11 18 AM](https://user-images.githubusercontent.com/814283/145055029-3c727eb1-facf-4a26-ae1e-eb8526a4fd0c.png)

3. Seems like it doesnt go all the way over to the right (bit of a gap on the right)
![Screen Shot 2021-12-07 at 10 12 55 AM](https://user-images.githubusercontent.com/814283/145055171-cbf118d4-3ab3-411d-a0ed-c79001ceb67e.png)

4. can we add a bit of test coverage for the new (and previous) code?
`npx jest --coverage -- process-ind`

![Screen Shot 2021-12-07 at 10 15 07 AM](https://user-images.githubusercontent.com/814283/145055525-c5effcf2-7bf6-4df9-bec5-aab7ca653a11.png)

2021-12-07 15:15 UTC, tmcconechy commented on demos/ids-process-indicator/example.html
> +        <div>
Since this is the public api. Maybe we should make a new simple component for this just so that we have the custom element? `ids-process-details` maybe something like that? Or maybe a named slot? But seems like a component perhaps

2021-12-07 19:18 UTC, vivz753 commented on demos/ids-process-indicator/example.html
> +        <div>
Yeah we can do that, will open a new issue for it

2021-12-07 19:19 UTC, tmcconechy commented on demos/ids-process-indicator/example.html
> +        <div>
Ok or i would consider it part of this because your adding the `div` in here.

2021-12-07 19:22 UTC, vivz753 commented
2. The breakpoint can be changed to condense when screen-size is below md. I had it like that initially but since the example didn't condense until below sm and ALSO had the cut off issue, I just mimicked that. 
3. It accounts space for details on the last step, let me try removing that extra width.
4. Will do!

2021-12-07 20:37 UTC, vivz753 commented on demos/ids-process-indicator/example.html
> +        <div>
So the div was added around ids-icon and ids-hyperlink because icon and hyperlink needed to be inline/styled on the same row, otherwise they were separating onto different lines. I was going to add in slots initially but I think it needs to be spec'd out a bit more.

Is this format of data going to be guaranteed every time in this order/structure?
```
<ids-text slot="detail"></ids-text>
<div slot="persons"><ids-icon></ids-icon><ids-hyperlink></ids-hyperlink><div>
<div slot="timestamp"></div>
```

2021-12-07 20:52 UTC, tmcconechy commented on demos/ids-process-indicator/example.html
> +        <div>
i think maybe something like `details` instead as its not always going to be about people's people/status. They could technically put any information there.

FYI original specs if that helps https://github.com/infor-design/enterprise/issues/3918

I called it details before https://github.com/infor-design/enterprise/pull/4636/files?authenticity_token=cEdIcOZP4Cyq8KLZ%2FVq6JIXpmMRXr9Ab3x1yADYnBd9ZsX5m2l4crYPzk2HRDsKKclFJ5PEkfrNY8rhgQMNX7w%3D%3D&file-filters%5B%5D=.html&file-filters%5B%5D=.js&file-filters%5B%5D=.png&file-filters%5B%5D=.scss#diff-3346d3f1b32cff9ef0617302a1923925d8f877a9c31b9ef8d4c6598faadede53R13

So maybe simply:
```
<div slot="details">
  <ids-icon></ids-icon><ids-hyperlink></ids-hyperlink>
  <ids-icon></ids-icon><ids-hyperlink></ids-hyperlink>
  <ids-icon></ids-icon><ids-hyperlink></ids-hyperlink>
<div>
```

2021-12-08 14:35 UTC, tmcconechy commented
With the coverage i think just try to get it from yellow to green as a goal? Trying to keep it all green so maybe one more test 👍🏻  ?

Then i think the only thing left from me is adding a slot name to the <div slot="details"> wrapper

2021-12-09 00:18 UTC, vivz753 commented
Slot for details added!

Can't figure out how to get this test to cover more branches.... it's stuck in yellow even though it runs through all the branches
<img width="743" alt="Screen Shot 2021-12-08 at 4 17 27 PM" src="https://user-images.githubusercontent.com/22609861/145311661-42681089-6575-4afd-af13-67a6d26f2d63.png">

The yellow highlighted code isn't the cause for branches being 66%... 
<img width="792" alt="Screen Shot 2021-12-08 at 4 17 37 PM" src="https://user-images.githubusercontent.com/22609861/145311648-de036a85-98f7-476e-8bc3-31f6fd8e7316.png">

2021-12-09 14:52 UTC, tmcconechy commented
Try doing a rebuild.
```
npm run build
npx jest --coverage -- process-i
```
Then rerun the tests. I think sometimes because of the livereload the code gets a bit funny so that should recompile cleanly all the code.

2021-12-09 20:46 UTC, vivz753 commented
Same result ^ 

But I was able to solve the problem, and increase branch coverage from 66% to 83% by adding another example into the demos. No matter what I did in the functional tests, it wasn't counted for those code paths. I had to add an example in the demos that didn't have labels to cover that ternary path for the xs-header label (which prints the index of the node if the active node has no defined label)

It works, but kind of dislike that I had to add an extra example in the demos index.html for ids-process-indicator. I tried having a dedicated example in its own html file, but that wasn't doing anything for the coverage percentage either. Lmk your thoughts

2021-12-09 20:50 UTC, tmcconechy commented
I think as we get more e2e tests going we will need examples for them, just about thinking of how to break it up in purposeful ways. I didn't see what you added yet but if we made it something different or more purposeful that would be good, or simply to split the example in two simpler ones i think thats totally valid. So if thats the case its probably good.

2021-12-09 21:06 UTC, vivz753 commented on demos/ids-process-indicator/example.html
> +  <ids-text font-size="12" type="h1">Process Indicator Without Labels</ids-text>
New example here was added for test coverage

2021-12-09 21:09 UTC, tmcconechy commented on demos/ids-process-indicator/example.html
> +  <ids-text font-size="12" type="h1">Process Indicator Without Labels</ids-text>
Ok dont mind it but you could add a new page for the test `no-labels.html` at least that way you dont need to see it as the main example as its probably not something we want to encourage

2021-12-09 21:09 UTC, vivz753 commented
I agree it would be better to break into more specific dedicated examples.

I don't really understand how or why the coverage results react to example.html only though and not my cases in the func test file and other html demo files.

2021-12-09 21:12 UTC, tmcconechy commented
Did you try this... https://github.com/infor-design/enterprise-wc/blob/main/test/ids-process-indicator/ids-process-indicator-e2e-test.js#L1

```
describe('Ids Process Indicator e2e Tests', () => {
  const exampleUrl = 'http://localhost:4444/ids-process-indicator';

  it('should not have errors', async () => {
    await page.goto(exampleUrl, { waitUntil: ['domcontentloaded', 'networkidle0'] });
    await expect(page.title()).resolves.toMatch('IDS Process Indicator Component');
  });

  it('should pass Axe accessibility tests', async () => {
    await page.setBypassCSP(true);
    await page.goto(exampleUrl, { waitUntil: ['networkidle2', 'load'] });
    await expect(page).toPassAxeTests({ disabledRules: ['color-contrast'] });
  });
});

describe('Ids Process Indicator No Label Tests', () => {
  const exampleUrl = 'http://localhost:4444/ids-process-indicator/no-labels.html';

  it('your test', async () => {
  });
});
```

i.e a new test loading the new page...

2021-12-09 22:55 UTC, vivz753 commented on demos/ids-process-indicator/example.html
> +  <ids-text font-size="12" type="h1">Process Indicator Without Labels</ids-text>
That's what I saying in the above comment. I did initially, but it wasn't getting picked up by the test coverage.

2021-12-09 22:58 UTC, vivz753 commented
What's the difference between e2e and functional tests? So far I've only really seen them used for axe testing and loading the DOM. I know recently there's been changes allowing UI tests involving clicking/dragging... but not sure how this would apply here or what I would write in the blanks for that test.

Tests aren't running properly on my personal mac atm... will try again later on the work mac.

2021-12-10 03:20 UTC, vivz753 commented on test/ids-process-indicator/ids-process-indicator-e2e-test.js
> +    await page.goto(emptyLabelExampleUrl, { waitUntil: ['domcontentloaded', 'networkidle0'] });
Adding dedicated example here increased test coverage. Lmk if this is acceptable @tmcconechy

2021-12-10 15:37 UTC, tmcconechy commented on test/ids-process-indicator/ids-process-indicator-e2e-test.js
> +    await page.goto(emptyLabelExampleUrl, { waitUntil: ['domcontentloaded', 'networkidle0'] });
Yeah think this is acceptable enough for now. I have some fixes coming that may help fix coverage up more in the future.

2021-12-10 15:37 UTC, tmcconechy submitted a review, later dismissed
Approving but there is a minor lint error to fix 👍🏻

2021-12-13 14:51 UTC, tmcconechy approved these changes

2021-12-14 09:56 UTC, andriivarhanov approved these changes

2021-12-14 16:30 UTC, merged