430 - Add themes to ids-tabs
infor-design/enterprise-wc pull request #452
Opened 2021-12-08 14:59 UTC by jeffwa428

**Explain the details for making this change. What existing problem does the pull request solve?**

Implement theme to ids-tabs, colors for light, dark, contrast and fix some style issues

**Related github/jira issue (required)**:

Closes https://github.com/infor-design/enterprise-wc/issues/430

**Steps necessary to review your pull request (required)**:

- Go to http://localhost:4300/ids-tabs
- Compare with https://main-enterprise.demo.design.infor.com/components/tabs/example-index.html?theme=new&mode=dark&colors=0066D4, especially colors

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [ ] A note to the change log.

2021-12-08 19:21 UTC, tmcconechy commented on src/components/ids-tabs/ids-tab.js
> +    this.onEvent('focus', this, () => {
What does this change do?

2021-12-08 19:26 UTC, jeffwa428 commented on src/components/ids-tabs/ids-tab.js
> +    this.onEvent('focus', this, () => {
When I checked this, https://main-enterprise.demo.design.infor.com/components/tabs/example-index.html?theme=new&mode=dark&colors=0066D4, I found that firing click event is implemented differently.
click fires event on mouseup and focus fires event on mousedown.

2021-12-09 19:58 UTC, tmcconechy requested changes
@jeffwa428 im not seeing this working the colors dont match in all 3 themes...See side by side..

<img width="441" alt="Screen Shot 2021-12-09 at 2 57 56 PM" src="https://user-images.githubusercontent.com/814283/145466948-837a243e-c0e2-4b55-b0a8-afa6162f2aba.png">
<img width="349" alt="Screen Shot 2021-12-09 at 2 57 42 PM" src="https://user-images.githubusercontent.com/814283/145466950-30a44d57-7948-43ee-9b3a-83b9d9bb99a4.png">
<img width="289" alt="Screen Shot 2021-12-09 at 2 57 19 PM" src="https://user-images.githubusercontent.com/814283/145466952-344e3b76-715b-4bf4-9695-710a094628f6.png">

2021-12-13 14:57 UTC, tmcconechy approved these changes

2021-12-14 10:12 UTC, andriivarhanov approved these changes

2021-12-14 16:07 UTC, merged