352 - IDS Error Page
infor-design/enterprise-wc pull request #461
Opened 2021-12-15 18:35 UTC by jmacaluso711

**Explain the details for making this change. What existing problem does the pull request solve?**
This PR adds the IDS Error page component

**Related github/jira issue (required)**:
closes #352 

**Steps necessary to review your pull request (required)**:
- Pull and run branch
- test http://localhost:4300/ids-error-page/ 
- compare to [enterprise](https://main-enterprise.demo.design.infor.com/components/error-page/example-index.html)
- test "Return" button closes the error page
- make sure there is sufficient test coverage

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2021-12-15 21:02 UTC, vivz753 commented on src/components/ids-error-page/ids-error-page.js
> +        <ids-empty-message icon="${!this.icon ? DEFAULT_ICON : this.icon}">
Consider using `this.icon ?? DEFAULT_ICON` instead of the ternary

2021-12-15 21:02 UTC, vivz753 commented on src/components/ids-error-page/ids-error-page.js
> +            ${!this.label ? 'Add Label' : this.label}
Same here. Consider using `this.label ?? 'Add Label'`

2021-12-15 21:02 UTC, vivz753 commented on src/components/ids-error-page/ids-error-page.js
> +            ${!this.description ? 'Add Description' : this.description}
And here

2021-12-15 21:03 UTC, vivz753 commented on src/components/ids-error-page/ids-error-page.js
> +            <span slot="text">${!this.buttonText ? 'Action' : this.buttonText}</span>
You know what I'm going to say

2021-12-15 21:21 UTC, vivz753 commented on src/components/ids-error-page/ids-error-page.js
> +    const emptyMessage = this.shadowRoot.querySelector('ids-empty-message');
Consider standardizing the use of `this.container`

2021-12-15 21:22 UTC, vivz753 commented on src/components/ids-error-page/ids-error-page.js
> +    const button = this.shadowRoot.querySelector('.action-button');
Same here for `this.container`

2021-12-15 21:23 UTC, vivz753 commented on src/components/ids-error-page/ids-error-page.js
> +    this.onEvent('touchstart', button, (e) => {
Is `touchstart` fired when the user first clicks, before releasing? I've had some issues where 'click' doesn't fire until after I lift my finger up off the mouse button

2021-12-15 21:24 UTC, vivz753 commented on src/components/ids-error-page/ids-error-page.js
> +    return `${label || ''} ${this.label || ''} ${this.description || ''}`;
Consider using `??` instead of `||`

2021-12-15 21:27 UTC, vivz753 submitted a review, later dismissed
Looks good! My comments are mostly just preferences in syntax, but if you choose not to go with them, the component will function mostly the same.

2021-12-15 21:50 UTC, tmcconechy requested changes
Just some minor things but overall looks good. In addition to the inline comments.

1. I noticed the old one doesnt animate on load maybe this one should also not animate
2. how do we change theme in the demo? I see in the percy image that the dark ICON is hard to see and I'm wondering if its the same as https://main-enterprise.demo.design.infor.com/components/error-page/example-index.html?theme=new&mode=dark so maybe we need to adjust that icon color in dark?

2021-12-15 21:50 UTC, tmcconechy commented on demos/ids-error-page/example.html
> +      description="SunSystems Configuration Manager access has been denied."
```suggestion
      description="Configuration Manager access has been denied."
```

Just thinking about removing specific names

2021-12-15 21:50 UTC, tmcconechy commented on src/components/ids-error-page/README.md
> +This example shows how to render a page in an IDS Error Page that shows an unknown error. Ideally its best to avoid these types of errors in your application but when an unexpected error occurs you c
```suggestion
This example shows how to render a page in an IDS Error Page that shows an unknown error. Ideally its best to avoid these types of errors in your application but when an unexpected error occurs you can use this component to render information about the error. The general use case is similar to a 40(x) error page.
```

2021-12-15 21:50 UTC, tmcconechy commented on src/components/ids-error-page/ids-error-page.d.ts
> +  /* label of te error page to be displayed */
```suggestion
  /* label of the error page to be displayed */
```

2021-12-15 21:50 UTC, tmcconechy commented on src/components/ids-error-page/ids-error-page.scss
> +// Error page styles
Maybe not needed?

2021-12-15 21:50 UTC, tmcconechy commented on src/components/ids-error-page/index.js
> +export { default } from './ids-error-page';
The index file isnt needed anymore after https://github.com/infor-design/enterprise-wc/pull/462
But I'll sync this up once the first of these is merged

2021-12-15 21:50 UTC, tmcconechy commented on test/ids-error-page/ids-error-page-func-test.js.snap
> +"<ids-overlay></ids-overlay><style nonce=\\"undefined\\">:host { background-color: transparent; }</style><ids-popup part=\\"modal\\" class=\\"ids-modal ids-error\\" type=\\"custom\\" position-style=\
Could set this to snap `ids-overlay.shadowRoot` (un-needed css and nonce)

2021-12-15 21:51 UTC, tmcconechy commented on demos/ids-error-page/example.html
> +    <ids-text font-size="12" type="h1">IDS Error Page</ids-text>
In this case maybe we dont need?

2021-12-16 19:47 UTC, jmacaluso711 commented
@tmcconechy
> how do we change theme in the demo? I see in the percy image that the dark ICON is hard to see and I'm wondering if its the same as https://main-enterprise.demo.design.infor.com/components/error-page/example-index.html?theme=new&mode=dark so maybe we need to adjust that icon color in dark?

I think this is handled in http://localhost:4300/ids-empty-message

@vivz753 I addressed your comments as well, thanks

2021-12-16 20:11 UTC, tmcconechy commented
@jmacaluso711 ok i see its the same on https://main-enterprise.demo.design.infor.com/components/emptymessage/example-widgets.html?theme=new&mode=dark&colors=0066D4 as http://localhost:4300/ids-empty-message

It looks better than i see in the percy image so i think we can leave that for now

2021-12-17 14:43 UTC, tmcconechy approved these changes

2021-12-17 15:33 UTC, andriivarhanov approved these changes

2021-12-17 15:49 UTC, danielortiz1982 commented on src/components/ids-error-page/ids-error-page.js
> +    return `${label || ''} ${this.label || ''} ${this.description || ''}`;
@vivz753 Could you possibly provide some more insight for @jmacaluso711 on this suggestion.

2021-12-17 16:11 UTC, merged