Refactoring: Abstract functionality from ids-list-view/builder into its own ids-sortable-mixin
infor-design/enterprise-wc pull request #464
Opened 2021-12-16 02:02 UTC by vivz753

**Explain the details for making this change. What existing problem does the pull request solve?**

Abstracts the sortable "drag and drop" functionality from `ids-list-view` and `ids-list-builder` into its own `ids-sortable-mixin`

The purpose of refactoring this is to allow modularity and usage of "swapping" `ids-draggable` elements on the DOM for other situations besides a list, i.e. `ids-tabs`

Added support for horizontal dragging (in consideration of tabs) in addition to vertical dragging (default).

**Related github/jira issue (required)**:

- Closes #399 

**Steps necessary to review your pull request (required)**:

 - https://localhost:4300/ids-list-view
 - https://localhost:4300/ids-list-builder

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [ ] A note to the change log.

2021-12-16 15:45 UTC, tmcconechy requested changes
Looks really great! Thanks @vivz753 

1. See inline suggestions
1. See tests/lint errors
1. on the example http://localhost:4300/ids-list-view - can we make it a http://localhost:4300/ids-list-view/sortable.html and:
  a. Can we make it have a drag icon (this could be added but the mixin perhaps)
  b. Can we make the background the page background on drag, i cant take a screen shot but fix the fact thats its transparent

For TODO Future or Now if you have an idea?
- keyboard support
- fire events on `sorted`

2021-12-16 15:45 UTC, tmcconechy commented on demos/ids-list-view/example.html
> +        <ids-list-view item-height="76" virtual-scroll="true" sortable>
Just for seperation of concerns/examples. And also as this isnt the most common use case. Maybe we can we make a new demo/ids-list-view/sortable.html example?

2021-12-16 15:45 UTC, tmcconechy commented on src/components/ids-list-view/ids-list-view.js
> +      this.attachDragEventListeners(); // for dragging list items
Can we do this in the connectedCallback inside the mixin code? That way less setup...

2021-12-16 15:45 UTC, tmcconechy commented on src/components/ids-list-view/ids-list-view.js
> +    return IdsStringUtils.injectTemplate(this.defaultTemplate, item);
Just FYI the exports are changing on https://github.com/infor-design/enterprise-wc/pull/462 back to the previous way. So when that gets merged we might have to change this again.

2021-12-16 15:45 UTC, tmcconechy commented on src/mixins/ids-sortable-mixin/README.md
> +1. Call `attachDragEventListeners()` as needed. Calling it once in `connectedCallback()` usually suffices, **but if your list is dynamic** (items get added/deleted/modified) **or the list dynamically
Again as above we could try to do this in the connectedCallback of the mixin to eliminate this setup step

2021-12-16 15:45 UTC, tmcconechy commented on src/mixins/ids-sortable-mixin/README.md
> +1. **[Optional]** Override `OnDragStart()`, `OnDrag()`, `OnDragEnd()`, `createPlaceholderNode()` accordingly if you need additional function calls to modify or style elements
One question: Is there an event that fires out for the component consumer so they can set/save the sorted items somehow?

2021-12-16 17:09 UTC, jmacaluso711 requested changes
Seeing a bunch of lint errors:
![Screen Shot 2021-12-16 at 12 08 39 PM](https://user-images.githubusercontent.com/1084735/146416961-d34e6f23-8b41-4c5f-adeb-5c5bff346b90.png)

2021-12-17 01:39 UTC, vivz753 commented on src/components/ids-list-view/ids-list-view.js
> +      this.attachDragEventListeners(); // for dragging list items
That's definitely possible, however I think leaving the programmer the option to call attachDragEventListeners() where they want makes more sense and is the modular way to go. What if the component needed to perform some logic check before attachDragEventListeners()? (i.e. making sure list items get rendered before attaching drag event listeners? I'm certain this could be an issue with scenarios with dynamic rendering like with virtual-scroll). Calling it inside the mixin's connectedCallback() would mean that component's super.connectedCallback() would bunch this setup call with all the connectedCallback() functions of other mixins + `ids-element`'s connectedCallback(), with no control or clarity over what gets ran first.

2021-12-17 01:40 UTC, vivz753 commented on src/components/ids-list-view/ids-list-view.js
> +    return IdsStringUtils.injectTemplate(this.defaultTemplate, item);
Sorry, can you explain to me again why stringUtils is better than using IdsStringUtils?

2021-12-17 01:43 UTC, vivz753 commented on src/mixins/ids-sortable-mixin/README.md
> +1. **[Optional]** Override `OnDragStart()`, `OnDrag()`, `OnDragEnd()`, `createPlaceholderNode()` accordingly if you need additional function calls to modify or style elements
Are you saying you want a 'sorted' signal fired after drag end? What do you mean set/save? Like return an array of the items if they wanted to export the list into some excel sheet or something? Or are you referring to the issue discussed previously about how virtual-scroll currently doesn't save the state when items are moved around?

2021-12-17 05:02 UTC, vivz753 commented
1. See my comment responses
2. Fixed lint errors
3. Separated example into sortable.html
  a. Are you saying you want it to have the dots on the left like how it is in ids-list-builder? If so, I would disagree and say that should not be included in the mixin. The mixin was solely for abstracting functionality of sorting, and adding specific CSS styles to it would be more coupling... If I add that CSS into the mixin, it will appear in tabs too, since this mixin was intended to be used for tabs.... and I don't think you want that... ?
  b. I don't really understand this, please elaborate what you mean by "make the background the page background on drag"?

I don't know what type of keyboard support would go well with this since it's "drag and drop". Can you give examples?

2021-12-17 14:54 UTC, tmcconechy commented on src/components/ids-list-view/ids-list-view.js
> +      this.attachDragEventListeners(); // for dragging list items
OK sounds good to me. I think the way to think about it is..

a. do you always need this setup when sortable is enabled? if so it would go in the mixin to reduce duplication
b. do you need to call it under some logic that could change in the component. if so it goes in the component

I thought it was a. But if you say it could be b. Then this seems good for now.

2021-12-17 14:59 UTC, tmcconechy commented on src/components/ids-list-view/ids-list-view.js
> +    return IdsStringUtils.injectTemplate(this.defaultTemplate, item);
Because of the changes we made on #301 soon this will not compile. We changed all the utils so that they are individual exported methods. This is intended to fix some duplication in the build output and assist with better code splitting. Also it will make it more consistent as it was done two ways before and now it cant be. (after thats merged soon)

See:
https://github.com/infor-design/enterprise-wc/pull/462/files#diff-2b47b7839d06c727e58038556e4b8e233084c484c929dd4b2de376ef0b5b737fL106

https://github.com/infor-design/enterprise-wc/pull/462/files#diff-da2443f86311737d564ac5748f4778e299669a56bff09e677f957f68d9a34b15R3

2021-12-17 15:01 UTC, tmcconechy commented on src/mixins/ids-sortable-mixin/README.md
> +1. **[Optional]** Override `OnDragStart()`, `OnDrag()`, `OnDragEnd()`, `createPlaceholderNode()` accordingly if you need additional function calls to modify or style elements
I think for now we could just emit a sorted event after the drag end  / sort is complete. Im not sure how they will save it yet maybe they need to change how they put the data in ect and not really our problem. So maybe just omit an event so the developer knows a sort finished and pass what we have (the list elements and any indexes ect) in the data.

2021-12-17 15:12 UTC, danielortiz1982 commented on demos/ids-list-view/sortable.js
> +xmlhttp.onreadystatechange = function onreadystatechange() {
This is great! However I would recommend using the `fetch()` instead of the `XMLHttpRequest ()` it's a better cleaner solution for the given task at hand. You will not need to check for status code and you do not need the `onreadystatechange`. It returns a promise and we can let the JS engine do it's thing in the background.

Fetch APi DOCS
https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch

2021-12-17 16:12 UTC, tmcconechy commented on demos/ids-list-view/sortable.js
> +xmlhttp.onreadystatechange = function onreadystatechange() {
Good idea - maybe we should standardize on `fetch` i use `XMLHttpRequest` in some examples too and should try to change to fetch someday

2021-12-17 16:21 UTC, tmcconechy commented
@vivz753 

>  Are you saying you want it to have the dots on the left like how it is in ids-list-builder? If so, I would disagree and say that > should not be included in the mixin. The mixin was solely for abstracting functionality of sorting, and adding specific CSS 
> styles to it would be more coupling... If I add that CSS into the mixin, it will appear in tabs too, since this mixin was intended to be used for tabs.... and I don't think you want that..

Ok you have a good point on tabs. I just suggested this because the drag dots icon is the indicator that you can drag it. So we put the icon on to show the behavior is there. Maybe you can just add it to the sortable example in the template so its specific to list view and in that css? 

> I don't really understand this, please elaborate what you mean by "make the background the page background on drag"?

I was able to stop in onDragend and get a screen shot:
![Screen Shot 2021-12-17 at 11 19 13 AM](https://user-images.githubusercontent.com/814283/146575403-404f200e-51da-4d14-aef7-8a5459d8cc07.png)

Im talking about the fact that the list is transparent so it looks wierd when you drag it. But the color can change in dark mode/ contrast ect so i think what you could do is use the same background colors as container https://github.com/infor-design/enterprise-wc/blob/main/src/components/ids-container/ids-container.scss on the list items or come up with something so its not transparent text on text when moving?

> I don't know what type of keyboard support would go well with this since it's "drag and drop". Can you give examples?
We can add this as a TODO? Nut its something like
- tab to the icon
- hit enter/space to activate drag mode
- move with arrow keys

Definitely out of scope for now but something we will need in the future to be accessible. https://www.barrierbreak.com/can-drag-and-drop-be-made-accessible-yes-it-can-be-in-different-ways/

2021-12-17 16:59 UTC, vivz753 commented on src/mixins/ids-sortable-mixin/README.md
> +1. **[Optional]** Override `OnDragStart()`, `OnDrag()`, `OnDragEnd()`, `createPlaceholderNode()` accordingly if you need additional function calls to modify or style elements
Let's be more specific about the signal being fired here. I think a better event name to fire would be 'swapped', because technically user can drag an item around, but unless they go far up/down enough, nothing actually changes. And we don't want to fire events esp when nothing changed. My suggestion is:

- fire 'swapped' when a swap() is successfully executed

Currently, the data list doesn't get updated. Only the DOM reflects the order correctly. Will have to open a new issue to implement this.

2021-12-17 17:02 UTC, vivz753 commented on demos/ids-list-view/sortable.js
> +xmlhttp.onreadystatechange = function onreadystatechange() {
This is code that I just copied from other examples so maybe it'd be better to have a separate PR that changes all `XMLHttpRequest()` to `fetch()` for all examples in the demo folder. I'll make a separate issue and assign that to myself.

2021-12-17 17:08 UTC, vivz753 commented on src/components/ids-list-view/ids-list-view.js
> +    return IdsStringUtils.injectTemplate(this.defaultTemplate, item);
Thx. It'll probably cause a merge conflict for you. Can change it back so there's less trouble for you

2021-12-17 17:58 UTC, tmcconechy commented on src/components/ids-list-view/ids-list-view.js
> +    return IdsStringUtils.injectTemplate(this.defaultTemplate, item);
Cool, that should work but be aware i did merge it in. So you might need to tweak it as you merge main on. let me know if you need help with the merge or have a question

2021-12-17 17:59 UTC, tmcconechy commented on src/mixins/ids-sortable-mixin/README.md
> +1. **[Optional]** Override `OnDragStart()`, `OnDrag()`, `OnDragEnd()`, `createPlaceholderNode()` accordingly if you need additional function calls to modify or style elements
yes good idea. i wasnt 100% sure what i wanted i just know it needs an event. I think swapped is fine. And it would be good if the data gets updated then you can send a ref to that in the event. If you would like to punt to a new issue. please do.

2021-12-17 18:06 UTC, vivz753 commented
Got it. Added the dragging dots to ids-list-view.scss and background-color of list items now match container background.

Am hoping this gets approved soon. Jon and I were planning to pair program and start the ids-swap-list but need this mixin. Thanks to all reviewing this

SIDE NOTE: Regarding keyboard accessibility, wouldn't it be better to just make up/down buttons that call swap()? Similar to the toolbar in listbuilder. I think that makes more sense to put those functions in buttons if we're trying to "emulate" drag and drop through keyboard. Technically not drag and drop, just give the ability to swap through keyboard

2021-12-17 19:48 UTC, vivz753 commented on src/mixins/ids-sortable-mixin/README.md
> +1. **[Optional]** Override `OnDragStart()`, `OnDrag()`, `OnDragEnd()`, `createPlaceholderNode()` accordingly if you need additional function calls to modify or style elements
Just added it to the existing issue #442

2021-12-17 20:38 UTC, tmcconechy reviewed
I only see one issue now worth solving is one you can see in the percy images

https://percy.io/00aaa841/enterprise-wc/builds/14642716/changed/827855238?browser=chrome&browser_ids=20&subcategories=unreviewed%2Cchanges_requested&viewLayout=side-by-side&viewMode=new&width=1280&widths=375%2C1280

But if i change the theme in the page it looks good? Any ideas why? It looks like maybe there is a slight delay on the color change? Worst case we can try 
```
await page.waitForTimeout(200);
```

Or we could add the background as a class that only is added when dragging?

2021-12-18 01:46 UTC, vivz753 commented
I'm not sure why it was doing that for the Percy tests. John & I tested locally too and it was fine how it looked. I know for sure it happened because of the background-color I added to the list items per your request. I was able to solve it though by moving bg-white from the default css styles into [mode='light']

2021-12-20 14:40 UTC, tmcconechy submitted a review, later dismissed

2021-12-20 15:50 UTC, jmacaluso711 reviewed
The draggable list-view item is transparent on first load. It's not until you switch themes does the bg render as white. However, I'd be for approving this and maybe we addressing the bg color issue in #368 ?

![Screen Shot 2021-12-20 at 10 41 21 AM](https://user-images.githubusercontent.com/1084735/146794633-f577046d-ecef-430a-b35a-9d90f53629f4.png)

@vivz753 @tmcconechy

2021-12-20 17:35 UTC, tmcconechy commented
Up to you guys if you want to do it later thats fine with me?

2021-12-20 17:55 UTC, jmacaluso711 requested changes

2021-12-20 17:55 UTC, jmacaluso711 commented on src/components/ids-list-view/ids-list-view.scss
> +  }
@vivz753 -- If you put the bg-color on `ids-draggable[is-dragging]` it should take care of the issue

2021-12-20 19:25 UTC, vivz753 commented on src/components/ids-list-view/ids-list-view.scss
> +  }
is `[is-dragging]` a css selector for an event fired? 

I just added `background-color: white;` in `ids-draggable` and it worked as well. Let's see if this passes the percy test

2021-12-20 19:36 UTC, jmacaluso711 commented on src/components/ids-list-view/ids-list-view.scss
> +  }
Looks like it's an attr that gets added to ids-draggable when the dragging event is firing

2021-12-20 19:52 UTC, vivz753 commented
No disruptive changes on the percy screenshots! Ready for approval @tmcconechy @jmacaluso711

2021-12-20 20:38 UTC, jmacaluso711 approved these changes
🍌

2021-12-20 20:45 UTC, tmcconechy approved these changes

2021-12-20 20:45 UTC, merged