265 card selection
infor-design/enterprise-wc pull request #470
Opened 2021-12-21 18:26 UTC by jeffwa428

**Explain the details for making this change. What existing problem does the pull request solve?**

Add selection mixin in order to make item/card seletable, both single/multiple selection.
Here, added selection-mixin to `ids-card` so that card can be selectable.
`ids-card/selection.html` for example.

**Related github/jira issue (required)**:

Closes https://github.com/infor-design/enterprise-wc/issues/265

**Steps necessary to review your pull request (required)**:

- Go to http://localhost:4300/ids-card/selection.html
- Try single/multiple selection for the cards
- See https://main-enterprise.demo.design.infor.com/components/cards/example-single-select.html and https://main-enterprise.demo.design.infor.com/components/cards/example-multi-select.html

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [ ] A note to the change log.

2021-12-21 22:03 UTC, tmcconechy requested changes
This is a good start.. Just some edits see inline. 

Overview:

- lets call the settings selection and selected instead
- add test for the event firing
- separate examples
- when selecting the card moves 2px because the border is added
- css changes broke the layout of cards on http://localhost:4300/
- on the multiselect one the title is in the wrong place

<img width="260" alt="Screen Shot 2021-12-21 at 5 03 01 PM" src="https://user-images.githubusercontent.com/814283/147003327-655e6ead-d4fd-4cdd-82df-4308ee645d0c.png">

2021-12-21 22:03 UTC, tmcconechy commented on src/components/ids-card/ids-card.js
> +    this.triggerEvent('selectionchanged', this, {
Can we add a test for this? Also could it somehow be put in the mixin code?

2021-12-27 01:10 UTC, jeffwa428 commented on src/components/ids-process-indicator/ids-process-step/ids-process-step.scss
>  @import '../../../core/ids-base';
I got bunch of issues from linting. So I fixed that. I am not sure how this was pushed to master.

2021-12-27 14:29 UTC, tmcconechy commented on src/components/ids-process-indicator/ids-process-step/ids-process-step.scss
>  @import '../../../core/ids-base';
Possibly you created the branch before we made a bunch of changes on another PR thats also been merged. I'll check this but it probably wasn't your fault 😄

2021-12-27 17:08 UTC, tmcconechy requested changes
I took a look and see a couple more improvements we could make

1. The border looks a bit different stylistically (is it 3px now with some grey in it?) I compared with https://main-enterprise.demo.design.infor.com/components/cards/example-multi-select.html

![Screen Shot 2021-12-27 at 12 02 44 PM](https://user-images.githubusercontent.com/814283/147492741-aa05942a-2f9c-4310-9acb-effa4f5a7803.png)

1. The checkbox on multiple-selection doesn't seem centered vertically

1. We could try to make the example look like https://main-enterprise.demo.design.infor.com/components/cards/example-multi-select.html with ids-text for the elements - i think we could use https://main.wc.design.infor.com/ids-summary-field/ but add a vertical option to put them next to each other. Im ok with leaving this as is and this can be an idea for later tho.

1. If not the previous one we could just remove the card-header and have no contents for now and put that in for a TODO for later. As i dont think that the cards will have headers in these scenarios.

3. The c

2021-12-27 17:14 UTC, danielortiz1982 commented on src/components/ids-card/ids-card.js
> +    this.onEvent('click', this, (e) => {
This is a nice solution, however I would recommend adding this to it's own function. We want to keep the handleEvents clean without too much business logic.

2021-12-27 17:20 UTC, danielortiz1982 commented on src/components/ids-card/ids-card.js
> +        for (const elem of cardElements) {
Just a preference thing for me, if you spread the array you can do a forEach and shorten this statement to return the setAttribute something like, `[... cardElements].forEach( (elem) => elem.setAttribute(attributes.SELECTED, false))`. This is just a preference of mine I think it makes for a cleaner pattern.

2021-12-27 17:24 UTC, danielortiz1982 requested changes
Remove business logic from handleEvents, Add logic for `this.selection === 'single')` into it's own function.

2022-01-03 15:43 UTC, tmcconechy approved these changes

2022-01-03 16:39 UTC, jmacaluso711 approved these changes

2022-01-03 17:06 UTC, merged