463 - Fix height issue on trigger field
infor-design/enterprise-wc pull request #474
Opened 2021-12-23 02:07 UTC by jeffwa428

**Explain the details for making this change. What existing problem does the pull request solve?**

Fix height issue from "TRIGGER FIELD - FIELD HEIGHTS (HEIGHT)" example on https://main.wc.design.infor.com/ids-trigger-field/test-sizes.html

**Related github/jira issue (required)**:

Closes https://github.com/infor-design/enterprise-wc/issues/463

**Steps necessary to review your pull request (required)**:

- Go to http://localhost:4300/ids-trigger-field/test-sizes.html
- Look at TRIGGER FIELD - FIELD HEIGHTS (HEIGHT) section
- Check height is working correctly

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [ ] A note to the change log.

2021-12-23 14:34 UTC, tmcconechy requested changes
This looks great! Only issues i see are

- in the xs input the text sites a little bit two high (maybe 1px?)
- a few tests seem to be broken (see output)

2021-12-27 17:15 UTC, tmcconechy requested changes
Sorry i see one more issue. If you compare http://localhost:4300/ids-input/test-sizes.html and  http://localhost:4300/ids-trigger-field/test-sizes.html there is a difference on the "Compact" example.

The way it should work is `compact="true"` should look the same sizes and padding as "Extra Small (compact)"

So just need a change to make that happen :)

2021-12-27 17:22 UTC, vivz753 commented
^ agree with Tim!

2021-12-28 14:48 UTC, tmcconechy approved these changes

2021-12-28 15:24 UTC, andriivarhanov approved these changes

2021-12-28 20:00 UTC, merged