444 - Ids Month View Component
infor-design/enterprise-wc pull request #481
Opened 2021-12-28 16:23 UTC by andriivarhanov

**Explain the details for making this change. What existing problem does the pull request solve?**
This PR adds ids-month-view component that provides calendar view with navigation

**Related github/jira issue (required)**:
Closes #444  

**Steps necessary to review your pull request (required)**:
- pull the branch and run the app
- go to main example http://localhost:4300/ids-month-view shows specified date
  - shows specified date
  - click to some day
  - click to a day not in the shown month
  - check console if dayselected event is firing with selected date
  - click to next/prev/today button
  - resize browser window or change container/grid cell size to less than 600px, see if compact view is triggering 
- go to current month example http://localhost:4300/ids-month-view/current-month.html, shows current date calendar and compact view
- compare to the design
  -  full size view https://main-enterprise.demo.design.infor.com/components/monthview/example-index.html
  - compact view https://main-enterprise.demo.design.infor.com/components/monthview/test-inpage-variations.html
- run tests `npm run test -- ids-month-view`
- run coverage `npm run test:coverage`
- check `coverage/components/ids-month-view/index.html` html file in browser
- check `components/ids-month-view/README.md`
- check standalone css http://localhost:4300/ids-month-view/standalone-css.html

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
~- [ ] A note to the change log.~

2022-01-03 16:34 UTC, tmcconechy requested changes
Looks like an excellent first start!!! Just have some questions about.

1. The compact vs mobile vs in page mode (but this is maybe ok for now)
2. Some of the renamed firstDayOfWeek
3. If this is the best approach for umalqura or not? (it might be but suggesting an option)

Some minor inline comments

2022-01-03 16:34 UTC, tmcconechy commented on demos/ids-month-view/index.yaml
> +  - link: current-month.html
Should we add range-in-month?

2022-01-03 16:34 UTC, tmcconechy commented on src/utils/ids-date-utils/ids-date-utils.js
> +export function umalquraToGregorian(year, month, day, hours = 0, mins = 0, secs = 0, mills = 0) {
This might be the only way to do it? But i was thinking that we could do it with `locale.formatNumber(2019, { locale: 'ar-SA' })` and then see about converting the digits to english or arabic as an option....

2022-01-04 16:09 UTC, andriivarhanov commented
@tmcconechy thanks for the feedback
> 1. The compact vs mobile vs in page mode

I like `compact` attribute more, and it already exists in the ids-attributes. The only reason I did it with `resizeObserver` because in the original issue https://github.com/infor-design/enterprise-wc/issues/444 there is the question
> It might be possible to combine these into just one thing where it takes the parent size only?

it will not take a lot to change it to `compact` attribute tho

> 2. Some of the renamed firstDayOfWeek

I was thinking I can safely rename some date utils while I'm working on it since they only used in week-vew and month-view components. Similarly to recent change from date utils like `add` -> `addDate`, `isToday` -> `isTodaysDate`

> 3. If this is the best approach for umalqura or not? (it might be but suggesting an option)

The implementation is pretty much the same as in the original, I did some research and I didn't find a better solution. The key changes are:
 - The original uses locale calendar conversions to get number of days in a month vs this one uses last day of month date util
- I moved most of the umalqura calculations to date utils

I will try `locale.formatNumber` as you suggested

2022-01-04 16:55 UTC, tmcconechy commented
ok thanks @andriivarhanov sounds good then. Lets try to put it against a compact option so we have both behaviors. Then leave the util renames as they are fine and consistent. Feel free to try the locale.formatNumber but if its not working well we can keep the new code you added.

2022-01-06 00:04 UTC, andriivarhanov commented on demos/ids-month-view/current-month.html
> +  <ids-text font-size="12" type="h1">Month View Current Month Compact</ids-text>
I've added `compact` attribute and removed resize observer. The border you mentioned probably is part of the popup
![image](https://user-images.githubusercontent.com/5204821/148307140-9853bb50-3f93-4fbc-af6c-cc0383f7bc1d.png)

2022-01-06 00:04 UTC, andriivarhanov commented on src/utils/ids-date-utils/ids-date-utils.js
> +export function umalquraToGregorian(year, month, day, hours = 0, mins = 0, secs = 0, mills = 0) {
No luck with formatNumber, getting formatted number, you can check it if set latin as numbering system
```
locale.formatNumber(2019, { locale: 'ar-SA', numberingSystem: 'latn' })
'2,019.00'
```
I've managed to simplify only `gregorianToUmalqura` util, I can't figure something out with  `umalquraToGregorian`

2022-01-06 14:18 UTC, tmcconechy approved these changes

2022-01-07 18:57 UTC, EdwardCoyle approved these changes

2022-01-10 14:38 UTC, merged