332 update password functionality
infor-design/enterprise-wc pull request #482
Opened 2021-12-29 19:34 UTC by Jah25

**Explain the details for making this change. What existing problem does the pull request solve?**

Change updates password type input fields to include a capslock indicator and allow for password visibility to be toggleable

**Related github/jira issue (required)**:

Closes [#332](https://github.com/infor-design/enterprise-wc/issues/332)

**Steps necessary to review your pull request (required)**:

1) run the changes locally
2) go to http://localhost:4300/ids-input
3) at the bottom of the page toggle the password visibility
4) turn on capslock and type in the password field, an icon should appear

**Included in this Pull Request**:
- [X] An e2e or functional test for the bug or feature.
- [ ] A note to the change log.

2022-01-03 16:24 UTC, andriivarhanov requested changes
looks good, just a couple of items to fix:
  - comparing to the design https://main-enterprise.demo.design.infor.com/components/input/example-password.html?theme=new&mode=dark :
    - show/hide button should be uppercase
    - show/hide button should not be focusable or have focusable styles
    - please check light/dark/contrast theme show/hide button color
- please add new attributes/properties to `ids-input.d.ts` file
- when caps lock is enabled and you toggle revealable text option - icon/button changes order
![image](https://user-images.githubusercontent.com/5204821/147953890-7f507504-8fb5-4301-8f08-15e468381db2.png)
- please add comments to any new getters/setters and functions in ids-input

2022-01-03 16:24 UTC, andriivarhanov commented on src/components/ids-input/ids-input.js
> +  passwordVisibilityHandler() {
please make the function private

2022-01-03 16:40 UTC, Jah25 commented
@andriivarhanov shouldn't the show/hide input be focusable since it's and input and changes the password field from a non screen readable to a screen readable format?

2022-01-03 16:42 UTC, tmcconechy requested changes
Looks good. Just some questions / comments inline like reveal vs revealable-password?

Also in the example can we move it to under the IDS INPUT - SIZES section. I think that would fill out the page a bit more instead of making it scroll.

2022-01-03 16:42 UTC, tmcconechy commented on src/components/ids-input/ids-input.js
> +      attributes.PASSWORD_VISIBLE
Can we keep this in alpha order?

2022-01-03 16:42 UTC, tmcconechy commented on src/components/ids-input/ids-input.js
> +  get revealableText() {
Pls add some JsDoc comments - will probably need this for docu generation

2022-01-03 16:42 UTC, tmcconechy commented on src/components/ids-input/ids-input.js
> +      this.onEvent('keyup.capslock', this.input, (event) => {
This could get called twice i think. Might need..
```
this.offEvent('keyup.capslock', this.input);
this.onEvent('keyup.capslock', this.input, ...
```

2022-01-03 16:42 UTC, tmcconechy commented on src/components/ids-input/ids-input.js
> +      this.onEvent('click.showhidepassword', showHidePasswordElem, () => {
Same here in case called more than once. Also check all methods/setters/getters do have a JSdoc even if private

2022-01-03 16:42 UTC, tmcconechy commented on src/components/ids-input/ids-input.scss
> +  #caps-lock-indicator {
Can we use class vs ID selectors for the css?

2022-01-03 16:42 UTC, tmcconechy commented on src/core/ids-attributes.js
> +  REVEAL: 'reveal',
I like calling it revealable-text but I think maybe we didnt need both options here. But about reveal-password instead?

2022-01-03 17:08 UTC, Jah25 commented on src/core/ids-attributes.js
> +  REVEAL: 'reveal',
so reveal being there is a mistake on my part I refactored the name of the attribute from reveal to revealable-text to be more specific but forgot I had added reveal in the first place and didn't want to alter a pre-existing attribute. So I can just pull reveal entirely.

as for revealable-text, I was trying to make it more distinct from password-visible so there wasn't confusion between the too but I'm pretty open to whatever naming convention you think makes sense

2022-01-03 17:09 UTC, tmcconechy commented on src/core/ids-attributes.js
> +  REVEAL: 'reveal',
ok yeah looked like a dup. I guess i like reveal-password as you are revealing the password not the text? But im not that fixed on that point. I do like either better than just reveal?

2022-01-03 17:11 UTC, andriivarhanov commented
@Jah25 I think it should be focusable, I just noticed it's not in the original implementation and added it to the list. 
Let's ask @tmcconechy should show/hide button be focusable?

2022-01-03 18:01 UTC, tmcconechy commented
@Jah25 and @andriivarhanov I think maybe we should work it into the new setting `tabbable` i.e. if thats on you can tab to it if not you cant. Same with caps lock button. It wasn't this way before but that was done before we did some accessibility and testing that ultimately you should be able to tab to it for the best accessibility.

2022-01-10 15:35 UTC, Jah25 commented
> 

When I was looking into updating this I was able to find the tabbable attribute in the project but I couldn't find anything that was using it. Is it an in progress feature?

2022-01-10 15:38 UTC, tmcconechy commented
@Jah25 I do see it being used in a few places (lookup, colorpicker, toolbar, search field).. search: `attributes.TABBABLE`

2022-01-10 16:44 UTC, Jah25 commented
> @Jah25 I do see it being used in a few places (lookup, colorpicker, toolbar, search field).. search: `attributes.TABBABLE`

okay it looks like this was an issue with my VScode search locally, I did the search nothing showed up but with a restart I'm seeing results.

2022-01-10 16:52 UTC, tmcconechy commented
I've been seeing a bug with it too - like when i have the changelog or bigger text files open it doesnt work

2022-01-14 19:24 UTC, Jah25 commented
@tmcconechy I added the tabbing functionality but it wound up being more of a separate story because it impacted things other than the show/hide functionality, should I add an item for tracking purposes or just move on?

2022-01-14 19:28 UTC, tmcconechy commented
@Jah25 you can just move on as at this stage a second issue for tracking wouldnt be used for anything if its done now.

2022-01-14 19:49 UTC, tmcconechy approved these changes
Looks all good to me now @Jah25 Thanks!
I just reorganized the input page to distribute the columns better. Will need visual test approvals.

2022-01-17 09:19 UTC, andriivarhanov approved these changes

2022-01-18 14:19 UTC, tmcconechy approved these changes

2022-01-18 14:19 UTC, merged