422 - Added IdsPagerMixin to IdsDataGrid
infor-design/enterprise-wc pull request #483
Opened 2021-12-31 04:49 UTC by clayinfor

**Explain the details for making this change. What existing problem does the pull request solve?**

Adds the IdsPagerMixin (and is inherited by IdsDataGrid web component): 

```html
<ids-data-grid
  id="data-grid-1"
  row-selection="multiple"
  label="Books"
  row-height="md"
  pagination="client-side"
  page-number="1"
  page-size="50"
>
</ids-data-grid>
```

**Related github/jira issue (required)**:

Closes https://github.com/infor-design/enterprise-wc/issues/422
See [Legacy Datagrid with Paging](https://main-enterprise.demo.design.infor.com/components/datagrid/example-paging-client-side.html)

**Steps necessary to review your pull request (required)**:

1. Checkout this branch: `422-data-grid-add-paging`
2. Run: `nvm use`
3. Run: `npm install`
4. Run: `npm run test data-grid-func`
4. Run: `npm run start:watch`
5. Go to and test:  http://localhost:4300/ids-data-grid/pagination-client-side.html
6. See [Legacy Datagrid with Paging](https://main-enterprise.demo.design.infor.com/components/datagrid/example-paging-client-side.html)

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [ ] A note to the change log.

2022-01-03 16:05 UTC, danielortiz1982 commented on demos/ids-data-grid/pagination-server-side.js
> +      setTimeout(() => {
This is a nice solution, however it's somewhat of an anti pattern having a setTime inside a Promise. You can remove the the promise and SetTime and use just the async and await pattern. The data will have to moved into a flat json file. Doing a fetch on that static json will return a promise with the data, this should be enough to simulate a server response.

2022-01-03 16:52 UTC, tmcconechy requested changes
Looks really great. Just a few things i noticed:

**http://localhost:4300/ids-data-grid/pagination-client-side.html**
- the text is a bit cut off. before we had this dynamically size (in case its like 1000 pages)

<img width="306" alt="Screen Shot 2022-01-03 at 11 44 49 AM" src="https://user-images.githubusercontent.com/814283/147956747-379d8670-5e19-49e3-bceb-bf2cfd0e8edf.png">

- the dropdown on the page size isnt using the style with the arrow pointer. i.e. instead of:
<img width="261" alt="Screen Shot 2022-01-03 at 11 44 57 AM" src="https://user-images.githubusercontent.com/814283/147956801-6fd27e89-5fd4-4c6c-8c6d-1dbf1332cbfc.png">
should be:
<img width="76" alt="Screen Shot 2022-01-03 at 11 45 03 AM" src="https://user-images.githubusercontent.com/814283/147956877-36ff6f20-f858-4e8b-bec8-fb2f6d01f9ca.png">
- Also when changing the page size 
- we will have to do some something with the auto fit option (so it sizes to the bottom of the page with the pager) but it appears this option is not working at the moment to size to bottom of the entire page container
http://localhost:4300/ids-data-grid/auto-fit.html


**http://localhost:4300/ids-data-grid/pagination-standalone.html**
- can we make this fire the events in the console so you can see the pager is responding?

**http://localhost:4300/ids-data-grid/pagination-server-side.html**
- could start out on 25 or 10 page size so it is showing the behavior without changing page size

2022-01-03 16:53 UTC, tmcconechy commented on demos/ids-data-grid/pagination-server-side.js
> +      setTimeout(() => {
Also removing that may make the tests a bit easier (percy/e2e doesnt like these delays)

2022-01-03 16:59 UTC, tmcconechy requested changes
A couple more things im wondering about...

2022-01-03 16:59 UTC, tmcconechy commented on src/components/ids-data-grid/ids-data-grid.d.ts
> +  pagination: 'standalone' | 'client-side' | 'none';
server-side too?

2022-01-03 16:59 UTC, tmcconechy commented on src/components/ids-pager/README.md
> +`start` and `end` slots allow you to position content to the left or the right side of the pager panel. If no slot is provided, the child-contents of the pager component will be automatically inserte
I think i prefer having a named component instead of just an unnamed div? Unless this is the only way? Or what was the purpose of this change?

2022-01-03 16:59 UTC, tmcconechy commented on src/mixins/ids-pager-mixin/TODO.md
> +- [ ] Add support for IdsBlockGrid
```suggestion
- [ ] Add support for IdsBlockGrid
- [ ] Add support for IdsListView
```

2022-01-04 14:05 UTC, clayinfor commented on src/components/ids-pager/README.md
> +`start` and `end` slots allow you to position content to the left or the right side of the pager panel. If no slot is provided, the child-contents of the pager component will be automatically inserte
I didn't really want to delete named sub-component, but there was some other logic that was in place just to properly position this sub-component and I felt it was a bit over-engineered.  You can see in the code-changes that I deleted that extra code. 

Another thing is, I think having this extra `ids-page-section` sub-component adds extra cognitive-load (i.e. need-to-know) to the end-users of the `ids-pager` component but with little added-value.  I replaced `ids-page-section` with `div` in some places for expediency, but an end-user could use something more semantic like the `section` element with a slot-name... or whatever they think is best for their use-case.

2022-01-04 14:11 UTC, clayinfor commented on src/components/ids-pager/README.md
> +`start` and `end` slots allow you to position content to the left or the right side of the pager panel. If no slot is provided, the child-contents of the pager component will be automatically inserte
Here is some of what I was able to delete once `ids-pager-section` was dropped:

https://github.com/infor-design/enterprise-wc/pull/483/files#diff-7f1a191e2c6e884cf5c47ca81bc5b1122b15abaf97256c22d7a0578ec8bad783L16

https://github.com/infor-design/enterprise-wc/pull/483/files#diff-934358cb4efcfba5d5c677ef80b35bd7426ff2618d91d3cdbee6ec84e4e99517L225

https://github.com/infor-design/enterprise-wc/pull/483/files#diff-934358cb4efcfba5d5c677ef80b35bd7426ff2618d91d3cdbee6ec84e4e99517L277

2022-01-04 14:24 UTC, tmcconechy commented on src/components/ids-pager/README.md
> +`start` and `end` slots allow you to position content to the left or the right side of the pager panel. If no slot is provided, the child-contents of the pager component will be automatically inserte
Ok i see - yeah i guess removing the need for the MutationObserver for a slot makes sense. Just wanted to check the justification. I guess it was just the raw div throwing me off. Maybe it could be an HTML `<section>` element? Just for further semantics.

2022-01-17 22:47 UTC, clayinfor commented
Hey @tmcconechy, I think this is finally good to go... it just needs an approvals on the Percy tests.

One thing, I wasn't able to get the tooltip wedge to appear on the page-size popup.  I tried to resolve it, but couldn't ,so I've decided to revisit... I think it has to do with the ids-popup-menu appearing in ids-pager's slot, as opposed to it's shadow root... this is tripping up the `getClosestRootNode()` helper function.

2022-01-18 14:17 UTC, tmcconechy commented
@clayinfor the only thing i do see is looks like in the percy images that the tree doesnt load and also some borders are missing on http://localhost:4300/ids-data-grid/list-style.html

But when i try the live page it seems fine. Maybe push some something to rerun?

2022-01-18 14:18 UTC, tmcconechy commented on demos/ids-data-grid/pagination-client-side.html
> +  <ids-text font-size="12" type="h1">Data Grid - client-side</ids-text>
```suggestion
  <ids-text font-size="12" type="h1">Data Grid - Paging Client Side</ids-text>
```

2022-01-18 14:45 UTC, tmcconechy approved these changes

2022-01-18 15:25 UTC, danielortiz1982 approved these changes
This PR looks great @clayinfor good job replacing XMLHttpRequest with the fetch api! 👍

2022-01-18 15:29 UTC, merged