257 - Add selection to block grid
infor-design/enterprise-wc pull request #485
Opened 2022-01-07 14:22 UTC by jeffwa428

**Explain the details for making this change. What existing problem does the pull request solve?**

Add new features to block grid
- Add selection (single/multiple) to block grid by using selection mixin

**Related github/jira issue (required)**:

Closes https://github.com/infor-design/enterprise-wc/issues/257

**Steps necessary to review your pull request (required)**:
- Go to http://localhost:4300/ids-block-grid/single-selection.html for single selection
- Go to http://localhost:4300/ids-block-grid/multiple-selection.html for single selection
- Should have feature of single/multiple selection from this, https://main-enterprise.demo.design.infor.com/components/blockgrid

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [ ] A note to the change log.

2022-01-07 16:49 UTC, tmcconechy requested changes
Nice @jeffwa428 everything looks to be working well but a couple notes/suggestions.

1. can we add tests for this functionality https://github.com/infor-design/enterprise-wc/tree/main/test/ids-block-grid
2. can we make the keyboard work as before (tab to the block (notice it seems to have a double tab stop) and space to select)
3. can we log the events in the console in the example
4. seems to be missing mixed mode
5. also on the issue there are two additional points this only solves one of them in the checks so this doesnt close the issue but its fine to do more than one PR for it. just have to look at the other two points on an additional PR

Thanks!!

2022-01-10 15:57 UTC, deep7102 commented
Looks good!!!
only one thing is confuseing `selection` api setting. Currently it's on "ids-block-grid-item" level. which means user can  do single and multiple type in same block-grid. I think it should be only one type selection on whole block-grid and it should be set on  its component level (`ids-block-grid`) not on each item.

2022-01-11 15:01 UTC, tmcconechy commented
Yeah i agree with that @deep7102 - @jeffwa428 can we put the selection setting up on the parent `ids-block-grid`

2022-01-11 15:08 UTC, jeffwa428 commented
Okay, I will implement that.

2022-01-21 18:00 UTC, tmcconechy commented on src/components/ids-block-grid/ids-block-grid-item.scss
> +  max-width: 300px !important;
Any way to do this without !important; by adjusting the rules. we try to avoid this.

2022-01-21 18:09 UTC, tmcconechy requested changes
Just some minor things I can see inline above. But also one problem with the keyboard which almost all works fine. Try tabbing and then shift-tab to reverse tabbing and the shift-tab isnt working correctly

2022-01-21 18:09 UTC, tmcconechy commented on src/core/ids-attributes.js
> +  PRE_SELECTED: 'pre-selected',
think this is spelled `preselected`

2022-01-25 01:06 UTC, jeffwa428 commented on src/components/ids-block-grid/ids-block-grid-item.js
> +    this.listen(['Tab'], this, (e) => {
I think we will need keyboard handler because we need to handle tab manually for mixed selection.
In mixed selection, each block-grid-item has 2 steps, first it will set focus on element and second it will set focus on checkbox.

2022-01-25 14:17 UTC, tmcconechy commented on src/components/ids-block-grid/ids-block-grid-item.js
> +    this.listen(['Tab'], this, (e) => {
Right but did you try to simple set the tabindex and let it use the DOM order? i can give it a try to confirm...But in the old version it did work this way..

block -> tabindex="0"
checkbox -> already has a tabindex

2022-01-25 14:49 UTC, tmcconechy commented on src/components/ids-block-grid/ids-block-grid-item.js
> +    this.listen(['Tab'], this, (e) => {
Yeah i see the issue - ok this i guess is the best solution for now. Approving!

2022-01-25 14:49 UTC, tmcconechy approved these changes

2022-01-25 15:21 UTC, EdwardCoyle approved these changes

2022-01-25 16:08 UTC, merged