439 - Add filtering capability to IdsAppMenu
infor-design/enterprise-wc pull request #495
Opened 2022-01-19 22:23 UTC by EdwardCoyle

**Explain the details for making this change. What existing problem does the pull request solve?**
This PR enables the filter functionality of IdsAppMenu similar to a feature from the 4.x Application Menu:
- Created an app menu style for IdsSearchField
- Added an IdsSearchField feature that allows an optional callback to be provided, running whenever the search field's value is changed
- Implemented `hidden-by-filter` and `child-filter-match` visual states into IdsAccordionHeader
- Implemented filter functionality of an IdsAppMenu's IdsAccordion when it contains both a slotted IdsAccordion and IdsSearchField

**Related github/jira issue (required)**:
Closes #439 

**Steps necessary to review your pull request (required)**:
- Pull/Build/Run
- Open http://localhost:4300/ids-app-menu
- Open the App Menu and focus the search field.
- Type "Re".  One header and two sub-headers should match the filter. "Employee" should be displayed but dimmed out, since it doesn't match the filter but its children do.
- Clear the filter and see that all accordion items are present.
- Try various filter and expand/collapse combinations to make sure they all work when the filter is applied
- Check http://localhost:4300/ids-app-menu/test-sandbox.htm, making sure filtering works there as well.
- All new tests should pass
- Docs/Types for App Menu and Search Field are updated

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2022-01-20 16:21 UTC, danielortiz1982 requested changes
Remove unnecessary map and move logic into filter as discuss.

2022-01-21 18:26 UTC, tmcconechy reviewed
This is really well done 💯 
Willing to approve but a couple of suggestions added. 

In terms of functionality could not find any issues but if you are on http://localhost:4300/ids-app-menu/test-sandbox.html and type "F" there is a bit of a darker "gap" but not sure if this can be avoided.

<img width="320" alt="Screen Shot 2022-01-21 at 1 25 55 PM" src="https://user-images.githubusercontent.com/814283/150580504-87faff1a-3773-4335-8b9f-a8a0fde0076e.png">

2022-01-21 18:26 UTC, tmcconechy commented on test/ids-header/ids-header-percy-test.js
> +    await waitForPageLoad(url, 'dark', 30);
Instead of a new util couldnt you just add `waitForTimeout`

```
await page.goto(url, { waitUntil: ['networkidle2', 'load'] });
await page.waitForTimeout(30); // approx. time for a theme to show
await page.evaluate(() => {
      document.querySelector('ids-theme-switcher').setAttribute('mode', 'dark');
});
await percySnapshot(page, 'ids-header-new-dark');
```

2022-01-24 17:48 UTC, EdwardCoyle commented on src/components/ids-accordion/ids-accordion-header.js
> +      attributes.CHILD_FILTER_MATCH,
Got rid of `mode` and `version` since those come from the theme anyway, seems to be ok

2022-01-24 17:49 UTC, EdwardCoyle commented on test/ids-header/ids-header-percy-test.js
> +    await waitForPageLoad(url, 'dark', 30);
Wasn't aware of that one, thanks

2022-01-25 14:51 UTC, tmcconechy requested changes
@EdwardCoyle the only problem i see is the percy images are showing that the background color on the search changed to transparent now https://percy.io/00aaa841/enterprise-wc/builds/15236236/changed/860787394?browser=chrome&browser_ids=20&subcategories=unreviewed%2Cchanges_requested&viewLayout=side-by-side&viewMode=new&width=1280&widths=375%2C1280

2022-01-25 22:25 UTC, EdwardCoyle commented
@tmcconechy I tried extending the wait time on the percy tests to see if that works.  The actual test pages seem fine so it must need a specific amount of time to pass before the color variants take effect

2022-01-25 22:51 UTC, EdwardCoyle commented
@tmcconechy I raised #511 to deal with the visual bug later... tried working out some logic for it but having some trouble with it

2022-01-26 14:50 UTC, jmacaluso711 reviewed
Looks great...Just seeing one minor edge case. If you type "Em" > Open and close the accordion header > clear the search > click the accordion header again. You'll see that it takes an extra click to see the child elements. Probably just need to refresh the accordion state when clearing the search? 

Demo of the bug:
![IDS App Menu Component](https://user-images.githubusercontent.com/1084735/151185610-dd80696d-8805-4536-8add-7f64d76d15a5.gif)

2022-01-26 19:59 UTC, tmcconechy reviewed
Looks good if we can fix the visual tests. I updated the TODO feel free to add anything else for app menu.

Maybe just increase the timeout more or you could do.. .

```
await page.waitForSelector('<whatever classes are added for the colors to work>');
```

2022-01-28 20:42 UTC, EdwardCoyle commented
@tmcconechy We finally sorted out the missing variant problem -- turns out styles weren't correctly being applied to Dark/Contrast modes at all before.  I have a temporary fix in, and will truly correct the colors there as part of #520

2022-01-31 14:46 UTC, tmcconechy submitted a review, later dismissed
:shipit:

2022-01-31 16:38 UTC, danielortiz1982 approved these changes
@EdwardCoyle This looks great! Good job on this, came out really clean. 👍

2022-01-31 16:48 UTC, jmacaluso711 requested changes
Hey @EdwardCoyle -- as discussed, just seeing the theme related issues:

![Screen Shot 2022-01-31 at 10 34 08 AM](https://user-images.githubusercontent.com/1084735/151836342-887ea8e9-839f-4b0c-81cb-0f13bc8ab9cd.png)

2022-01-31 18:40 UTC, EdwardCoyle commented
@jmacaluso711 -- I fixed the dark/contrast modes on App Menu and its child components.  The Search Field styles need work but I plan on fixing all theme related issues as part of #520

2022-02-01 12:23 UTC, EdwardCoyle commented
@infor-design/eng-ids I think the remaining visual regression issues are either new screenshots or minor color corrections

2022-02-01 15:31 UTC, tmcconechy approved these changes

2022-02-01 15:31 UTC, merged