501 - Add missing focus styling and fix mobile view double toggling
infor-design/enterprise-wc pull request #523
Opened 2022-01-27 18:44 UTC by jdilag90

**Explain the details for making this change. What existing problem does the pull request solve?**
:focus styling was missing for classic/new dark/high contrast themes.
Found issue with expanding/toggling panel twice when in mobile view. 
Refactored ids-accordion-panel -> select() to increase code coverage 

**Related github/jira issue (required)**:
Close #501 

**Steps necessary to review your pull request (required)**:
1. Checkout branch `501-accordion-focus`
2. `npm run start`
3. Go to http://localhost:4300/ids-accordion
4. Click or tab navigate accordion panels and compare styles to 4x https://main-enterprise.demo.design.infor.com/components/accordion/example-index.html?theme=classic&mode=dark&colors=0066D4
5. Also, switch dev tools to mobile view and expand/collapse panels to ensure double toggling is fixed on mobile

![IDS Accordion Component](https://user-images.githubusercontent.com/98347152/151422701-b3a3684c-59e5-4f67-8d2f-3e7f20c37cdb.png)

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [ ] A note to the change log.

2022-01-27 20:40 UTC, tmcconechy requested changes
Looks good! Just a few small suggestions...

2022-01-27 20:40 UTC, tmcconechy commented on src/components/ids-accordion/ids-accordion-panel.js
> +    if (panel && panel.tagName === 'IDS-ACCORDION-PANEL') {
```suggestion
    if (panel?.tagName === 'IDS-ACCORDION-PANEL') {
```

Can also do this i think?

2022-01-27 20:40 UTC, tmcconechy commented on src/components/ids-accordion/ids-accordion-header.scss
> +  --ids-color-palette-classic-azure-50: #54a1d3;
I didnt add these on purpose so classic isnt 100% 1-1 it uses the same new color pallette.
So instead of adding all these you can just subsitute

--ids-color-palette-azure-50
--ids-color-palette-azure-60


And use whats there...

2022-01-28 14:43 UTC, tmcconechy approved these changes
Great First PR thanks @jdilag90  👍🏻

2022-01-28 18:39 UTC, danielortiz1982 approved these changes
@jdilag This looks great! Good job.

2022-01-28 20:49 UTC, EdwardCoyle approved these changes
Looks great @jdilag90!

2022-01-31 14:49 UTC, merged