350 - Add ids editor
infor-design/enterprise-wc pull request #529
Opened 2022-01-29 21:56 UTC by deep7102

**Explain the details for making this change. What existing problem does the pull request solve?**
Added Ids Editor component

**Related github/jira issue (required)**:
Closes #350

**Steps necessary to review your pull request (required)**:
- Pull this branch and build/run the demo app
- Navigate to:
- http://localhost:4300
- http://localhost:4300/ids-editor
- http://localhost:4300/ids-editor/sandbox.html
- http://localhost:4300/ids-editor/side-by-side.html
- See editor all variations and uplift styles 
- Added e2e and functional tests
- See the docs

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2022-01-30 12:21 UTC, danielortiz1982 commented on src/components/ids-editor/ids-editor.js
> +    if (clipboardData?.types) {
This came out really clean, however I feel this can be optimized further if you perhaps used the `navigator.clipboard.readText()` and `navigator.clipboard.write(data)` API. I think using these API's will reduce the amount of checking you will need to perform, also it has a wider browser support and returns a promise. This feedback is under the condition you will not need to use the `Permissions API` 


https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Interact_with_the_clipboard
https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/readText
https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/write

2022-01-30 12:34 UTC, danielortiz1982 commented on src/components/ids-editor/ids-editor.js
> +      for (let i = 0, l = paragraphs.length; i < l; i++) {
100% code style option here but I think this should be changed to a `forEach` instead. In my opinion it's cleaner because it is a lot more readable and also forEach keeps the variable’s scope to the block which will help in future code updates that are less prone to errors. Having to use a temporary `i` variables can add a lot of confusion to your code. This change I am requesting is just my humble opinion.

2022-01-30 12:53 UTC, danielortiz1982 requested changes
Please change all while statements on lines 571, 638, 784, 791 to `for` or `forEach`. The iterators for and forEach is a better solution because they are less prone to memory leaks and infinite loops locking up the IO and window.

2022-01-31 10:35 UTC, danielortiz1982 commented on src/components/ids-editor/ids-editor.js
> +// List of view modes
Can you possible move the settings from line 24 to 72 into it's own file. You can see IdsButton as a reference. 

IdsButton Attributes:
https://github.com/infor-design/enterprise-wc/blob/main/src/components/ids-button/ids-button-attributes.js

2022-01-31 10:44 UTC, danielortiz1982 requested changes
Overall I think this came really well, great job! One thing I would like to see on the `ids-editor.js` file. Ids-editor.js is currently over 2,000 lines so maybe we can break this down into different files to make future updates easier and more readable. Perhaps you can pick out core functionality and group them into there own file and import them. This will reduce the file size while making the logic more modular

2022-01-31 14:49 UTC, deep7102 commented
> Please change all while statements on lines 571, 638, 784, 791 to `for` or `forEach`. The iterators for and forEach is a better solution because they are less prone to memory leaks and infinite loops locking up the IO and window.

agree with concern about `while` loops it can be wonky if not use carefully, so will update as `for` or `forEach`, but some will still there because thinking `while` is good place for it

2022-01-31 14:56 UTC, deep7102 commented on src/components/ids-editor/ids-editor.js
> +    if (clipboardData?.types) {
yes, I also had looked thru this api and personally liked it, but had few points as below which not supported that's why did not go with it.

1) it only support `https`, and it cannot be used from a content script running on `http:` pages
2) to paste just text content we can use `navigator.clipboard.readText()` which is fine, but in order to use images with clipboard it require to use `navigator.clipboard.read()` and which is not fully supported yet with new/major browsers like chrome/firefox https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/read
3) this requires the permission to "clipboardRead" or "clipboardWrite" (I think this is fine)

2022-01-31 14:59 UTC, deep7102 commented
> Overall I think this came really well, great job! One thing I would like to see, `ids-editor.js` is currently over 2,000 lines so maybe we can break this down into different files to make future updates easier and the codebase more readable. Perhaps you can pick out core functionality and group them into there own file and import them. This will reduce the file size while making the logic more modular

Great point, like this to be breakdown in smaller parts, will do as much can -thanks

2022-01-31 15:16 UTC, danielortiz1982 commented on src/components/ids-editor/ids-editor.js
> +    if (clipboardData?.types) {
okay cool, just wanted to throw it out there... I will leave it up to your better judgement. 👍

2022-01-31 15:16 UTC, tmcconechy requested changes
This looks really good Deepak 🥇 

Only small things from me for now. The only functional thing i saw in addition while testing was that on http://localhost:4300/ids-editor/sandbox.html on the dirty example i did a quick test to make it bold and then not bold and the dirty indicator stayed when it shouldnt.

2022-01-31 15:16 UTC, tmcconechy commented on demos/ids-editor/index.yaml
> + description: An input for multi line editable text
```suggestion
 description: An input for multi line rich text
```

2022-01-31 15:16 UTC, tmcconechy commented on demos/ids-editor/index.yaml
> + keywords: theme, color, switcher
```suggestion
 keywords: editor, rich text, content editable, RTE
```

2022-01-31 15:16 UTC, tmcconechy commented on doc/CHECKLIST.md
> + - [ ] ~~Fontpicker (ids-font-picker)~~
```suggestion
 - [x] Fontpicker (added as part of editor)
```

2022-01-31 15:16 UTC, tmcconechy commented on src/components/ids-editor/README.MD
> +  <div slot="content">
Is there more than one slot?

2022-01-31 15:36 UTC, tmcconechy commented on src/components/ids-editor/README.MD
> +  <div slot="content">
Yeah thats what i was getting at but do we have a html view/normal view slot?

2022-01-31 15:36 UTC, deep7102 commented on src/utils/ids-debounce-utils/ids-debounce-utils.js
> +    timeout = setTimeout(delayed, threshold || 250);
Yes, did try and was first preferences `requestAnimationFrame` but did not help.

2022-02-02 15:20 UTC, deep7102 commented
@tmcconechy @danielortiz1982 it's updated, and ready for review now.

2022-02-02 15:21 UTC, tmcconechy approved these changes

2022-02-02 19:21 UTC, tmcconechy approved these changes

2022-02-02 19:22 UTC, danielortiz1982 approved these changes
This looks great @deep7102 really nice work!

2022-02-03 14:29 UTC, merged