480 data label
infor-design/enterprise-wc pull request #530
Opened 2022-01-31 13:21 UTC by jeffwa428

**Explain the details for making this change. What existing problem does the pull request solve?**
Created new component for data label

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise-wc/issues/480

**Steps necessary to review your pull request (required)**:
- Go to localhost:4300/ids-data-label
- Check top and left positioned data label
- Check data label for RTL (French locale)
- Should be same as https://main-enterprise.demo.design.infor.com/components/form/example-labels.html

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [] A note to the change log.

2022-01-31 15:05 UTC, tmcconechy requested changes
A few suggestions inline. Also try to fix the lint errors on the build (npm run lint)
I didnt see any problems with e2e percy / maybe it was temporary

2022-01-31 15:05 UTC, tmcconechy commented on src/components/ids-data-label/ids-data-label.js
> +  set labelPosition(value) {
I noticed that changing these properties inline in the html does not update. Should fix that. It should add/remove the class and be dynamic for all properties

2022-01-31 15:05 UTC, tmcconechy commented on src/components/ids-data-label/ids-data-label.scss
> +:host([lang='fr']) {
Pls Make sure this works when setting via the container...I dont see that it is or it doesnt update

2022-01-31 15:05 UTC, tmcconechy commented on src/core/ids-attributes.js
> +  LABEL_POSITION: 'label-position',
Alphabetically pls

2022-01-31 15:05 UTC, tmcconechy commented on test/ids-data-label/ids-data-label-func-test.js
> +  it('renders with label-position', () => {
Maybe add tests for making it dynamically change and the colon setter?

2022-01-31 16:27 UTC, EdwardCoyle commented on demos/ids-data-label/example.html
> +  <ids-data-label label="Shipping to" label-position="left" lang="fr">Los Angeles, California 90001 USA</ids-data-label>
Until we build langauge switch into the demoapp a bit further, maybe put this on a separate test page so we can still test it quickly?

2022-01-31 17:43 UTC, tmcconechy commented on demos/ids-data-label/example.html
> +  <ids-data-label label="Shipping to" label-position="left" lang="fr">Los Angeles, California 90001 USA</ids-data-label>
@EdwardCoyle i dont think it needs a seperate page can just use the container on that page. And actually you cant really change language on it like that it needs to be on the container now so i dont think this is correct on a new page..

2022-02-04 14:47 UTC, tmcconechy requested changes
Some more things im seeing here. Lets just have 2 in the page not a seperate one for french and we can test it by the container on the top of the page

also can add one more test that 
- starts in en and test the colon is right
- changes to fr and test the colon is right

2022-02-04 14:47 UTC, tmcconechy commented on demos/ids-data-label/example.html
> +  <ids-container language="fr">
Please just use the container at the top of the page..

2022-02-04 14:47 UTC, tmcconechy commented on demos/ids-data-label/index.yaml
> + keywords: label, data, readonly, read only
Add to [example.js (or index.js)](https://github.com/infor-design/enterprise-wc/blob/main/demos/example.js)  so it shows on http://localhost:4300/i

2022-02-04 14:47 UTC, tmcconechy commented on src/components/ids-data-label/README.md
> +The IDS Data Label component used to show both label and value.
```suggestion
The IDS Data Label component used to show both label and value for readonly (non editable data).
```

2022-02-04 14:47 UTC, tmcconechy commented on src/components/ids-data-label/README.md
> +Typically, these data labels are useful to show information with top/left/right label positioned.
```suggestion
- When you need to show a readonly data item with a label
```

2022-02-04 14:47 UTC, tmcconechy commented on src/components/ids-data-label/README.md
> +```html
```suggestion

Shows a data label with one top label and one with a left label.

```html
```

2022-02-04 14:47 UTC, tmcconechy commented on src/components/ids-data-label/ids-data-label.js
> +/* eslint-disable no-nested-ternary */
Is this needed?

2022-02-04 14:47 UTC, tmcconechy commented on src/components/ids-data-label/ids-data-label.js
> +      attributes.LANGUAGE
Could be in order

2022-02-04 14:47 UTC, tmcconechy commented on src/components/ids-data-label/ids-data-label.scss
> +    direction: rtl;
Only ar and hi are RTL so no need to make french RTL. The difference the colon spacing ' : ' vs ': '

2022-02-04 14:47 UTC, tmcconechy commented on src/components/ids-data-label/ids-data-label.js
> +    return this.labelPosition === 'left' ? ':' : '';
The logic should be if french a space on both sides ' : ' vs ': ' for all others.

2022-02-07 16:16 UTC, tmcconechy commented on src/components/ids-data-label/ids-data-label.scss
> +:host([language='fr']) {
```suggestion
:host([language='fr']) {
```

I noticed that if using language `fr-FR` or `fr-CA` it doesnt work can we add cases for language = 'fr-FR' and 'fr-CA'?

As those are also valid. And im not sure if just changing here is enough?

2022-02-07 16:18 UTC, EdwardCoyle commented on src/components/ids-data-label/ids-data-label.scss
> +:host([language='fr']) {
Could this work?
```suggestion
:host([language*='fr']) {
```

2022-02-07 17:07 UTC, deep7102 reviewed
Looks Nice! @jeffwa428 
saw only one thing when it wraps looks weird (try on smaller view port) might just need to adjust the css `white-space: nowrap;`
<img width="469" alt="image" src="https://user-images.githubusercontent.com/38439203/152837701-0fd5559a-bd5e-496a-8e0b-8be744ec556f.png">

I try to edit with console this css property and looks as below:
<img width="520" alt="image" src="https://user-images.githubusercontent.com/38439203/152837577-31064ae7-19d4-4cb8-869e-42a52351bb8c.png">

2022-02-08 16:22 UTC, tmcconechy approved these changes

2022-02-08 18:43 UTC, deep7102 approved these changes
Thanks! @jeffwa428 
LGTM 🍌

2022-02-09 14:14 UTC, merged