537 - Add ids-card examples
infor-design/enterprise-wc pull request #559
Opened 2022-02-22 14:15 UTC by jeffwa428

**Explain the details for making this change. What existing problem does the pull request solve?**
Add more ids-card examples
- Add a secondary toolbar example like this https://main-enterprise.demo.design.infor.com/components/cards/example-group-action.html
- Add variations like https://main-enterprise.demo.design.infor.com/components/cards/example-variations-hitboxes.html
- 

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise-wc/issues/537

**Steps necessary to review your pull request (required)**:

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [ ] A note to the change log.

2022-02-22 15:36 UTC, tmcconechy reviewed
This looks good..Only see a couple things

- maybe make the new cards on a new page
- i think they need a better name than "variant" but not sure what? will research
- check the lint errors
- can you add a visual test / check test coverage on the card code
- even tho the old version is like this i think it is wrong - can we make the title text line up 
<img width="196" alt="Screen Shot 2022-02-22 at 10 35 54 AM" src="https://user-images.githubusercontent.com/814283/155165940-6df68c9b-d890-4408-8c3c-c9ab760b25d7.png">

2022-02-22 15:36 UTC, tmcconechy commented on demos/ids-card/toolbar.scss
> +#primary-toolbar {
We shouldnt style by ID as this may change. I think need to use a class.

2022-02-22 20:37 UTC, tmcconechy commented
@jeffwa428 as discussed in the call lets try to do this without any special variant class. i.e.

- card gets auto-height setting to fit to contents
- add a card-actions (or similar) sub component that floats action buttons on the right (or left in RTL) with flex or vss grid
- see markup examples https://getbootstrap.com/docs/4.0/components/card/
- ids-text will just get proper padding between

2022-02-25 20:41 UTC, tmcconechy commented
```
<ids-card auto-height="true">
  <div slot="card-content">
    <ids-text color="green" font-size="14">Action Item</div>
    <ids-text font-size="14">Submit 360 Review</div>
    <ids-text font-size="14">Send review by May 2nd</div>

    <ids-card-actions> <!-- flex to the right / also test rtl-->
       <!-- look at ids-button -->
      <ids-button icon="..."></ids-button> 
    </ids-card-actions>
  </div>
</ids-card>

<ids-card auto-height="true">
  <div slot="card-content">
    <ids-image src="photo.jpg" alt="photo"></ids-image>
    <ids-text color="green" font-size="14">Action Item</div>
    <ids-text font-size="14">Submit 360 Review</div>
    <ids-text font-size="14">Send review by May 2nd</div>

    <ids-card-actions> <!-- flex to the right / also test rtl-->
       <!-- look at ids-button -->
      <ids-button icon="..."></ids-button> 
    </ids-card-actions>
  </div>
</ids-card>
```

2022-03-01 19:12 UTC, tmcconechy requested changes
- Minor cleanup
- Rename variants to info for the example
- Try to do this without any needed example csss

2022-03-01 19:12 UTC, tmcconechy commented on demos/ids-card/index.yaml
> +  - link: variants.html
Can we rename this to `info.html` - i.e. info cards.... (cards with various dynamic information)

2022-03-01 19:12 UTC, tmcconechy commented on demos/ids-card/toolbar.scss
> +  content: 'a';
Is this right?

2022-03-01 19:12 UTC, tmcconechy commented on demos/ids-card/variants.html
> +          <ids-text labelFontSize="16" color="emerald-60">Action Item</ids-text>
`labelFontSize` should be `font-size`

2022-03-01 19:12 UTC, tmcconechy commented on demos/ids-card/variants.scss
> +.ids-card-content-variant {
I dont think we need this anymore..

2022-03-01 19:12 UTC, tmcconechy commented on demos/ids-card/variants.js
> +import './variants.scss';
Remove?

2022-03-01 19:12 UTC, tmcconechy commented on demos/ids-card/variants.scss
> +[slot='card-content'] {
I tried to remove this but both http://localhost:4300/ids-card/toolbar.html and http://localhost:4300/ids-card/info.html do get messed up.

The goal would be that the cards are dynamic and work without adding any special css so maybe this needs to go in the card somehow

2022-03-01 19:12 UTC, tmcconechy commented on src/components/ids-card/ids-card-action-base.js
> +import IdsThemeMixin from '../../mixins/ids-theme-mixin/ids-theme-mixin';
We probably only need IdsElement in here not the other mixins..

2022-03-01 19:12 UTC, tmcconechy commented on src/components/ids-card/ids-card-action.js
> + * @mixes IdsEventsMixin
Same here - just IdsElement

2022-03-01 19:12 UTC, tmcconechy commented on src/components/ids-card/ids-card-action.scss
> +  margin-right: auto;
Is this needed? Not sure what auto would do in terms of margin? But it would be better to use the mixins here as it works with margin-start/end instead of left and right.. fx

```
@include ml-4;
@include mx-4;
```

2022-03-03 16:13 UTC, tmcconechy commented on src/components/ids-card/ids-card-action.scss
> +  margin-right: auto;
The whole thing could be
```
host {
    margin-inline-start: auto;
}
```

2022-03-03 16:13 UTC, tmcconechy commented on src/components/ids-card/ids-card-action.scss
> +  margin-right: auto;
See https://github.com/infor-design/design-system/issues/478 for more info

2022-03-08 16:09 UTC, tmcconechy commented on demos/ids-card/toolbar.scss
> +.primary-toolbar {
@jeffwa428 the only question is is this needed? As the styles should be in the component so the end user doesnt need any css? Maybe it works without this?

2022-03-08 16:52 UTC, EdwardCoyle reviewed
In addition to Tim's comments, I had one more request for this one.  Overall, looks good and will approve once comments are addressed 👍

2022-03-08 16:52 UTC, EdwardCoyle commented on src/components/ids-card/ids-card.scss
> +  ::slotted([slot='card-content']) {
@jeffwa428 are these styles needed to shape the component?  If so, we also need to consider standalone CSS usage (non-webcomponent, styles only).  Currently the way this is written, we can't use this new feature when only the styles are used, due lack of a host element.

Could these same rules instead be applied to a CSS class that we would add to the Card's container element (the first element in Shadow root that has the class `.ids-card`)?  Maybe we can use a css class `.flex-content` to match the attribute name?

2022-03-08 16:54 UTC, EdwardCoyle commented on src/components/ids-card/ids-card.scss
> +  ::slotted([slot='card-content']) {
For reference, run your local demoapp and see the markup for IdsCard on this URL:  http://localhost:4300/ids-card/standalone-css.html

2022-03-09 15:00 UTC, tmcconechy reviewed
The only (last problem) i see is if you load http://localhost:4300/ids-card/info.html and look in the console you will see an error:

Uncaught TypeError: Cannot read properties of undefined (reading 'call')
    at HTMLElement.connectedCallback (ids-card-action.js:18:5)

2022-03-09 19:13 UTC, tmcconechy approved these changes

2022-03-09 20:13 UTC, tmcconechy commented
@jeffwa428 i synced this with main for you after the big merge. Looks good to me but you might want to take a quick look everything is as expected

2022-03-09 21:54 UTC, EdwardCoyle approved these changes
Looks good!

2022-03-09 22:18 UTC, tmcconechy approved these changes

2022-03-09 22:18 UTC, merged