Ids text weight and default ellipsis overflow
infor-design/enterprise-wc pull request #56
Opened 2021-04-07 14:55 UTC by rob2d

**Explain the details for making this change. What existing problem does the pull request solve?**

- For `IdsText`, overflow text ellipsis was not possible as it is in a span which has a quirk in CSS. 
- Also added a `font-weight` property as the component injects `font-weight: 400`. 

Aliased `extrabold` as `bolder` since `extrabold` can be confused with two words without hyphen but internally in our code does not have hyphen.

**Related github/jira issue (required)**:

**Steps necessary to review your pull request (required)**:

- pull branch `ids-text-weight-and-default-ellipsis-overflow` and run dev server locally via `npm run start`.
- visit http://localhost:4300/ and scroll to `TEXTS/TYPOGRAPHY`
- in Chrome Inspector, set `<ids-layout-grid-cell>` surrounding the text demo section to have `element.style` `max-width: 100px` and see that text ellipsis properly.
![image](https://user-images.githubusercontent.com/1799905/113883365-18aae280-978c-11eb-98d2-c061b645d689.png)
- edit an `ids-text` component to have font weight of `bold`. Notice that the text changes properly.
![Kapture 2021-04-07 at 10 51 20](https://user-images.githubusercontent.com/1799905/113887159-43e30100-978f-11eb-9b47-e4f8a9274777.gif)

--------------------

+ also have a fix in this PR so that calling `this.render()` clears inner shadow DOM HTML if it existed already without duplicating markup. 

This allows us to use it predictably in lifecycle without having to add second `rerender()` methods when all we would like to do is modify the template.

Spoke with @EdwardCoyle on this change but if there's any problems it creates please let me know.

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [X] A note to the change log.

2021-04-07 15:08 UTC, tmcconechy requested changes
Some small edits

- unsure these new props need a full rerender
- in the example maybe just leave the two examples out and put them in a test instead https://github.com/infor-design/enterprise-wc/blob/main/test/ids-text/ids-label-func-test.js
- also noticed the test is called label (old name) can rename that to text
- the PR will eventually likely report coverage dropped so need a test for the new settings 

Otherwise looks good.

2021-04-07 15:08 UTC, tmcconechy commented on src/ids-text/ids-text.js
> +    this.render();
rerender/render is a bit more expensive. The best is if we can do this with a class change. Wouldn't that work here? Im thinking this is only needed if you need to change the node type. The rest you can toggle a class or something simpler?

2021-04-07 15:08 UTC, tmcconechy commented on src/ids-text/ids-text.js
> +    this.render();
Seem here maybe we can just toggle the class?

2021-04-07 15:17 UTC, rob2d commented on src/ids-base/ids-element.js
> +    if (this.shadowRoot?.innerHTML) {
@tmcconechy yeah actually -- the innerHtml on `shadowRoot` is for current element, so it exists and creates duplicates in lifecycle in many cases. Added this since it was creating issues on the WIP `ids-wizard` branch.

2021-04-07 15:19 UTC, tmcconechy commented on src/ids-base/ids-element.js
> +    if (this.shadowRoot?.innerHTML) {
Ok dont think it would hurt... But if its related to using the full re render method to update we want to try and minimize that for cases like you need to change ALL the markup. (comments below)

2021-04-07 15:24 UTC, rob2d commented on src/ids-text/ids-text.js
> +    this.render();
will look into this -- was trying to follow the 80/20 rule since the pattern of manually editing classes seems error-prone vs the payoff in this sort of thing (since the browser still needs to repaint the component... I think may be more expensive than our template method if the logic isn't crazy). But will try to just change the class list on the element directly in this csae.

2021-04-07 15:27 UTC, tmcconechy commented on src/ids-text/ids-text.js
> +    this.render();
Dont see any reason adding and removing classes should be error prone. But that was what i was thinking is that you really dont need to remove all the html and add it again. When you can just toggle a class.

Rule is do the minimum you can to make the property active and its a pattern we have been following (maybe in the end its about the same but it seems logical that toggling a class/attribute would be simpler to me then removing it all and adding it again).

2021-04-08 14:50 UTC, rob2d commented
Closing to push onto new branch to clean the merges from commit log -- have fixes for the test that was breaking so that we can work with jest mock a little more safely also.

2021-04-08 14:52 UTC, closed without merging