IdsText: overflow and weight, fix existing issues with attributes in setters/getters/template()
infor-design/enterprise-wc pull request #58
Opened 2021-04-08 22:06 UTC by rob2d

**Explain the details for making this change. What existing problem does the pull request solve?**

- For `IdsText`, overflow text ellipsis was not possible as it is in a span which has a quirk in CSS. Added `overflow` property which defaults to `ellipsis` behavior. Specifying `clip` or `none` would remove this functionality.
- Also added a `font-weight` property as the component injects `font-weight: 400`. 
Aliased `extrabold` as `bolder` since `extrabold` can be confused with two words without hyphen but internally in our code does not have hyphen.
- Discovered several issues with properties in ids-text such as audible as a tag, or template() rendering full mark-up while making changes based on feedback from last PR. Adjusted tests accordingly.

+ also have a fix in this PR so that calling `this.render()` clears inner shadow DOM HTML if it existed already without duplicating markup. 

This allows us to use it predictably in lifecycle without having to add second `rerender()` methods when all we would like to do is modify the template. This should not cause issues after #57, since we fixed that there.

⚠️ just a heads up that this PR is rebased onto #57 . Because of that I'll label it WIP until then -- and would be good to get feedback on this early either way ⚠️

**Related github/jira issue (required)**:

Needed to address infor-design/enterprise-wc#56

**Steps necessary to review your pull request (required)**:

- pull branch `ids-text-weight-and-default-ellipsis-overflow` and run dev server locally via `npm run start`.
- visit http://localhost:4300/ and scroll to `TEXTS/TYPOGRAPHY`
- in Chrome Inspector, set `<ids-layout-grid-cell>` surrounding the text demo section to have `element.style` `max-width: 100px` and see that text ellipsis properly.
![image](https://user-images.githubusercontent.com/1799905/113883365-18aae280-978c-11eb-98d2-c061b645d689.png)
- edit an `ids-text` component to have font weight of `bold`. Notice that the text changes properly.
![Kapture 2021-04-07 at 10 51 20](https://user-images.githubusercontent.com/1799905/113887159-43e30100-978f-11eb-9b47-e4f8a9274777.gif)

--------------------

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [X] A note to the change log.

2021-04-08 22:41 UTC, rob2d commented
There's some visual regressions on this which seem to just be:
- the line-height (or padding) increasing on text components
- ellipsis text cutoff since ids-text is used in many other components.

It seems in retrospect, that having the new overflow property ellipsis by default may be a bad idea due to multiline considerations. Might be bad in retrospect after seeing it is used in all of these other components (@tmcconechy @deep7102 or anyone else with more big picture understanding of our use cases have input on it?)

Will be able to check into this in the AM tomorrow either way and hopefully the first type of snapshot diff was also just caused by the ellipsis rule as-default.

2021-04-09 13:39 UTC, tmcconechy requested changes
Couple small things

2021-04-09 13:39 UTC, tmcconechy commented on app/ids-text/example.html
> +    <ids-text font-size="16" font-weight="bold">Size 16 + Bold</ids-text>
```suggestion
    <ids-text font-size="16" font-weight="bold">Size 16 + Bold</ids-text>
```

Lets remove this from this example as it throws it off. Can either be a separate page or no example (example is where you end up really using it).

2021-04-09 13:39 UTC, tmcconechy commented on doc/CHANGELOG.md
> +- `[Text]` Add overflow attribute (default: `'ellipse'`, anything else will clip).
Can probably leave this out for now. Change log is initially about all the breaking changes. But i think we need to refine it a bit more for actual changes before/after release 1.0.0

2021-04-09 13:39 UTC, tmcconechy commented on src/ids-text/ids-text.scss
> +    @include ellipsis;
```suggestion
    @include ellipsis;
```

Do these work? I thought it was @include ellipsis();

2021-04-09 16:23 UTC, rob2d commented on src/ids-text/ids-text.scss
> +    @include ellipsis;
@tmcconechy yep. If there's no params for mixins, we can omit parens -- but for consistency sake I can change it.

2021-04-09 16:53 UTC, rob2d commented
changed the overflow behavior, addressed feedback + updated tests, hopefully Percy agrees with it now 🤞

2021-04-09 17:15 UTC, tmcconechy commented on src/ids-text/ids-text.scss
> +    @include ellipsis;
Wish i knew that before. Well lets use () for now for consistency

2021-04-09 17:17 UTC, tmcconechy submitted a review, later dismissed

2021-04-09 19:22 UTC, tmcconechy submitted a review, later dismissed

2021-04-12 16:50 UTC, tmcconechy approved these changes

2021-04-12 21:37 UTC, deep7102 requested changes
Looks good, 
few things like to address -sorry if too picky but I think not to add any extra stuff can be helpful for down the road in performance since we building up from scratch

And try not to use as much as we can the things which can slow down, until we relay need them like..
- pseudo-class selectors `:not(some-selector)`
- partial selectors `*=`, `$=` , `^=` etc...

2021-04-12 21:37 UTC, deep7102 commented on src/ids-text/ids-text.js
> +    const isValueTruthy = (value && value !== 'false') || (value === '');
To check the boolean values, please use the utils 
```
import { IdsStringUtils as stringUtils } from '../ids-base/ids-string-utils';

// then use where it need
const val = stringUtils.stringToBool(value);
```

2021-04-12 21:37 UTC, deep7102 commented on src/ids-text/ids-text.js
> +    if (isValueTruthy && elem && !elem?.classList.contains('audible')) {
I think these multi checks here can be combine to one
```
if (val) {
      this.setAttribute(props.AUDIBLE, val.toString());
      elem?.classList.add('audible');
} else {
      this.removeAttribute(props.AUDIBLE);
      elem?.classList.remove('audible');
}
```

2021-04-12 21:37 UTC, deep7102 commented on src/ids-text/ids-text.js
> +    this.setAttribute('overflow', isEllipsis ? 'ellipsis' : '');
Here same multi checks can be combine to one
```
if (isEllipsis) {
      this.setAttribute('overflow', 'ellipsis');
      elem?.classList.add('ellipsis');
} else {
      this.removeAttribute('overflow');
      elem?.classList.remove('ellipsis');
}
```

2021-04-12 21:48 UTC, rob2d commented on src/ids-text/ids-text.js
> +  FONT_SIZE: /^ids-text-[0-9]+$/,
@deep7102 this one is for `ids-text-${fontsize}` -- we currently use numeric font size which seems it may be variable. But good point on `:not(*)`, will address.

2021-04-12 22:08 UTC, rob2d commented on src/ids-text/ids-text.js
> +    return this.getAttribute(props.FONT_WEIGHT) || 'normal';
definitely valid point that a default can be omitted. Figured if a user was doing some conditional logic, setting to bold/bolder would be nice with alternative as `normal` for base behavior to read it e.g. `font-weight: normal` like CSS; esp if they had one-way binding to their UI to avoid errors.

But I can see validity in default being omitted/making it only include least amount of attribs at any time also.

2021-04-12 22:16 UTC, rob2d commented on src/ids-text/ids-text.js
> +    if (isValueTruthy && elem && !elem?.classList.contains('audible')) {
just checked and in this case, the user may be setting audible to true/false or change how they declare but the class name might not need to be changed.

e.g. <ids-text audible=true> vs <ids-text audible> register as prop changes.
Or <ids-text audible=false> vs <ids-text> also register as prop changes.

2021-04-12 22:19 UTC, rob2d commented on src/ids-text/ids-text.js
> +    if (isValueTruthy && elem && !elem?.classList.contains('audible')) {
edit: actually just changed for simplicity sake anyway -- at least now we don't call render() so should be a bit faster regardless what it does internally.

2021-04-12 22:33 UTC, rob2d commented on src/ids-text/ids-text.js
> +    return this.getAttribute(props.FONT_WEIGHT) || 'normal';
@deep7102 just noticed also that we now have to add Nullable types to ts side; so if we don't add default type cannot be `string` in TS but `string` || `null`. Looked around and seems several things may need to go back and annotate but at least can make the change here.

2021-04-12 23:35 UTC, rob2d commented on src/ids-text/ids-text.js
> +    const existingClass = elem?.classList && [...elem.classList].find(
Just noticed these --- was not familiar with Github's review UI completely since this is the first time seeing it. I implemented something similar once I did, but not sure if I should revert or use this. You can take a look and let me know what you think.

(also good point/clever approach, thanks).

2021-04-13 13:29 UTC, tmcconechy commented on src/ids-text/ids-text.js
> +  FONT_SIZE: /^ids-text-[0-9]+$/,
Not a big fan of this syntax either. Find it less clear but willing to let it go.

2021-04-13 13:31 UTC, tmcconechy commented on src/ids-text/ids-text.js
> +    const elem = this.shadowRoot?.querySelector('*:not(style)');
Actually looking at this im not sure why it changed? Another way is to use

```
const elem = this.container
```

In the base/IdsElement we made a container element reference which is the first child in the shadow DOM. If its that the needs this and nothing else this should work on that (which it seemed to be before)

2021-04-13 13:33 UTC, tmcconechy commented
Regarding the visual image test - i think i fixed this on my PR, it is intermittent. So maybe when we fix the issues on this and it passes we just let it go. OR approve the image changes until my theme PR is merged

2021-04-13 15:01 UTC, deep7102 commented on src/ids-text/ids-text.js
> +  FONT_SIZE: /^ids-text-[0-9]+$/,
@rob2d, No! `/^ids-text-[0-9]+$/` this selector not target all
because we not only use numeric font size, we have mix set of them as:
```
'xs', 'sm', 'base', 'lg', 'xl', 10, 12, 14, 16, 20, 24, 28, 32, 40, 48, 60, 72
// `ids-text-${fontsize}`
```

2021-04-13 15:06 UTC, deep7102 commented on src/ids-text/ids-text.js
> +    if (isValueTruthy && elem && !elem?.classList.contains('audible')) {
@rob2d, I agree e.g. `<ids-text audible=true>` vs `<ids-text audible>`
either way is fine, just like to be consistency which ever approach we go with so far other components user that style.

2021-04-13 15:57 UTC, rob2d commented on src/ids-text/ids-text.js
> +  FONT_SIZE: /^ids-text-[0-9]+$/,
@deep7102 addressed this one yesterday.

2021-04-13 16:09 UTC, rob2d commented on src/ids-text/ids-text.js
>      if (value) {
`Array.indexOf()` is really slow O(N) to run through 20 cases each change --> so that is O(N * 15[font-count]) runtime each change.

I am guessing in JS, they use a bin-tree or set internally, and already do the diffing there (so is no-op). Added a check for the className where it was intuitive to read otherwise but that's why I hadn't put it here when re-adding.

2021-04-13 16:35 UTC, rob2d commented on src/ids-text/ids-text.js
> +    if (isValueTruthy && elem && !elem?.classList.contains('audible')) {
I agree in our own code it was from perspective of the end user. In HTML it can be easy for them to assume they can write `<ids-text audible>....</ids-text>` because there's other internal things they might use like `<button disabled>....</button>`. But I can revert that check if that is preferred, just explaining what I meant.

2021-04-13 16:50 UTC, tmcconechy commented on src/ids-text/ids-text.js
> +    if (isValueTruthy && elem && !elem?.classList.contains('audible')) {
I think its probably fine if we accept either but we had been using `attribute="true"/attribute="false"` so you would be only fixing one of many cases. But definitely dont accept only `attribute`

2021-04-13 16:58 UTC, deep7102 commented on src/ids-text/ids-text.js
>      if (value) {
Yes, agree if it takes much to iterates -I think should be fine to not use `indexOf()` here if end-user add some class which we no use, it just extra css class in html and will not break our logic since we only apply the one we use.

2021-04-13 16:59 UTC, deep7102 commented on src/ids-text/ids-text.js
> +    if (isValueTruthy && elem && !elem?.classList.contains('audible')) {
It's fine either way to me which ever approach we go with.

2021-04-13 17:10 UTC, tmcconechy commented on src/ids-text/ids-text.js
>      if (value) {
Does
```
this.container
```
work instead of 
```
const elem = this.shadowRoot?.querySelector('.ids-text');
```

2021-04-13 17:11 UTC, tmcconechy commented on src/ids-text/ids-text.js
> +    if (isValueTruthy && elem && !elem?.classList.contains('audible')) {
I'd suggest either just true/false or both true/false and none -> whatever is fastest to do

2021-04-13 17:49 UTC, rob2d commented
These should be good -- am using the string utils to set that var but
github's preview doesn't update here.

On Tue, Apr 13, 2021, 1:11 PM Tim McConechy ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In src/ids-text/ids-text.js
> <https://github.com/infor-design/enterprise-wc/pull/58#discussion_r612632632>
> :
>
> > @@ -94,16 +141,47 @@ class IdsText extends IdsElement {
>     * @param {string | null} value The `audible` attribute
>     */
>    set audible(value) {
> -    if (value) {
> +    const isValueTruthy = (value && value !== 'false') || (value === '');
> +    const elem = this.shadowRoot?.querySelector('*:not(style)');
> +
> +    if (isValueTruthy && elem && !elem?.classList.contains('audible')) {
>
> I'd suggest either just true/false or both true/false and none -> whatever
> is fastest to do
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/infor-design/enterprise-wc/pull/58#discussion_r612632632>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AANXNYJ3S4N5GY4HRNYZY73TIR3MXANCNFSM42TY74SQ>
> .
>

2021-04-13 18:23 UTC, deep7102 commented on src/ids-text/ids-text.js
>      if (value) {
yes, if `this.container` works will be nice, it save some query load to find the element from dom-tree because `this.container` is already cached.

2021-04-13 18:52 UTC, rob2d commented on src/ids-text/ids-text.js
> +    const elem = this.shadowRoot?.querySelector('*:not(style)');
@tmcconechy sorry just seeing this one. But also for @tmcconechy  @deep7102 for context on this PR.

This component wasn't using setters/getters before, and I just started adding this code to fix bugs with different permutations as our rerender() was flushing certain updates (+prev attribs), and with even more props added it increases the problem.

@tmcconechy So I started to add those from your request to "please do" (change everything to prop updates as it will be perf boost either way + handle cases we didn't before). 

So it increased the scope quite a lot and I was just trying to complete the functionality, but we are not incrementally updating here at this point.

I know everyone has a lot on their plate so I completely understand also. Just giving some context that the `ids-text` had a lot of hidden issues that could show up later and primary goal was just to fix those, and give slight iteration so I can get back to the `ids-wizard` branch.

One thing I found as a reference which I used (and also remind myself, since I do the same when reviewing and try to be thorough) is Google has a nice standard system for PRs where they differentiate between things that need to change or things that must be changed. The overall goal they say is: "as long as the branch improves the quality of the codebase, it is enough to accept".

But definitely am learning a lot and appreciate the feedback/your patience on it! awesome experience on my end. Only pointing this out because its been kind of tough to learn + also get new work done on wizard component which these two props were needed for.

For ref: https://google.github.io/eng-practices/review/

^ really useful since it articulates some sane things. If you guys also have a document I can reference that would be cool too. Apologies also that I'm slow to catch issues with consistency or norms and things and everything you're saying *definitely* makes sense, so not to throw out any good advice. I am agreeing with all of it.

2021-04-13 18:58 UTC, rob2d commented on src/ids-text/ids-text.js
> +    const elem = this.shadowRoot?.querySelector('*:not(style)');
@tmcconechy re: `this.container` -- I think it is a little dangerous to expose it as public since we'll make that a pattern, and it holds the core `this.shadowDom` element... so maybe we can add a private property? e.g. #container = null on the class, then ref inside the other methods to set/get? (this would require babel plugin but its becoming standard feature on ESNext) Mainly because it may defeat the purpose of our efforts if a user can just look at an element and then just go to JS and say `elem.container` => but as a private class field it's not.

(also asking because: we don't do this anywhere yet, so trying to minimize the turnaround if its an issue)

2021-04-13 19:00 UTC, rob2d commented on src/ids-text/ids-text.js
> +    const elem = this.shadowRoot?.querySelector('*:not(style)');
For reference:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields

2021-04-13 19:03 UTC, tmcconechy commented on src/ids-text/ids-text.js
> +    const elem = this.shadowRoot?.querySelector('*:not(style)');
Thanks thats a good point with the article, will read it in full (skimmed it). I usually make it a "suggestion" or mention I'm not overly worried about something but will read that in more details otherwise when i comment i think its needs addressing.

At the moment i this PR i wasnt aware f anything wrong in here- figured you would just add the properties but these changes made it more complicated.

Concerning this issue comment i see its outdated now. But was wondering why we didnt just use this.container. For the review UI. It helps to resolve the conversation on points that are done/outdated.

2021-04-13 19:52 UTC, rob2d commented on src/ids-text/ids-text.js
>      if (value) {
ok sorry guys did not realize `this.container` has ref in IdsElement => that is adjusted now.

2021-04-13 19:55 UTC, tmcconechy approved these changes
Think this is good for me now. Thanks @rob2d

2021-04-14 13:38 UTC, deep7102 approved these changes
Thanks! @rob2d this looks good.

2021-04-14 13:54 UTC, merged