486 - Add ids data grid filters
infor-design/enterprise-wc pull request #624
Opened 2022-03-23 22:14 UTC by deep7102

**Explain the details for making this change. What existing problem does the pull request solve?**
Added Ids Data Grid Filters

**There are some known issues will handle separately**
- Scrolling, align position and bleeding (need to find the way can popup outside from data-grid): date-picker, time-picker, dropdown, menu-button [#565](https://github.com/infor-design/enterprise-wc/issues/565)
- Time picker, dropdown/s not able to open [#565](https://github.com/infor-design/enterprise-wc/issues/565)
- Date picker, year/month popup not able to open [#565](https://github.com/infor-design/enterprise-wc/issues/565)
- Cannot reset to blank value after select one: date-picker, time-picker [#623](https://github.com/infor-design/enterprise-wc/issues/623)

**Related github/jira issue (required)**:
Closes #486

**Steps necessary to review your pull request (required)**:
- Pull this branch and build/run the demo app
- Navigate to:
- http://localhost:4300/ids-data-grid/filter.html
- http://localhost:4300/ids-data-grid/filter-books.html
- http://localhost:4300/ids-data-grid/filter-custom.html
- See editor all variations and uplift styles
- Added e2e and functional tests
- See the docs

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2022-03-24 13:47 UTC, tmcconechy requested changes
Some suggestions/comments, we can make a new issue for the things we know are not working

http://localhost:4300/ids-data-grid/filter.html
- in the Color column type "Gree" -> notice when the filter is applied the focus is lost. Maybe we can only rerender the body (there is a function for that) keeping the focus (or restore it)
- the borders are a different color on https://main-enterprise.demo.design.infor.com/components/datagrid/example-filter.html
- Noting: will need to add column alignment (left, right center)
- the input box in the pager is really big

2022-03-24 13:47 UTC, tmcconechy commented on src/assets/data/books.json
> +    "inStock": true,
Weird formatting?

2022-03-24 13:47 UTC, tmcconechy commented on src/components/ids-data-grid/README.md
> +Data rows can be easily filter based on one or several criteria. Whole filter row can turn on/off by api setting `filterable` and can be disabled by api setting `filter-row-disabled`. The filter cond
```suggestion
Data rows can be filter based on one or several criteria. Whole filter row can turned on/off by the api setting `filterable` and can be disabled by the api setting `filter-row-disabled`. The filter conditions can be applied thru the UI or programmatically. Each column can have its own filter type and turn on/off by columns setting.
```

2022-03-25 22:05 UTC, deep7102 commented on src/assets/data/books.json
> +    "inStock": true,
updated now

2022-03-25 22:06 UTC, deep7102 commented
@tmcconechy Update now, the point you found.

2022-03-28 13:34 UTC, tmcconechy approved these changes
This is good for me for now. Nice job @deep7102 
Next we should fix the popup issues..

2022-03-28 17:46 UTC, danielortiz1982 approved these changes
Nice work on this PR @deep7102 👍

2022-03-28 17:48 UTC, merged