329 - Autocomplete mixin
infor-design/enterprise-wc pull request #643
Opened 2022-04-11 19:10 UTC by jmacaluso711

**Explain the details for making this change. What existing problem does the pull request solve?**
This PR adds the autocomplete mixin to `ids-input`

**Related github/jira issue (required)**:
closes #329 

**Steps necessary to review your pull request (required)**:
- Pull and run branch
- Go to http://localhost:4300/ids-input/autocomplete.html and start typing a state name in the input
- Make sure popup opens with results.
- Select a state by clicking. The input value should update.
- Select a state by navigating up/down with keyboard and press enter. The input value should update.

- Go to http://localhost:4300/ids-trigger-field
- Repeat the same steps from above in the input labeled "Autocomplete Trigger Field"

- Go to http://localhost:4300/ids-search-field
- Repeat the same steps from above in the input labeled "Autocomplete Search Field"

- Go to http://localhost:4300/ids-lookup/autocomplete.html
- Repeat the same steps from above. Search for description (i.e 101, 102, 103).

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [ ] A note to the change log.

2022-04-12 10:16 UTC, andriivarhanov reviewed
looks good, everything works, some adjustments to add/discuss:
- Please add some events to autocomplete. Events in the original autocomplete beforepopulated, populated, listopen, listclose, selected. I’m thinking maybe `selected` and `cleared` like suggested in https://github.com/infor-design/enterprise-wc/issues/329
- Keyboard Escape should close popup
- Keyboard arrow up/down should cycle through the list. First item selected -> arrow up -> last item selected and vise versa
- Please add all autocomplete.html examples to component yaml files
ids-lookup: I think maybe use same `search-field` attribute instead of `field` for consistency
- If possible to add more tests to autocomplete to increase test coverage

2022-04-12 13:46 UTC, tmcconechy requested changes
See a couple things worth considering.

A) One small behavior i noticed is if you 
- type a (any example)
- down arrow repeatedly
- doesn't scroll you cant see the items

B) Also if you go to mobile size (345px ish) the popup doesnt lineup.

<img width="321" alt="Screen Shot 2022-04-12 at 9 42 16 AM" src="https://user-images.githubusercontent.com/814283/162976047-1b3b9938-3286-4898-bc9f-947645138885.png">

C) Also the under border is a different color... (minor)
<img width="557" alt="Screen Shot 2022-04-12 at 9 40 52 AM" src="https://user-images.githubusercontent.com/814283/162976359-b0977aa4-3400-4171-aa12-725508d10148.png">

D) Also in dark mode the colors are a bit off
<img width="321" alt="Screen Shot 2022-04-12 at 9 42 16 AM" src="https://user-images.githubusercontent.com/814283/162976489-454b8abc-9b0d-4761-a848-86c6dff617be.png">

2022-04-12 13:46 UTC, tmcconechy commented on src/components/ids-input/README.md
> +- `data` when autocomplete is enabled a instance of [IdsDatasource](../../core/README.md)]
```suggestion
- `data` when autocomplete is enabled an instance of [IdsDatasource](../../core/README.md)]
```

2022-04-12 13:46 UTC, tmcconechy commented on src/core/ids-base.scss
> +.highlight {
We should keep this out of ids-base.scss -> i was working on cleaning this up on another PR as this class will end up in every component even if not needed.

You could do it as a mixin instead that way the class isnt directly added and put it in general-mixins? Or just put it where its needed in the component css

2022-04-12 13:46 UTC, tmcconechy commented on src/components/ids-input/demos/autocomplete.html
> +          label="Autocomplete Input 2"
```suggestion
          label="Autocomplete Input (states)"
```

2022-04-13 13:27 UTC, tmcconechy reviewed
All my points look addressed now. Thanks. Except for one about dark mode. I see i attached the wrong file. But it looks like this:

![Screen Shot 2022-04-13 at 9 24 49 AM](https://user-images.githubusercontent.com/814283/163190770-c461c290-d0d4-45d4-ac54-e289978cd724.png)


One other thing i noticed is "No Results" is "hardcoded" in ids-autocomplete.js - should pull this out use Locale.translate() (ids-locale-mixin)

2022-04-13 14:47 UTC, tmcconechy commented
Ok makes sense @jmacaluso711 can you make a separate issue? I can look as i was looking at something similar on that other PR, and i know that it did work when i made the dropdown originally. I think i may have broken this during TS or Webpack rework.

2022-04-13 15:12 UTC, tmcconechy commented
@jmacaluso711 i fixed it on this PR https://github.com/infor-design/enterprise-wc/pull/647/commits/4715cd76fb35e046022fba4e008b76a536450da7#diff-65bc07cdd0a0e5e100943aa1cfd7d9007d73ea78e9decfa94b85e38f4c0ba1f4R37

Was just missing the connectedCallback (think i might have accidentally removed). So the theme mixin isnt registering
If you want to copy that in this branch for any reason feel free. But im willing to approve.

2022-04-13 15:14 UTC, tmcconechy approved these changes

2022-04-14 13:27 UTC, merged