565 - IdsPopup: Improve scrolling behavior
infor-design/enterprise-wc pull request #651
Opened 2022-04-13 20:55 UTC by EdwardCoyle

**Explain the details for making this change. What existing problem does the pull request solve?**
This PR fixes issues related to the scrolling behavior of IdsPopup components:
- Top/Left CSS values are now applied to the IdsPopup's host element instead of its ShadowRoot container
- Extraneous CSS rules that change position style (like some `fixed` and `absolute`) have been removed
- In some cases, `position: relative` has been added to elements that contain an IdsPopup in order to simplify the way it calculates placement
- Some parts of the JS method used for placement have been simplified

**Related github/jira issue (required)**:
Closes #565

**Steps necessary to review your pull request (required)**:
Pull/Build/Run the branch.  Most components should behave exactly as they used to, but will be in the correct place when scrolled.

*New test cases:*
http://localhost:4300/ids-popup/scrolling.html
- Try scrolling the the draggable container, and dragging it to move. 
- Open/Close the Popups.  They should place and behave predictably

http://localhost:4300/ids-data-grid/filter-books.html
- shrink the browser viewport to make the IdsDataGrid scrollable
- scroll it to the right and open some of the filter pickers.  When they open they should appear relatively close to their trigger elements, and the arrow should be placed correctly.

http://localhost:4300/ids-data-grid/filter-custom.html
- Open the filter pickers in the Color and Product ID columns (which are "custom" and added via slot instead of template). When they open they should appear relatively close to their trigger elements, and the arrow should be placed correctly.

*Also smoke test these pages to ensure they still work properly*:
- http://localhost:4300/ids-popup/sandbox.html
- http://localhost:4300/ids-contextual-action-panel
- http://localhost:4300/ids-dropdown
- http://localhost:4300/ids-menu-button
- http://localhost:4300/ids-modal
- http://localhost:4300/ids-popup-menu
- http://localhost:4300/ids-time-picker
- http://localhost:4300/ids-tooltip

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2022-04-14 13:40 UTC, tmcconechy requested changes
A couple things in order of importance


1. on http://localhost:4300/ids-dropdown the dropdown no longer seems to open at all (or its in an invisible spot?)
2. on http://localhost:4300/ids-tooltip/sandbox.html make it so you have to scroll down to the text field and then hover it (its way far up)
![Screen Shot 2022-04-14 at 9 39 52 AM](https://user-images.githubusercontent.com/814283/163402868-ea081a33-2e62-478a-a9a9-58dbfd95f1b7.png)
3. on http://localhost:4300/ids-data-grid/filter-books.html
- if you open the datepicker its cut off
![Screen Shot 2022-04-14 at 9 36 26 AM](https://user-images.githubusercontent.com/814283/163402270-993e68f6-7e72-4da0-b23d-b52a30dbc87e.png)

- the time picker is too close to the icon (but doesnt do it on http://localhost:4300/ids-time-picker)
![Screen Shot 2022-04-14 at 9 36 19 AM](https://user-images.githubusercontent.com/814283/163402317-b46f24ed-4f47-49ed-a960-cbe7c86473bb.png)

2022-04-14 13:40 UTC, tmcconechy commented on src/components/ids-time-picker/ids-time-picker.scss
> +      min-width: 75px;
Is this going to impact sizes? I guess we need to see as we dont have them yet

2022-04-14 16:29 UTC, EdwardCoyle commented on src/components/ids-time-picker/ids-time-picker.scss
> +      min-width: 75px;
I wasn't sure it would.  I tested the dropdown field sizes by digging into the picker shadow root on http://localhost:4300/ids-time-picker and setting the field size and it can still change (something unrelated going on with the listbox size)

2022-04-15 14:13 UTC, tmcconechy commented on src/components/ids-time-picker/ids-time-picker.scss
> +      min-width: 75px;
OK skip it for now...

2022-04-18 13:12 UTC, danielortiz1982 submitted a review, later dismissed
Great job on this PR @EdwardCoyle - This css pattern is a nice way to make sure the positioning of any element inside of the popup is a lot more reliable and more importantly predictable. 👍 
I am approving this PR under the condition that @tmcconechy comments have been addressed.

2022-04-18 13:45 UTC, tmcconechy commented
@EdwardCoyle The only things i still see are

a) datepicker is cut off 
![Screen Shot 2022-04-18 at 9 44 38 AM](https://user-images.githubusercontent.com/814283/163817062-f237c24e-d857-43f4-b34b-686933a88cad.png)
b) if you go in the time field and type: 1:00 AM and hit enter the timepicker opens

If you want to punt on those for now let me know and i'll approve and we can make an issue? But the datepicker one does seem related

2022-04-26 11:31 UTC, EdwardCoyle commented
@tmcconechy @danielortiz1982 I think what's left of the visual regressions here are acceptable:
- The menu-based ones are displaying "more" text than before due to some adjustments in the menu item CSS
- The standalone CSS examples for IdsAbout and IdsTooltip needed some manual correction due to the Popup changes
- Not sure about the minor shifts in size/padding on IdsEmptyMessage or IdsWeekView

2022-04-26 18:08 UTC, tmcconechy approved these changes

2022-04-27 22:34 UTC, deep7102 approved these changes
LGTM 🍌

2022-04-28 14:01 UTC, merged