502 accordion features fix
infor-design/enterprise-wc pull request #657
Opened 2022-04-18 14:56 UTC by jeffwa428

**Explain the details for making this change. What existing problem does the pull request solve?**
- Add a setting to disable accordion-header similar to the [old version](https://main-enterprise.demo.design.infor.com/components/accordion/example-disabled.html)
- Add an example like the [old version](https://main-enterprise.demo.design.infor.com/components/accordion/test-different-header-types.html) showing how to set an icon in the slot and hide the chevron.
- Add events to replace selected expanded and collapsed events. With tests
- Update readme settings files for all accordion settings, events and methods (like ids-tag)
- Improve coverage as much as possible
- Improve new navigation methods to account for disabled/hidden/collapsed (children inside collapsed panes should become tabIndex="-1")
- 
**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise-wc/issues/502

**Steps necessary to review your pull request (required)**:

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [ ] A note to the change log.

2022-04-18 16:55 UTC, tmcconechy approved these changes
Looks good to me..

2022-04-18 16:55 UTC, tmcconechy commented on src/components/ids-accordion/ids-accordion.ts
> +      attributes.DISABLED
Minor but keep in order

2022-04-18 18:14 UTC, tmcconechy requested changes
@jeffwa428 sorry i thought of one thing looking at this again. As a general rule we should use colors for disabled not opacity? So can you change the css to use the color instead of the opacity rules (and check the themes in https://main-enterprise.demo.design.infor.com/components/accordion/example-disabled.html)

2022-04-19 14:38 UTC, tmcconechy commented
@jeffwa428 you will also have to add disabled colors for the other themes. If you try dark mode and high contrast ect then then component doesnt appear disabled there

2022-04-21 11:03 UTC, andriivarhanov reviewed
looks good, some findings:
- comparing to the original version it looks like disabled accordion panel should not have cursor pointer and focused styles. Steps:
  - go to http://localhost:4300/ids-accordion/disabled.html
  - click on chevron icon
  - see box shadow and border
<img width="615" alt="image" src="https://user-images.githubusercontent.com/5204821/164443179-60bd09b0-9b79-47e7-b8a7-7b443b7e7780.png">

- please change chevron icon color in dark theme, same for slotted icon 

<img width="615" alt="image" src="https://user-images.githubusercontent.com/5204821/164444290-c99eac83-8675-4bf9-a711-78c6bfb0c9c9.png">

2022-04-25 13:35 UTC, danielortiz1982 commented on src/components/ids-accordion/ids-accordion-header.scss
> +// :host([disabled='true']) {
This PR looks good so far @jeffwa428 - If these styles are not going to be used or are not needed please remove on your next commit. Thanks.

2022-04-25 14:39 UTC, tmcconechy commented
There is a small lint issue https://github.com/infor-design/enterprise-wc/runs/6158003635?check_suite_focus=true#step:7:9

2022-04-25 14:51 UTC, tmcconechy commented
Also one other thing in wondering if these handlers are needed https://github.com/infor-design/enterprise-wc/pull/657/files#diff-5ca6055f470a0a306082a01e8e65e4cac0601bca8fc275bd80a72dc8fa6cb8a5R263 -> should only need the original one... These probably never fire?

2022-04-25 19:28 UTC, jeffwa428 commented
> Also one other thing in wondering if these handlers are needed https://github.com/infor-design/enterprise-wc/pull/657/files#diff-5ca6055f470a0a306082a01e8e65e4cac0601bca8fc275bd80a72dc8fa6cb8a5R263 -> should only need the original one... These probably never fire?

Expanded/Collapsed events are fired when we toggle accordion. This is one of the requirements and we also discussed it before. So we have 3 events defined. Did I misunderstand something?

2022-04-25 19:33 UTC, tmcconechy commented
@jeffwa428 no you got it right that they should fire with `triggerEvent` but i dont think they need to be watched here https://github.com/infor-design/enterprise-wc/pull/657/files#diff-5ca6055f470a0a306082a01e8e65e4cac0601bca8fc275bd80a72dc8fa6cb8a5R263-R270

Unless that does something im not understanding? So maybe just remove those highlight lines if that makes sense to you?

2022-04-26 08:55 UTC, andriivarhanov approved these changes
requested changes have been fixed, looks good, thank you

2022-04-26 12:51 UTC, EdwardCoyle approved these changes
@jeffwa428 Looks great!

2022-04-26 12:55 UTC, merged