Ids multiselect 363
infor-design/enterprise-wc pull request #742
Opened 2022-05-25 20:26 UTC by Jah25

**Explain the details for making this change. What existing problem does the pull request solve?**

Addes Ids-Multiselect component to the project. This component is a child of Ids-Dropdown and extends it's functionality allowing for a styled dropdown that lets end users select multiple options.

**Related github/jira issue (required)**:

closes (#363)[https://github.com/infor-design/enterprise-wc/issues/363]

**Steps necessary to review your pull request (required)**:

- run the build locally and navigate to http://localhost:4300/ids-multiselect/example.html
- the first example should be disabled, clicking the tag close button should not do anything, the menu should not open when clicked
- the second option should have a preselected option 'New Jersey'
- open the second option, it should display a list of options with checkboxes on the left, 'New Jersey' should be checked
- select an option, the display should be updated with the new selection in a comma separated string
- repeat until you have three options selected, further selections should be prevented
- example three should be empty
- make a selection, the display should have a ids-tag with a dismiss button
- click the dismiss button on the tag, the dismissed option should be removed and unselected

**Included in this Pull Request**:
- [X] An e2e or functional test for the bug or feature.
- [X] A note to the change log.

2022-05-26 14:31 UTC, tmcconechy requested changes
Looks pretty good - a bunch of trivial stuff in the comments inline. In terms of behaviors im seeing a couple of things in the demo:

1. Can you label the examples they all say "Test Dropdown". Suggest
Non-Tag Multiselect
Tag Multiselect
Disabled Multiselect
1. when selected the check/uncheck has the wrong style:
<img width="345" alt="Screen Shot 2022-05-26 at 10 28 38 AM" src="https://user-images.githubusercontent.com/814283/170508837-76ef39d3-a027-41b6-866d-e10b814a3f1d.png">
<img width="319" alt="Screen Shot 2022-05-26 at 10 28 31 AM" src="https://user-images.githubusercontent.com/814283/170508839-4723721f-743f-4c02-9705-35ce785def2b.png">
1. A lot of space between items
<img width="347" alt="Screen Shot 2022-05-26 at 10 29 31 AM" src="https://user-images.githubusercontent.com/814283/170508984-b5d2c3c7-9eba-44e1-a714-4c4f7ae7775e.png">
1. Can you add side by-side example or put it in the todos for later
1. on the second dropdown i can only select 3?
1. each time i select it closes
1. dont seem to be able to arrow down past the selected items
1. in general style should be https://main-enterprise.demo.design.infor.com/components/multiselect/example-index.html

2022-05-26 14:31 UTC, tmcconechy commented on src/components/ids-dropdown/ids-dropdown.ts
> +  /*
Can possibly remove this commented code

2022-05-26 14:31 UTC, tmcconechy commented on src/components/ids-list-box/ids-list-box-option.scss
> +  //background-color: plum;
Can remove?

2022-05-26 14:31 UTC, tmcconechy commented on src/components/ids-multiselect/README.md
> +multiselect inherits most of it's settings from ids-dropdown, please refer to that document [here](../ids-dropdown/README.md) for more details. below are listed new settings or ones that have been mo
```suggestion
IdsMultiselect inherits most of it's settings from ids-dropdown, please refer to that document [here](../ids-dropdown/README.md) for more details. Below are listed new settings or ones that have been modified or are different from ids-dropdown:
```

2022-05-26 14:31 UTC, tmcconechy commented on src/components/ids-multiselect/TODO.md
> +
```suggestion
```

2022-05-26 14:31 UTC, tmcconechy commented on src/components/ids-multiselect/ids-multiselect.scss
> +ids-trigger-field{
```suggestion
ids-trigger-field {
```

Lint might complain about all of these?

2022-05-26 14:31 UTC, tmcconechy commented on src/components/ids-multiselect/ids-multiselect.ts
> + * @inherits IdsElement
```suggestion
 * @inherits IdsDropdown
```

2022-05-26 14:31 UTC, tmcconechy commented on src/components/ids-multiselect/ids-multiselect.ts
> +    window.requestAnimationFrame(() => {
```suggestion
    requestAnimationFrame(() => {
```

2022-05-26 14:31 UTC, tmcconechy commented on src/components/ids-multiselect/ids-multiselect.ts
> +      attributes.TAGS,
Alpha Order?

2022-05-26 14:31 UTC, tmcconechy commented on src/components/ids-multiselect/ids-multiselect.ts
> +    this.unlisten('Enter');
Can remove all unneeded code in comments

2022-05-26 14:38 UTC, danielortiz1982 commented on src/components/ids-dropdown/ids-dropdown.ts
> +        return;
This looks great, one thing. Since you do not have an else statement you really do not need the `return` I think you can remove it.

2022-05-26 14:46 UTC, danielortiz1982 commented on src/components/ids-multiselect/ids-multiselect.ts
> +    window.requestAnimationFrame(() => {
This looks good, however I am not sure a `RAF` is a good solution for resetting the dirty tracking. Using a `RAF` inside the connectedCallback can possibly cause some unintended outcomes. Maybe try creating a fn that directly reset the dirty tracker when needed instead of every time connectedCallback is run.

2022-05-26 14:53 UTC, danielortiz1982 commented on src/components/ids-multiselect/ids-multiselect.ts
> +    this.onEvent('click', this, (e: any) => {
Nice solution here, one thing. Can you move these into there own functions. We want to keep the attachClickEvent method lean. Having too much business logic in the attachClickEvent can cause confusion.

2022-05-26 14:55 UTC, danielortiz1982 commented on src/components/ids-multiselect/ids-multiselect.ts
> +     * TO DO: update to select and group functionality to follow updates to ids-dropdown
If this will not make it into `main` on this merge can this be removed for now? Maybe you can save this in a different branch for later use.

2022-05-26 14:58 UTC, danielortiz1982 commented on src/components/ids-multiselect/ids-multiselect.ts
> +            option.querySelector('ids-checkbox').checked = 'false';
This looks pretty good, however If possible let's try to stay away from using `RAF`  to update values.

2022-05-26 14:59 UTC, Jah25 commented on src/components/ids-multiselect/ids-multiselect.scss
> +ids-trigger-field{
sure I can change it are you seeing errors on your end, my lint hasn't had any issues with this one

2022-05-26 15:35 UTC, tmcconechy commented on src/components/ids-multiselect/ids-multiselect.scss
> +ids-trigger-field{
Ok thought it was - but please, prefer the space for consistency

2022-05-27 13:50 UTC, Jah25 commented on src/components/ids-multiselect/ids-multiselect.ts
> +    this.onEvent('click', this, (e: any) => {
Hey I was just looking this one, attachClickEvent was a carve out from attachEventHandlers to keep business logic off of that, should I isolate each click event further into it's own function.

2022-05-31 15:08 UTC, tmcconechy commented
Adding WIP tag until complete

2022-05-31 15:54 UTC, EdwardCoyle reviewed
Just to elaborate on some of the usability/behavior Tim called out above because I think it's important we address:

"Keep open" on select behavior
- Open http://localhost:4300/ids-multiselect/example.html
- Use the third Multiselect and select any item
- The multiselect can stay open between selections.  It should be configurable -- other IDS components use `keep-open` (boolean) to prevent the component from hiding on selection

Clicking the "X" on a tag shouldn't affect the open/closed state of the dropdown - should only remove tags from the list

Keyboard navigation seems to work, but only in "selected items" list:
- Open http://localhost:4300/ids-multiselect/example.html
- Use the third multiselect and select multiple items
- Use the keyboard arrows to open the list and navigate to the bottom.  Once focus is on the last item in the "selected" list it doesn't go further.
 
After that, this should be good to go

2022-05-31 15:54 UTC, EdwardCoyle commented on src/components/ids-multiselect/ids-multiselect.ts
> +        // #updateMaxSelections(value);
Can this be removed?

2022-05-31 15:54 UTC, EdwardCoyle commented on src/components/ids-multiselect/ids-multiselect.ts
> +     * TO DO: update to select and group functionality to follow updates to ids-dropdown
Maybe we can add this to TODO.md with a brief description of what needs to be updated, and specifically call out "add to `attachClickEvent`" for context

2022-05-31 15:54 UTC, EdwardCoyle commented on src/components/ids-multiselect/ids-multiselect.ts
> +    this.onEvent('click', this, (e: any) => {
I'm guessing this was updated, since `#handleOptionClick()` appears to contain all the logic?

2022-05-31 15:54 UTC, EdwardCoyle commented on src/components/ids-multiselect/ids-multiselect.ts
> +    Base.prototype.connectedCallback.apply(this);
`Base.prototype.connectedCallback.apply(this);` is a more "legacy" version of `super.connectedCallback();`. Thinking this would be better:

```suggestion
    super.connectedCallback();
    this.#populateSelected();
```

2022-05-31 15:54 UTC, EdwardCoyle commented on src/components/ids-multiselect/ids-multiselect.ts
> +   */
Maybe another one that can go in TODO.md?

2022-06-16 13:43 UTC, tmcconechy commented
@Jah25 please let us know when this is ready to review again by removing the WIP flag

2022-06-24 14:18 UTC, tmcconechy commented
I'lll double check when they run

2022-06-24 14:54 UTC, tmcconechy requested changes
Still seeing a number of issues but i will just mention the most important ones:

1. When opening the multiselect and selecting it closes each time you selectonhttp://localhost:4300/ids-multiselect/example.html
2. the styling is pretty far off the old on https://main-enterprise.demo.design.infor.com/components/multiselect/example-index.html
<img width="367" alt="Screen Shot 2022-06-24 at 10 51 57 AM" src="https://user-images.githubusercontent.com/814283/175561060-f87ab1ef-94ab-44a9-ac47-b493035e70f8.png">
3. keyboard doesnt work at all when i tried down arrow it unselected all my items if some selected, if non selected it works to arrow down but the styling is off on the checkbox. if i click space there is an error.

2022-06-24 14:55 UTC, tmcconechy commented on src/components/ids-multiselect/demos/example.html
> +            <ids-list-box-option id="nj" value="nj"><ids-checkbox checked="true" label="New Jersey" class="justify-center"></ids-checkbox></ids-list-box-option>
This may be part of the styling issue (should not be centered)

2022-06-24 14:56 UTC, tmcconechy commented on src/components/ids-multiselect/demos/example.html
> +        <ids-multiselect id="dropdown-3" tags="true" label="Test Dropdown (tags; 10 max choices)" max="10" dirty-tracker="true">
```suggestion
        <ids-multiselect id="dropdown-3" tags="true" label="Test Dropdown (tags and 10 max choices)" max="10" dirty-tracker="true">
```

2022-06-24 14:57 UTC, tmcconechy commented
Also for the percy tests i can see the wrong page is being used https://percy.io/00aaa841/enterprise-wc/builds/19166497/changed/1075712790?browser=chrome&browser_ids=23&subcategories=unreviewed%2Cchanges_requested&viewLayout=side-by-side&viewMode=new&width=1280&widths=375%2C1280

2022-06-24 15:29 UTC, Jah25 commented
> Also for the percy tests i can see the wrong page is being used https://percy.io/00aaa841/enterprise-wc/builds/19166497/changed/1075712790?browser=chrome&browser_ids=23&subcategories=unreviewed%2Cchanges_requested&viewLayout=side-by-side&viewMode=new&width=1280&widths=375%2C1280

just put in fix

2022-06-24 15:33 UTC, tmcconechy commented
ok, do what you can with it - i would say those are the main things left here that i can. see:

IDEA:
Concerning the checkbox actually instead of using `ids-checkbox`component there is an option to use the https://github.com/infor-design/enterprise-wc/blob/main/src/mixins/sass/ids-checkbox-mixin.scss (so just the styling). Then attach that to the list item,  that we you can customize it a bit bettter as the styles end up in the component.

Also the padding / list items sizes ect could be improved

2022-06-24 15:36 UTC, tmcconechy commented
@Jah25 also let me know if you need me to dive in on any part..  just ping me in teams

2022-06-29 17:56 UTC, EdwardCoyle approved these changes
Looks really good now, thanks @Jah25

2022-06-29 19:16 UTC, merged