729 - Implement Module Tabs
infor-design/enterprise-wc pull request #745
Opened 2022-05-26 21:21 UTC by EdwardCoyle

**Explain the details for making this change. What existing problem does the pull request solve?**
This PR implements the 4.x Module Tabs style as an IdsTabs color variant:
- Module Tabs color variant has been implemented
- Light/Dark/Contrast themes for Module Tabs added
- Re-organizes SCSS styles to reduce amount of style rules needed and better share behaviors
- Fixed some issues with selection behavior occasionally not triggering content panel changes
- Adds Disabled state/functionality to all tabs styles
- Adds "Actionable" Tabs and `onAction` callback that can be applied to specific tabs (takes precedent over selection, replacing the built-in add/remove/app menu behaviors from 4.x Tabs and generalizes them to user-defined behavior).
- Adds examples/docs

**Related github/jira issue (required)**:
Closes #729

**Steps necessary to review your pull request (required)**:
Pull/Run/Build, then review the following:

http://localhost:4300/ids-tabs/example.html
- Review behavior... should be the same as [`main`](https://main.wc.design.infor.com/ids-tabs/example.html), except for the disabled tab.  The disabled tab should be ignored by keyboard focus, and should not activate its content panel when clicked.

http://localhost:4300/ids-tabs/vertical.html
- Review behavior, should be similar to its [`main`](https://main.wc.design.infor.com/ids-tabs/vertical.html) counterpart but also has a disabled tab now
- Tabs don't stretch 100% of the page width.  This is how vertical tabs previously behaved in 4.x (width control was optional)

http://localhost:4300/ids-tabs/header-tabs.html
- Review behavior, should be similar to its [`main`](https://main.wc.design.infor.com/ids-tabs/header-tabs.html) counterpart but also has a disabled tab now

http://localhost:4300/ids-tabs/module.html
- Ensure all states appear easy to read and "correct".  
- Review all states on light/dark/contrast modes.  Some colors are slightly different than 4.x
- When selecting the (actionable) App Menu tab, console messages should be logged
- When selecting the (actionable) "+" tab, New tabs should be added to the tab list.  If a new tab is selected, its content panel should be displayed.
- When selecting the (actionable) "Reset" tab, any new tabs previously added should be removed and the page should appear to "reset"
- Try adding a new tab and selecting it to see its content activated.  Next, use the reset tab to remove it.  The "selected" tab and the content panel should change to display a tab that is still present in the tab list.
- Try making the browser viewport smaller, or add many more tabs.  A "More" Tab should display and accurately reflect the number of tabs currently hidden by overflow.
- Use the "More" Tab's popup menu to select an overflowed tab.  Either its content should be displayed, or an actionable tab like "+" or "Reset" should perform its corresponding action.

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2022-06-09 14:45 UTC, andriivarhanov reviewed
looks great, just two small things:
- initial focus:
  - go to http://localhost:4300/ids-tabs/header-tabs.html
  - press Tab on the keyboard
  - see no focused styles on the active tab
  - there are some mix of 0 and -1 tabindex
![Screen Shot 2022-06-09 at 5 33 31 PM](https://user-images.githubusercontent.com/5204821/172875492-36c58e34-cb52-4119-add0-f0590cada561.png)

2022-06-09 14:45 UTC, andriivarhanov commented on src/components/ids-tabs/ids-tab-more.ts
> +        <ids-text id="more-text" size="22"${selectedAttr}> ${this.locale?.translate('More')}</ids-text>
please use `translate-text=“true”` its-text attribute here if possible and remove `#attachLocaleEvents()` since ids-text will respond to container changing language

2022-06-09 19:03 UTC, tmcconechy requested changes
Looks great! Some minor things ranked in order (my perception anyways)

- Dont seem to be able to tab to the tabs and work with them
- the menu has the wrong text alignment (works on other demo pages so maybe just when in here...)
![Screen Shot 2022-06-09 at 2 57 11 PM](https://user-images.githubusercontent.com/814283/172923977-8fdfe391-2129-48d4-b4d2-fa8190f27117.png)
- this text isnt really correct as its not just for mingle - maybe "Top Level Tabs"
![Screen Shot 2022-06-09 at 2 58 06 PM](https://user-images.githubusercontent.com/814283/172923862-ec0ba185-9513-4540-b49e-d472debfa95f.png)
- if i click + a lot i cant in the situation where first it clicks the more menu and secondly the + disappears (if it helps we could use a shorter ... icon instead of a count in the menu)
![Screen Shot 2022-06-09 at 3 01 15 PM](https://user-images.githubusercontent.com/814283/172924241-e4a4c1a8-4a12-4637-b2cb-ce683ee5b49a.png)
- should we have a tooltip on the + and revert button (translated?)
- should the app menu open (doesn't have to just a question)

2022-06-10 19:37 UTC, EdwardCoyle commented on src/components/ids-tabs/ids-tab-more.ts
> +        <ids-text id="more-text" size="22"${selectedAttr}> ${this.locale?.translate('More')}</ids-text>
I was not aware of the benefit of using the attribute instead, thanks!

2022-06-13 12:47 UTC, andriivarhanov approved these changes

2022-06-13 15:42 UTC, tmcconechy submitted a review, later dismissed
This is good for me aside from other comments

2022-06-14 13:58 UTC, tmcconechy submitted a review, later dismissed
Just out of date with main but looks good to me...

2022-06-14 14:07 UTC, danielortiz1982 submitted a review, later dismissed
@EdwardCoyle Really good job on this PR 🚀  looks nice and clean.

2022-06-14 16:24 UTC, andriivarhanov approved these changes

2022-06-14 16:37 UTC, merged