551: Fix IdsColorPicker and IdsColor remaining features
infor-design/enterprise-wc pull request #746
Opened 2022-05-31 00:42 UTC by clayinfor

**Explain the details for making this change. What existing problem does the pull request solve?**

Fixes remaining Bugs/Features for a 100% IdsColorPicker Component

**Related github/jira issue (required)**:

Closes #551

**Steps necessary to review your pull request (required)**:

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [ ] A note to the change log.

2022-05-31 17:46 UTC, EdwardCoyle reviewed
Looks pretty good so far!  I saw one usability thing with the tooltip -- appears that there's one coming from the field swatch no matter the setting:

![Screen Shot 2022-05-31 at 1 13 13 PM](https://user-images.githubusercontent.com/3249601/171251011-b95792d1-a6c0-4e76-a2c5-a016622bf56e.png)

2022-06-01 11:23 UTC, andriivarhanov reviewed
looks good, nothing major, some findings:
- please fix tests and prod build
- when setting input value and open popup the value should be focused

![image](https://user-images.githubusercontent.com/5204821/171393016-30546efa-59f2-454f-a82a-40fae6391257.png)

2022-06-01 11:23 UTC, andriivarhanov commented on src/components/ids-color-picker/ids-color-picker.ts
> +        <ids-text audible="true">color picker trigger</ids-text>
it should be translated text from locale, I'm just not sure which one, it looks like we don't have `ColorpickerTriggerButton` key in locale messages @tmcconechy could you please advise what to use here?

2022-06-01 11:26 UTC, andriivarhanov commented on src/components/ids-color-picker/ids-color-picker.ts
>        attributes.ADVANCED,
please list all used attributes here

2022-06-01 13:08 UTC, tmcconechy commented on test/ids-color/ids-color-func-test.ts
> +  it.skip('shows black checkmark when IdsColor.class contains "light" class', () => {
I dont mind skipped tests as a TODO point for later.

2022-06-01 13:14 UTC, tmcconechy commented on src/components/ids-color-picker/ids-color-picker.ts
> +        <ids-text audible="true">color picker trigger</ids-text>
you can put a new one in locale/cultures/en-us.js -> just put the english string in that one file for now like `TimepickerTriggerButton`

It will eventually get translated from there. However im not sure about the current text. I think it should be something like: "Click to Open Color Picker" and we change TimepickerTriggerButton as well.

2022-06-01 13:15 UTC, tmcconechy commented on src/components/ids-color-picker/ids-color-picker.ts
> +        <ids-text audible="true">Pick Custom Color</ids-text>
Same see above - I think click to open color picker still applies so can use the same new translation in 2 places

2022-06-01 13:26 UTC, danielortiz1982 commented on src/components/ids-color-picker/ids-color-picker.scss
> +  .color-input {
@clayinfor  This look great so far. I can not tell, can you please sure any `position: absolute` selector has a parent that is `position: relative` Thanks!

2022-06-01 14:31 UTC, tmcconechy requested changes
Some smaller issues (mostly minor but worth a quick look if possible)

1. on http://localhost:4300/ids-color/example.html if you tab through, some have a nice focus state and some are missing. Also can the focus ring have a border radius?
2. similar on the popup i see a double focus state (outline showing)
Not show here i couldnt screen shot it:
![Screen Shot 2022-06-01 at 10 16 26 AM](https://user-images.githubusercontent.com/814283/171429168-2330a2eb-01e7-4569-9d3d-7fab80b653d8.png)
3. can make the width bigger on the tooltip
![Screen Shot 2022-06-01 at 10 19 55 AM](https://user-images.githubusercontent.com/814283/171429274-a01b5ef7-36c8-4c57-9075-7229bfeafd20.png)

2022-06-01 14:31 UTC, tmcconechy commented on src/components/ids-color-picker/README.md
> +- `tooltips` {boolean} If true, the color-swatchs will display tooltips on mouseover. Valid values are 'true' | 'false'
Could consider the setting `suppressTooltips` i used elsewhere where its on by default. Not sure whats the best here so just putting this as an option

2022-06-01 14:31 UTC, tmcconechy commented on src/components/ids-color-picker/ids-color-picker.scss
> +  // contain: content;
Can fully remove. Not really needed. But it helps with rendering performance when possible

2022-06-08 13:25 UTC, tmcconechy approved these changes

2022-06-08 16:59 UTC, tmcconechy commented
@clayinfor the only thing im wondering is whats up with this page https://percy.io/00aaa841/enterprise-wc/builds/18745859/changed/1051830286?browser=chrome&browser_ids=23&subcategories=unreviewed%2Cchanges_requested&viewLayout=side-by-side&viewMode=new&width=1280&widths=375%2C1280 ?

Do we need a quick adjustment to the responsive grid?

2022-06-09 14:15 UTC, merged

2022-06-09 15:20 UTC, clayinfor commented on src/components/ids-color-picker/demos/example.html
> +          <ids-color hex="#999999" class="light"></ids-color>
will change these class-names to `light-color` / `dark-color`... these class-names are what determine if a light-checkmark or dark-checkmark is used...

2022-06-09 16:03 UTC, tmcconechy commented on src/components/ids-color-picker/demos/example.html
> +          <ids-color hex="#999999" class="light"></ids-color>
Sure now that its merged anything else just do a new PR. Sorry if i missed waiting for some details.