708 - IdsModal Additional Features
infor-design/enterprise-wc pull request #765
Opened 2022-06-13 21:42 UTC by EdwardCoyle

**Explain the details for making this change. What existing problem does the pull request solve?**
This PR improves the behavior of the IdsModal/IdsContextualActionPanel and adds some additional features:
- Implements the `fullsize` setting from 4.x on IdsModal, allowing the Modal to take over the full width/height of the browser viewport with responsive/scrollable behavior in the content area
- Adds ability for Modals to respond to breakpoint changes using new IdsBreakpointMixin
- Fixes small regression in Focus Capture behavior (missing as of a recent PR)
- Adds example of how to disable `onOutsideClick` default behavior
- Adds missing event handling for `aftershow`/`afterhide` to Modals
- Fix animation bugs in overlay/modal fading and scaling

**Related github/jira issue (required)**:
Closes #708
Closes #553 

**Steps necessary to review your pull request (required)**:
Pull/Build/Run, then:

http://localhost:4300/ids-modal/example.html
- Open the Modal
- Shrink the browser viewport to less than 600px.  At this breakpoint, the modal becomes full size.  Enlarge the browser viewport to disable fullsize mode

http://localhost:4300/ids-modal/fullsize.html
- Note the radio buttons that represent supported IDS Breakpoints
- Choose a radio and open the Modal.  Scale the browser viewport to below the specified width.  The modal should switch to fullsize mode when below the breakpoint, and switch back to normal when moving above the breakpoint.
- Select `Never`.  The modal should never change to fullsize in this case.
- Select `Always`. The modal should always be fullsize in this case.

http://localhost:4300/ids-modal/keep-open.html
- Open the modal
- Uncheck the checkbox and click out into the Overlay area.  The modal should not close
- Check the box again and click out into the Overlay area.  Now the modal should close

http://localhost:4300/ids-modal/focus.html
- Open the modal
- Use the "Tab" key and "Shift+Tab" to navigate contents within the Modal.  Focus should never leave elements inside the Modal - it should cycle back to the first/last elements inside if necessary.

Also, smoke test the following components which are all based on IdsModal.  All should switch to fullsize mode at the 600px (sm) breakpoint by default:
- http://localhost:4300/ids-about/example.html
- http://localhost:4300/ids-contextual-action-panel/example.html
- http://localhost:4300/ids-message/example.html

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2022-06-14 14:11 UTC, tmcconechy requested changes
Really only some minor things. Looks really good

1. build failing with lint issue(s)
2. curious what http://localhost:4300/ids-modal/keep-open.html is for - doesnt hurt but wondering the use case
3. similar issue to https://github.com/infor-design/enterprise/pull/6567 -> do we need to change to RGBA here instead of opacity. The issue im seeing on all modal pages is if you want carefully when it loads you see the color change after a moment (not sure if this video captures it good enough https://watch.screencastify.com/v/7y2mExHq7HNNTT1r3kyZ)

2022-06-14 14:11 UTC, tmcconechy commented on src/components/ids-hidden/ids-hidden.ts
> +import { attributes, Breakpoints } from '../../core/ids-attributes';
breakPoints maybe (lower case?)

2022-06-14 14:11 UTC, tmcconechy commented on src/components/ids-hidden/ids-hidden.ts
> +import { attributes, Breakpoints } from '../../core/ids-attributes';
And would it be better in ids-breakpoint-utils so in some cases might just need one import?

2022-06-14 14:11 UTC, tmcconechy commented on test/helpers/match-media-mock.ts
> +Object.defineProperty(window, 'MediaQueryList', {});
Minor: but should this be moved up to the other comment?

2022-06-14 14:13 UTC, EdwardCoyle commented on src/components/ids-hidden/ids-hidden.ts
> +import { attributes, Breakpoints } from '../../core/ids-attributes';
`Breakpoints` is the TS type.  `breakpoints` is the object that contains the breakpoints.  They're both needed

2022-06-14 14:16 UTC, EdwardCoyle commented
@tmcconechy the `keep-open` test demonstrates functionality that was in 4.x that isn't an explicit setting in 5.x -- just overrides the default `onOutsideClick` behavior to prevent the modal from closing.  It's described up at the top if you want more info

2022-06-14 14:18 UTC, tmcconechy commented on src/components/ids-hidden/ids-hidden.ts
> +import { attributes, Breakpoints } from '../../core/ids-attributes';
What about IdsBreakpoints for the type? I think thats what we had been doing? Super minor. I think im missing the point

2022-06-14 21:17 UTC, EdwardCoyle commented
@tmcconechy I see the slight darkening you're describing, but doesn't seem consistent.  I tried replacing the usage of opacity with an `rgba()` background color instead, and it seems we're getting the same result.  Not sure what's going on there but I see it on https://main.wc.design.infor.com/ids-modal/example.html as well

2022-06-15 08:28 UTC, andriivarhanov reviewed
looks great, nothing major, just one thing to clean up a bit

2022-06-15 14:32 UTC, EdwardCoyle commented on src/components/ids-popup/ids-popup.ts
> +    // this.style.top = `50%`;
Thanks Andrii, good catch 👍

2022-06-15 14:47 UTC, tmcconechy approved these changes
ok then aside from that everything looks good (once the checks pass)

2022-06-15 15:08 UTC, andriivarhanov approved these changes

2022-06-16 13:53 UTC, deep7102 approved these changes
Great! looks nice 🍌

2022-06-16 17:55 UTC, merged