673 - IdsCalendar Component
infor-design/enterprise-wc pull request #770
Opened 2022-06-20 20:21 UTC by jdilag90

**Explain the details for making this change. What existing problem does the pull request solve?**
Create Ids Calendar Component. Add events to month view
Fix accordion panel expand animation when accordion component is initialized

**Related github/jira issue (required)**:
Closes #673 
Closes #675 

**Steps necessary to review your pull request (required)**:
1. Checkout branch, `npm run start`
2. Go to http://localhost:4300/ids-calendar/example.html
3. Compare to [enterprise](https://main-enterprise.demo.design.infor.com/components/calendar/test-allow-single-pane.html)

**Settings**
`date` - Should set view to provided date. Attribute should also reflect date from user UI date navigation.
`show-legend` - Should add/remove legend pane if set/unset
`show-details` - Should add/remove details pane if set/unset

**Switching views**
Test changing between month/week/day views via view picker menu button in toolbar
Should change to view corresponding to selected/focused date

**Legend Pane (left side)**
Toggling checkboxes in legend pane should filter calendar events in month/week/day view

**Details Pane (right side)**
Only visible in month view. 
With month view selected, click (keyboard navigate) on different days. 
Details pane should update with events within selected day.
Accordion should no longer flash an expanded state when details pane is rendered with calendar events.

**Calendar events**
Calendar should populate month/week/day views with calendar events
1. Select month view
2. Navigate to date `10/22/2019`
3. Click on `4+ more` (indicates count of calendar events that overflow table cell)
4. It should switch to day view of clicked overflow element

**RTL**
Switch locale to Arabic.
It should make elements RTL in month/week/day view
Any text containing dates/times should be localized

**Mobile Layout (when Month view selected)**
Switch to mobile layout through dev tools. Or resize browser width to less than `840px` (md breakpoint size)
It should hide legend pane. 
It should show horizontal axis calendar event type labels under month view element
It should render list of event details within selected/focused day.

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [ ] A note to the change log.

2022-06-21 13:58 UTC, tmcconechy requested changes
Looks awesome. Just a few minor things

1. get too know and use the  inline/block start/end properties instead of right and left so the RTL rules aren't even needed
2. Minor commenting and questions/comments inline
3. http://localhost:4300/ the calendar isnt appearing on that page so just need to add it here: https://github.com/infor-design/enterprise-wc/blob/main/src/components/ids-demo-app/demos/index.ts
4. The more is sentence case (also is it should use the translations as its not changing when i change language)
<img width="95" alt="Screen Shot 2022-06-21 at 9 54 42 AM" src="https://user-images.githubusercontent.com/814283/174816995-c56356e8-0cd9-4a78-ae2f-bf4859daaf94.png">
5. Can we set a width on the text so that ... shows. I think this means even bigger/longer text will bleed over the icon:
<img width="807" alt="Screen Shot 2022-06-21 at 9 56 35 AM" src="https://user-images.githubusercontent.com/814283/174817494-b755a146-a629-41ef-aad8-cb40d99fcc29.png">
6. (minor) but on http://localhost:4300/ids-calendar/example.html if you go to the weekview then try to hover each event (go one by one top to bottom and then back up). You see some get the tooltip and some dont...(sort of randomly)

Thats all i could see. Looks good

2022-06-21 13:58 UTC, tmcconechy commented on src/components/ids-calendar/ids-calendar-event.scss
> +      right: 0;
Instead of right and left we had been using properties like `inset-inline-start` and `inset-inline-end`.

This will prevent the need for any RTL specific rules I think you can change all of these:  https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Logical_Properties

See also:
https://medium.com/the-non-traditional-developer/stop-using-left-right-top-and-bottom-in-your-css-e39905adde65

2022-06-21 13:58 UTC, tmcconechy commented on src/components/ids-calendar/ids-calendar.scss
> +    border-left-width: 4px;
Same here can use `border-inline-end-width` and` border-inline-start-width` and get rid of the rtl rule...

(i think this one is border-inline-start-width)

2022-06-21 13:58 UTC, tmcconechy commented on src/components/ids-month-view/ids-month-view.scss
>  :host([dir='rtl']) {
Almost all these can possibly be replaced with things like `text-align-last` and and `padding-inline`

2022-06-21 13:58 UTC, tmcconechy commented on src/components/ids-month-view/ids-month-view.ts
> +  #removeAllEvents() {
Could add a comment? Also would this be something publicly usable to remove all events and clear the calendar (or is there another method for that)

2022-06-21 13:58 UTC, tmcconechy commented on src/components/ids-month-view/ids-month-view.ts
> +  filterEventsByMonth(data: CalendarEventData[] = []): CalendarEventData[] {
Please do add comments to the public methods especially.

2022-06-21 13:58 UTC, tmcconechy commented on src/components/ids-week-view/ids-week-view.scss
> +  margin: 0 8px;
`margin-inline-end` maybe?

2022-06-21 13:58 UTC, tmcconechy commented on test/ids-calendar/ids-calendar-e2e-test.ts
> +describe('Ids Week View e2e Tests', () => {
```suggestion
describe('Ids Calendar View e2e Tests', () => {
```

2022-06-21 20:36 UTC, jdilag90 commented on src/components/ids-calendar/ids-calendar-event.scss
> +      right: 0;
Removed RTL styles. Now uses `margin-inline-start`

2022-06-21 20:37 UTC, jdilag90 commented on src/components/ids-calendar/ids-calendar.scss
> +    border-left-width: 4px;
Removed border-left-width. Now using `border-inline-start-width`

2022-06-21 20:41 UTC, jdilag90 commented on src/components/ids-month-view/ids-month-view.ts
> +  #removeAllEvents() {
Updated to make `removeAllEvents` public with comments

2022-06-21 20:42 UTC, jdilag90 commented on src/components/ids-month-view/ids-month-view.ts
> +  filterEventsByMonth(data: CalendarEventData[] = []): CalendarEventData[] {
Added missing comments

2022-06-21 20:43 UTC, jdilag90 commented on src/components/ids-week-view/ids-week-view.scss
> +  margin: 0 8px;
Also updated to use to `margin-inline-end` here

2022-06-22 10:04 UTC, andriivarhanov reviewed
looks great, some findings are below:
- I’m not sure if it’s critical, but it looks like view picker should be ids-dropdown not popup menu
- go to http://localhost:4300/ids-date-picker/example.html and check Date Field (legend) example -> open the popup, it’s wider, please check if some styles have been removed or changed

2022-06-22 13:51 UTC, tmcconechy submitted a review, later dismissed

2022-06-22 18:45 UTC, jdilag90 commented
Thanks for all the feedback guys. Addressed all of the inline comments. Decided to keep the menu button instead of dropdown for the view picker.

2022-06-22 18:45 UTC, tmcconechy approved these changes

2022-06-22 19:02 UTC, andriivarhanov approved these changes

2022-06-23 13:37 UTC, merged