Chore: Update dependencies and incremental build improvements
infor-design/enterprise-wc pull request #771
Opened 2022-06-22 15:21 UTC by tmcconechy

**Explain the details for making this change. What existing problem does the pull request solve?**
In this PR there a few things:

1. Updated dependencies from the demo the other day
2. Removed nodemon since it was "vulnerable" and was only used for initial webpack work
3. Adds back the filter concept we had before for faster build and incremental build (reloads) `npm --components=alert run start`
4. Turned off writeToDisk for modest gains (not seeing any issues with it but if anything is found this could be reverted)
5. Turned on `transpileOnly` -> this was the most significant gain. It stops the typechecker from checking types during builds and only compiles. This is done in or dev environment anyways and does report an error situation.

**Related github/jira issue (required)**:
NA

**Steps necessary to review your pull request (required)**:
- pull
- `npm prune && npm i` -> should be no warnings or vulnerabilities
- `npm run start` -> a faster faster now (3x?)
- save a file so a page reloads and recompiled -> a bit faster now  (3x?)
- for even faster speed can now use the filter an example command is shown in the package.json but you need to just run it like this `npm --components=data-grid run start` this will only include the component your working on and other pages wont work. save a file and its very fast now on reload

2022-06-22 19:15 UTC, danielortiz1982 requested changes
This PR looks good so far, one thing tho. Can you please make a standalone PR for the dependencies. Besides that I think everything else looks good to go. 👍

2022-06-22 19:17 UTC, tmcconechy commented
ok i can - but i felt like these were closely related...

2022-06-22 19:35 UTC, danielortiz1982 approved these changes

2022-06-23 07:39 UTC, andriivarhanov submitted a review, later dismissed

2022-06-23 14:11 UTC, andriivarhanov approved these changes

2022-06-23 14:38 UTC, merged