757 - IdsCalendar editing
infor-design/enterprise-wc pull request #795
Opened 2022-07-07 13:37 UTC by jdilag90

**Explain the details for making this change. What existing problem does the pull request solve?**
Adds creating/editing feature to calendar

**Related github/jira issue (required)**:
#757 

**Steps necessary to review your pull request (required)**:
1. Checkout branch, `npm run start`
2. (Edit) Click on any calendar event and edit inputs/dates/times
3. (Create API) Click on any month view day, then click + button next to theme switcher, then click "Create (API)" 
4. New event with default values should have been added to calendar inside day selected.
5. (Create Modal) Click on + button next to theme switcher, then click "Create (Modal)".
6. Edit popup form fields and click submit. Calendar event should be added to specified date/times.
7. (Clear Event) Click on + button next to theme switcher, then click "Clear". It should remove all calendar events.

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [ ] A note to the change log.

2022-07-07 15:33 UTC, tmcconechy requested changes
Really Nice Work! Just seeing a couple of "bugs".

1) Does it close it all here: https://github.com/infor-design/enterprise-wc/issues/757 (i made it "fixed #757"
2) If you add an event (for example "Add Event API") i think the accordion should be open so you can see the info. I.E. Accordion can be open by default. Also can set off "only one open" setting like the old version.
3) In the old version you could double click an calendar day and it would do "add event modal" for that day.
4) For the date range on the modal, can default it to today to tomorrow (not 2019) like the old version.
5) In the modal setting a few days range like7/7/2022 -7/9/2022 that isn't woorking

2022-07-18 14:42 UTC, jdilag90 commented
Will repush when lifecycle changes #789 are merged into main

2022-08-17 20:33 UTC, tmcconechy approved these changes
Looks good. Thanks! Anything else QA can test and discover for later 👍🏻

2022-08-19 12:51 UTC, andriivarhanov approved these changes

2022-08-19 14:35 UTC, merged