776 app menu example
infor-design/enterprise-wc pull request #809
Opened 2022-07-18 13:04 UTC by celhalal

**Explain the details for making this change. What existing problem does the pull request solve?**
Aligned header and footer icons in app-menu.

**Related github/jira issue (required)**:
closes #776

**Steps necessary to review your pull request (required)**:
1. Checkout branch, npm run start
2. Go to http://localhost:4300/ids-app-menu/example.html
3. Click icon menu (top left corner)
4. Check the misaligned footer
    -  example.html changes:
    - changed the Infor logo from a div to a slot element 
    - removed the toolbar footer and replaced it with the slot's name for the logo
5. Created another demo called example-footer.html
    Go to http://localhost:4300/ids-app-menu/example.html
     - this demo only includes the toolbar footer so I removed the infor logo
     - removed type='fluid' and align='center-even' since it was pushed to the right.

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2022-07-18 15:07 UTC, andriivarhanov reviewed
looks good, just a minor text adjustment

2022-07-18 15:07 UTC, andriivarhanov commented on src/components/ids-app-menu/demos/index.yaml
> +    type: Main Example
please change to just Example since there is main example above

2022-07-18 17:23 UTC, tmcconechy requested changes
Actually another suggestion it looks like some of the changes effected the masthead and toolbar:

https://percy.io/00aaa841/enterprise-wc/builds/19725648/changed/1108099133?browser=chrome&browser_ids=23&subcategories=unreviewed%2Cchanges_requested&viewLayout=side-by-side&viewMode=new&width=375&widths=375%2C1280 

https://percy.io/00aaa841/enterprise-wc/builds/19725648/changed/1108088263?browser=chrome&browser_ids=23&subcategories=unreviewed%2Cchanges_requested&viewLayout=side-by-side&viewMode=new&width=1280&widths=375%2C1280

Probably becauseof https://github.com/infor-design/enterprise-wc/pull/809/files#diff-a5dee3d127a457aaf5d9d5a79e725cddd541907baafb6b0c646b677afd91f44eR22 so maybe we need to add that rule either in the app-menu scss rules or as a setting (can youo make it it work for only .fluid?)

2022-07-19 15:15 UTC, tmcconechy commented
@celhalal looking at the screen shots in percy it seems like it still breaks:

http://localhost:4300/ids-masthead/example.html
and
http://localhost:4300/ids-toolbar/formatter.html

But i dont understand 100% why? Can compare to:
https://main.wc.design.infor.com/ids-masthead/example.html
https://main.wc.design.infor.com/ids-toolbar/formatter.html

2022-07-22 14:19 UTC, tmcconechy approved these changes
I changed this a bit to isolate the styles for fluid/center-even

2022-07-22 16:56 UTC, merged