4973 add ids counts
infor-design/enterprise-wc pull request #82
Opened 2021-04-14 12:52 UTC by chrisakinrinade

**Explain the details for making this change. What existing problem does the pull request solve?**
Adding IDS Counts component to the web component repo. Currently supports hyperlinked, compact, and disabled counts.

**Related github/jira issue (required)**:
https://github.com/infor-design/enterprise/issues/4973

**Steps necessary to review your pull request (required)**:
1. Pull this branch, build, and run the app
2. Go to http://localhost:4300/ids-counts
3. Check the code implementations and functional tests.

**Included in this Pull Request**:
- [x An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2021-04-14 14:56 UTC, tmcconechy requested changes
Looks really great for a first PR 🍌  Nice Job.
Im just adding a few suggestions. Also you could add an e2e test like the others?

Im soon merging a PR where it will mean we have to add themes here as well. But thats not merged so dont worry about that until it is and i'll let you know. So just a heads up for now

2021-04-14 14:56 UTC, tmcconechy commented on app/ids-counts/example-default.html
> +      <div slot="value">4</div>
Suggestion: Would a span be a better choice here that a div for the two slot elements?

2021-04-14 14:56 UTC, tmcconechy commented on app/ids-counts/example.html
> +{{> example-not-actionable.html }}
Can probably just show the default one here and leave the others for sub pages (for example simplicity). This might mean removing example-default and just putting in in example.

2021-04-14 14:56 UTC, tmcconechy commented on app/ids-counts/example-not-actionable.html
> +    <ids-counts disabled="true">
```suggestion
    <ids-counts disabled="true">
```

i think maybe disabled is the wrong word here. Its not disabled looking its just not linked. Maybe we can do this with just the presence of a `href` or not instead of making a disabled property as that would imply to me it looks disabled..

2021-04-14 14:56 UTC, tmcconechy commented on app/ids-counts/example-short.html
> +    <ids-counts short="true">
Was going to start calling this compact https://github.com/infor-design/enterprise/issues/5077#issue-857302801
Could we change the short setting to compact to match up?

2021-04-14 14:56 UTC, tmcconechy commented on app/index.html
> +{{> ids-counts/example.html }}
Can you put this down at the bottom instead of the first one (and as above we can just show the default)

2021-04-14 14:56 UTC, tmcconechy commented on app/index.js
> +import IdsCounts from '../src/ids-counts/ids-counts';
Can also move this down to the bottom - but that doesn't effect the the kitchen sink example. So not that important.

2021-04-14 14:56 UTC, tmcconechy commented on src/ids-counts/ids-counts.d.ts
> +  /** Set the tag type/color */
Seems to be missing the new settings in the component (looks like just copied from the tag)

2021-04-14 14:56 UTC, tmcconechy commented on src/ids-counts/ids-counts.js
> +   * @returns {number} the font size
```suggestion
   * @private
   * @returns {number} the font size
```

2021-04-14 14:56 UTC, tmcconechy commented on src/ids-counts/ids-counts.js
> +   * @returns {number} the font size
If this is private? Sometimes we use the full wording on these for example numberSize

2021-04-14 14:56 UTC, tmcconechy commented on src/ids-counts/ids-counts.js
> +    return [props.COLOR, props.DISABLED];
Add these both  to d.ts?

2021-04-14 14:56 UTC, tmcconechy commented on src/ids-counts/ids-counts.js
> +   * @returns {object} Object containing the outer HTML to be rendered
Private?

2021-04-14 14:56 UTC, tmcconechy commented on src/ids-counts/ids-counts.js
> +    return `
This is ok - but in many cases we just had the string template as a one expression with Template Literals all in the template. https://github.com/infor-design/enterprise-wc/blob/main/src/ids-accordion/ids-accordion.js#L31

Might simplify it a bit as this is rather simple...

2021-04-14 14:56 UTC, tmcconechy commented on src/ids-counts/ids-counts.js
> +    this.container.style.color = prop || '';
As a test case - what happens if they clear the color? Did not test it but something to think about

2021-04-14 14:56 UTC, tmcconechy commented on src/ids-counts/ids-counts.js
> +  set disabled(value) {
As per above i think disabled isnt the correct name for what this is doing. Maybe we can try doing it off of having a href or not

2021-04-14 18:58 UTC, chrisakinrinade commented on app/ids-counts/example-default.html
> +      <div slot="value">4</div>
Possibly, what's your thought behind that? I wanted to ensure they wound up on different lines @tmcconechy

2021-04-14 19:01 UTC, chrisakinrinade commented on app/ids-counts/example-not-actionable.html
> +    <ids-counts disabled="true">
I don't know why I thought the issue description explicitly mentioned "disabled" when, because it didn't. My mistake, I was actually thinking the same thing, the presence of an href is all you need.

2021-04-14 19:22 UTC, tmcconechy commented on app/ids-counts/example-default.html
> +      <div slot="value">4</div>
Yeah thats why i wondered - if you needed the div to make it different lines. 

Originally, my thinking is that divs are for sections/divisions in the document but spans are more for text.

But thinking again when its in the slot the could technically add anything... For example maybe they put a span or ids-text or ids-icon in there for some use case. So maybe we should make it be as flexible as we can - which is possibly more important then the span vs div. So making each slot a seperate line no matter what it is could be the answer there.

If we dont let them add data in the slot and "lock it down" we could use settings instead but having some options like you did it seems more flexible

2021-04-14 19:27 UTC, chrisakinrinade commented on app/ids-counts/example-short.html
> +    <ids-counts short="true">
sure thing!

2021-04-14 19:31 UTC, chrisakinrinade commented on app/ids-counts/example.html
> +{{> example-not-actionable.html }}
will do

2021-04-14 19:32 UTC, chrisakinrinade commented on app/index.html
> +{{> ids-counts/example.html }}
yup! do all new components go at the bottom by default? wasn't sure where to put it.

2021-04-14 19:34 UTC, chrisakinrinade commented on app/index.js
> +import IdsCounts from '../src/ids-counts/ids-counts';
will do

2021-04-14 19:36 UTC, tmcconechy commented on app/index.html
> +{{> ids-counts/example.html }}
Yeah pretty much but its sort of free form for example i might put a new button next to the other buttons or the checkbox next to the radio ect. So more like where ever it fits with something similar if anything not then bottom. 

I'm thinking we wont keep this page for long as it gets a bit much. Probably replace it with a list like https://master-enterprise.demo.design.infor.com/components/list with a description, link ect eventually but looking for a design first

2021-04-14 20:58 UTC, EdwardCoyle reviewed
Looks good so far @chrisakinrinade.  I've got nothing to add to Tim's comments.  Will approve once you post changes 👍

2021-04-14 23:57 UTC, chrisakinrinade commented on app/ids-counts/example-default.html
> +      <div slot="value">4</div>
Good point about the user injecting additional elements into the slots!

2021-04-15 00:00 UTC, chrisakinrinade commented on app/index.html
> +{{> ids-counts/example.html }}
Got it, I'm remembering now that you mentioned earlier about converting to a list.

2021-04-15 15:31 UTC, deep7102 commented
This looks very nice, only saw
- the value slot `normal` and `compact` both are on 32px.
- are we adding `compact` and `href` to `properties()` array and setter so live change, currently saw only use by attributes
- will coming back to add  the `standalone-css` and `README.md` (no docs)

2021-04-15 20:12 UTC, tmcconechy commented
@chrisakinrinade - I merged in a big PR so you might have to fix a conflict when you apply main on.
Also it adds another task for this issue. Since i implemented a theme mixin you can now make this component have the themes

https://github.com/infor-design/enterprise-wc/blob/main/src/ids-base/README.md#ids-theme-mixin <- try and follow that and look at the components. And ask me if any questions or that doesnt make any sense

2021-04-19 13:59 UTC, chrisakinrinade commented
> This looks very nice, only saw
> 
> * the value slot `normal` and `compact` both are on 32px.
> * are we adding `compact` and `href` to `properties()` array and setter so live change, currently saw only use by attributes
> * be good if you could take a first pass at adding the `standalone-css` example and `README.md` (similar to the other components with DOCS)

Question on the compact and href attributes -- should those be added to ids-constants.js?

2021-04-19 14:19 UTC, tmcconechy commented
@chrisakinrinade - yes generally we want to list all possible settings in the consts. So if it has a setter/getter and its used in properties should just add it in the consts..

2021-04-23 13:46 UTC, chrisakinrinade commented on src/ids-counts/ids-counts.d.ts
> +  /** Set the tag type/color */
Ok, I've added these now

2021-04-23 14:41 UTC, tmcconechy commented
@chrisakinrinade only a couple more things that should be easy to fix.

1) for the tests i split it in https://github.com/infor-design/enterprise-wc/tree/main/test/ids-badge two. ids-counts-percy-test.js for just the percy tests and other e2e tests in ids-counts-e2e.js
1) notice in the percy test the import changed - this is why your tests are failing
1) did you add the themes? im not seeing that working when i change the theme switcher to dark mode an

2021-04-26 17:33 UTC, tmcconechy commented
@chrisakinrinade is this done and ready for re-review? If so i think just some tests need to be updated..

2021-04-26 19:43 UTC, chrisakinrinade commented
> @chrisakinrinade is this done and ready for re-review? If so i think just some tests need to be updated..

@tmcconechy I was waiting to see if it passed the checks. I noticed the axe test keeps timing and I'm not sure what's wrong with it. Would you happen to know if there's something simple it's missing? The error it gives is that the async call never gets a response.

2021-04-27 19:26 UTC, tmcconechy requested changes
Tried to fix a few things for you but didnt get it all. I think the following should be fixed

1. The focus state on the default counts
2. The linkable counts should use the azure color (same as ids-hyperlink and you could try using that directly).
3. The non linkable should be the text color as you have it note that color="base" redundant instead should be just 2/3
4. the color setting is no longer working (worked at one point) see http://localhost:4300/ids-counts/compact
5. the standalone css example isnt 100% http://localhost:4300/ids-counts/standalone-css
6. Make it so you can reorder the two slot items to make the text vs count on top/bottom. Didnt realize this was a feature

I'm looking at the axe test failure so will PR that... separate and you can pull it in

2021-05-03 18:34 UTC, tmcconechy commented
Closing this for now - but when its done you can repopen the PR

2021-05-03 18:34 UTC, closed without merging