505 - IdsActionSheet remaining issues
infor-design/enterprise-wc pull request #822
Opened 2022-07-22 15:22 UTC by celhalal

**Explain the details for making this change. What existing problem does the pull request solve?**
This PR includes:
- Rename `btnText` to `cancelBtnText` and make it update live (DOM)
- Add visual test for having no cancel button (when the button is not displayed)
 - Test it by going to the Dev tools on a mobile simulator and typing in the console:
     `document.querySelector('ids-action-sheet').btnText = ''`

**Related github/jira issue (required)**:
closes wc#504
closes wc#505

**Steps necessary to review your pull request (required)**:
1. Checkout branch, `npm run start`
2. Go to http://localhost:4300/ids-action-sheet
3. In Dev tools select a mobile simulator
4. Click ... icon in the top left corner to open the menu
5. In the console type: `document.querySelector('ids-action-sheet').btnText = 'test'`
6. See error (button text doesn't update)

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2022-07-27 14:45 UTC, EdwardCoyle requested changes
Hi @celhalal!  This is looking good so far -- just a couple things:

- Please update the steps for testing this PR to reflect the `cancelBtnText` change.  I think I tested correctly and the feature seems to work, but not totally sure of the intention of the testing steps
- I think unless there are more features coming we should not have this PR close #504.  There are some other items unaddressed here -- #505 does cover this issue so that one is fine to close.  Note that when you use `closes #[issue number]` in a Github PR, automation occurs that will actually close the issue once this PR merges.

Hopefully that helps, please reach out if you need anything

2022-07-27 19:27 UTC, jmacaluso711 submitted a review, later dismissed
@celhalal Approved  👍

2022-07-28 18:03 UTC, EdwardCoyle approved these changes
Awesome, good stuff @celhalal 🎉

2022-07-29 13:34 UTC, EdwardCoyle reviewed
@celhalal Glad you got the test running!  I think we just need one more tweak and this PR is golden:

2022-07-29 13:34 UTC, EdwardCoyle commented on test/ids-action-sheet/ids-action-sheet-percy-test.ts
> +      idsButton.style.display = 'none';
Instead of hiding with CSS, I'd suggest using the same API you're using in the functional tests to hide the button, just to make the test a bit more accurate:

```suggestion
      idsButton.cancelBtnText = null;
```

2022-08-01 13:30 UTC, EdwardCoyle reviewed
@celhalal Was looking at this again and found a couple additional items we should address.  Other than that, this is looking great 👍

2022-08-01 13:30 UTC, EdwardCoyle commented on src/components/ids-action-sheet/ids-action-sheet.ts
> +    const idsButton = document.querySelector('ids-action-sheet')?.shadowRoot?.querySelector('ids-button') as HTMLElement;
Each of the components should be "self-contained" as much as possible... For example, we already have a reference to "this" action sheet reference, so we want to use that as the starting point for reaching the button:

```suggestion
    const idsButton = this.shadowRoot?.querySelector('ids-button') as HTMLElement;
```

2022-08-01 13:30 UTC, EdwardCoyle commented on src/components/ids-action-sheet/ids-action-sheet.ts
> +const btn = document.querySelector('#icon-button') as HTMLElement | null;
Probably want to remove Line 172 through 177 -- I'm guessing this was targeting something for a test case?  This code existing outside the component class can cause memory leaks, so better off moving it to a test page's TS if needed.

2022-08-02 18:59 UTC, EdwardCoyle approved these changes
Looks really good now!  Thanks @celhalal 👍

2022-08-02 19:11 UTC, celhalal commented
@EdwardCoyle The percy test snapshot still includes the cancel button so im going to try it in the e2e test in the meantime. Appreciate all the help and suggestions!

2022-08-02 19:26 UTC, tmcconechy approved these changes

2022-08-02 19:39 UTC, merged