780 ids date picker
infor-design/enterprise-wc pull request #833
Opened 2022-08-02 17:07 UTC by celhalal

**Explain the details for making this change. What existing problem does the pull request solve?**
This PR fixes the following issues:
1. Double click does not enforce Range - Min (N) Days
   - Fixed issue by creating an if statement to compare the start date and end date and ensure that they are not equal
2. Cannot select dates on FF and Safari since the popup automatically closes if it detects a click event
   - Updated `e.path` to `e.composedPath()` since path is being deprecated and the browsers are not responding to it.

**Related github/jira issue (required)**:
fixes #780 

**Steps necessary to review your pull request (required)**:
1. Checkout branch, npm run start
2. Go to http://localhost:4300/ids-date-picker/range.html on any browser
  - Click on date picker field with Range - Min (5) Days
  - Select a date and double click it
  - See error: user is able to input a single day on date picker with range Min 5 days
3. Go to http://localhost:4300/ids-date-picker/range.html on Safari/FF
  - Click on date picker field
  - Select a date
  - See error: popup automatically closes

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2022-08-03 09:47 UTC, andriivarhanov commented on doc/CHANGELOG.md
> +- `[ActionSheet]` Updated event path for clicking event and ensured appropriate date input for Range - Min(N) Days. ([#780](https://github.com/infor-design/enterprise-wc/pull/780))
[DatePicker]

2022-08-03 09:47 UTC, andriivarhanov commented on src/components/ids-date-picker/ids-date-picker.ts
> +  #rangePickerMin = this.container.querySelector('#e2e-datepicker-min');
the id can't be used here since it works only for the particular example and will be different for another ids-date-picker

2022-08-03 09:47 UTC, andriivarhanov commented on src/components/ids-date-picker/ids-date-picker.ts
> +        if (this.#rangePickerMin && (val.minDays !== undefined)) {
`if (this.rangeSettings.minDays) {` would work same way here

2022-08-03 09:47 UTC, andriivarhanov commented on src/components/ids-date-picker/ids-date-picker.ts
> +            this.rangeSettings.end = new Date(this.rangeSettings.end + (val.minDays * 24 * 60 * 60 * 1000));
let's select days forward here like on https://main-enterprise.demo.design.infor.com/components/datepicker/example-range.html 
rangeSettings.start + minDays

2022-08-03 17:02 UTC, celhalal commented on src/components/ids-date-picker/ids-date-picker.ts
> +            this.rangeSettings.end = new Date(this.rangeSettings.end + (val.minDays * 24 * 60 * 60 * 1000));
Thank you @andriivarhanov for the feedback! I updated everything  👍

2022-08-04 10:11 UTC, andriivarhanov commented on src/components/ids-date-picker/ids-date-picker.ts
> +            this.rangeSettings.end = new Date(this.rangeSettings.end + (val.minDays * 24 * 60 * 60 * 1000));
looks good, thanks

2022-08-04 10:11 UTC, andriivarhanov approved these changes

2022-08-04 13:25 UTC, danielortiz1982 commented on src/components/ids-date-picker/ids-date-picker.ts
> +            this.rangeSettings.end = new Date(this.rangeSettings.end + (val.minDays * 24 * 60 * 60 * 1000));
Why are we using 4 `if` statements? The first statement can be true, then the second can be false, then nothing happens, maybe we can change this to `if else` ?

2022-08-04 17:35 UTC, tmcconechy requested changes
I noticed a wierd thing about double clicking @celhalal 

1. in chrome to to http://localhost:4300/ids-date-picker/range.html
2. click min 5 days and open the picker
3. double click aug 16 and then 11 becomes selected and then you can hit apply

2022-08-08 17:08 UTC, tmcconechy commented
I still think double clicking a day in the picker acts weird in that it selects two days. I think maybe we should try to ignore double clicks (same thing as a single click should happen).

Maybe
```
this.onEvent('dblclick',  .....
    event.preventDefault();  
    event.stopPropagation(); 
  },
);
```

2022-08-09 12:53 UTC, tmcconechy approved these changes

2022-08-09 17:28 UTC, andriivarhanov approved these changes

2022-08-09 20:06 UTC, tmcconechy approved these changes

2022-08-10 09:09 UTC, andriivarhanov approved these changes

2022-08-10 14:34 UTC, merged