357 - Add IdsForm Components
infor-design/enterprise-wc pull request #868
Opened 2022-08-19 17:57 UTC by tmcconechy

**Explain the details for making this change. What existing problem does the pull request solve?**

This PR adds an initial IdsForm Component as per #357 initial code includes:

- form layouts via ids-layout-grid
- ability to set compact mode
- ability to reset dirty tracker
- ability to get invalid form fields
- ability to check form isValid
- ability to check form isDIrty

More can be added later as requested

**Related github/jira issue (required)**:
Fixes #357 

**Steps necessary to review your pull request (required)**:
**Dirty**
- go to http://localhost:4300/ids-form/example.html
- change a field like Purchase Form
- in the console check `document.querySelector('ids-form').isDirty`
- reset the tracker with `document.querySelector('ids-form').resetDirtyTracker()`
- check output. in   `document.querySelector('ids-form').dirtyFormComponents`

**Validation**
- clear a field like Purchase Form or more
- in the console check `document.querySelector('ids-form').isValid`
- check output. in   `document.querySelector('ids-form').errorFormComponents`

**Submit**
- change a field like Purchase Form
- click submit
- check the console and notice the data is showing the values, dirty state and validation state

**Compact**
- in the DOM add "compact="true" to ids-form and notice this works

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2022-08-22 14:05 UTC, EdwardCoyle reviewed
Looks great @tmcconechy !  Just a couple of questions/minor stuff:

2022-08-22 14:09 UTC, tmcconechy commented on src/components/ids-form/ids-form.ts
> +    const isCompact = stringToBool(value);
How would we share that? Way i look at it was that this has to set every one of them... Not thinking of a way we can. Really only the `set compact` `get compact` part is "not shared".

Wasn't also allowing field height tio be set at the form level only compact

2022-08-22 14:35 UTC, tmcconechy commented
@EdwardCoyle I see what you mean, i made it use the FieldHeightMixin more (and added field-height so that works now too)

2022-08-22 14:46 UTC, EdwardCoyle approved these changes

2022-08-23 14:38 UTC, EdwardCoyle submitted a review, later dismissed

2022-08-23 16:15 UTC, deep7102 commented
Looks all good!
only one thing like to point about validation `isValid` return the current validation-state for each component, but I think it should check for validation also so it can use before submit the form data. 

issue see on fresh page, if you run `document.querySelector('ids-form').isValid`  it will return `isValid: true`
but if you see there are few component are not valid like textarea, timepicker, upload so I guess will be good if it have some kind of method or with same name `document.querySelector('ids-form').checkValidation()` where it will check for validation -vs- validation-state on each component.

FYI: if run [checkValidation()](https://github.com/infor-design/enterprise-wc/blob/4f805e5a1fc2f60dcb8f50a15616e0b51db0c194/src/mixins/ids-validation-mixin/ids-validation-mixin.ts#L160) on each component it will check validation and add/remove validation message.

2022-08-23 16:53 UTC, tmcconechy commented
yes good idea with `checkValidation`. I added a method that fires on submit in the example, but i only log the info on submit- check it out @deep7102

2022-08-23 17:13 UTC, deep7102 approved these changes
Looks good! Thanks, @tmcconechy

2022-08-24 15:26 UTC, danielortiz1982 requested changes
Please update the package.json in a independent PR.

2022-08-24 15:32 UTC, danielortiz1982 commented on src/components/ids-form/ids-form.ts
> +  get idsComponents(): Element[] {
@tmcconechy Should we turn this into a mixin? Thoughts?

2022-08-24 15:35 UTC, tmcconechy commented on src/components/ids-form/ids-form.ts
> +  get idsComponents(): Element[] {
Maybe later how about? I could be a util but usually I do that later when/if its ever needed a second time.

2022-08-24 15:35 UTC, tmcconechy commented
@danielortiz1982 took the package.json change out will make a new PR

2022-08-24 15:36 UTC, danielortiz1982 commented on src/components/ids-form/ids-form.ts
> +  get idsComponents(): Element[] {
Sounds good. 👌

2022-08-24 15:37 UTC, danielortiz1982 approved these changes
This looks 🔥 @tmcconechy great job on this!

2022-08-24 15:46 UTC, deep7102 approved these changes

2022-08-24 16:20 UTC, merged