5026 - ids-wizard wc
infor-design/enterprise-wc pull request #88
Opened 2021-04-19 20:27 UTC by rob2d

**Explain the details for making this change. What existing problem does the pull request solve?**

Adding the ids-wizard functionality

**Related github/jira issue (required)**:

Closes infor-design/enterprise#5026

**Steps necessary to review your pull request (required)**:

- pull `5026-ids-wizard-submission`
- run through ids-wizard tests: `npm run test ids-wizard`
- browse wizard examples at http://localhost:4300/ids-wizard/
- make sure each example matches description based on whether it's partially clickable
- make sure wizard navs to proper hash URL based on your clicks
- make sure you can nav using tab/enter on the wizard

--------------------------

Known functionality WIP/incomplete: 
- explicit external callback on step changes by user

^ This is just because the scope of this branch was already increased several times to add base functionality e.g. ids-text font-weight/overflow, ids-element callbacks, event fixes, etc. Can revisit/add if it is must have for this sprint.

--------------------------

Changes also included for this branch:
- needed to bump Jest to v27-next build since JSDOM had MutationObserver circular loop bug breaking wizard tests.
- ids-events-mixin: make target specified as optional in case we cannot find that reference anymore -- this is useful in rendered() behavior since we don't need to store a "previous" reference to delete old callbacks.
- changed linter rule so we can have non alphabetized rules; this is so we can have hierarchy based rules i.e. `display`/`position` > `top/left/bottom/right` or putting things next to each other. Also discussed briefly during last group chat.
- changed linter rule to remove need to specify radix with `parseInt`. Talked to Ed on this but seems a little superfluous with no hex/binary code as a norm (so its a < 1% use-case to need to specify parseInt(number, 10) each time).
- ids-element: added rendered() callback based on chat with Tim's input for lifecycle method/also future usage.
- ids-text: added `color` property which can be `unset` with a test case, to allow for coloring the steps.

**Included in this Pull Request**:
- [X] An e2e or functional test for the bug or feature.
- [X] A note to the change log.

2021-04-20 15:13 UTC, tmcconechy requested changes
Just added a few comments overall this looks really good!

- can you add the themes (new) this is probably just the line/dot color per theme
- clean up the examples a bit to split in two
- the clickable default

Aside from the comments inline
 - in some of the examples the text is not centered
 - can we implement the focus state its just showing the default

2021-04-20 15:13 UTC, tmcconechy commented on test/ids-wizard/ids-wizard-func-test.js
> +/**
Nice tests!!!! 💯

2021-04-20 15:13 UTC, tmcconechy commented on src/ids-wizard/ids-wizard.js
> +import clsx from 'clsx';
This is now the only dependency so i'm a little uneasy about it. This feels a little to me like adding jQuery / some external API that got us in trouble before. Personally I find the a bit confusing/non standard. We had just been doing this

```
template = `<blah class="${condition ? 'class1 ; ''}`
```

If necessary can we add the code directly into https://github.com/infor-design/enterprise-wc/blob/main/src/ids-base/ids-string-utils.js or https://github.com/infor-design/enterprise-wc/blob/main/src/ids-base/ids-dom-utils.js as a function so we own it. 

This may seem counterintuitive but that way we own it if it ever goes away or has security flaws or something we need to fix. 

Maybe others might find this useful? So willing to debate but i think we should put it utils and my vote is not include it. cc @EdwardCoyle @deep7102

2021-04-20 15:15 UTC, rob2d commented on app/ids-wizard/example.html
> +    <ids-wizard step-number="1">
yeah I was not sure of this one -- thanks. I will revert the behavior in this case.

2021-04-20 15:15 UTC, rob2d commented on src/ids-wizard/ids-wizard.js
> +  // @ts-ignore
must have deleted a line and forgotten about this one, thanks for catching.

2021-04-20 15:17 UTC, rob2d commented on src/ids-wizard/ids-wizard.js
> +  updateHrefUrls() {
the reason I used this one is the `updateHrefs` only runs when the component mounts or the children change. 

I didn't add a specific event for that (yet) since there's none else there. But it basically is a little bit expensive to go through and concat all strings/detect duplicates, and it shouldn't change when a user changes a step or clickable on parent. So that's why I updated here.

(It's private though also)

2021-04-20 15:18 UTC, tmcconechy commented on src/ids-wizard/ids-wizard.js
> +  updateHrefUrls() {
Ok then lets just add a comment jsdoc with @private - its all good.

2021-04-20 15:20 UTC, rob2d commented on app/ids-wizard/example.html
> +    <ids-wizard step-number="3" clickable>
it can be on either -- if it is on the parent, then all children are clickable by default. If it's not on the parent, then it becomes clickable via children flags. Actually re: the other question on parent clickable, this might have been why I didn't make parent clickable by default, since in the older step wizard you need to make children clickable.

2021-04-20 15:20 UTC, rob2d commented on app/ids-wizard/example.html
> +    <ids-wizard step-number="3" clickable>
Maybe I can do a better job also in the doc here...

2021-04-20 15:22 UTC, rob2d commented on app/ids-wizard/example.html
> +    <ids-wizard step-number="1">
just had my memory jogged from the other question: the reason the paren't wasn't by default is the previous wizard had children become "clickable" with a flag on wizard steps. I just based it on that. But if you think this default makes more sense we should probably discard that then (and I agree -- just wasn't sure if that was ok).

2021-04-20 15:23 UTC, tmcconechy commented on app/ids-wizard/example.html
> +    <ids-wizard step-number="3" clickable>
Ok we might have done the old one wrongly. But the default page is clickable https://master-enterprise.demo.design.infor.com/components/wizard/example-index.html

I think usually they are clickable so i think that should be the default. I also feel like that cleans this up as you would only need clickable="false" if not clickable (on parent for all or each child one by one). We can change that...

2021-04-20 15:24 UTC, tmcconechy commented on app/ids-wizard/example.html
> +    <ids-wizard step-number="1">
Yeah i think it makes most sense as clickable="true" as the default...knowing how this is used now a bit more in practice since when it was made originally.

2021-04-20 15:44 UTC, rob2d commented on src/ids-wizard/ids-wizard.js
> +import clsx from 'clsx';
makes sense. My reasoning on this one (we chatted already just listing for discussion) is just that:

- it's pretty minimal (228bytes)
- well documented
- prevents user error with stringifying things (spaces, accidental "undefined/false")
- a bit more concise in logical/conditional cases e.g. 
```
className = clsx(
     cond && 'class-a', // < false does not get thrown into classes
     condB ? 'class-b', : someOtherVar // <- some other var doesn't dirty-up if undefined/false
     'class-c', // clean to list multiple without conditionals over and over
     'class-d'
)
```
- it's basically a drop-in replacement for `classnames` which is pretty popular, just more minimal
![image](https://user-images.githubusercontent.com/1799905/115425415-9a0f6580-a1cd-11eb-9577-146819bcdcd6.png)
![image](https://user-images.githubusercontent.com/1799905/115425527-b27f8000-a1cd-11eb-8e80-afe6c1801187.png)
- probably can catch cropping up VM/security issues also

But I'm not opposed to putting in our own lib either, and if it feels icky I can take it out. Just some reasoning why I thought this was ok since I am aware that diff places use diff tools so no biggie.

2021-04-20 16:12 UTC, rob2d commented on .vscode/settings.json
> +  "editor.tabSize": 2
yeah. We didn't have this before in our `.vscode`. So I just added it since otherwise we need to override the global settings `.vscode` instead, or else just keeping having issue in the git with a hanging file changed.

(I try to just not touch the global for projects locally after having that habit for some time before/it causing issues with switching vscode projects easily, but also maybe if a client/external user wants to contribute code that's not working with us they don't need to worry also)

2021-04-20 16:21 UTC, tmcconechy commented on .vscode/settings.json
> +  "editor.tabSize": 2
ok as long as it means a tab is two spaces and doesnt change that this point is just fine - i wasnt sure 100% what the config did.

2021-04-20 16:27 UTC, tmcconechy commented on src/ids-wizard/ids-wizard.js
> +import clsx from 'clsx';
OK - yeah it feels "icky" to me. I think we should remove it (or to much lesser degree of favorability include it in dom utils). Reason being:

- the rules we wanted to go for are no external dependencies (except for build tools and language extensions (bable ect))
- its trivial / can be done other ways and does add anything critical enough to invalidate not sticking to the first rule
- its not standard JS and personally i find the template/standard if's a little simpler to follow
- feels a bit like adding jQuery / underscore which we strongly wanted to avoid

2021-04-20 16:38 UTC, rob2d commented on doc/CHANGELOG.md
> -- `[Button]` The button component has been changed to a web component. ([#4390](https://github.com/infor-design/enterprise/issues/4390))
yeah sorry about that -- had two editor tabs open and was using a reference to edit the other issue. Must have changed the wrong one by accident (also fixed, thanks for catching it).

2021-04-21 14:57 UTC, EdwardCoyle reviewed
Piggybacking on Tim here - Overall looks really great!  Functionally everything works really well.  The one concern I've got is the alignment problem -- steps two and three below show it pretty well:

![Screen Shot 2021-04-21 at 10 45 28 AM](https://user-images.githubusercontent.com/3249601/115573792-0e5e0d80-a28f-11eb-8157-035590b78eae.png)

I was wondering how we solved this problem in the original Enterprise code and realized that each tick label is located inside the tick, with some CSS to push it beneath, and some Javascript-generated CSS rules to "align" it with the tick.

In this PR the labels are in a separate containment from the ticks.  I see the centering done on the two/three ticks, but it doesn't always line up depending on screen width.  I'm guessing if you wanted to make the alignment perfectly-centered, you'd need some JS for it... but maybe there's a CSS-based way?

2021-04-21 15:38 UTC, rob2d commented
@EdwardCoyle yeah -- was trying to go for a pure-CSS approach from Tim's suggestion to rely more on flex. So actually I went at first with something we had before, but the text sizing is a huge issue there since you can't calculate the bounds easily in CSS and changed it to be in 2 "strips"; e.g.

```
----------------------------------------------------
|    m1         m2           m3         m4         |
----------------------------------------------------
|{pdpd} l1   {pd}    l2  {pd}   l3 {pd}  l4  {pdpd}|
----------------------------------------------------

mx -> marker
lx -> label
pd -> padding


first/last marker => not center aligned
in-between => always center aligned
```

So the fact that it looks at all aligned is just a visual trick and figured the offset would be ok considering most text would be 2/3 words? But in that case it definitely pushes the limit of what is ok.

Will try to revisit this approach though and see if there's a non JS intensive solution since that adds more complexity to the component and this one is already a little non-standard.

2021-04-21 15:43 UTC, tmcconechy commented
Yeah sorry - flex was an idea but mainly i meant do it with css. But whatever it takes to make it center with css (flex/rejiggering the html markup/css grid) really anything aside from JS would be 100% acceptable.

2021-04-21 17:52 UTC, rob2d commented
After trying another approach, may need some simple Javascript to grab the offsets of each marker/container size as in the original implementation 😕

If we offset the text, to limit the size there is a gotcha where the parent has to be the step-node (the path segments between the markers space them out evenly w/flex-grow: 1`, so they cannot obtain a larger width if they're nodes on the ends to fill padding).

So positioning under, I went with an approach where we iterate through a for loop in the SCSS from 2-20 (step-count). The gotcha is the width cannot simply be parent divided by the number of steps, since that's relative to the step marker and not the label.
![image](https://user-images.githubusercontent.com/1799905/115598262-39089000-a2a8-11eb-8f46-a640e31fe056.png)

We can solve this via a manual label max size: but if there's a significant amount of text with ellipsis cutoff it may be seem really-arbitrarily limiting to the end user.

Will try to think of something outside of the box on this briefly before taking the JS-measure-it-all approach though.

2021-04-21 18:11 UTC, tmcconechy commented
Just a thought but if a width does solve it maybe you can make a container width 100%/<number of items> for each one. (After that it goes into an ellipsis or at a small breakpoint we show one)

i.e. css grid - auto-fit
https://css-tricks.com/auto-sizing-columns-css-grid-auto-fill-vs-auto-fit/

It is similar to the approach i did here https://master-enterprise.demo.design.infor.com/components/processindicator/example-labels.html but the labels are left aligned there..

2021-04-21 18:36 UTC, rob2d commented
@tmcconechy yeah with this method the issue is just the text isn't centered -- it is consistent but I think having text on the top/bottom even that out a bit.

See previous wizard for example what I mean: https://master-enterprise.demo.design.infor.com/components/wizard/example-index.html

2021-04-21 23:18 UTC, rob2d commented
Got something. It's not perfect with centering -- but -- not using any JS here and labels are not deviating away from the target markers.

The approach was to lean things over (since the first is slightly left, and last is slightly to the right of the marker) and transform slightly more-center based on the position as things keep leaning over.

The downside is it doesn't perfectly use h-space, since it doesn't take perfect measurements on resize like the original wizard, but can see below that it does responsively make some room when provided space.

![wizard-scss-widths-1](https://user-images.githubusercontent.com/1799905/115631772-76831280-a2d4-11eb-975b-8be928072797.gif)

![wizard-scss-widths-2](https://user-images.githubusercontent.com/1799905/115631926-bf3acb80-a2d4-11eb-8566-f79778ea0a1c.gif)

2021-04-21 23:30 UTC, rob2d commented on src/ids-base/ids-element.js
> +    this.rendered?.();
I'm not quite sure how that would look -- but sort of maybe illustrates a bit of what I was thinking which is: if we have the lifecycle method available and we can see the use-case, then it seems a bit more consistent if we can call `render` that we can override the `rendered` method -- especially if every IdsElement has that special method and components should extend it. 

The idea for ref was also taken from `LitElements` -- they have a method called `updated` in their class which we were referencing, and since we have a render method and our lifecycle is simpler it kind of fits in there.

(It could definitely use better documentation also, but I just felt the scope was growing quite a lot since the other tab component I haven't started this sprint and it was just added here).

2021-04-21 23:32 UTC, rob2d commented on src/ids-wizard/README.md
> +A card is created by using the custom `ids-wizard` element. It's sub-components/steps are represented by `<ids-wizard-step>`.
no, thanks for catching 😅

2021-04-21 23:35 UTC, rob2d commented on src/ids-wizard/ids-wizard-step.js
> +import styles from './ids-wizard.scss';
yeah -- the IdsElement is extended on `IdsWizardStep` -- so it would throw an error since IdsWizard isn't included here.

For context: at this point, the step component is just for end users to use that in case we add functionality besides that... but at least they wouldn't need to retrospectively change things on this if importing it.

2021-04-22 15:54 UTC, rob2d commented on src/ids-wizard/ids-wizard-step.js
> +import styles from './ids-wizard.scss';
(ok, just realized you are referencing styles and not the IdsElement -- in that case 100% correct thanks)

2021-04-23 14:36 UTC, tmcconechy reviewed
So the only issue i still see is is the centering/position of the labels. They aren't 100% centered. But also they are "cut off early". Meaning that you cant see a very long label.

We could introduce wrapping but im seeing a few examples that behave the way i would expect like:

https://stackblitz.com/edit/angular9-archwizard-css
https://jsfiddle.net/yeyene/59e5e1ya/

Basically what im thinking is
- each step is a box (div) and they are all equal width (css grid or flex)
- on the top of the box you have the lines (top-border)
- you have a link you center in each box for the text and some element for the dot
- in the middle top you align a dot in the center
- below that you align a text element

![Screen Shot 2021-04-23 at 10 25 09 AM](https://user-images.githubusercontent.com/814283/115887226-b9053600-a41f-11eb-8615-18bd326a48f1.png)

2021-04-23 14:52 UTC, rob2d commented
@tmcconechy I actually tried this as the very first attempt. The reason I didn't go with it is the paddings are not consistent and vary really extremely. So a user could not align the wizard with some content in their page very well; this would add some unpredictability in styling on actual applications and probably be a little frustrating in some scenarios.

In the example that you gave for example, everything inside the component looks aligned, but check out the overall layout as you add items:
![image](https://user-images.githubusercontent.com/1799905/115888245-b2c38980-a420-11eb-9cb4-e4ce0c83ef53.png)
![image](https://user-images.githubusercontent.com/1799905/115888771-4ac17300-a421-11eb-9197-230cf5102eea.png)

So in the test sandbox I created multiple elements specifically to make sure at least the guiding markers were aligned to the same paddings regardless of # of items since the whitespace can be used as ref in flow e.g.
![image](https://user-images.githubusercontent.com/1799905/115889468-f79bf000-a421-11eb-8d62-b48e1ab011d4.png)

(and I think this may be why we had it that way in the previous one as well, since that also wasn't always perfectly accurate)

2021-04-23 14:55 UTC, tmcconechy commented
OK is there any tweaks that we could make to the design to make it work better? I think the centering and fact that the labels are cut off will make people think this isnt as good as the old solution...

2021-04-23 14:57 UTC, rob2d commented
@tmcconechy for the cut-off I can try to tweak the SCSS generation a bit. Other than that I think using JS to measure the points/calculate width and offsets may work best, but I think we cannot use `style` anymore because of the `nonce` rule? (not entirely sure honestly)

2021-04-23 15:01 UTC, tmcconechy commented
NO you can use js to set the css - you just cant inline it (i.e. `style="width: 100px"`). But you can use CSS DOM https://www.w3schools.com/js/js_htmldom_css.asp

i.e.
`htmlelement.style.width="100px"`

2021-04-26 14:36 UTC, tmcconechy commented
Just pushing one comment - that i had made this example https://stackblitz.com/edit/wizard-idea?file=styles.css and it seems to work pretty good. However there is probably a lot more cases to consider. Just posting it for future reference or if needed. Im ok with whatever solution makes it work the best in the end.

2021-04-26 20:00 UTC, rob2d commented
thanks for the suggestion @tmcconechy . The reason I did not go with this is I tried it initially, and when there's variable steps the padding is really inconsistent/unpredictable in the overall page flow (and it would probably be ok, if it wasn't a thing before). This is actually why I used the grid to stretch the content together and at proportions on the test-sandbox examples -- since it shows that pretty clearly with different step counts and resizing, as it would really suck to go back to reflow this component again since it is tricky/involving.

So I reflowed the content again and a side benefit is the anchor tags nest both the label and step. But I couldn't use exactly the same approach as before (which long run is ok since we said we wanted to be able to iterate things to make them simpler if possible). After some iteration came up with a recursive solution which runs fast enough that we shouldn't even need a debounce or feel the "flicker" that we had before:

![resizeviajs](https://user-images.githubusercontent.com/1799905/116142806-583c5e80-a6a8-11eb-8937-a6ede02635ce.gif)

2021-04-27 20:12 UTC, tmcconechy submitted a review, later dismissed

2021-04-28 14:39 UTC, tmcconechy submitted a review, later dismissed

2021-04-28 15:13 UTC, tmcconechy submitted a review, later dismissed

2021-04-28 16:20 UTC, deep7102 commented
Looks good, found few styles
http://localhost:4300/ids-wizard/

1) Mouse courser on last selected step (Step Three on this page)
and http://localhost:4300/ids-wizard/test-sandbox (Steps 4/5 unclickable via clickable=false on children) and some others

2) Not sure it is example issue only, see the url have spaces(%20)

3) Focus state
<img width="259" alt="image" src="https://user-images.githubusercontent.com/38439203/116435753-b89edd80-a819-11eb-92ad-331ca4d5d729.png">

4) A square ghost behind the last selected step (Step Three)
<img width="100" alt="image" src="https://user-images.githubusercontent.com/38439203/116436028-fc91e280-a819-11eb-90cd-3f9f0e89a13f.png">

2021-04-28 16:46 UTC, tmcconechy commented
When revising for the last comment i'd add the styling isnt 100% like https://master-enterprise.demo.design.infor.com/components/wizard/example-index.html for the focus state

<img width="128" alt="Screen Shot 2021-04-28 at 12 45 50 PM" src="https://user-images.githubusercontent.com/814283/116441745-b63f8200-a81f-11eb-90d5-325d624088c4.png">

2021-04-28 16:47 UTC, rob2d commented
@deep7102 great catches on the styles, thanks! 

For #2, the URLs have %20 just cause I'm using `encodeURI` to make sure no unsafe chars go in the URL. So the spaces are converted for that reason. See: https://www.w3schools.com/tags/ref_urlencode.asp#:~:text=replaces%20a%20space

2021-04-28 18:25 UTC, rob2d commented
I noticed that the functionality for the links to work when revisiting was going to be re-used on the next WIP I am on (`ids-tabs`) -- though may need to make that a mixin or some variant of Pool/Factory, so just a heads up that I added that to this branch for the Wizard. Was having a coverage quirk locally but if CI passes it should be ready afaik.

Only one note on this though: for testing, we would need e2e to do that proper and there are nice puppeteer libs for shadow dom so that we can really quickly query i.e. `shadow/.step-label`. Looked into the code on those repos and there's a lot of nuances, so didn't want to open a can of worms at end of sprint and left a `TODO` on proper coverage there.

2021-04-28 19:46 UTC, tmcconechy commented
@rob2d can you just add these for example:

```
/* istanbul ignore next */
if (!this.pane) {
  return;
}
```

On the new lines... 
https://coveralls.io/builds/39199495/source?filename=src%2Fids-wizard%2Fids-wizard.js#L430

That way the coverage doesnt dip from 100 and you can go back to it. My check was supposed to be at 100% so fixing that. I really want that badge to stay at 100% for past reasons... Even if something isnt totally tested we skip it that way

2021-04-29 14:36 UTC, tmcconechy approved these changes

2021-04-29 14:58 UTC, deep7102 commented
Thanks! @rob2d for updates, but still see some as below
1. the focus style isnt matching 4.x
WC:
<img width="128" alt="image" src="https://user-images.githubusercontent.com/38439203/116572076-a4bab080-a8d9-11eb-856b-b2e88e1f4fc5.png">

4.x
<img width="144" alt="image" src="https://user-images.githubusercontent.com/38439203/116572148-b603bd00-a8d9-11eb-8166-7f7ddccae5b2.png">

2. unclickable should be unfocusable since its readonly
<img width="702" alt="image" src="https://user-images.githubusercontent.com/38439203/116571981-910f4a00-a8d9-11eb-84f8-b7df4ab8e8ac.png">

2021-04-29 20:00 UTC, rob2d commented
Good points @deep7102 , should be corrected; took a little bit since over-engineered the initial approach with some logic changing for the focus handlers w selection vs clickable.

2021-04-29 21:42 UTC, deep7102 approved these changes
Thanks! @rob2d, Looks very nice.
🍌

2021-04-30 13:20 UTC, EdwardCoyle approved these changes
@rob2d this is looking great!  I'm comfortable calling this one good to go 👍 

One thing I think we should think about for a phase two pass: I noticed on the sandbox page that when you push multiple labels into ellipsis, then change the active step, there's a very brief Flash of Unstyled Content (FoUC) that looks to me like the text being "out of ellipsis", then being put back.  I tried to record it but the framerate in the GIF below isn't fast enough to capture it.  If you try to follow similar steps to what's happening in the GIF, you'll see it:

![Untitled_-Apr-30-2021-9_11-AM](https://user-images.githubusercontent.com/3249601/116700801-2de2ed80-a995-11eb-9a18-a4eab1c56c7f.gif)

I wouldn't get hung up on this for now, but maybe we can spec out some future improvements once we get more components done.

2021-04-30 13:22 UTC, merged

2021-04-30 13:22 UTC, tmcconechy commented
Merging.. nice work @rob2d 🧇