932 - Fix filter issues with datagrid
infor-design/enterprise-wc pull request #965
Opened 2022-10-19 17:34 UTC by deep7102

**Explain the details for making this change. What existing problem does the pull request solve?**
Fixed some filter issues with datagrid

- Added support to disable client filter (ui only and get info by event)
- Added support to in-range for date filter
- More tests and coverage
- Update docs and other cleanup

**Related github/jira issue (required)**:
Fixes #932

**Steps necessary to review your pull request (required)**:
Pull this branch and build/run the demo app
- Navigate to:
- http://localhost:4300/ids-data-grid/filter.html
- http://localhost:4300/ids-data-grid/filter-custom.html
- http://localhost:4300/ids-data-grid/filter-trigger-fields.html
- http://localhost:4300/ids-data-grid/disable-client-filter.html (see console logs)
- Check filters and all tests should pass

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2022-10-21 14:13 UTC, tmcconechy requested changes
A few small things...Also:

http://localhost:4300/ids-data-grid/filter-trigger-fields.html
- can center the active column
- for some reason the dropdown looks smaller?
<img width="137" alt="Screen Shot 2022-10-21 at 10 10 48 AM" src="https://user-images.githubusercontent.com/814283/197216561-2c03c2e5-a66a-4d61-9490-f20304d45e20.png">

http://localhost:4300/ids-data-grid/filter-custom.html
- can center the in stock column
- can we show one with only a text input that works? This is an m3 use case

2022-10-21 14:13 UTC, tmcconechy commented on src/components/ids-data-grid/README.md
> +- `filterable` {boolean} Sets to turned on/off filters.
```suggestion
- `filterable` {boolean} Turns on or off the filter functionality.
```

2022-10-21 14:13 UTC, tmcconechy commented on src/components/ids-data-grid/README.md
> +- `disableClientFilter` {boolean} Sets to disable filter logic client side and let server do it.
```suggestion
- `disableClientFilter` {boolean} Disables the filter logic client side in situations you want to filter server side.
```

2022-10-21 14:13 UTC, tmcconechy commented on src/components/ids-data-grid/README.md
> +- `filter-row-disabled` {boolean} Sets to disable filter row.
```suggestion
- `filter-row-disabled` {boolean} Disables the filter row.
```

2022-10-21 14:13 UTC, tmcconechy commented on src/components/ids-data-grid/README.md
> +- `clientfiltered` Fires after filter conditions changed, only fire with `disableClientFilter: true`.
```suggestion
- `clientfiltered` Fires after filter conditions are changed. Only fires when `disableClientFilter: true`.
```

2022-10-21 14:13 UTC, tmcconechy commented on src/components/ids-data-grid/README.md
> +1. `disableClientFilter` This is an api setting to disable filter logic client side. It will set filter conditions and fire an event `clientfiltered` which can listen for custom logic.
Any reason to not use the same filtered event?

2022-10-22 02:52 UTC, deep7102 commented on src/components/ids-data-grid/README.md
> +1. `disableClientFilter` This is an api setting to disable filter logic client side. It will set filter conditions and fire an event `clientfiltered` which can listen for custom logic.
updated event name as `filtered`

2022-10-22 02:58 UTC, deep7102 commented
@tmcconechy updated now, all the points you find.

2022-10-24 18:14 UTC, tmcconechy approved these changes

2022-10-26 08:54 UTC, andriivarhanov approved these changes
looks good

2022-10-26 17:07 UTC, merged